### ISSUE TITLE
Attempting to convert a dct file

### ISSUE THREAD

**Issue by eonhand** [openstenoproject/plover#1002]
## Summary

The dct plugin isn't working for me. It's giving errors indicated on the digitalcat dictionary conversion plugin page, but doesn't seem to have been addressed. 

I'd just like to get this dictionary converted to a Plover compatible format. (It's an older one; no longer have access to DigitalCat.) This is in response to ted on Discord.

The dictionary is on Dropbox here: https://www.dropbox.com/s/8l8pemvnqekrz42/ARB.dct?dl=0

I attempted to upload it, but uploads seem to be disabled. Thanks!

**Comment by gdwaynewarner** [comment]
Some years back, I installed Wine on my Mac, and ran the installer for digitalCAT, in the hopes that Wine's developers would actually get USB working ... but it's been several years now, and no such luck.
Still have digitalCAT though ... and the Dictionary Maintenance program works just fine.
Here you go ....
[ARB.rtf.zip](https://github.com/openstenoproject/plover/files/2299962/ARB.rtf.zip)

**Comment by gdwaynewarner** [comment]
You're welcome!
I opened a similar issue a few months back:
[https://github.com/openstenoproject/plover/issues/940]
... and was referred to one specifically for the Dictionary Plugin:
[https://github.com/marnanel/plover_eclipse_dictionary/pull/6]
... so hopefully, the bug has already been squashed (technical term), and should work in the next build.
