### ISSUE TITLE
I can't install midi plugin and run a midi piano setup properly

### ISSUE THREAD

**Issue by LorenzoFeroleto** [openstenoproject/plover#1006]
## Summary

In the plugin manager I can't install the midi plugin version 0.2.6, and create a michela machine-like setup with my midi piano (Kawaii VPC-1 Master keyboard)

## Reproducing

I'm really new to stenotyping and I have little experience with computer programs so I apoligize in advance for some mistakes I'll eventually do. I've installed Plover and I reached the plugin manager to download the Michela and the midi plugin. I've installed the first one (along with WPM meter, etc), perfectly fine, but the midi one is 'stucked', and it doesn't work. The dialog window looks like this:
![immagine](https://user-images.githubusercontent.com/42780537/44740230-360a7100-aafa-11e8-8640-7ea6a2f9f574.png)
I've waited some time but nothing changes, and if I close the window, Plover says that Python isn't working and the application closes itself and I have to run it again, and the plugin isn't installed.
What do I have to do?
Thanks!

## Plover Version

weekly-v4.0.0.dev8+66.g685bd33

## System

Windows 10

**Comment by benoit-pierre** [comment]
It looks like no wheels are provided for the latest release of `python-rtmidi` on [PyPI](https://pypi.org/project/python-rtmidi/#files). As a temporary workaround, try running this command in a command prompt (from plover's install directory):
```cmd
> plover_console.exe -s plover_plugins install "python-rtmidi==1.1.0"
```
Then try to install the `plover-midi` plugin again.

**Comment by LorenzoFeroleto** [comment]
I'm really sorry to bother you again but I think it's not working: I did what you said (I hope I've understood the right thing) and this is what windows says me
![immagine](https://user-images.githubusercontent.com/42780537/44814555-62e38480-abdd-11e8-9e40-1bf5915f6d2b.png)
I'm italian, so translated it's like: "It's not recognized as an internal or external command, a executable program or a batch file"
Nonetheless I tried to install the plugin again and it's not working. I'm not good with these moves on the pc so I might have done something wrong
Thanks for your patience

**Comment by benoit-pierre** [comment]
The `>` was not part of the command (just the prompt indicator): but since you left it as part of the command, and it's the redirect operator, your copy of `plover_console.exe` is now empty. Please re-install Plover, and run only this part:
`plover_console.exe -s plover_plugins install "python-rtmidi==1.1.0"`.

**Comment by Sillabix** [comment]
Hi Lorenzo, in my case with v4.0.0.dev8+8.ge062 and Windows 10 there hasn't been any problem installing the midi and the Michela plugins directly from the plugin manager.

**Comment by benoit-pierre** [comment]
Newer releases of `python-rtmidi` now include wheels, so installing the midi plugin should not be a problem anymore.
