### ISSUE TITLE
{^}troke: *

### ISSUE THREAD

**Issue by Konotori** [openstenoproject/plover#1008]
## Summary
I've seen using Plover3 so far, but today I installed Plover 4.0.0.dev8+66.
To my dismay, I found that instead of deleting strokes, `*` is typing "troke".
I looked up and indeed saw an entry in the dictionary for `{^}troke: *`.
I know it's using my own dictionary since a translation I've made that overrides the default was still there.
I then opened Plover 3.1.1 again. I found that the same `{^}troke: *` is there, but it behaves as it should, i.e, deletes strokes. 
I don't know what this translation is supposed to do, but as I see now reason for me to have added it to the dictionary I suppose that it is there by default, and therefore for a reason, which is why I have not yet removed it. 
For what it's worth, in the past I have already once installed Plover 4.0.0.dev6.5; I don't remember what it was that I didn't like about it that I returned to 3.1.1, but it wasn't this problem, so it cropped up sometime in between. 

Thank you.

## Reproducing
Install Plover 4.0.0.dev8+66. 
Open. 
Hit `*`.

## Plover Version
Plover 4.0.0.dev8+66.g685bd33

## System
Windows 8.1

**Comment by benoit-pierre** [comment]
With Plover 4.0.0, the undo stroke can be remapped (and you can map other chords to "undo" by using the translation `=undo`). This particular `{^}troke: *` entry was a mistake and has been removed from the main dictionary, so I suggest you update it by removing it and restarting Plover.
