### ISSUE TITLE
Strokes should be sorted based on steno order in the dictionary editor

### ISSUE THREAD

**Issue by amikumanto** [openstenoproject/plover#1017]
## Summary

When looking at the dictionary editor, by default it sorts the entries by stroke and sorts the strokes in alphabetical order. This means that, for example, strokes that start with A will show before any of the strokes on the left hand side of the keyboard, even though in the context of steno strokes you would expect it to be the other way around. I think changing it to sort them based on steno order would make it more intuitive.

## Plover Version

Plover 4.0.0.dev8 

## System

Windows 10

**Comment by amikumanto** [comment]
Unfortunately I'm not sure I could be much help to you there - I assumed this was a pretty straight forward ask and your attempted implementation is already a bit over my head. Sorry!

**Comment by benoit-pierre** [comment]
Fixed by #1362.
