### ISSUE TITLE
unable to enable?

### ISSUE THREAD

**Issue by bfigueras** [openstenoproject/plover#1019]
## Summary

I've downloaded plover for windows. my machine is properly hooked up with both a usb and a charger, but when I try to select "enable" under 'output' I'm not being allowed to do so. when I hit the refresh button where it shows my stentura is disconnected, I get an error message that the serial port cant open.

**Comment by km-pg** [comment]
Maybe the port isn't the right one. Go to Configure then Machine. Then click the scan button. Click the drop down and try the different ports.

**Comment by CharleyShattuck** [comment]
I think you may need to click the scan button and make a choice in the drop you down even it it looks like the right port is there. I seem to need to do this the first time I use a different keyboard. (I use quite a few because I make them and have to test each one. If I'm wrong about this, sorry. It's totally anecdotal, not thoroughly tested.

**Comment by CharleyShattuck** [comment]
Does the device show up in "device manager/Ports(COM & LPT)"? If not then maybe a serial driver needed. Just brainstorming here.

**Comment by morinted** [comment]
Sounds like you are trying to connect over USB and not serial (I'm guessing based on your message)

1. You probably want the latest pre-release version: https://github.com/openstenoproject/plover/releases/
1. After installing, open the "Plugins Manager" from the main window.
1. Install "plover-stenograph-usb" plugin.
1. Restart Plover.
1. Select "Stenograph USB" machine from the drop down to connect.

You'll need the stenograph USB drivers installed.

**Comment by mulka** [comment]
@bfigueras Did this work for you? Should we close this issue? Update the documentation to better explain?

**Comment by bfigueras** [comment]
Oops yes sorry! I fixed it with a serial cable.

**Comment by kool601** [comment]
Is someone going to close this? It seems it's been fixed for them since December.
