### ISSUE TITLE
Case is not respected for all Unicode characters

### ISSUE THREAD

**Issue by Twey** [openstenoproject/plover#1029]
## Summary

When writing a word starting with some Unicode characters, the word will be aggressively lower-cased.

## Reproducing

1) add a dictionary entry for an upper-case non-ASCII Unicode character, e.g. `Æ`:
```json
{ "5E": "Æ" }
```
2) use Plover to enter the stroke in a lower-case context.  See the character appear in lower-case (e.g. `æ`).
3) use Plover to enter the stroke in an upper-case context.  See the character appear in lower-case again.

## Plover Version

Plover 4.0.0.dev8

## System

NixOS, installed from Nix derivation.  XMonad, no DE, &c.

**Comment by fourshade** [comment]
What do you mean by "lower-case" or "upper-case" context? Do you mean, beginning of sentence/end of sentence? I couldn't replicate it on Windows using 4.0.0.dev8+3fdda2 (latest commit as of now). The Æ character always came out uppercase.

**Comment by SeaLiteral** [comment]
I've sometimes had trouble with Å, and just that one character. It gets stuck in lowercase and I can't write it in uppercase until it gets unstuck, which I first wound I could do by restarting Plover, then I found scrolling the suggestions window up and down could also help. I haven't figured out how to cause it to get stuck though.

**Comment by SeaLiteral** [comment]
I'm on Ubuntu, in case it matters. Running from source. But for me, this doesn't affect the letter Æ at all. But, as I say, Å sometimes gets lowercased. It happened again while writing this message, and it stopped happening when I tried to write the lowercase å and then again the uppercase one. And it never uppercases it when it shouldn't. It happens both with fingerspelling and when the characters appear in words that I use.
