### ISSUE TITLE
Mac development instructions don't say how to install plugin manager when running from source

### ISSUE THREAD

**Issue by mulka** [openstenoproject/plover#1031]
## Summary

When I ran from source (using ./launch.sh), the plugin manager didn't show up by default. I didn't see any documentation about how to install it on Mac.

## Reproducing

Follow Mac development instructions here:
https://github.com/openstenoproject/plover/blob/master/osx/README.md

Use ./launch.sh to run Plover. Notice plugin manager doesn't show up.

## Plover Version

3fdda2c

## System

macOS High Sierra 10.13.6

**Comment by mulka** [comment]
After I asked in Discord, oktopuse told me to just install the plugin manager with pip, which you can find in pypi here:
https://pypi.org/project/plover-plugins-manager/

Is that the right way to do it? 

I then opened up the Linux development instructions and found this little tidbit:

`To install the standard plugins, you can use:
pip3 install --user -e . -r requirements_plugins.txt`

Wondering if it is the same on Mac.

**Comment by benoit-pierre** [comment]
The plugins manager itself is a plugin, so yes, using pip is one way to install it.

**Comment by mulka** [comment]
So, I thought I fixed the problem from #1032 , but ran into another when running `pip3 install --user -e . -r requirements_plugins.txt`

```
  Running setup.py develop for plover
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -c "import setuptools, tokenize;__file__='/Users/mulka/Documents/Code/plover/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --user not recognized
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -c "import setuptools, tokenize;__file__='/Users/mulka/Documents/Code/plover/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /Users/mulka/Documents/Code/plover/
```

**Comment by benoit-pierre** [comment]
That's a known bug in setuptools/pip with PEP 518 support: https://github.com/pypa/setuptools/issues/1405.

**Comment by mulka** [comment]
Alrighty then. So I guess the work around is adding --no-build-isolation to the end of the command?

`pip3 install --user -e . -r requirements_plugins.txt --no-build-isolation`
