### ISSUE TITLE
Instructions broke my pip :-(

### ISSUE THREAD

**Issue by mulka** [openstenoproject/plover#1032]
## Summary

I think the Mac development instructions broke my pip :-(

After I ran this:
`pip3 install --user -r requirements.txt`

pip3 stopped working:
Kyles-MacBook-Pro-3:plover mulka$ pip3
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pip3", line 7, in <module>
    from pip import main
ImportError: cannot import name 'main'

## Plover Version

3fdda2c

## System

macOS High Sierra 10.13.6

**Comment by benoit-pierre** [comment]
The later versions of pip use a different main entry point, I assume you ended up installing a new pip in your user site, but because you still use the system launcher, the wrong entry point is being used. Update your PATH: use `python3 -m site` to get an idea of where your user site is. Alternatively, you can invoke pip with `python3 -m pip`.

**Comment by mulka** [comment]
Kyles-MacBook-Pro-3:plover mulka$ python3 -m site
sys.path = [
    '/Users/mulka/Documents/Code/plover',
    '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip',
    '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6',
    '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload',
    '/Users/mulka/Library/Python/3.6/lib/python/site-packages',
    '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages',
]
USER_BASE: '/Users/mulka/Library/Python/3.6' (exists)
USER_SITE: '/Users/mulka/Library/Python/3.6/lib/python/site-packages' (exists)
ENABLE_USER_SITE: True

**Comment by benoit-pierre** [comment]
I don't know what's the standard user site bin directory on macOS, using `python -c 'from pip._internal.locations import bin_user; print(bin_user)'` should print it. This directory should contain a working pip launcher.

**Comment by km-pg** [comment]
I think for me it was /Users/mulka/Library/Python/3.6/bin. I added that to my path, and it seems to work now.

**Comment by mulka** [comment]
I think for me it was /Users/mulka/Library/Python/3.6/bin. I added that to my path, and it seems to work now.

**Comment by mulka** [comment]
(to get that, I just just took the USER_BASE from the previous command and added /bin

**Comment by mulka** [comment]
I'm curious why you guys aren't using a virtual environment.
