### ISSUE TITLE
Better support for 2KRO keyboard by slightly delaying key_up

### ISSUE THREAD

**Issue by user202729** [openstenoproject/plover#1035]
## Summary

*(although arpeggiate is required on non-NKRO keyboards, at least we should try to make it easier)*

On 2KRO keyboards, assuming the 3 keys O, E and U cannot be held at once, then doing the following:

* Hold O
* Hold EU
* Release O
* Release EU

While the expected output is `/`, the actual output is `to I`.

The events sent, in processed order, are:

* O pressed
* O released
* EU pressed
* EU released

If the "O released" event is delay for a short while, for example 0.01 seconds (this patch would do it on Linux)

```
diff --git a/plover/oslayer/xkeyboardcontrol.py b/plover/oslayer/xkeyboardcontrol.py
index 4004d54..7c9b770 100644
--- a/plover/oslayer/xkeyboardcontrol.py
+++ b/plover/oslayer/xkeyboardcontrol.py
@@ -245,7 +245,7 @@ class KeyboardCapture(XEventLoop):
             if modifiers == 0:
                 self.key_down(key)
         elif event.evtype == xinput.KeyRelease:
-            self.key_up(key)
+            threading.Timer(0.01, self.key_up, (key,)).start()
 
     def start(self):
         self._update_devices()
```

the expected output `/` would be obtained.

Also, having the output delayed by 0.01 seconds is usually not a problem.

## Plover Version

Latest master.

## System

Arch Linux.

**Comment by morinted** [comment]
If the O key is not physically released before the EU keys are pressed, this shouldn't happen at the code level. I've definitely never noticed this behavior on Windows or Mac. Can't speak for Linux.

**Comment by user202729** [comment]
@morinted It may be that you're using a better keyboard and don't notice the issue.

More information:

* If the E and U are not pressed simultaneously, the keydown event for the button that is pressed first is sent at the correct time (before the release of O) and the bug doesn't happen.
* The keydown event of E and U are sent *right after* O is released. (that's why delaying the keyup event for 0.01 seconds fix the issue)

**Comment by morinted** [comment]
If we were to support this, I wouldn't want it on by default (because of false positives being possible).

It would need to be added as an opt-in setting, and we'd have to implement it cross-platform. More settings means more potential confusion for end-users.

That's a pretty big ask for supporting keyboards that, in all likelihood, can't actually handle sending chords that are 6+ keys, due to circuitry limitations.

I think it's an okay idea and maybe something to run in a local fork until you get a better keyboard, I just don't think it's something I'd want to give everyone. Does that make sense?

**Comment by user202729** [comment]
That makes sense, but I think:

* I wouldn't worry about false positive, 0.01 second is too small to be noticed.
* Since we are already using the `threading` module, delaying the operation is not hard - just start a `threading.Timer`.

**Comment by benoit-pierre** [comment]
I agree with @morinted: I don't think we want the added complexity, and you can always make a dedicated machine plugin for Linux.
