### ISSUE TITLE
malloc_consolidate(): invalid chunk size crash when running with pyqt

### ISSUE THREAD

**Issue by verbalshadow** [openstenoproject/plover#1042]
## Summary

When running Plover whether from installed version or from git master it crashes with malloc_consolidate(): invalid chunk size error.

## Reproducing

run `plover` from command line or `launch.sh` from git

[verbalshadow@ozma plover]$ plover
malloc_consolidate(): invalid chunk size
Aborted (core dumped)

[plover.log](https://github.com/openstenoproject/plover/files/2800530/plover.log)

https://pastebin.com/WdG7Tcww

When run `--gui none` steno works.

## Plover Version

git version 3fdda2c &&
installed from AUR plover-git 4.0.0.dev8-2

## System

OS: ARCH LINUX fully updated
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]
python-pyqt5 5.11.3-2

**Comment by cass00** [comment]
FYI, if the list in `QApplication` is not empty then it does not crash, e.g.
```
from PyQt5.QtWidgets import QApplication, QLabel
app = QApplication(['a'])
label = QLabel('Hello World!')
label.show()
app.exec_()
```

**Comment by benoit-pierre** [comment]
Is that still an issue?
