### ISSUE TITLE
No output on Mac with Elan Cybra over USB

### ISSUE THREAD

**Issue by ElliotHolland** [openstenoproject/plover#1053]
## Summary

It's all in the title. Plover says it's connected using the stenograph USB plug-in, and it recognizes the strokes in the paper tab, but it won't output English (or anything) in textedit, microsoft word, or my browser's URL bar.  

## Plover Version

4.0.0.dev8+66.g685bd33 

## System

10.14

**Comment by morinted** [comment]
Are you able to use the Keyboard machine with your computer's keyboard? You
may need to first enable Accessibility Permissions for Plover.

https://support.apple.com/en-ca/HT202866

This will rule out the Cybra as the problem if it shows the same behavior.

**Comment by ElliotHolland** [comment]
Plover was enabled under accessibility. I can use my computer's keyboard normally.

**Comment by ElliotHolland** [comment]
If you mean if I can use my computer's keyboard as a steno machine through plover, no. It says disconnected since I've updated plover to 4.0.0

**Comment by ElliotHolland** [comment]
This issue has been resolved by deleting and reinstalling Plover. Deleted the accessibility of a text expansion software. Thanks everyone for your help! I'm writing this on my steno machine now!
