### ISSUE TITLE
Plover Shortcut Keeps Disappearing

### ISSUE THREAD

**Issue by Darcy783** [openstenoproject/plover#1056]
## Summary

I downloaded and installed Plover for Windows yesterday, and pinned the shortcut to my task bar.  This morning, I got an error saying that the application for which the shortcut had been made had been moved or something.  I did not touch it at all.  And the installation file is no longer in my Downloads folder either (I didn't move it).

**Comment by gdwaynewarner** [comment]
Darcy, I would try downloading Plover again, leave it on the desktop (though my installation on my Windows 7 laptop is in the Programs folder), and see if that works. I try to empty my Downloads folder at least once a month, and never run anything from there.

**Comment by Darcy783** [comment]
Is it not an installation program that gets downloaded?  I usually download installation files to Downloads, run them from there, and install to Program Files or an appropriate other folder.  Then I create shortcuts as necessary on the desktop.

**Comment by gdwaynewarner** [comment]
If I recall correctly, the "win32.zip" file is the full program. The "win32.setup.exe" is the installer.

**Comment by Darcy783** [comment]
I downloaded it and moved it to the Program Files folder.  Now, my shortcut has stayed.  Thanks!
