### ISSUE TITLE
Interactive Drills not recognising keystrokes 

### ISSUE THREAD

**Issue by mushyoshi** [openstenoproject/plover#1070]
## Summary

I have followed the instructions in lessons 1 and 2 with success stroking keystrokes in a word document as instructed but the interactive drills aren't working. I installed flash player (on Mac OS) and the programme seems to be working and I am stroking the hints but it isn't reading correctly. I'm using an Ergodox ez if relevant. Thanks

**Comment by mushyoshi** [comment]
I tried to edit the above so apologies if comment not the best format. I am using the Mac version 3.1.1 py2 and the latest flash player is installed (at least one of the practice sites required it). I am on the latest Mac OS.
Many Thanks for any assistance :) 

https://github.com/openstenoproject/plover/releases/download/v3.1.1/plover-3.1.1-py2-mac.dmg

**Comment by benoit-pierre** [comment]
Just to be clear, since there are a number of different learning resources, what are you using exactly?

**Comment by mushyoshi** [comment]
Hi and thanks!

It is “Plover, Learn!” 

It is the resource of the “interactive drills” linked to in the main “Learn Plover!” resource by Zach Brown. 

It looks like a great resource that would make the lessons much more effective and I would love to work out what’s going on.
If you have suggestions for other similar resources I might have better luck with I would be grateful for advice. I haven’t explored the other resources on the wiki page yet as this type of drill seems an ideal starting place. I would like to work through the lessons with the drills if possible. The lessons are great otherwise.

Thanks again for you help. I appreciate your time,
Kate

**Comment by benoit-pierre** [comment]
Sorry, but with the state of Flash in general, and particularly on Linux, I can't even get the drills to load correctly. I suggest using the [Learn Plover! drills](https://joshuagrams.github.io/steno-jig/learn-plover.html) on [Steno Jig](https://joshuagrams.github.io/steno-jig/) instead.

**Comment by mushyoshi** [comment]
Oh thank you! Reassuring that it’s not just me. Thank you for the suggestion, I will do that.
Do the StenoJig drills need flash? I will uninstall if not. I’m on a Mac and would prefer to skip flash completely... (in new to Mac, not an IT person so never got near Linux, maybe one day :) I’m just here for the fast typing!
Thank you so much again,
Kate

**Comment by benoit-pierre** [comment]
> Do the StenoJig drills need flash? I will uninstall if not.

They don't.

**Comment by mushyoshi** [comment]
Thank you heaps! Have an awesome day 😊
