### ISSUE TITLE
words get typed out wrong

### ISSUE THREAD

**Issue by grenzionky** [openstenoproject/plover#1071]
## Summary
[heres a video](https://streamable.com/bv4pp)  of me typing (excuse the  flickering, its only the video ❨not on my  actual screen❩).   many words get typed out wrong, like "of" got typed out as  “fo” and “you'll” got typed out as “youll'” first so when i tried again it got typed out as “yo'ull”. as you can see in the video, it happens pretty often.
[heres another video](https://streamable.com/213dv) of me typing into the firefox omnibar (search bar). the same thing also happens in opera and chrome's omnibar .

## Plover Version
 Im currently using `Plover 4.0.0.dev8+152.gd4ace92`  but the same bug was present on 3.1 too  (i switched to 4 with the hopes that it will be gone, but it isnt…)

## System
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.0.9-2-MANJARO
DE: KDE 5.57.0 / Plasma 5.15.4
WM: KWin
 the first video is plover that I got plover from the AUR, and the second video is what i just downloaded from source, but both exhibit the same problem.

EDIT: I think #1059 has the same problem as me

**Comment by benoit-pierre** [comment]
Does it happen with other applications (maybe something lighter than the behemoths that are most web browsers)? Do you have an input method running (e.g. ibus)? Does it happen when simulating input with xdotool (see https://github.com/openstenoproject/plover/issues/1059#issuecomment-511785907)?
