### ISSUE TITLE
Default dictionaries should save to disk right away

### ISSUE THREAD

**Issue by mulka** [openstenoproject/plover#1074]
## Summary

When opening Plover for the first time, the default dictionaries show up in the Plover UI, and I can hover over them to see where they would be on disk, but they don't show up on disk in those locations until after I close the app the first time. I'm thinking these default dictionaries should be saved to disk upon first open instead of on first close so there isn't confusion there.

## Reproducing

Start with a fresh copy of Plover, no dictionaries.
Open Plover for the first time.
Notice dictionaries are in the Plover UI and you can see the file path if you hover over them.
Notice that they aren't on disk.

## Plover Version

4.0.0.dev8+66.g685bd33 

## System

Mac 10.14.5

**Comment by benoit-pierre** [comment]
They are saved immediately, I don't know why you're not seeing them. What are you using for checking? Maybe you need to refresh?

**Comment by mulka** [comment]
Using the MacOS Finder. Pretty sure that gets updated right away and I don’t think there’s a refresh button

**Comment by benoit-pierre** [comment]
Are you sure you're looking in the right location? Have you checked with the recently added "Open config foder" in the File menu?

**Comment by mulka** [comment]
I just re-tested this and they do seem to be saved right away. Not sure what was happening before.
