### ISSUE TITLE
Suggestion: Have Plover Create a File With all of the Outlines Revealed via Plover Suggestions Window

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#1078]
## Summary

While transcribing a court case the other day with the Suggestions window open, there were several phrases and outlines that were already in my dictionary that I had obviously forgotten were available. It might be good to have Plover collect such outlines in a list for the user to access afterwards for study via a flash card program. 

## Reproducing

Essentially, I was writing up a rather interesting case from Kentucky the other day, and the Suggestions window would suggest all sorts of outlines I had in one dictionary or another that I had forgotten about.

I wrote some of the more interesting outlines down on a few pieces of paper (front and back, two and a half pages, for the curious) and am currently going through those outlines and adding them to a file for one of those flash card programs ([Genius](https://sourceforge.net/projects/genius), for the curious) for later practice. Hopefully that will cement those outlines into muscle memory so I don't stroke them the long way the next time they come up.

## Plover Version

4.0.0.dev8+66.g685bd33 

## System

Mac OS X 10.10.5

**Comment by mulka** [comment]
You just want a file with the output of the suggestions window?

Are you aware that you can copy/paste the contents of the suggestions window? Ctrl+A to select all, Ctrl+C to copy, and Ctrl+V to paste.

Would that work? Would the file need to be in a specific format?

**Comment by gdwaynewarner** [comment]
Kind of.
While I am aware that I can copy and paste and all that via the steno keyboard, it is not necessarily something I want to do when I am in the middle of transcribing an audio file, which is where the file would come in handy! :o)
As for formatting, .txt would be fine.

**Comment by mulka** [comment]
I don’t think you would do it in the middle. You would do it at the end. Maybe I’m missing something

**Comment by gdwaynewarner** [comment]
Hmm. I could *SWEAR* I responded to this one already ...

You're right -- at the end would be best.  That way, I can do whatever I need to do with that list of outlines and words, including plugging them into one of those flash card programs.

One potential problem might be the suggestions that appear for word parts, but for that, perhaps some way to control which suggestions should be displayed ... as in, "Only show outlines for translations with greater than three letters," or something like that.

**Comment by antistic** [comment]
Would [plover-clippy](https://github.com/tckmn/plover_clippy) be useful?

**Comment by gdwaynewarner** [comment]
Maybe! I'll have to install it and see!

**Comment by antistic** [comment]
Since then I've created [plover-cards](https://github.com/antistic/plover_cards) which could be helpful if you use Anki as your flash card program.

**Comment by gdwaynewarner** [comment]
I actually use Genius these days:

[https://sourceforge.net/projects/genius](https://sourceforge.net/projects/genius)
