### ISSUE TITLE
Space before comma and period

### ISSUE THREAD

**Issue by ms009986** [openstenoproject/plover#1080]
## Summary

When I type certain words with suffixes and then a comma, there is a space between the end of the word and the comma.  This also happens with periods, maybe other suffixes.

Example:
SKWRUFPL/-R/RBGS
comes out
jumper ,

Dictionary entries:
SKWRUFPL  = jump
-R = {^er}
RBGS = {,}

What I've tried:
Renaming the comma entry to {^,} or {^}{,} or {^^^^^,}, etc., but same extra space.  
My dictionaries are all RTF, so I've tried adding the user.json dictionary with the {,} definition, but no effect.

If I add the word jumper outright to my dictionary, the space disappears, but adding every word that ends in 'er' isn't a very workable solution to my mind.  :-)

Is this a bug?  If so, what's the workaround?  If not, what am I doing wrong?

Thanks!

## Reproducing

Always

## Plover Version

Possibly relevant information:
plover-3.1.1-py2-windows
Windows 10
Stentura 400 SRT
Phoenix Theory
Familiar with Eclipse
RTF dictionaries, not JSON

**Comment by benoit-pierre** [comment]
I can't reproduce the issue on master, considering the number of changes to the formatting code since 3.1.1, I suggest trying the last 4.0.0 pre-release and see if you can reproduce the problem with it.

**Comment by ms009986** [comment]
Do we have an ETA of 4.0 stable release? If it's soon I will live with this for a little longer  and just wait for that.  If not I will try pre-release. Thanks so much!

**Comment by ms009986** [comment]
You can close this one out if you like, I did try a pre-release and am having much better luck.

:-)

Chris
