### ISSUE TITLE
Warning when plover.config missing 'undo_levels'

### ISSUE THREAD

**Issue by benhormann** [openstenoproject/plover#1081]
## Summary

I installed latest release (i.e. no existing config). I soon started getting a warning when launching Plover, which reads "ERROR: invalid value for 'undo_levels' option plover.config.InvalidOptionConfig: None". No other impact that I've noticed.

Changing the number of undo levels saves the option, and so the warning ceases.

## Reproducing

Delete plover config, launch plover, change configuration to start attached, restart plover.

## Plover Version

Plover 4.0.0.dev8+66.g685bd33

## System

Window 7 64 bit

**Comment by Geremia** [comment]
I get `ERROR: invalid value for 'undo_levels' option plover.config.InvalidConfigOption: None` with weekly-v4.0.0.dev8+66.g685bd33.AppImage.

**Comment by benoit-pierre** [comment]
I can reproduce using the steps above with `weekly-v4.0.0.dev8+66.g685bd33`, but not master (and the configuration is correctly fixed when using master and tweaking it). So the fix will be available in the next weekly, in the meantime, @Geremia, you can use the workaround above (change the undo levels).
