### ISSUE TITLE
List Stenokey in Supported Hardware

### ISSUE THREAD

**Issue by arunisaac** [openstenoproject/plover#1087]
Could you please list the Stenokey ( https://github.com/mike-ady/Stenokey ) stenographic keyboard in the list of supported hardware at https://github.com/openstenoproject/plover/wiki/Supported-Hardware ?

Thank you.

**Comment by gdwaynewarner** [comment]
I am fairly sure that if you were to put together, say, ten of these and post their availability in the Plover Google Group, you would sell out in no time flat!
I would love to have one myself, but 3D printing isn't something I can readily do, and I'm sure I am not the only one in that position.

**Comment by arunisaac** [comment]
That's an interesting idea. I'll certainly consider it. But, for now,
I'm only making one for myself and another for a friend. Perhaps, once I
am confident with the process, I can make it for others.

**Comment by gdwaynewarner** [comment]
A good place to start ...!

Might be a good idea to send one to Mirabai for greater exposure. You might have to start hiring people to put them together!

**Comment by arunisaac** [comment]
Perhaps you misunderstand. I didn't actually develop the Stenokey. It
was developed by Mike and I think he already sent it to Mirabai. See
http://plover.stenoknight.com/2018/01/stenokey-post-part-1.html

**Comment by gdwaynewarner** [comment]
Oops! Wrong guy! Sorry about that!

**Comment by nsmarkop** [comment]
@arunisaac Added it to the wiki page. Let me know if you think any wording or whatnot should be changed:

https://github.com/openstenoproject/plover/wiki/Supported-Hardware#dedicated-machines-designed-for-use-with-plover

**Comment by arunisaac** [comment]
No, that is sufficient.

Thanks!
