### ISSUE TITLE
Request - Two dictionary files

### ISSUE THREAD

**Issue by mighele** [openstenoproject/plover#109]
Plover should come with two dictionary files. The base one dict.json and the user's custom one (starts off empty) called userdict.json.

That way if a release of Plover requires the users to update their base dictionary, their own entries will not be affected.

Also, when using the new feature to add my own dictionary entry it re-orders the dictionary file to be alphabetical. So if I want to see my custom strokes that I added to my dictionary with a text editor, they are now no longer at the top of the file where I put them, but they are mixed in amongst all the other entries in the file.

If the userdict.json file is the last dictionary in the list in Plover, all new custom entries will be put into this file and the base dictionary file will not be affected.

I am willing to make the code change myself if developer time is an issue.

Thanks
Mike N
Windows 7
Plover 2.5.1

**Comment by morinted** [comment]
I like this idea. I think that it would be nice to come with: commands (list of commands), main (default dict), and user/custom (user's dictionary) by default. Would the user dictionary get stored in application data or would we move it somewhere more local like ~/plover for easy location?

**Comment by morinted** [comment]
Working on this, guys. I'll submit a PR shortly.
