### ISSUE TITLE
Clicking on the Plugins Manager button causes Plover to crash

### ISSUE THREAD

**Issue by jladdjr** [openstenoproject/plover#1091]
## Summary

Clicking on the Plugins Manager button any time after start-up causes Plover to crash.

## Reproducing

1. Launch Plover (do this from the terminal in order to see traceback)
2. Click on the Plugins Manager button
3. Plover crashes. The terminal reports:
```
[1:1:0100/000000.666492:ERROR:broker_posix.cc(41)] Invalid node channel message
Segmentation fault (core dumped)
Received signal 7 BUS_ADRERR 7f91fe3d35f0
```

## Plover Version

```
/usr/local/bin/plover-4.0.0.dev8.66.g685bd33-x86_64.AppImage --version
Plover 4.0.0.dev8+66.g685bd33
```

## System

Fedora 31
GNOME 3.34.1
x11
Using the AppImage

**Comment by mulka** [comment]
Plugins Manager works for me with that version on Mac from the terminal. Maybe it is a Linux or AppImage specific issue?

**Comment by davidedelvento** [comment]
I confirm this behavior with `Plover 4.0.0.dev8+66.g685bd33` on

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

Just for the sake of it, I tried also `Plover 4.0.0.dev8+8.ge062cda` and the failure mode is slightly different, namely spitting out also `Received signal 7 BUS_ADRERR 7f1525c06330` but the end result is the same: Invalid node channel message and Segmentation fault (core dumped).

I haven't tried from source yet.

**Comment by benoit-pierre** [comment]
Can you try upgrading the plugins manager itself; from the terminal, run: `plover-4.0.0.dev8.66.g685bd33-x86_64.AppImage -s plover_plugins install --upgrade --upgrade-strategy only-if-needed plover_plugins_manager`.

**Comment by davidedelvento** [comment]
Yes, this solved the issue! Great thanks!

**Comment by marnen** [comment]
@benoit-pierre Thanks, this also solved an issue on Mac OS where Plover couldn't contact the PyPi repository to get a plugin list (but the path is different, so I had to run `/Applications/Plover.app/Contents/MacOS/Plover -s plover_plugins install --upgrade --upgrade-strategy only-if-needed plover_plugins_manager`). Perhaps it's worth having an "update plugins manager" command in the GUI for this?
