### ISSUE TITLE
Plover 4 doesn't display properly on high DPI screens

### ISSUE THREAD

**Issue by AshenColors** [openstenoproject/plover#1093]
## Summary

On a Windows system using high DPI, Plover opens up looking like this:
![image](https://user-images.githubusercontent.com/3249074/70598059-d0cb7980-1b9e-11ea-8288-96798ac24d64.png)

PyQt5 has an environmental variable that enables DPI support, so a workaround in Windows is to set QT_AUTO_SCREEN_SCALE_FACTOR = "1". The main Plover window is displayed correctly, besides the fuzzy-looking arrows on the right of the toolbar. As far as I can tell, everything else continues to work fine with no issues.
![image](https://user-images.githubusercontent.com/3249074/70598615-13da1c80-1ba0-11ea-8818-c7567bc68da8.png)

## Reproducing

On Windows 10, set the resolution to 3840 × 2160, and set scaling to 250%. Other high DPI configurations may also exhibit the issue, but haven't been tested.

## Plover Version

Plover 4.0.0.dev8+66.g685bd33 

## System

Windows 10 Pro 1903

**Comment by mulka** [comment]
I wonder if this also affects Macs. I'm not sure I have a high DPI display to test on though.

**Comment by marnen** [comment]
@mulka It seems fine on my Retina MacBook Pro.

**Comment by backerman** [comment]
It seems to work for me on an XPS 17 (3840x2400) at 225% scale.
