### ISSUE TITLE
Warnings when running ./test.sh on Mac

### ISSUE THREAD

**Issue by mulka** [openstenoproject/plover#1101]
## Summary

Getting these warnings when running ./test.sh on Mac:

venv/lib/python3.6/site-packages/objc/_bridgesupport.py:834
  /Users/mulka/Documents/Code/personal/plover/venv/lib/python3.6/site-packages/objc/_bridgesupport.py:834: DeprecationWarning: use createStructAlias instead
    warnings.warn("use createStructAlias instead", DeprecationWarning)
  /Users/mulka/Documents/Code/personal/plover/venv/lib/python3.6/site-packages/objc/_bridgesupport.py:834: DeprecationWarning: use createStructAlias instead
    warnings.warn("use createStructAlias instead", DeprecationWarning)
  /Users/mulka/Documents/Code/personal/plover/venv/lib/python3.6/site-packages/objc/_bridgesupport.py:834: DeprecationWarning: use createStructAlias instead
    warnings.warn("use createStructAlias instead", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html

## Reproducing

clone master
use python 3.6
install requirements
run ./test.sh

## Plover Version

master branch
f4e4536

## System

Mac
10.15.3 (19D76)

**Comment by mulka** [comment]
It looks like upgrading pyobjc will fix this. I upgraded to 6.1

**Comment by benoit-pierre** [comment]
We updated to 6.2 last year.
