### ISSUE TITLE
Making a steno machine from a DB board

### ISSUE THREAD

**Issue by AnelSA** [openstenoproject/plover#1102]
Hello everyone.

I am very new to this. I showed my dad how you built your own steno-keyboards and he wants to try and make one from a plastic DB board.

According to him, it should work but the problem would be to do the connection to the computer.

Do any of your technical guys and girls have any ideas?

I will post photos and updates as we do it, should we be able to solve this issue.

Thank you.

**Comment by JoshuaGrams** [comment]
I'm not sure what a DB board is, but I'd suggest hooking it up to an Arduino. It's fairly simple to use the Arduino toolchain to write firmware to send the chords to Plover, e.g. https://github.com/SmackleFunky/StenoMod-C

That's what we did when we made an experimental steno board from paper and aluminum foil.
![paper-steno-done](https://user-images.githubusercontent.com/39438/74458265-7200d580-4e57-11ea-9ce5-38f3b61d1db4.png)

**Comment by AnelSA** [comment]
Thank you. I didn't even think about the different terminology we use. Here is a link
https://www.arb.co.za/distribution-board-plastic-surface-18-way.html

![dbs-0809_1](https://user-images.githubusercontent.com/61020917/74460788-27527e00-4e96-11ea-872e-0a322704d0f1.jpg)

**Comment by memoriasIT** [comment]
Well the enclosure you have doesn't matter when creating a keyboard.
I am unsure of how deep you want to go into the rabbit hole, but these are your routes:
- You want to buy parts for making a mechanical keyboard: you will just require to solder (or not depends on what you look for but usually you will need to).
- You want to design the circuit and everything from scratch: there are tons of resources out there, I like this series of videos: https://youtu.be/BhFqkVggv8Q

Just design your keyboard with the layout you want and make sure you have NKRO, you should be okay :)
I can give more details if you want to.
