### ISSUE TITLE
Suggestion:  Make the Steno Section of the Dictionary Only Accept Steno Outlines

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#1107]
## Summary

I ran across a few suggestions for outlines on Facebook that looked useful:

![Screen Shot 2020-03-11 at 1 24 04 PM](https://user-images.githubusercontent.com/17680111/76461095-78be3200-639c-11ea-92cb-9370c1d34612.png)

So I added them first to my copy of digitalCAT's Dictionary Maintenance Program:

![Screen Shot 2020-03-11 at 1 32 15 PM](https://user-images.githubusercontent.com/17680111/76461287-dc485f80-639c-11ea-89e1-446a807d168c.png)

... where when I want the steno for J to appear, I actually hit the J on my computer's keyboard.

Unfortunately, when I was adding that particular outline to Plover, I forgot that I couldn't just hit the computer's J key, so Plover locked up for several minutes before shutting down completely.

That's why making that particular field "steno only" might be a good idea. 

## Reproducing

Open a Plover dictionary
Add the pictured outline, but type the letter J instead of SKWR
Wait for either an error message (didn't happen) or Plover to crash. 

[plover.log](https://github.com/openstenoproject/plover/files/4320803/plover.log)

## Plover Version

4.0.0.dev8+66.g685bd33

## System

Mac OS X 10.10.5

**Comment by morinted** [comment]
I don't actually receive a crash here when entering nonsteno. I think the feature suggestion is good though.

**Comment by gdwaynewarner** [comment]
Interesting ...! It was definitely a surprise, though!

**Comment by benoit-pierre** [comment]
Fixed by #1362.
