### ISSUE TITLE
MIDI not available 

### ISSUE THREAD

**Issue by davidedelvento** [openstenoproject/plover#1109]
## Summary

I have installed the plover-michela plugin and I was expecting to see MIDI as an option in the Machine menu, but there is not

## Reproducing

I connected a MIDI keyboard via USB. Started plover and selected one of the two michela options (tried both orthographic and phonetic) in the configure->system menu. Clicked Apply. Searched in the machine list expecting to see MIDI, but it was not there.

Verified via lsusb that the MIDI keyboard was properly connected. Verified it works using qjack and qsynth. It does. Do I need to install also plover-midi? I can't because of issue #1108 

## Plover Version

4.0.0.dev8+66.g685bd33 (AppImage)

## System

Distributor ID: Ubuntu
Description: Ubuntu 18.04.4 LTS
Release: 18.04
Codename: bionic

**Comment by benoit-pierre** [comment]
Yes, if you want to use the Michela theory with a MIDI keyboard, you need both plugins.
