### ISSUE TITLE
Stroke Display window is missing Z

### ISSUE THREAD

**Issue by LilithHafner** [openstenoproject/plover#1110]
## Summary

The Stroke Display window is missing Z in the header:
<img width="216" alt="Screen Shot" src="https://user-images.githubusercontent.com/60898866/77109053-43938e80-69f1-11ea-91ae-fdecd29cf0bc.png">

## Reproducing

I have been unable to reproduce this issue after restarting Plover.

## Plover Version

Plover 3.1.1

## System

macOS Catalina
Version 10.15.3 (19D76)

**Comment by gdwaynewarner** [comment]
Have you tried version 4.0xxx of Plover? If not, you should:

[https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)

That should make things quite a bit easier for you, I would imagine ... I have it installed on my Macs that are all running Yosemite (Mac OS 10.10.5).

**Comment by LilithHafner** [comment]
Thanks.

I am trying weekly-v4.0.0.dev8+66.g685bd33 (on Windows 10, now), and have yet to notice this issue.
