### ISSUE TITLE
Plover messed with KDE keyboard layout

### ISSUE THREAD

**Issue by Geremia** [openstenoproject/plover#1113]
## Summary

Plover - KDE Plasma keyboard layout conflict

## Reproducing

I ran Plover, then after rebooting KDE forced my keyboard layout to standard US, when it was Dvorak before. Keyboard system settings didn't change the layout back to Dvorak.

I had to run:
```
setxkbmap dvorak
```
and
```
xmodmap ~/.Xmodmap
```
to get things back to normal. Normally, I don't need to do this.

Did Plover modify some keyboard layout file?

## Plover Version

weekly-v4.0.0.dev8+66.g685bd33 AppImage

## System

Slackware Linux -current
KDE Plasma 5.18.3

**Comment by Geremia** [comment]
I had a file permissions issue on my end.

**Comment by morinted** [comment]
Thanks for the follow up!

**Comment by Geremia** [comment]
@morinted I did get an issue where X11 (it seems) completely froze up while I was typing in Plover. Does Plover leave crash logs?
