### ISSUE TITLE
macOS: Font selection not working

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#1114]
## Summary

Font selection on suggestions and paper tape windows do nothing on macOS Catalina. Unclear when the issue was introduced.

Additionally, the default font for Mac on the paper tape is not monospace:

<img width="413" alt="Screen Shot 2020-04-01 at 1 19 15 PM" src="https://user-images.githubusercontent.com/5840970/78167057-ce29b400-741b-11ea-8c7f-08fbcb2a3170.png">

## Plover Version

Plover 4.0.0.dev8 

## System

macOS Catalina 10.15.4

**Comment by perryprog** [comment]
Just an FYI, if I press the font selection button within the paper tape window (the "Tt" one), I'm able to change the font to a monospace one which works fine.

**Comment by morinted** [comment]
Fixed by https://github.com/openstenoproject/plover/pull/1122
