### ISSUE TITLE
Windows 10 Plover error "Trackback"

### ISSUE THREAD

**Issue by TazBand** [openstenoproject/plover#1133]
## Summary

Hi, sorry, I know nothing about coding, I'm a steno student who has been using Plover without issue up until tonight when suddenly I'm getting the following error message (see attached).

Any help is appreciated. All I do is download the .exe file for windows and try to run it. The program will not open. This issue reporting box is very intimidating, if more info is needed I'll gladly provide it but honestly I don't understand half of what is being asked for. 
![plover error](https://user-images.githubusercontent.com/67246447/85238537-9ae43900-b3fc-11ea-9b71-669914bc6358.png)

**Comment by gdwaynewarner** [comment]
Which version of Plover are you using? If you're using version 3.0, you should download version 4.0 from here:

[(https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)]

You want the .zip file. Hopefully that will take care of the problem.
