### ISSUE TITLE
Plug-In-Manager Error: Too Many Requests

### ISSUE THREAD

**Issue by 7632416** [openstenoproject/plover#1142]
## Plugins Manager Error: failed to fetch list of available plugins (Too Many Requests)

Plug In Manager version 0.5.11

## Reproducing

Sorry, I am at a loss what to write, but:
Plover runs okay as normal, but when I went to install and explore a plug-in I think I read about somewhere (use Exel dictionary), I clicked on "Plug In Manager," and I receive the error code, but the Plugin Manager Windows opens and shows my four plug-ins (plugins, retro, usb,and treal) (where did Treal come from, and why can't I uninstall it?)
I can close the non-populated Plugins Manager Window and continue using Plover fine.
I am using a Stenograph Stentura Protoge on Windows 10  AND an Elan Cybra on Windows 10. Both setups arose the problem at the same time. Imagine.
I ran Plover debug on one setup, and the console window runs and runs and runs. By that I mean that the command lines and data output lines keep appearing, and do not stop. Is that right?

## Plover Version

Version 4.0.0.dev8+66.g685bd33

## System

Windows 10 2004

**Comment by BruceMustache** [comment]
I can reproduce with Linux Mint 19.3
Plover 4.0.0.dev8+66.g685bd33

**Comment by morinted** [comment]
I've opened https://github.com/benoit-pierre/plover_plugins_manager/issues/12

**Comment by benoit-pierre** [comment]
Please follow the directions here: https://github.com/benoit-pierre/plover_plugins_manager/issues/12#issuecomment-687570667.

**Comment by 7632416** [comment]
[CMD Output.txt](https://github.com/openstenoproject/plover/files/5619864/CMD.Output.txt)

Installed Plover Version 4.0.0.dev8+66.g685bd33 on new PC. Got the "Plug-in-Manager Error: Too Many Requests" error. Ran benoit-pierre's ongoing method from here: benoit-pierre/plover_plugins_manager#12 (comment). and received cmd output that included multiple "Need Visual Studio to Run this"  (or something like that).  CMD output file attached.  Does anyone have any pointers? (I need the Stentura USB extenson and the Retro-something extension.) thanks everybody.
