### ISSUE TITLE
 suggestions window doesn't understand newlines

### ISSUE THREAD

**Issue by tckmn** [openstenoproject/plover#1145]
## Summary

the suggestions window seems to ignore newlines, instead merging the last word before an R-R stroke with the first word after it

## Reproducing

after the strokes TEFT/R-R/TEFT:

![image](https://user-images.githubusercontent.com/2389333/94217142-e1877a80-fea6-11ea-8021-4d7c9d483f2b.png)

```
test:
   TEF
   T*ES
   TEFT
   TEFLT

TestTest: no suggestions
```

## Plover Version

4.0.0.dev8

## System

Linux (NixOS, no DE, i3wm, plover.dev via nixpkgs stable)

**Comment by user202729** [comment]
What definition of `R-R` do you have? 
If it's something like `{#return}` (although that is changed in the newer version of Plover), you may want to read https://github.com/openstenoproject/plover/wiki/Dictionary-Format#undoable-line-breaks-and-tabs .

**Comment by tckmn** [comment]
ah, yeah, it seems like i just forgot to update my dictionaries. thanks!
