### ISSUE TITLE
Cannot open the program

### ISSUE THREAD

**Issue by memoriasIT** [openstenoproject/plover#1148]
## Summary
It happens every time. I just downloaded Plover, and ran it once. However, when I changed the configuration and re-opened it it no longer works.
Release v3.1.1 for Windows 10.0.18362.959

Screenshot provided bellow.

## Reproducing

Open the program.
Check two of the open window on startup check boxes (the two top ones, can´t remember exact labels).
Click on Save
Close the program.
Open again the program.

I believe no log is produced, or at least that I know of.
I tried restart with no success. Also administrator rights.

![Sin título](https://user-images.githubusercontent.com/32130278/96172210-5c800600-0f26-11eb-87e7-c291a1bcc300.png)

## Plover Version
v3.1.1

## System
Release v3.1.1 for Windows 10.0.18362.959

**Comment by morinted** [comment]
Hi, thanks for your awesome bug report.

Unfortunately, this is a known issue with the older version of Plover. We're trying to release v4 at some point in the future, but for now you can download the latest alpha release which should be more stable: https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33

**Comment by memoriasIT** [comment]
Incredibly fast reply, I really love your community and hopefully I can be part of it soon.
Downloading the latest weekly release solved the problem. Thanks!
