### ISSUE TITLE
Won't save keyboard configuration settings

### ISSUE THREAD

**Issue by DSDragon** [openstenoproject/plover#1172]
## Summary

I use Plover with the /SOFT/HRUF keyboard. Every time I reopen Plover (having it open while I'm working in other programs and don't need it just uses up RAM and slows down my computer even more than it should), I have to set up the /SOFT /HRUF keyboard again to TX Bolt, despite saving the configuration settings in Plover.  Why?  I _**only**_ use /SOFT/HRUF for steno, and I have a USB ergonomic keyboard for QWERTY typing, so I would like the settings for those keyboards to stay when I have closed Plover and reopened it, instead of the /SOFT/HRUF reverting to QWERTY every time.

## Plover Version

Version 3.1.1

## System

Windows 10 Home version 1909

**Comment by user202729** [comment]
Not sure what's going on exactly, but you can try updating to version 4. https://github.com/openstenoproject/plover/releases

**Comment by benoit-pierre** [comment]
Fixed in version 4.
