### ISSUE TITLE
[Question] Plover for German

### ISSUE THREAD

**Issue by Glitchy-Tozier** [openstenoproject/plover#1173]
## Question

Hey, I didn't find anything so I figured I would ask here: Is there some (official) way of using Plover to type German texts or is it English-only?

**Comment by jenchanws** [comment]
It's certainly _not_ English only (there are plugins for steno systems in several languages), but  I don't think the German plugins are particularly developed:

* [plover-german](https://github.com/benoit-pierre/plover_german) follows this [official-looking layout](http://www.zav.cz/german/compkomasch.htm) but doesn't have a dictionary so you'll either have to import one you can find or build one yourself;

* [plover-regenpfeifer](https://github.com/mkrnr/plover_regenpfeifer) has a decently-sized dictionary but the author claims it's [still in development](https://stenoblog.com/working-on-a-german-steno-theory/) and I'm not sure there's much documentation on the system itself besides the blog post and the code

**Comment by Glitchy-Tozier** [comment]
I see, thank you for helping me out!
