### ISSUE TITLE
Configuration is not saved if the only change is enabling one extension plugin

### ISSUE THREAD

**Issue by user202729** [openstenoproject/plover#1180]
## Summary

See title.

## Reproducing

* Open Plover
* find some way to install any extension plugin
* go to Plover configuration to enable it (by clicking the check box, obviously)
* click "Ok" in the configuration window
* exit Plover (control+Q)
* reopen Plover. Observe that the plugin is still disabled.

## Plover Version

Latest git master at the present.

## System

Arch GNU/Linux (but this should be system-independent), run from source.

**Comment by benoit-pierre** [comment]
Is that still an issue?

**Comment by user202729** [comment]
Yes.

It does happen with the qt GUI, but does not happen with the console ui.

(haven't got the time to debug the issue, but a guess is that some configuration function returns the mutable internal structure, then it cannot detect if it has been mutated)
