### ISSUE TITLE
plover not recognizing my stentura protégé on windows 10 

### ISSUE THREAD

**Issue by josefina1996** [openstenoproject/plover#1181]
## Summary

I was using Plover with my Stentura Protegé on win7 for a while, worked fine, and now i upgraded my computer to win10, installed all drivers and still Plover doesnt recognize my steno machine. I open the program and it works fine with my computer keyboard, but when i select Stentura, Configure, Scan, nothing shows up. The computer recognize the Stentura machine on the port configurations and all, but not the program itself. Really tried it all and still haven't figure out what's wrong. The cables are not damaged, they are  connected correctly.  Closed and opened Plover many times, rebooted the computer... still not working.
Help please! I need it to keep practicing. 

## Reproducing

Open the program, select Stentura, Configure, Scan. Still, Stentura disconnected. 

## Plover Version

Plover 3.1.1.

## System

Windows 10 Pro, Version 20H2, 64 bits.  with Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz   2.40 GHz,  4GB RAM,

**Comment by gdwaynewarner** [comment]
I don't believe version 3.1.1 works with Windows 10.

On the plus side, that means you can upgrade to version 4.X of Plover:

https://github.com/openstenoproject/plover/releases

Unfortunately, of late there has been a bit of an issue with the Plugins Manager, but this one should help:

https://github.com/openstenoproject/plover/wiki/Manually-Installing-Plugins

Good luck!

**Comment by josefina1996** [comment]
thanks. i didn't know Plover has a version 4. But still, i instaled it, keyboard working fine, but the Stentura is still not connecting. Still, when I click Scan, a small Plover symbol comes out in the right low corner, but the machine is still not connecting.

**Comment by josefina1996** [comment]
Sorry, it worked. Had to installed the plugins and then select Stentura USB, not just Stentura.
thanks a lot.
