### ISSUE TITLE
Plover Won't Recognize Which Serial Port My Steno is Plugged Into

### ISSUE THREAD

**Issue by kelsradford** [openstenoproject/plover#1185]
## Summary

Every time I try to open the plover program, it says there is an error in the serial port. Even when I have uninstalled and reinstalled plover, and switched the port I plug my steno into, it still doesn't work.

## Reproducing

My steno uses a VGA cable, and I have a VGA cable to USB so I can plug it into my laptop. I never take this set apart, only take the USB in and out of my computer. Then, I open plover. To which the error appears after 10 seconds. I'm unable to type or do anything. 
![PXL_20210215_184034620 (1)](https://user-images.githubusercontent.com/79110933/107985763-f2d14080-6f87-11eb-8399-b2a93eaeda38.jpg)

## Plover Version

3.1.1

## System

Windows 10.

**Comment by hodgep** [comment]
hey, possibly a silly question but.... which steno device do you have?

**Comment by kelsradford** [comment]
A Stentura 200 SRT

**Comment by hodgep** [comment]
hi,

It's not a steno device that I have personally used I am afraid, but I have done some searching and it seems that the Stentura 200 SRT and the Stentura 400 SRT are very very similar (so similar that the user manual is the same for both machines).

It seems that there is already a wiki entry for getting the Stentura 400 SRT to work with Plover.

I'll link to it in a moment, but the key piece of information seems to be that the machine needs a RS232 (Also called DB9) male to female cross over-cable. My understanding is that the transmit and receive pins need to be swapped around inside the cable.
The error message that you are getting is saying that there was a timeout when trying to communicate.

If the RS232 cable that you have isn't the cross over-cable variant then your computer will be sending messages to the pins for sending messages on the steno device and listening for messages on the pins that also listening for messages on the steno device.
So it is definitely worth double checking that you have a RS232 male to female cross over-cable.

The link to the wiki entry is [https://github.com/openstenoproject/plover/wiki/How-to-setup-and-use-Plover-with-a-Stentura-400SRT](https://github.com/openstenoproject/plover/wiki/How-to-setup-and-use-Plover-with-a-Stentura-400SRT)

I hope that helps you get you a bit further :)
