### ISSUE TITLE
Caps Lock doesn't work

### ISSUE THREAD

**Issue by stenoknight** [openstenoproject/plover#119]
In previous versions of Plover, defining a stroke as {#Caps_Lock} would successfully turn on Caps Lock, but then would stop translating text, because it was receiving capitalized input, which it couldn't parse as steno keys. Currently it continues to translate keys after the {#Caps_Lock} command is invoked, but the translations are not capitalized. Both programmers and transcriptionists occasionally need to input capitalized text, and while they're able to select text and convert to uppercase as needed, that can get cumbersome if it needs to be done frequently. If it's not simple to make the {#Caps_Lock} command function as usual, would it be possible to have capitalized (and maybe also camelcase or underscore-delineated) toggle options invokable via steno command in Plover?

**Comment by khaaan** [comment]
Depending on how it's resolved, issue https://github.com/openstenoproject/plover/issues/72 ("Sticky" Metakeys) might also resolve this issue by allowing Shift to be sticky.

**Comment by morinted** [comment]
This is working in Windows if my PR gets merged. I'd have to test it in OS X and Linux to see if it's across the board. That being said, case modes may also nullify the problem if that becomes merged. This is on my mind.

**Comment by morinted** [comment]
Will be resolved by #215.
