### ISSUE TITLE
Engine start failed Exception: Enable access for assistive devices

### ISSUE THREAD

**Issue by slavad** [openstenoproject/plover#1190]
## Summary
When I start plover I'm getting the following exception: "engine start failed Exception: Enable access for assistive devices".

I added plover to the "Accessibility" under System Preferences -> Security and Privacy -> Privacy

## Reproducing
Open Plover under macOS (or refresh devices list) and you will see this notification.

## Plover Version
Plover 4.0.0.dev8+66.g685bd33 

## System
macOS 10.15.7

**Comment by morinted** [comment]
Hi, for now it's necessary to also enable Accessibility for `env`. This is fixed on master but hasn't been released yet. Let me know if this workaround is sufficient for you.

**Comment by slavad** [comment]
Seems to be working now, thx.

**Comment by Di-o-go** [comment]
> 

Hi! How does one enable Accessibility for env?
