### ISSUE TITLE
A Myriad of Issues

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#1194]
## Summary

Last night (28MAR21), Plover's output ceased entirely on my iMac.

Curious, I connected my Flash to my laptop via Bluetooth, started Plover there, and it worked fine, so I knew the writer was okay.

Rebooted the iMac, tried Plover again, with the same results.

Deleted Plover and everything related to Plover in the Application Support folder, emptied the Trash, then downloaded and installed another copy.

Loaded my dictionaries just fine, removed the ones I didn't need, switched to my text editor, brought up the "Paper Tape" window, and stroked out my usual test sentence:  "**_Is this thing on?_**"

Nothing in the text editor, and nothing in the paper tape window.

I then decided to upgrade the Plugins Manager, which was where I ran into yet another issue, in that the command I had used (and saved in a text file) before did not work.

Quit Plover and went to sleep.

Next day, I started Plover, stroked out my usual test sentence -- and this time it worked!

Tried again with the Plugins Manager, but still no luck, with the added addition of this wordy error message:

![Plover_Plugins_Update_Error](https://user-images.githubusercontent.com/17680111/112951554-55257100-90f0-11eb-88bf-688d264c5ae2.png)

Here's the command I used:

**/Applications/Plover.app/Contents/MacOS/Plover -s  plover_plugins install --upgrade plover_plugins_manager 0.5.16**

Here's the output from the terminal:

Last login: Tue Mar 30 00:06:52 on ttys000
Macintosh-58b035f05c47-2:~ macbookpro$ /Applications/Plover.app/Contents/MacOS/Plover -s  plover_plugins install --upgrade plover_plugins_manager 0.5.16
2021-03-30 00:11:19,080 [MainThread] ERROR: error loading gui.qt.tool plugin: plugins_manager (from plover_plugins_manager.gui_qt.manager)
Traceback (most recent call last):
  File "./build/plover-4.0.0.dev8+66.g685bd33.app/Contents/Frameworks/Python.framework/Versions/3.6//lib/python3.6/site-packages/plover/registry.py", line 56, in register_plugin_from_entrypoint
  File "./build/plover-4.0.0.dev8+66.g685bd33.app/Contents/Frameworks/Python.framework/Versions/3.6//lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
  File "./build/plover-4.0.0.dev8+66.g685bd33.app/Contents/Frameworks/Python.framework/Versions/3.6//lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
  File "./build/plover-4.0.0.dev8+66.g685bd33.app/Contents/Frameworks/Python.framework/Versions/3.6//lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
pkg_resources.ContextualVersionConflict: (Pygments 2.2.0 (/Applications/Plover.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages), Requirement.parse('Pygments>=2.5.1'), {'readme-renderer'})
Unexpected error: Traceback (most recent call last):
  File "./build/plover-4.0.0.dev8+66.g685bd33.app/Contents/Frameworks/Python.framework/Versions/3.6//lib/python3.6/site-packages/plover/main.py", line 101, in main
  File "./build/plover-4.0.0.dev8+66.g685bd33.app/Contents/Frameworks/Python.framework/Versions/3.6//lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
  File "./build/plover-4.0.0.dev8+66.g685bd33.app/Contents/Frameworks/Python.framework/Versions/3.6//lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
  File "./build/plover-4.0.0.dev8+66.g685bd33.app/Contents/Frameworks/Python.framework/Versions/3.6//lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
pkg_resources.ContextualVersionConflict: (Pygments 2.2.0 (/Applications/Plover.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages), Requirement.parse('Pygments>=2.5.1'), {'readme-renderer'})

Here's the plover.log file:

[plover.log](https://github.com/openstenoproject/plover/files/6227468/plover.log)

So. Any ideas to get that Plugins Manager working again?

## Reproducing

Unfortunately, I don't know how to reproduce the "no response" portion of this lengthy issue, but I included the commands I used to install the updated Plugins manager.

## Plover Version

weekly-v4.0.0.dev8+66.g685bd33 

## System

Mac OS X 10.10.5 (Yosemite)

**Comment by benoit-pierre** [comment]
Try updating the `Pygments` package: `/Applications/Plover.app/Contents/MacOS/Plover -s pip install --disable-pip-version-check -U --user pygments`.

**Comment by gdwaynewarner** [comment]
Thanks, Pierre.

It took a couple of attempts, but it seems to be working correctly now.

The first attempt at installing a new plugin appeared to work -- until I tried to use the plugin, which caused Plover to close.

Decided to go to sleep and try again later.

So, some 13 hours later, I installed the "Stitch Word" plugin, restarted as directed, used the plugin ... and it worked!

It's been a strange few hours, but at least things are almost back to normal again. Good thing, too ... I have a transcript to work on!

**Comment by gdwaynewarner** [comment]
All good now. Still no idea why Plover ceased working in the first place, though.

As for the "missing updates" issue, it might help to include a command to check for such things and install them automatically, if possible. I don't mess with the terminal very often, so those "missing this" or "that needs updating" messages are nice, but average Mac users are used to the OS handling that sort of thing.

**Comment by user202729** [comment]
About the first issue -- did you mean that Plover appear to work normally, but there's simply no output, without any change in the environment? Then that's weird.

(could be some automatic operating system update too, but then why does the uninstall/reinstall help?)

About the missing updates issue, that can only happen with a broken Python environment; however (I think) if the Python environment is independent and you didn't do anything specifically to make it inconsistent then it should not happen in the first place.

**Comment by gdwaynewarner** [comment]
Yes, Plover initially started up just fine, but refused to actually do anything.

The Mac it is running on is a 2008 24-inch iMac, running the latest version of the Mac OS it can run, so no software updates are available.

You are right about the Python issue. I think with the next build, the version of Python being used will make that iMac unable to upgrade to the newer version, so we'll see how that goes.

On the plus side, I think this has been the first major problem I've had since I started using Plover, so there's that.

**Comment by benoit-pierre** [comment]
> As for the "missing updates" issue, it might help to include a command to check for such things and install them automatically, if possible. I don't mess with the terminal very often, so those "missing this" or "that needs updating" messages are nice, but average Mac users are used to the OS handling that sort of thing.

It's supposed to be handled by the package manager used internally (`pip`), but there's a bug in its resolver... Next release is going to bump `pip` to the latest version, which comes with a brand new resolver, so... fingers crossed!

> You are right about the Python issue. I think with the next build, the version of Python being used will make that iMac unable to upgrade to the newer version, so we'll see how that goes.

Initially, yes, we were expecting to drop support for versions older than 10.13 (High Sierra), but the new CI / build might change that: it's possible we'll extend support back to 10.9 (Mavericks) and newer.

**Comment by gdwaynewarner** [comment]
That's good!

My Macs are old (2008 24 inch iMac running Yosemite (10.10), a 2009 17 inch MacBook Pro running "el Crapitan" (10.11, but that might be bumped up to High Sierra (10.13, courtesy of a savvy Mac tech that "knows a guy")), and a 2010 15 inch MacBook Pro, also running Yosemite).

I might get lucky and upgrade the 17 inch MBP to a 2011 model (the last of the line) and maybe the iMac up to a 27 inch 2011 model with some serious shopping, but that might be a while (pesky plannedemic).

**Comment by benoit-pierre** [comment]
Sorry, the cutoff is definitively going to be 10.13...

I think that you might be able to make the version work by:
* downloading and installing the DMG (latest master here: https://github.com/openstenoproject/plover/actions/runs/712547324)
* and then downgrading PyQt5: `/Applications/Plover.app/Contents/MacOS/Plover -s pip install --user 'PyQt5==5.13.2' 'PyQt5-sip==4.19.19'`

**Comment by benoit-pierre** [comment]
If that does not work, keep going backward in time: try older versions of PyQt5. (But I think 5.13.x is old enough).

**Comment by morinted** [comment]
That command as written exactly worked fine for me on my old machine running Sierra (10.12)

Seems like a good option until there are breaking changes in QT!

**Comment by benoit-pierre** [comment]
TODO: check if there's a way to write a requirement with a conditional marker to check the macOS version.

**Comment by gdwaynewarner** [comment]
That sounds like a great idea, Ted!

**Comment by gdwaynewarner** [comment]
Thanks, Pierre.

I will give it a try, but I have a lengthy hard-to-hear court proceeding I
have to get going on, so I will try this when I'm done with the job (~two
or three days).

--gdw

**Comment by benoit-pierre** [comment]
Let's move the discussion about supporting older Macs here: https://github.com/openstenoproject/plover/discussions/1231.
