### ISSUE TITLE
Start Plover on Boot

### ISSUE THREAD

**Issue by petercpark** [openstenoproject/plover#1217]
**Is your feature request related to a problem? Please describe.**

Plover doesn't open up automatically.

Plover is something I have constantly on, and it is a minor inconvenience to have to open it manually each time I start the computer.

**Describe the solution you'd like**
It would be nice to give plover the option to startup when you turn on the computer within the plover app.

In Plover settings, a toggle switch that makes plover start on loading of the computer.

**Describe alternatives you've considered**

I placed a shortcut of the plover app in the Startup folder (win+r then shell:startup) on windows manually. It would be nice if this could be done with a click of a button within Plover settings.

**Additional context**

**Comment by wentropy** [comment]
On Ubuntu, you can configure the appImage to start, using **Session and Startup>Application Autostart**. I guess windows and others systems also have this feature

**Comment by greenwyrt** [comment]
Since this is out of scope for Plover and up to the user's operating system, this issue is closed.
