### ISSUE TITLE
UI for Italian

### ISSUE THREAD

**Issue by Sillabix** [openstenoproject/plover#1246]
Plover has been interfaced with the vast majority of international steno machines and the next release candidate will probably have UI for Spanish and French. Plover has been also interfaced with the two existing Italian steno systems: Melani and Michela. So the existence of an Italian UI could be useful, in my opinion, to further promote the usage of Plover in the Italian steno community.

Happy to help for the translation of all the commands and the UI check if needed.

**Comment by user202729** [comment]
You can do it yourself (lookup "how to use Python gettext" etc.) I think the process is:

* copy the file `plover/gui_qt/messages/plover.pot` to `plover/gui_qt/messages/<language>/LC_MESSAGES/plover.po`
* edit the header correspondingly (see the Spanish translation pull request for an example)
* compile the `.po` file to `.mo`
* try running Plover to see if it is correct
* add news snippet
* make a pull request.

**Comment by benoit-pierre** [comment]
OK, here are the steps using Poedit and some upcoming support to make things easier:
- download [this version of Plover](https://github.com/benoit-pierre/plover/releases/tag/continuous), including the *Translations Catalogs* archive
- extract/install Plover
- extract the *Translations Catalogs* archive in your Plover's configuration folder (so the `messages` directory is right under there)
- download and install [Poedit](https://poedit.net/)
- launch Poedit
- click on "Create new translation", navigate to Plover's configuration folder and open `messages/plover.pot`
- select the language your going to translate to
- click on the save icon, Poedit will propose to name the file according to the language code, instead, save the file in `messages/${language_code}/LC_MESSAGES/plover.po`, where language code is the code in question (e.g. `messages/it/LC_MESSAGES/plover.po` if you're translating to Italian)
- translate, translate, translate
- to test, save you translation, and assuming your locale is already configured for the language your targeting, just run Plover

Note:
- you'll have to restart Plover every time you update the translation
- you can force Plover to use a language by setting `LANGUAGE=${language_code}` in your environment

**Comment by user202729** [comment]
@benoit-pierre I see that you updated latest master to add the "translation catalog" in the archive...

For better visibility you can copy that comment to `CONTRIBUTING.md`, or some wiki pages.

**Comment by Sillabix** [comment]
Thanks Benoit for addressing this in PR #1268.
