### ISSUE TITLE
Editable grammar rules for suffixes/prefixes

### ISSUE THREAD

**Issue by Sillabix** [openstenoproject/plover#1247]
**Proposal**
A function to edit on the fly the regex table of the grammar rules in the system.py file

**Description**
To apply correctly prefixes and suffixes Plover has a very good built in grammar engine based on several rules. These grammar rules work well and so usually for many users there isn't any need to change them or add new ones. Professional users instead could have the need to introduce new rules or slightly modify the existing ones to better adhere to their personal steno theory (for instance this function is present by a long time in professional softwares like Eclipse).

Besides, for the International users this function would be really helpful because for several International steno systems implemented in Plover he grammar rules still don't exist or they are at a very first experimental stage. 

Of course is always possible to edit the content of the system.py file manually but this is a frustrating experience because the files is not easily reachable and Plover has to be restarted every time a new rule is introduced. 

It's true that the present rules are based on regex and this language could be not easy understandable by all. But with the help of a a little document which could describe the main basis of the rules used in Plover all the interested users could start to introduce some new rules (also following the example of the ones utilized for the English steno system). 

In any case a "reset" button should be provided in case of problems with the change made to restore the original rules. 

Also a "restart" button (like the one present in the plugin manager) should be useful to restart Plover after every change of the system.py file.

**Comment by user202729** [comment]
Since Python is very flexible (mostly no private class variables, dynamically typed, easy to monkey patch), it is probably possible to make a plugin to do it.

To make this an official feature would be a little confusing.

More documentation is good, but there (will be) developer plugin documentation which should include that; and the developers should be able to understand regex without too much difficulty.

**Comment by Sillabix** [comment]
Thanks for your suggestions. Hope someone will want to write a plugin for this in the future.

**Comment by user202729** [comment]
There's a label https://github.com/openstenoproject/plover/labels/plugin-candidate for issues that people think "a plugin is better suited to handle this issue", and those issues remain open.

You might want to leave the issue open for more visibility.

(although there are already so many feature-requests and plugin-candidates that nobody implements...)
