### ISSUE TITLE
Double clicking add translation in dictionary editor crashes Plover

### ISSUE THREAD

**Issue by Nicbudd** [openstenoproject/plover#1250]
**Describe the bug**

In the dictionary editor, double clicking the "Add a new translation" button will crash Plover

**To Reproduce**

1. Open up dictionary editor by double clicking a dictionary
2. Click "Add a new translation" button at bottom left twice
3. Plover crashes

**Operating system**

 - OS: Windows 10
 - Plover Version 4.0.0.dev8

**Hardware**

Being used with NKRO keyboard
![image](https://user-images.githubusercontent.com/13754207/114319774-e88f7680-9ae0-11eb-9aa0-6ae5dddae467.png)

**Comment by benoit-pierre** [comment]
Can you check with the [latest development version](https://github.com/openstenoproject/plover/releases/tag/continuous)? I can't reproduce the issue.

**Comment by user202729** [comment]
Duplicate of #1040 , fixed in latest master.

**Comment by user202729** [comment]
Duplicate of #1040

**Comment by user202729** [comment]
(fixed in latest master. The "duplicate of" comment won't work unless it's the only content in the comment. I wondered what the [duplicate] label is used for)
