### ISSUE TITLE
Raise and focus running instance of Plover when launching it while running

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#1279]
**Is your feature request related to a problem? Please describe.**

We get a lot of support requests when people try to start Plover and it says "Another instance of Plover is already running". Often it's just minimized to the tray. I've noticed that other programs on my computer handle this by just raising the minimized window rather than trying to open a second instance.

**Describe the solution you'd like**

When a second instance of Plover with QT is launched and another instance with QT UI is already running, raise and focus the main Plover window instead.

**Additional context**

This will break any forks where people run multiple instances of Plover at once, but I'm not really worried about that. It might also lead people to believe that Plover is really closing every time that they hit the "x" button, but that's already happening so… maybe not worth solving.

**Comment by user202729** [comment]
Regarding the [x] button, it's also possible to make another button on the top bar (what's it called?) to minimize it to the to the tray... or pop up another window to ask the user what to do. Both are (UI-) breaking changes.

Or pop up a message "Plover is still running" on minimize to tray.

I don't think people running multiple instances will be affected anyway.

**Comment by morinted** [comment]
I think the most common solution is:

> Or pop up a message "Plover is still running" on minimize to tray.

Which you would show every time until someone interacts with the tray once, after which you would never show it again.

I think that adding that would be a separate feature request.

**Comment by user202729** [comment]
Ah, I see why this will break people running multiple instances of Plover at once.

I think the fix is simple? Make the pipe/socket name dependent on some hash value of Plover configuration directory.

**Comment by benoit-pierre** [comment]
Or don't support it? Apart from the very specific case of running under Linux with another display, running multiple instances of Plover is a good recipe for disaster.

If we do want to support it, we should make it explicit: `plover --instance INSTANCE_NAME`.

**Comment by user202729** [comment]
Yes, same configuration directory might confuse configuration save. Especially when there's some simple save trigger (most frequently dictionary change)
