### ISSUE TITLE
speed up rtf loading time

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#129]
RTF loading may be too slow.

Also, it's been reported that RTF loading time is longer on startup than when later added.

**Comment by morinted** [comment]
Is this because we have to parse it on start up, unlike JSON which we parse on stroke?

**Comment by jeremy-w** [comment]
Anyone have a sample "this is way too slow" RTF dictionary to reproduce this against?

**Comment by user202729** [comment]
There's https://github.com/sammdot/plover-better-rtf (which claims to be faster)

**Comment by benoit-pierre** [comment]
Closing, #1365 + #1362 really sped things up.
