### ISSUE TITLE
Missing message in i18n catalog

### ISSUE THREAD

**Issue by nvdaes** [openstenoproject/plover#1294]
**Describe the bug**
The following message is not translated

> plover/gui_qt/paper_tape.py:    ''' Paper tape display of strokes.

**To Reproduce**

1. Open plover in a language like Spanish
2. In the main window, see the toolbar button corresponding to paper tap

**Expected behavior**
The tooltip should be translated

**Operating system**

 - OS: Windows 10
 - Plover Version 4.0.0.dev9

**Comment by benoit-pierre** [comment]
Fixed in #1420.
