### ISSUE TITLE
[osx][mavericks][universal access]  cannot allow access ...

### ISSUE THREAD

**Issue by rprimus** [openstenoproject/plover#131]
Wed 30 Oct 2013 20:30:34 GMT

Hello.  Just heard about Plover and wanted to install it.

With Mavericks, there is no longer a Universal Access section.
This is now controlled by Security & Privacy -> Privacy -> Accessibility

After attempting to run an app that does require 'Access for assistive devices', the app *should* show up in the app window with a checkbox next to it.

See this link for pics describing the problem for flexiglass: 

https://coderwall.com/p/4auyiq

Plover crashes on startup with an "Exception: Enable access for assistive devices."

![screenshot 2013-10-30 20 41 26](https://f.cloud.github.com/assets/278414/1440980/65ae61a6-41a4-11e3-8612-622671d9cdc7.png)

The app should then show up so that it can be allowed,  however it does not.

**Comment by elswythe** [comment]
Hi there, sorry, I had the same problem with rprimus, and I tried the method mentioned but I have a problem with trying to drag Plover into the "list of programs in the System Preferences". I tried dragging but the Plover wouldn't go into the System Preferences. I am probably doing something wrong. I tried dragging it into the list of options box there is in Accessibility (with the one with the Seeing, Hearing, Interacting sections), and also tried to drag Plover into the System Preferences' main page, the one with all the icons where Flash Player and Java are.
Please help! Thank you :)

**Comment by coreyjewett** [comment]
Find the correct pref. pane spot here: https://support.apple.com/en-us/HT202866, then drag and drop Plover into the application list.

**Comment by morinted** [comment]
The correct pane is "Security & Privacy" > "Privacy" > "Accessiblity" > Click the lock to make changes > + button > Find Plover.app in the applications folder to add it.
