### ISSUE TITLE
config file gets bogus values

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#133]
There have been several reports that the config file can have bogus values be written to it. Of course, it's also possible for people to write bogus values. Plover should make sure not to write bad values to the config file but also be resilient to them.

port = None. This causes an OSError instead of the expected SerialException and so isn't caught.

[Main Frame]
x = -32000
y = -32000

This causes the window to not be visible.

**Comment by morinted** [comment]
I think this requires better checking around all loads and maybe even writes. The window problem may be addressed when #272 gets solved.
