### ISSUE TITLE
Stenograph USB plugin does not work on newer Plover 4 versions

### ISSUE THREAD

**Issue by brownbaer** [openstenoproject/plover#1336]
**Describe the bug**

Attempting to use a stenograph machine with any version of Plover 4 other than earlier builds (specifically "weekly-v4.0.0.dev8+66.g685bd33" for me, released July 2018) does not recognize/use the plugin "Stenograph USB" properly. Plover then cannot recognize the machine and use it for stenography.

Myself (nikonekonyaa#1716 on discord) and another user (jcsteno#4685) both encountered this problem within the last week. I was using a Stentura Protege that was proven to work by it's previous owner (another user in the discord) and jcsteno was attempting to use their Luminex CSE. 

The steno writer was recognized by the computer as a "Stentura Protege" in device manager, with all drivers being up to date. 

Things that did not fix it:
-Re-installing Plover 4
-Re-installing USB drivers for the steno writer
-Completely removing all program files/registry files for Plover, re-installing it
-Using the pre-packaged plugin manager in later versions of Plover 4, as it installs from the same plugin file it's downloaded with.
-Attempting to manually install the plugin on later versions through Powershell 
-Putting the Stentura Protege into TX Flash mode and attempting to use it through that option
-Installing Plover 3 on it's own

Untested:
-Using the Serial port

Things that did fix it:
-Downloading an older version of Plover 4 from July 2018 or earlier.
-Manually installing the plugin "Stenograph USB" using the file downloaded off it's project page through the Powershell.
-Enabling "Stenograph USB" on Plover 

**To Reproduce**
Install all drivers for steno writer model, set it up, connect to computer with USB cable.
Install any newer Plover 4 release past the July 2018 release.
Attempt to connect to the steno writer using Plover and it's USB cable - Plover will not recognize the steno writer.

**Expected behavior**
That the "Stenograph USB" plugin works properly by recognizing the steno writer connected through USB to the computer. 

**Operating system**
Windows 10, Professional
Plover 4 beyond "weekly-v4.0.0.dev8+66.g685bd33", released july 2018

**Comment by benoit-pierre** [comment]
My attempt at fixing: https://github.com/benoit-pierre/plover_stenograph_usb/tree/fix_win_py38.

**Comment by benoit-pierre** [comment]
https://github.com/morinted/plover_stenograph_usb/pull/2
