### ISSUE TITLE
Bluetooth Connection Quit Working

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#1337]
**Describe the bug**

Can't get the new version of Plover to work when connected via Bluetooth

**To Reproduce**

I bought one of these a few years ago:

http://www.irxon.com/english/products/bt578_e.htm

... which looks like this:

![bluetoothiness](https://user-images.githubusercontent.com/17680111/119603694-8645b900-bda2-11eb-87fa-7e629c6a78c5.png)

It worked fine, until I upgraded to the current build (4.0.0.dev9+65.gdf65bf1), as shown in the text editor on the right side of the below screenshot.

**Expected behavior**

After getting both Plover and the Mac to recognize the Bluetooth device, I tried writing my usual "Is this thing on?" test sentence, and nothing happened. 

**Screenshots**
![Plover_Bluetooth_Fail](https://user-images.githubusercontent.com/17680111/119602570-4aa9ef80-bda0-11eb-8790-43b8941ed1a3.png)

This screenshot shows, from left to right, the Bluetooth Explorer Dashboard, the new document I stroked my usual test sentence in ("Is this thing on?"), then going back to the left you should see my Apple Bluetooth Keyboard at the top, and my "Bluetooth Gadget" below that, then the Bluetooth Explorer Event Log, and below that, Plover, letting me know it is connected to the "Bluetooth Gadget."

**Operating system**

 - OS: Mac OS X High Sierra, thanks to a download from "The DOS Dude" which enables me to run High Sierra on this non-supported Mac.
 - The computer is a 2009 17" MacBook Pro:

https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-2-duo-2.8-aluminum-17-mid-2009-unibody-specs.html
 - Plover Version: Plover 4.0.0.dev9+65.gdf65bf1

**Hardware**

The writer is my ProCAT Flash, and here's a screenshot of the Machine settings:

![Plover_Machine_Settings](https://user-images.githubusercontent.com/17680111/119603323-ceb0a700-bda1-11eb-9eb2-baf1093d6bf9.png)

Hopefully I'm not the only one with this issue!

**Comment by gdwaynewarner** [comment]
Same issue with the last two builds.

**Comment by gdwaynewarner** [comment]
Sadly, the same issue exists with the new build, 4.0.0.dev10+4.g8495a32.

**Comment by gdwaynewarner** [comment]
Nothing on the paper tape. Haven't touched the Accessibility pane in years, and Plover doesn't appear there.

**Comment by gdwaynewarner** [comment]
Sorry for the delay in getting back to you.

As I may have mentioned in another bug report (most likely on the new build), I had to go back to version 4.0.0.dev10. Using it right now, in fact with no issues at all.

**Comment by benoit-pierre** [comment]
So `4.0.0.dev9+65.gdf65bf1` does not work, 2 other builds and `4.0.0.dev10+4.g8495a32` don't work, but `4.0.0.dev10` does?  

They are no machine related code changes, or changes to the distribution packaging that would explain your issue.

And I'm still waiting for an explanation of the other problem with the new build.

**Comment by benoit-pierre** [comment]
This includes better save code, yes.

**Comment by gdwaynewarner** [comment]
Okay, compressed the old version I was using, downloaded the new version, and I didn't see anything like that bunch of messages telling me that many of the outlines I used to use no longer works, so that's good.

 ... and I'm using it via my Bluetooth gadget (technical term).

Most likely, the only thing different was I didn't do anything with the plugins.
