### ISSUE TITLE
Word not output correctly

### ISSUE THREAD

**Issue by aeroplane380** [openstenoproject/plover#1349]
**Describe the bug**
When trying to type the word `calls`, I type `KAULS` as shown in the dictionary. However, this produces the word `cals`, not `calls`.

**To Reproduce**

1. Key `KAULS` in a text editor.

**Expected behavior**

`calls` should be output.

**Screenshots**

**Operating system**

 - Windows 10
 - Plover Version 3.1.1

**Hardware**
This occurs when using an n-key rollover keyboard without arpeggiation enabled.

**Comment by JorWat25** [comment]
Sounds like the `U` isn't being picked up. Can you try it with the paper tape open and see what keys it's seeing?

**Comment by sammundayhall** [comment]
> Sounds like the `U` isn't being picked up. Can you try it with the paper tape open and see what keys it's seeing?
> 
> You might also want to upgrade to v4, rather than 3.1.1.

The paper tape shows `KAULS` as I'd expect, just the output text is incorrect. I'll take a look at the weekly v4, I started off with 3.1.1 as it's the latest stable.

**Comment by user202729** [comment]
Also note that if you initially used, you would need to remove `main.json` in the config folder ("File -> Open config folder" menu). When you run Plover v4 it will recreate the v4 `main.json`
