### ISSUE TITLE
AppImage doesn't run

### ISSUE THREAD

**Issue by jasoninja** [openstenoproject/plover#1376]
Running Raspberry Pi OS.
I downloaded the AppImage for Plover 4, followed the directions to make it executable, but it did nothing when I tried to execute it.
When I tried to run it from the terminal I got a "command not found" message.
I was able to download, install, and run the .deb file for Plover 3, so the system seems to be able to handle the app.
Thanks for the help.

**Comment by benoit-pierre** [comment]
The AppImage is for x86_64, you can't use it on a Raspberry Pi.

**Comment by benoit-pierre** [comment]
You'll have to run from source.

**Comment by benoit-pierre** [comment]
Or install the wheel.

**Comment by tkyler** [comment]
FYI, installing from wheel,  4.0.0.def12  doesn't seem to include the plugins manager.  Attemps to manually install plugins results in "no such script - plover_plugins".  Other than that, I successfully installed Plover via the wheel using pip3
