### ISSUE TITLE
Plover crashes when input method for CJK languages is selected on macOS

### ISSUE THREAD

**Issue by ybkimm** [openstenoproject/plover#1377]
**Describe the bug**

Segmentation fault occurs when input methods for CJK are selected in macOS.

**To Reproduce**

1. Add "2-Set Korean"(한국어 - 두벌식) keyboard to the input source.
2. Change the input source to 2-Set Korean.
3. Start plover, and it's crashed.

**Expected behavior**

<img width="353" alt="스크린샷 2021-07-13 오전 1 48 31" src="https://user-images.githubusercontent.com/48612325/125325908-7434cf80-e37c-11eb-9481-33430045062e.png">

**Screenshots**

```
➜  ~ /Applications/plover.app/Contents/MacOS/Plover ; exit;
[1]    55780 segmentation fault
```

**Operating system**

 - OS: macOS Big Sur
 - Plover Version: 3.1.1

**Hardware**

[Planck keyboard](https://drop.com/buy/planck-mechanical-keyboard) with [QMK Firmware](https://qmk.fm/), using `STENO_MODE_GEMINI`.

**Comment by sammdot** [comment]
Please switch to the [latest version](https://github.com/openstenoproject/plover/releases/tag/v4.0.0.dev10) -- 3.1 hasn't been updated in a long time.

**Comment by ybkimm** [comment]
Oh, I didn't know there was a dev version. I changed it to 4.0.0 and it's working. Thank you!
