### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#138]
weapon + ized -> weaponnized. Should be weaponized.
heptamer + ized -> heptamerrized. Should be heptamerized.

**Comment by morinted** [comment]
Short of the really long medical terms here, all these spelling mistakes are fixed with the new orthography rules and the incoming dictionary update.

**Comment by stenoknight** [comment]
Fantastic!

On Mon, Sep 28, 2015 at 5:44 PM, Ted Morin <notifications@github.com> wrote:

> Short of the really long medical terms here, all these spelling mistakes
> are fixed with the new orthography rules and the incoming dictionary update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openstenoproject/plover/issues/138#issuecomment-143882767>
> .
>



-- 
Mirabai Knight, CCP, RDR
StenoKnight CART Services
917 576 4989
mkk@stenoknight.com
http://stenoknight.com
