### ISSUE TITLE
Number glue interacts badly with inserted space?

### ISSUE THREAD

**Issue by JoshuaGrams** [openstenoproject/plover#1380]
Write several digits individually, say, 123. Then hit your insert-space stroke (`{^ ^}`), then a word (maybe "and"). Instead of "123 and" I get "12 3and".

Windows 10, Plover 4.0.0.dev9+65.gdf65bf1, Georgi rev2

**Comment by user202729** [comment]
Can't reproduce. What is the definition for your digit/number strokes?

**Comment by JoshuaGrams** [comment]
Oh, man. The Phoenix dictionary has a bunch of outlines defined with the space stroke after, which changes the behavior because now the definition is not only numbers so it doesn't get glued.

So `WUPB` -> "1" and `WUPB/SP-Z` -> "1 {^}"

Grr. Sorry about that.
