### ISSUE TITLE
Plyer not listed in pip requirements

### ISSUE THREAD

**Issue by Kenny2github** [openstenoproject/plover#1386]
**Describe the bug**

When installing plover from wheel, the dependency `plyer` is not installed.

**To Reproduce**

1. Download the Python wheel for Plover from releases
2. Run `pip3 install <wheel file>`
3. Run `plover -l debug`
4. See error about missing module `plyer` at the top of the log

**Operating system**

 - OS: Windows 10
 - Plover Version: weekly

**Comment by benoit-pierre** [comment]
It's optional, provided by the `log` extra.
