### ISSUE TITLE
A proper keyboard shortcut for turning plover on/off

### ISSUE THREAD

**Issue by xsrvmy** [openstenoproject/plover#1397]
Currently, in order to turn on plover with the keyboard, you have to use a steno stroke. This works fine if you are in a textbox, but elsewhere it can produce side effects as erfvol and six backspaces are sent to the computer. A prime example is if you try and turn on plover when in command mode in vim. A dedicated shortcut would solve this problem.

**Comment by aerickt** [comment]
With the latest version of Plover, you can send a command via the terminal to Plover on and off. You could bind this command to a shortcut as a work around:
```
./plover -s plover_send_command toggle
```

**Comment by xsrvmy** [comment]
Does this work on windows?

**Comment by aerickt** [comment]
Haven't tested it, but it should work. I think you want to use the plover_console exectuable:
```
 .\plover_console.exe -s plover_send_command toggle
 ```

**Comment by xsrvmy** [comment]
Actually I downloaded plover 3 instead of 4 by mistake earlier. Just to clarify, the Ctrl+. shortcut only works in the main window of plover, even though it shows on the right click menu in the tray?

**Comment by aerickt** [comment]
> Just to clarify, the Ctrl+. shortcut only works in the main window of plover, even though it shows on the right click menu in the tray?

That's correct.

**Comment by user202729** [comment]
I don't see any easy way to fix the issue. Plover is supposed to do nothing when it's turned off, but suppressing `erfvol` would require it delaying the key presses.

Besides, Plover (at the moment) cannot capture the action of keys like ctrl or f12. Autohotkey (on Windows) (or vim binding, etc.) can be used to call the command above.
