### ISSUE TITLE
`Stroke` object constructed with no key does not have a `is_correction` property

### ISSUE THREAD

**Issue by user202729** [openstenoproject/plover#1402]
If a stroke is constructed like `Stroke([])`, it does not have `is_correction` property. (which should be `False`)

Normally this should not happen, but some of my plugins relies on this to construct an impossible stroke.

In practice, there has been no issue with it so far; however it might interfere with some other part of Plover.

**Comment by user202729** [comment]
Caused by https://github.com/openstenoproject/plover/commit/2d9acde6f8e87aee6196a95107b40d014cbd1c6f.

**Comment by benoit-pierre** [comment]
Fixed by #1362.

> (I see that it's such that it works without plover.system being available, but why?)

Because the `plover.translation` module would execute this on import (before the system is configured):
```python
PREFIX_STROKE = Stroke(())
```
