### ISSUE TITLE
Firefox on Linux deduplicates keypresses

### ISSUE THREAD

**Issue by thesecretmaster** [openstenoproject/plover#1408]
When stroking words that have multiple repeated letters (i.e. roll, spell, room, etc), firefox will attempt to deduplicate the duplicate letters causing incorrect output (i.e. `ROL` -> "rol" instead of "roll", `CUF` -> "cuf" instead of "cuff"). The issue is inconsistent, but occurs frequently enough to be disruptive.

It would be nice to either include this issue in documentation somewhere (potentially with steps to remediate the issue / undo the incorrect word because `*` no longer works) or to include a toggle for delaying these duplicate keypresses slightly when plover sends them to X. I'd be happy to write a patch to do that, it seems like the relevant code is here:

https://github.com/openstenoproject/plover/blob/0501aa33a0504971d1ba7452979c54798f7c3986/plover/oslayer/xkeyboardcontrol.py#L1243-L1260

And then I'd just need to figure out how/where to add the setting.

**Comment by thesecretmaster** [comment]
I resolved this issue for myself by switching from Ubuntu on Xorg to Ubuntu on Wayland. However, I still think this issue deserves attention so I'm leaving it open, and I will still be able to reproduce it on Xorg if debugging is needed.

**Comment by gdwaynewarner** [comment]
Maybe turn off auto-correct or spellcheck in Firefox's preferences?

--gdw

**Comment by thesecretmaster** [comment]
The issue occurs regardless of spell check being turned on or off, I've just tested with the "Check your spelling as you type" setting turned on and off.

**Comment by user202729** [comment]
I can't reproduce the issue. If you are using IBus or some similar input method program, turn them off.

There's a pull request for sleeping between key presses: https://github.com/openstenoproject/plover/pull/1132

**Comment by thesecretmaster** [comment]
The bug occurs with IBus turned on and turned off. However, it only occurs on X not on Wayland. That's the only distinguishing factor I have found.

**Comment by thesecretmaster** [comment]
This issue sounds similar to the one described in #1132, although possibly not identical. I've only experienced this issue with words that have the same letter repeated twice (as described in my first comment), although I'm still very much a newbie so it's possible that it is the same issue and the description in #1132 is a more general description of it.

**Comment by user202729** [comment]
"Turned on and turned off"? I think you should disable/exit IBus completely.

**Comment by thesecretmaster** [comment]
I switched it in the "Language Support" preferences by toggling "Keyboard input method system" from "IBus" to "none" as described [here](https://askubuntu.com/questions/510430/disable-ibus-in-ubuntu-14-04) then logging out and logging back in.

**Comment by thesecretmaster** [comment]
Ok, I was hesitant to fully uninstall IBus because zoom depends on it and I need zoom for work, but surprisingly enough uninstalling IBus appears to resolve the issue. I've now rebuilt zoom without the (apparently optional) dependency on IBus (using the instructions [here](https://hashman.ca/zoom/)) and the issue seems to be resolved.

This seems like a common enough case to want to be included in the documentation somewhere, but the issue seems to be solved on my end.

**Comment by user202729** [comment]
I think it's possible to right click on the IBus tray icon and choose "exit", although I'm not sure how it affects the  
existing applications.

Not really related, but zoom has a web app version.

**Comment by benoit-pierre** [comment]
> This seems like a common enough case to want to be included in the documentation somewhere, but the issue seems to be solved on my end.

It is mentioned in the [troubleshooting section](https://github.com/openstenoproject/plover/wiki/Troubleshooting:-Common-Issues#missing-or-jumbled-output), and supposedly fixed in >=1.5.11, what's your version?

**Comment by thesecretmaster** [comment]
Oh, I don't know how I totally missed that section. I suppose I wouldn't have initially referred to my issue as "missing or jumbled output" but that's also an accurate description of it. Thank you both for your help!

**Comment by benoit-pierre** [comment]
Please confirm your version of IBus so the wiki can updated.

**Comment by thesecretmaster** [comment]
I no longer have IBus installed, but based on `apt-cache show ibus` it was 1.5.22

**Comment by benoit-pierre** [comment]
Thanks, I'll remove the mention that it's fixed in >=1.5.11.
