### ISSUE TITLE
Toggle output command only works while application is focused on Mac OS.

### ISSUE THREAD

**Issue by CrimsonPolar** [openstenoproject/plover#1409]
**Is your feature request related to a problem? Please describe.**

The toggle output command for the desktop app isn't very useful if it only works while the plover app is focused.

**Describe the solution you'd like**

The toggle output command should be able to work with any app focused, not just the plover application.

**Describe alternatives you've considered**

I can't think of any alternatives that aren't already implemented.

**Comment by user202729** [comment]
You mean the ctrl+. shortcut?

This is partially by design, and partially by implementation limitation.

You can use the chord instead (PHROLG, see https://github.com/openstenoproject/plover/wiki/Dictionary-Format#plover-control-commands)
