### ISSUE TITLE
Python 3.8 in Plover app shows as a suspicious process

### ISSUE THREAD

**Issue by doctopus** [openstenoproject/plover#1411]
**Describe the bug**

Python3.8 in the frameworks in Plover does not have code signature, so it is detected as a suspicious process.

**To Reproduce**

Install Little Snitch, see in the apps list. 

**Expected behavior**

Should use signed version of python

**Screenshots**
[https://imgur.com/a/9HZGmUg](https://imgur.com/a/9HZGmUg)

![CleanShot 2021-10-07 at 01 01 41](https://user-images.githubusercontent.com/8637933/136323458-3793bc02-288a-48b3-a949-859bcd4f4ee4.png)

**Operating system**

 - OS: MacOS 11.6
 - Plover Version [4.0.0.dev10+2.g0501aa3]

**Comment by user202729** [comment]
Unfortunately, it's not free, as you can see from the linked issue.
