### ISSUE TITLE
Stenograph Mira Elan A3 not connecting to Plover 4.0.0 or Plover 3.1.1

### ISSUE THREAD

**Issue by DK-in-Oz** [openstenoproject/plover#1412]
I have much the same problem as that described by **Mista-Ma** below, except that I'm trying to connect a Stenograph Mira Elan A3 to Plover - by USB or by serial cable and on a Mac or on a PC - and have had no joy. I have looked at all the forum posts I can find on it, and have installed the latest weekly version, along with libsub, stenograph drivers and the USB plug-in via Plug-in Manager. I did it first on my Macbook Pro, with the latest Big Sur OS. I then bought a PC running Windows 10 and went through the same process using the Windows version. Windows 10 has recognised the machine. I can get 'Enabled' in the configuration. I've had it show 'connected' on the Mac using the serial cable with a USB adapter and the TX Bolt machine setting of all things, but can get no machine output coming through in Plover. I've also managed to get my old Stenograph Smartwriter machine 'connected' using the serial cable and USB adapter, with the machine protocol set to Stentura, but with the same result - that is, no stenotype output in Plover. The Plug-in Manager shows the USB plug-in as installed, but it doesn't show in the Plug-in tab under Configuration.

I would be grateful for any help anyone can offer on what I can do to get my Stenograph Mira Elan properly connected to Plover so I can use it. I gather some of the project proponents have been doing work in this area, but it doesn't seem to be solved yet. Thanks in advance.

### Discussed in https://github.com/openstenoproject/plover/discussions/1322

<div type='discussions-op-text'>

<sup>Originally posted by **Mista-Ma** May 19, 2021</sup>
I have the Stenograph USB plug in and stenograph driver, but all I get is the "stenograph machine is not connected " message. Switching the machine option to "Stentura "does not make a difference. Plover 3.1.1 is also not connecting.  I am running the latest version Windows 10 if that is relevant. Anyone have any idea for a fix? Any help would truly be appreciated. </div>

**Comment by benoit-pierre** [comment]
I have no idea if the Stenograph Mira Elan A3 is supported by the stenograph usb plugin (it's not listed in the README). If it is, on Windows, you might be hitting [that bug](https://github.com/morinted/plover_stenograph_usb/pull/2). To try the fix:
- uninstall the plugin
- run `plover_console.exe -s plover_plugins install https://github.com/benoit-pierre/plover_stenograph_usb/archive/refs/heads/fix_win_py38.zip` from a command prompt

**Comment by DK-in-Oz** [comment]
Hi Benoit

 

Thanks for your prompt response. I had found this release, which mentions the Elan Mira, and had installed it – but struck the problems I mentioned.

 

https://github.com/sammdot/plover-stenograph/releases/tag/v2.0

 

I tried to use your suggestion and uninstalled the plugin, but could not run the command you supplied. The message I got was that ‘plover_console.exe’ is not recognized as an internal or external command, operable program or batch file’.

 

I was able to download the zip folder you mentioned, but don’t know how to run the program. I’m not well versed in computer software.

 

I found a Plover_console command file in the downloaded files with this version of Plover (plover-4.0.0dev10-win64) but double-clicking that just gets me a black command window that flashes briefly and disappears.

 

I also seem to have lost the Plugin Manager with deleting the usb plugin, as trying to open it just gets ‘Error: QT GUI error – AttributeError: ‘NoneType’ object has no attribute ‘version’.

 

I guess all I can do from here is reinstall everything and hope for a different result, but if you do have suggestions on how to proceed to get my machine connected I would be most grateful.

 

Thanks again.

 

Regards

 

David

 

 

 

________________________________

David Keating

mob 0408 285 390

email ***@***.***

1 Veitch Street MOGO NSW 2536

 

 

 

From: Benoit Pierre ***@***.***>
Reply-To: openstenoproject/plover ***@***.***>
Date: Friday, 8 October 2021 at 3:59 am
To: openstenoproject/plover ***@***.***>
Cc: David Keating ***@***.***>, Author ***@***.***>
Subject: Re: [openstenoproject/plover] Stenograph Mira Elan A3 not connecting to Plover 4.0.0 or Plover 3.1.1 (#1412)

 

I have no idea if the Stenograph Mira Elan A3 is supported by the stenograph usb plugin (it's not listed in the README). If it is, on Windows, you might be hitting that bug. To try the fix:
uninstall the plugin
run plover_console.exe -s plover_plugins install https://github.com/benoit-pierre/plover_stenograph_usb/archive/refs/heads/fix_win_py38.zip from a command prompt
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
