### ISSUE TITLE
Suggestions and Lookup not working for some Korean entries

### ISSUE THREAD

**Issue by nikyq** [openstenoproject/plover#1431]
**Describe your issue**

I'm using Plover 4.0.0 dev10 version with the plover-korean plugin ( https://github.com/nsmarkop/plover_korean ). The issue is that for not all, but some Korean entries, the Suggestion and Lookup display nothing as results. The entries are specified explicitly with concrete definitions in the dictionary in json format. They are displayed correctly when looked up on Spectra or filter in their dictionary.

**Steps you've taken**

I attached the dictionary files I have enabled below so that you can reproduce the behavior. I added txt extensions because of Github not supporting json and yaml file types, so you'll have to remove those first. ㄷ-ㄷ <=> 드디어 (stroked by pressing A and P together on a qwerty keyboard),  ㅇ-ㅈ <=> 이제 (stroked by pressing S and L together on a qwerty keyboard), ㅁ-ㄷ <=> 모두 (W and P), ㅁ-ㄴ <=> 마냥 (W and J),  ㄱㄹ-ㄴ <=> 그러나 (E, G, J) are the examples of strokes that don't work with Suggestions and Lookup.

[cas_dictionary_full.json.txt](https://github.com/openstenoproject/plover/files/7446448/cas_dictionary_full.json.txt)
[ko_cas_single_keys.yaml.txt](https://github.com/openstenoproject/plover/files/7446449/ko_cas_single_keys.yaml.txt)

**Expected behavior**

- The strokes of the entered phrases should appear in the Suggestions window.
- The phrases should appear in Lookup.

**Screenshots**

![image](https://user-images.githubusercontent.com/14940809/139532733-1b9bf7ab-d8b4-4751-a8e9-992b7686f092.png)

![image](https://user-images.githubusercontent.com/14940809/139532759-ad86dc5e-7858-41b7-bf78-11c6702ad5d0.png)

**Operating system**

 - OS: Manjaro Linux 21.1.6
 - Plover Version 4.0.0 dev10

**Comment by benoit-pierre** [comment]
Same issue with the latest continuous release?

**Comment by nikyq** [comment]
After updating to the latest release, I get an "invalid number_key" instead upon enabling the Korean system.

```
Traceback (most recent call last):
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/engine.py", line 147, in run
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/engine.py", line 168, in _start
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/engine.py", line 219, in _update
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/system/__init__.py", line 70, in setup
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/steno.py", line 76, in setup
ValueError: invalid `number_key`
```

In plover-korean, number_key is defined as so:
```python
NUMBER_KEY: str = ''
NUMBERS: Dict[str, str] = {}
```

I assume this is what causes the problem.

**Comment by benoit-pierre** [comment]
Yes, an empty string is not valid, `None` should be used instead.

**Comment by nikyq** [comment]
Fixed it. The system works, but the original issue still persists. The mentioned words are still not giving any results in Suggestions or Lookup.

**Comment by benoit-pierre** [comment]
It's because you don't have `마냥` in your dictionary, you have this:
```json
"ㅁ-ㄴ" : "마냥 "
```
With an extra space at the end of the translation.

**Comment by nikyq** [comment]
Oh, I see. Thanks.

**Comment by nikyq** [comment]
Removing spaces fixed the issue.
