### ISSUE TITLE
Plover: Paper Tape window exports no stroke data

### ISSUE THREAD

**Issue by Phorofor** [openstenoproject/plover#1433]
**Describe the bug**

The Plover: Paper Tape window only exports a blank file when saving it to a file. It will be 0 bytes with no stroke data despite strokes being logged on the Paper Tape window.

**To Reproduce**

1. Have the _Plover: Paper Tape_ window open.
2. If there are no strokes logged on the Paper Tape window yet, input some strokes before continuing.
3. Click the 'Save' icon located at the bottom of the _Plover: Paper Tape_ window.
4. Choose a folder to save the file and click _Save_.
5. Navigate to the folder the file was saved to.

**Expected behavior**

The output that the Paper Tape window produces should match the data in the `steno-notes-YYYY-MM-DD-HH-MM.txt` file.

**Screenshots**

Not applicable.

**Operating system**

 - OS: Windows 10
 - Plover Version: Plover 4.0.0.dev10+115.gc75215e                

**Hardware**

Not applicable.

**Comment by gdwaynewarner** [comment]
So I just tried this one with the Mac version of Plover and had no issues:

![Screen Shot 2021-11-03 at 6 41 06 PM](https://user-images.githubusercontent.com/17680111/140243197-98a51b85-e997-41c7-9001-a409ca2bf675.png)

Note that I opened the saved strokes with a program called "skEdit," which is, among other things, used for HTML and etc. ... so maybe try using a different text editor?

**Comment by benoit-pierre** [comment]
It's not an editor issue, I can reproduce.

@Phorofor: you do get an error notification, right? (`AttributeError: 'QListView' object has no attribute 'count'`).

**Comment by morinted** [comment]
Great find and report. Thank you!
