### ISSUE TITLE
ValueError: too many values to unpack (expected 2) on Mac

### ISSUE THREAD

**Issue by NickG13** [openstenoproject/plover#1445]
**Describe the bug**

I can't install any plugin becuase I get an error when opening Plugin Manager. With a clean install of Plover I just can't open it, 0 plugins. 

**To Reproduce**

1. Open Plover after a clean install on Mac
2. Click on Plugin Manager
3. Tada, error

**Expected behavior**

I should be able to enter plugin manager. I did before, but I don't know why I can't anymore. 

**Operating system**

 - OS: macOS Catalina 10.15.7
 - Plover Version Latest (4.0.0.dev10) no pre-release, but "latest" stable

I will attach my log
[plover.log](https://github.com/openstenoproject/plover/files/7656446/plover.log)

**Comment by benoit-pierre** [comment]
Looks like something is wrong with the plugins manager's HTTP cache.

Try removing it:
- go to the configuration folder (if you don't know where that is, use the  "File → Open config folder" menu entry in Plover)
- there should be a hidden `.cache` directory: remove the `plugins.sqlite` file inside of it
- try to start the plugins manager again

**Comment by NickG13** [comment]
thank you very much! I does work now!
