### ISSUE TITLE
Error - Plugin - plover-digitalcat-dictionary  - missing 'plover_casecat_dictionary' module

### ISSUE THREAD

**Issue by infodungeon** [openstenoproject/plover#1462]
**Describe the bug**

Plover 4.0.0.dev10 
Windows 11
Plugin:  plover-digitalcat-dictionary 

Enable Plugin in Plugin Manager
Restart

Throws 2 Errors:

Error:  error loading dictionary plugin: mdb(from plover_casecat_dictionary) ModuleNotFoundError: No module name 'plover_casecat_dictionary'
Error:  error loading dictionary plugin: dct(fromplover_casecat_dictionary)  ModuleNotFoundError: No module name 'plover_casecat_dictionary'

**Comment by user202729** [comment]
This is not a bug with Plover, rather it's a bug with the plugin. Report bug in the plugin repository.

It's already reported at https://github.com/marnanel/plover_digitalcat_dictionary/issues/4 however. (fix: install from GitHub source)

Although it looks like that the original author is quite inactive recently, check the issues on GitHub if you have other issues. https://github.com/marnanel/plover_digitalcat_dictionary/issues
