### ISSUE TITLE
native support for disable Plover translation for a single stroke

### ISSUE THREAD

**Issue by Josiah-tan** [openstenoproject/plover#1464]
**Is your feature request related to a problem? Please describe.**

So I went online to find that this feature was not a natively supported command in steno which surprised me
so for example:
"HL PHRA\*EUBL HL WORL" would output "hello HL world"
where PHRA\*EUBL means Plover disable

**Describe the solution you'd like**
something like KPA* which enables the next word to be capitalized
as well as something like KAPD* which retrospectively capitalizes a word
but for Plover disable of course

**Describe alternatives you've considered**
there's a solution to this (for the next word)
https://discord.com/channels/136953735426473984/136953735426473984/842168418663792650
and also one in the Plover dictionary examples

**Comment by user202729** [comment]
Why make the core more complex? Just make plugins.

Wouldn't a Python dictionary be sufficient? See the example in https://github.com/benoit-pierre/plover_python_dictionary#usage .

------

KA*PD are actually "just plugins" (they're defined as separate functions and linked together with setuptools entry points), they just happens to be bundled with Plover source code.
