### ISSUE TITLE
 raw keyboard input

### ISSUE THREAD

**Issue by Josiah-tan** [openstenoproject/plover#1465]
**Describe the bug**

"TKPWHR*LTZ": "{#at}",
when stroked produces 2

thought it would output @?

Temporary solution
use shift in the command like {#shift(@)} would make it work

why I need this? (For those curious)
Cause I'm making a vim variant of Emily's modifiers so that all macros can be stroked in a single stroke
{#control(j) at a} for example stroked with AFPTZ

**Comment by user202729** [comment]
... because it's how it's implemented currently.

It's explicitly documented in https://github.com/openstenoproject/plover/wiki/Dictionary-Format

> Note: a key name will determine a key to emulate with no modifiers based on your keyboard layout. For example, let's say we want to make a keyboard shortcut to hit shift-2 which is "@" in QWERTY: {#at} will only press the 2 key. To get the @ symbol, we need to add the shift key: {#shift(at)}, which is functionally the same as {#shift(2)}.

... so can't say it's a bug.

Alternatively use `{#control(j)}{^}@a{^}`, although it messes up the undo history a bit.

**Comment by 4hrue2kd83f** [comment]
This is intended behavior. You can always just add shift(2) to the list of keys that Emily's Modifiers can press
