### ISSUE TITLE
Other characters are not suppressed on linux

### ISSUE THREAD

**Issue by xsrvmy** [openstenoproject/plover#1476]
When using plover on Linux with the keyboard interface, other characters are not suppressed. In particular, backspace/ctrl+backspace can be used instead of `*`, which breaks `*` if you use it later.

Version: latest master
OS: archlinux
Note: I am using wayland so plover only work with programs that fallback to X. Not sure if this affects anything.

**Comment by user202729** [comment]
This is likely intentional.  
Ctrl+C is not suppressed either.  
Just don't use these keys.

**Comment by xsrvmy** [comment]
Ah never mind I see that backspace is not an no-op by default.
Should it be? Other characters that affect input directly (except tab also) are no-op.
Not that it matter too much to me because I don't use keyboard as input.

**Comment by user202729** [comment]
I think the purpose of those keeps being mapped to no-op is to prevent pressing the wrong button.
Normally, there's no way you could press backspace by mistake.
