### ISSUE TITLE
Plover does not set WM_CLASS on Linux

### ISSUE THREAD

**Issue by MarkoSchuetz** [openstenoproject/plover#1497]
**Describe the bug**

The windows that are opened by plover do not have the WM_CLASS property set.

**To Reproduce**

1. Launch Plover
2. `xprop | grep CLASS`
3. click on any Plover window
4. empty output

**Expected behavior**

`WM_CLASS(STRING) = "plover", "Plover"`

**Operating system**

 - OS: Manjaro
 - Plover Version 4.0.0.dev10+146.g3e7ba1a

**Comment by benoit-pierre** [comment]
See #1498.
