### ISSUE TITLE
Icons get left in Windows task tray after warning/error messages are shown.

### ISSUE THREAD

**Issue by gskaplan** [openstenoproject/plover#1502]
**Describe the bug**
With Plover running, when any warnings or errors are shown as Windows notifications, an icon is left in the Windows task tray. For example, shutting off my writer will get an error, or a warning that says stenograph machine disconnected, then when I turn the machine back on, I'll get another warning that the machine is connected. If I look in the task tray, there will be a series of Plover icons. If I move the mouse over each one, it will disappear. It appears there's one icon put in the task tray for each warning or error that is displayed. Eventually, only the Plover main icon is remaining.

**To Reproduce**

With plover running and Stenograph machine running and showing "connected":
1. Turn off steno machine - warning or error should be shown.
2. Turn on steno machine - warning about reconnecting should be shown.
3. Repeat a few times if desired. 
4. Note the system task tray - it may contain one Plone green icon for each message that was displayed.
5. Hover over each one - they will disappear.

**Expected behavior**
No icon should be put in the system task tray as a result of messages.

**Screenshots**
Here's what it looks like after a number of error/warnings were displayed:
![image](https://user-images.githubusercontent.com/1245198/158507471-0c00cdc2-36d2-482f-91c8-520d137393a3.png)

Example of the errors that slide-in:
![image](https://user-images.githubusercontent.com/1245198/158508201-75018580-ae9f-42c3-a3a4-5021f31f0b08.png)
![image](https://user-images.githubusercontent.com/1245198/158508231-e68f5fab-7c65-4a8b-838f-1666be4e3f22.png)

Video:  https://www.screencast.com/t/gnoNjLFDU0

**Operating system**

 - OS: Windows 11
 - Plover Version: 4.0.0.dev10

**Hardware**

Lenovo Intel-based machine (somewhat new, high powered)
Stenograph Luminex CSE

**Comment by benoit-pierre** [comment]
So exit handlers were not getting called: see #1507.

This fix the problem of some the icons being left even after exit, but there's still the issue that you end up with multiple ones. And the library we're using is creating a dedicated thread for each one and only removing the icon if the thread is garbage collected or on exit...

**Comment by benoit-pierre** [comment]
#1508 should take care of the remaining issues.
