### ISSUE TITLE
Python Module Error in Python 3.10

### ISSUE THREAD

**Issue by qastokes** [openstenoproject/plover#1530]
I'm running Pop!_OS 22.04 LTS with Python version 3.10.4

Error: engine update failed AttributeError module 'Collections' has no attribute 'Sequence'

This is a known trouble with python 3.10 as example:

https://stackoverflow.com/questions/69596494/unable-to-import-freegames-python-package-attributeerror-module-collections

I'd be glad to provide a dmesg or anything else that may be useful. 

Specifically the error means I cannot work out how to use my Uni steno keyboard with plover and attach it as an interface.

**Comment by benoit-pierre** [comment]
Which Plover version? This has been fixed in 001e332689fd738c9c13351c4122ce6383649f84, available starting with dev9.

**Comment by qastokes** [comment]
I didn't realize there was a 4.0 release candidate at the time.

Pulled an old version from Ubuntu/Pop repos.
Grabbed the appimage. Didn't get this error, but ran into a problem with
brltty. Idk if disabling that fixed everything, been using plover on a
Slackware install instead.

I'd have to do another troubleshoot to clarify all of what was going on.

But I do have it working somewhere now so I'm good. Thanks.
