### ISSUE TITLE
Orthography rules don't seem to be applied consistently

### ISSUE THREAD

**Issue by jthlim** [openstenoproject/plover#1548]
**Describe the bug**

Minimal reproduction:

With a 3-entry dictionary (and main.json disabled):
-G: {^ing}
HOP: hop
HOEP: hope

Pressing HOPG and HOEPG both produce "hoping", rather than the expected "hopping" and "hoping"

**Expected behavior**

Due to the last orthography rule in english_stenotype.py, I expect this to work

```
    # == misc ==
    # defer + ed = deferred (consonant doubling)   XXX monitor(stress not on last syllable)
    (r'^(.*(?:[bcdfghjklmnprstvwxyz]|qu)[aeiou])([bcdfgklmnprtvz]) \^ ([aeiouy].*)$', r'\1\2\2\3'),
```

Note: having the additional entries:
"SHOP": shop
"TOP": top

causes SHOPG and TOPG to produce "shopping" and "topping" as expected.

**Operating system**

 - OS: macOS Monterey
 - Plover Version: 4.0.0.dev11

**Comment by user202729** [comment]
This might be related to the word frequency.  In american_english_words.txt:

```
topping 35
toping 70

shopping 10
shoping (not in the list)

hoping 10
hopping 35
```

Not sure what can be done about this other than defining explicit entries, like main.json does. Deleting the word list file doesn't seem viable.

**Comment by jthlim** [comment]
Hmm.. interesting. Does word frequency play a part in determining add_suffix? For my understanding, can you point me to the related file/function?

**Comment by benoit-pierre** [comment]
https://github.com/openstenoproject/plover/blob/master/plover/orthography.py#L19

**Comment by jthlim** [comment]
I see: It's this bit here:

https://github.com/openstenoproject/plover/blob/master/plover/orthography.py#L28-L31

That adds in the word without orthographic rules, and that ends up taking higher priority than the match with orthographic rules.

**Comment by jthlim** [comment]
I guess this could be marked as closed, working-as-intended then?

**Comment by user202729** [comment]
probably because there are too many special cases that the rules alone are insufficient.

That having said having a morphological dictionary https://en.wikipedia.org/wiki/Morphological_dictionary would be better (as long as it's comprehensive enough), but I guess back then the developer didn't come up with the idea, and this one works well enough.
