### ISSUE TITLE
Macros triggered from a suffix stroke get printed as literal string

### ISSUE THREAD

**Issue by AntoineBalaine** [openstenoproject/plover#1573]
Hello,
I'm trying to trigger a macro from a suffix stroke, but the name of the macro gets printed as a literal string (see attached gif)

Is there a work-around?

this would have various use cases: 
- split previous word's last stroke and attach to new stroke. This is useful for syllabic sténo systems that have words' endings colliding all the time. 
- cycle through homophones
- apostrophe key in word. Currently, it's possible to have apostrophe keys coalesce with the rest of a stroke, but it does require to add a dictionary entry for each and every stroke that would contain an apostrophe, which is not ideal.

**To Reproduce**

1. Add suffix key `ß`
2. Python script for macro:
```python
def space_or_split(translator: Translator, stroke: Stroke, cmdline: str):
    if len(stroke.steno_keys) > 1:
        # contains multiple keys in stroke
        split_previous(translator, stroke, cmdline)
    else:
        # only one key in stroke, treat as 
        translator.translate_stroke(Stroke("<spacekey>"))
``` 
3. add space_or_split to dictionnary with entry `{"ß": "=space_or_split"}`

**Expected behavior**

The macro triggers and receives the full stroke, including both the suffix key and the preceding keys of the stroke.

**Screenshots**

![Peek 2022-11-14 20-58](https://user-images.githubusercontent.com/54488126/201832357-d7f7389b-2537-4ccb-aca6-a1fe429fcc54.gif)

**Operating system**

 - OS: ArchLinux
 - Plover Version 4

Thank you!

**Comment by user202729** [comment]
I guess the most reasonable thing to do in this case would be to interpret the part and the suffix as separate _strokes_, although that's not exactly "correct".

It might be easier for you to do something like writing a custom dictionary plugin/Python dictionary to handle the lookup automatically instead of relying on macros.

**Comment by AntoineBalaine** [comment]
Mm… this means that I would have to look up in the other dictionaries for the strokes, as well as access Plover's translator from the python dict. 

- for the dictionaries: Is there a way to access them through plover's internals ? or is the only way through [websocket](https://github.com/nsmarkop/plover_dictionary_lookup) ? 
- for Plover's translator: could you nudge me in the right direction ? I'm not sure I'm finding something like a plug-in example that fits this scenario.

**Comment by user202729** [comment]
I can find [plover_palantype_german/compound_builder.py at master · percidae/plover_palantype_german](https://github.com/percidae/plover_palantype_german/blob/master/plover_palantype_german/dictionaries/compound_builder.py#L13) which might be interesting, but that does involve hard coding the dictionary file name.

**Comment by AntoineBalaine** [comment]
Sounds good, I'll go the hard coding route, then. Thank you very much!
