### ISSUE TITLE
Improper screensaver activation on Linux

### ISSUE THREAD

**Issue by rbrewer123** [openstenoproject/plover#158]
While using a steno machine with TX bolt protocol, the screensaver activates even while steno input is occurring.  This is with Plover 2.5.6 on Ubuntu 13.04.  Since the "input" is originating over the serial device, there must be something extra Plover needs to do so the screensaver realizes that user input is ongoing to prevent the screensaver from activating.

**Comment by morinted** [comment]
I saw your fix for this in your other PR. Is this still an issue at large in current Ubuntu releases? Just reopen if it is -- I'll close for the sake of issue age and lack of discussion.

**Comment by rbrewer123** [comment]
I can't test if this is still a problem right now and I think it's fine to close it.
