### ISSUE TITLE
Installing on Linux

### ISSUE THREAD

**Issue by jsampson45** [openstenoproject/plover#1590]
I have been trying to install Plover on the current version of Ubuntu Linux. As the human lifespan is short,
it seems to me best to desist, and then follow a path previously trodden rather than trying to get help penetrating undergrowth
where there is no path to follow and I could be going in the wrong direction altogether. I am not a Linux expert or enthusiast. I only try to use it because the keyboard I have does not work with Windows, which I would much prefer.
So: Are there any known cases where some version of Plover was successfully installed on some version of Ubuntu Linux distro?
If so, which version of Plover was installed, to which version of Ubuntu? How was it done? Where were the items
needed found?

**Comment by Robberduckzilla** [comment]
Hi @jsampson45 ! What's the specific issue you're having?
I have installed plover 4.0.0dev12 on Ubuntu 22.04.1 (Jammy Jellyfish) and it's working ok for me.

If you scroll to the bottom of the releases page: [Link](https://github.com/openstenoproject/plover/releases/tag/v4.0.0.dev12) and select the Linux Appimage, that should download for you. 
If you're unable to run that as an executable, right click it, click on the permissons tab, and check 'allow executing file as program'.
More details in the [Installation Guide](https://github.com/openstenoproject/plover/wiki/Installation-Guide#install-plover-on-linux)

The other option is you can install the python package with `pip3 install plover` if you already have python3/pip installed and prefer to do it that way.

**Comment by tkyler** [comment]
The sequence of links in the instructions were a bit misleading, directing the user away from the page with the AppImage on it before the user could have a chance to see it at the bottom of the page.  I too fell victim to this.  I amended the Linux instructions with a link to point back to the page with the AppImage on it.
