### ISSUE TITLE
investigate cpu usage of protocols

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#161]
@rbrewer123 reported that tx bolt protocol was wasting CPU cycles by spinning over the port (and fixed it, thanks).

It is likely that several of the other protocols have this problem. This issue is to investigate this for each one and fix as necessary.

**Comment by morinted** [comment]
The stentura has a PR fix. Otherwise, I'm closing this as there are no current complaints hovering around CPU cycles.
