### ISSUE TITLE
Plover doesn't output into Notepad properly

### ISSUE THREAD

**Issue by tc-kirby** [openstenoproject/plover#1619]
Running Plover 4.0.0.dev12 on Windows 11. The output into Windows Notepad 'lags' behind what is being typed on the keyboard. Furthe keypresses or mouse movement seems to 'release' the text into Notepad.

This happens if I use NKRO with a regular USB keyboard, NKRO with a Picosteno, or serial with a Picosteno.

Everything works just fine in Word, Outlook or the address bar in Chrome. I am able to do Typey Type no problem.

The paper tape seems to look as expected in Plover whether I use Notepad or another application (to my untrained eye!).

Please do let me know if there's further info needed.

### Discussed in https://github.com/openstenoproject/plover/discussions/1617

<div type='discussions-op-text'>

<sup>Originally posted by **tc-kirby** July 16, 2023</sup>
Hello I'm just getting started with steno and I've built myself a Picosteno and installed Plover on a Windows 11 machine.

I've got up to the point of trying to write 'Hello World' according to the instructions on the Wiki, but it's going badly. I am sure Plover is enabled and I am pressing the right key combinations, but it keeps giving me different output each time. Sometimes I press keys and it does nothing, and then I move the mouse and then the output "comes through".

I've tried running Plover as admin, I've tried running version 3, and I've tried installing Plover on a different Win 11 machine, but none of those things work.

This happens whether I use my Picosteno or just a regular keyboard.

I also have an Ubuntu machine, but I understand that Plover is incompatible with Wayland, so at the moment unless I install an old/difficult-to-use Linux distro, I have no way of even beginning to get started with stenography.

Please can someone help me?

Thanks

Tom</div>

**Comment by saweiss** [comment]
For what it's worth, I have the same issue on Windows 11 with my multisteno. Applications other than Notepad work fine.

**Comment by jpjerkins** [comment]
I'm seeing the same.  Just hand-soldered my Georgi, and wanting to dive into steno w/ Plover.   Literally everything works except Notepad, specifically on Windows 11.

Will try reverting to the previous dev build, and will report back.

**Comment by xsrvmy** [comment]
Apparently people have reported this issue with charachorder as well.
Maybe notepad doesn't like keystrokes that are sent too quickly?

**Comment by user202729** [comment]
The problem appears with several things, not just Plover.

https://stackoverflow.com/questions/76177119/sendinput-malfunctions-in-notepad

https://www.autohotkey.com/boards/viewtopic.php?t=116789
