### ISSUE TITLE
Installing Emily Modifiers dictionary

### ISSUE THREAD

**Issue by jsampson45** [openstenoproject/plover#1637]
Issue is: Cannot install Emily Modifiers Dictionary

Method tried:
From Edit menu of Plover selected "Add dictionaries" then "Load dictionaries". From file selector window navigated to Open Steno Project, data, emily-modifiers-master, stuff - selected "emily-modifiers-py" and clicked "open". 

Result:
Pop-out Python error message appeared, "Trying to install Emily Modifiers python dictionary on Windows 10 using the Plover plugin plover-python-dictionary - error message 'Qt GUI error: Type error - can only concatenate list (not "list_reverseiterator") to list'".

**Operating system**

Windows 10 64-bit

  - Plover Version [e.g. 3.x, 4.x, weekly]
Plover 4.0.0.dev12

**Hardware**
HP Elitedesk desktop computer

**Comment by jsampson45** [comment]
AFAICS this applies to any Python or JSON dictionary.

**Comment by greenwyrt** [comment]
Need to first install the [plover-python-dictionary](https://github.com/openstenoproject/plover_python_dictionary) plugin from the plugins manager, *then* add your python dictionary.

**Comment by jsampson45** [comment]
Thanks - had done that. Same error message occurs on trying to load any dictionary including json. I thought *removing* plover-python-dictionary plugin might help but I haven't tried that yet.

**Comment by greenwyrt** [comment]
It's working on my end (Windows 10, dev 12). I downloaded the py file directly from github and added it since I don't have your directory structure. 

The error does make it seem like it's to do with the ui.

**Comment by jsampson45** [comment]
I tried it with dev10 instead of dev12. The Emily Modifiers json dictionary loaded without showing the error message. I then tried again on dev12 after reinstalling it (dev12). The error message appeared again, but I notice that the dictionary is in the list of installed dictionaries all the same.. I will investigate further to find out if it works.

**Comment by jsampson45** [comment]
Looks as if json Emily Modifiers dictionary works so perhaps error message should be ignored.
