### ISSUE TITLE
Can’t get Stentura 8000 to connect to plover

### ISSUE THREAD

**Issue by HelpMuhPlehs** [openstenoproject/plover#1659]
I purchased 2 cables referring to a guide that helped connect a Stentura 400 to Plover. I have a Stentura 8000 and I am trying to connect on windows 10. I can get a regular keyboard to connect but not the Stentura. I downloaded the driver for the cable and tried different settings but the status still shows as disconnected.

**Comment by turnipjs** [comment]
Could you please link the guide you are referring to? It would help with narrowing down the problem.

**Comment by HelpMuhPlehs** [comment]
Hello,

This is an older thread. I have a working machine now. Thank you for your
time.

Kaly Stormer
