### ISSUE TITLE
 "-T/<!8>/9/5": "the 1995", in dictionary

### ISSUE THREAD

**Issue by Mqrius** [openstenoproject/plover#170]
The following entry is present in the default dictionary:
```
"-T/<!8>/9/5": "the 1995",
```
I don't know what it's supposed to be, but probably not what it is right now.

**Comment by morinted** [comment]
These still exist in the Plover dictionary. I'd say we should remove all nulls and flushes. Let's cover this in #257

**Comment by morinted** [comment]
As a sidenote, I think that I can find bad strokes like this with a regex.

    grep -Ev "^\"[\dSTKPWHRAO#\*-EUFBLGDZ]+\"" dict.json

**Comment by Achim63** [comment]
I did that using BBEdit which has search/replace with regexp. TextWrangler (free) should also be able to do this easily.

**Comment by morinted** [comment]
Is there a reason that we don't include the c-word in the dictionary? We already have b, f, a, and other swear words. In Britain, the c-word is very inoffensive and I am not too sure why we don't include it. However, I do realize that some people find the word exceptionally offensive and that might be why it's not included. Thoughts?

**Comment by stenoknight** [comment]
It's not in there? I thought it was K*UPBT. Surprised it's not there.

**Comment by Achim63** [comment]
I wouldn’t buy any dictionary that is incomplete just because some words could hurt somebody's feelings.
It would contradict the purpose of steno as long as those words are used by folks.
Thankfully none of the translation dictionaries I use had an ethics commission that sorts out potentially offensive words.

**Comment by morinted** [comment]
Welp consider it added. Thanks guys.
