### ISSUE TITLE
Solitary apostrophe in dictionary doesn't work

### ISSUE THREAD

**Issue by Mqrius** [openstenoproject/plover#172]
In the dictionary the following entries show up:
 "AE": "{^'}",
 "A*E": "{'^}",
 "-PBT": "{'}",
 "SKW*TS": "{'}",
 "SKW*T": "{'}",
 "SKW-TS": "{'}",
 "SKW-T": "{'}",

The first two work, but the others don't. Nothing shows up when you try to use them.

**Comment by morinted** [comment]
Fixed in #202
