### ISSUE TITLE
Suggestion: look into using a Berkeley db

### ISSUE THREAD

**Issue by boborama** [openstenoproject/plover#177]
In working on my own Plover-clone I tried a number of things to boost performance, and eventually settled on using a Berkeley db to act as the dictionary -- this solution combined fast loading times with fast look ups, with the downside of having to store the contents of the dictionary in a binary file.  While I can't port any code over for you (I'm no good at python) I do know that that the Berkeley db has python bindings.  Additionally, by using transactions you could probably eliminate those occasional crashes people have when using the add-a-new-item plover command (assuming those are in fact caused by threading issues).  If you are interested, I am willing to help out as much I can by sharing what worked and didn't work for me.

**Comment by morinted** [comment]
After the recent debates related to dictionary formats, I think this isn't really something that the community wants at the moment. Thanks for the suggestion, though :)
