### ISSUE TITLE
Add support for "glue" with a specified separator

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#178]
Right now Plover supports "glue" which will cause all output items with glue to be attached without spaces.

However, sometimes the user wants to glue with a specified separator such as a hyphen.

We will add this feature with the following syntax. Glue will continue to be indicated by & for example: {&A} {&B} (&C} will result in ABC.

To connect with a hyphen the user would use: {&-A} {&-B} {&-C} which will result in A-B-C.

**Comment by morinted** [comment]
What is the reason that this doesn't work now? Is & limited to one character?

**Comment by morinted** [comment]
@stenoknight Where does the use case for this come from? Can you provide an example stroke set that I'd use for things that I want to separate with a concern operator?

**Comment by stenoknight** [comment]
People might want stitching (A-B-C-D) alphabets for spelling or initialized (A.B.C.D.) alphabets for acronyms or initials. But frankly, I just handle these cases by putting the hyphens or periods in manually when they come up. Very low priority, IMO.
