### ISSUE TITLE
Update on PyPi? :)

### ISSUE THREAD

**Issue by relrod** [openstenoproject/plover#185]
Hi there,

I noticed that on GitHub you have up to version 2.5.8 tagged, but on [PyPi](https://pypi.python.org/pypi/plover/) the last upload was in 2011 and is 2.2.0.

Any chance of updating that to the latest release and possibly making that part of your release process?

When this is done, I would like to package Plover for Fedora (I already have most of an RPM spec done for it, but then I noticed the version issue. I also ran into an issue of the .desktop file having the wrong `Version` field, but this is fixed in newer releases (just not on PyPi).

I'm happy to help if I can somehow, let me know. :)

**Comment by morinted** [comment]
I think that removal from PyPi is probably the right way to go here. Thoughts?

**Comment by morinted** [comment]
This isn't in the works right now.
