### ISSUE TITLE
Ask users if they want to log strokes on configuration generation

### ISSUE THREAD

**Issue by burbilog** [openstenoproject/plover#199]
Plover log file is created with 644 permissions by default. That means that ANY unprivileged user on the same machine can read it. Potentially it's a huge security hole, exposing passwords and other private stuff:

dragon pts/7%id
uid=1000(rm) gid=1000(rm) groups=1000(rm)
dragon pts/7%ls -al   /home/rm/.local/share/plover/plover.log
-rw-r--r-- 1 rm rm 300087 Jul 28 16:38 /home/rm/.local/share/plover/plover.log

note@dragon:/tmp$ id
uid=1001(note) gid=1001(note) groups=1001(note)
note@dragon:/tmp$ tail /home/rm/.local/share/plover/plover.log
2014-07-28 16:39:30,859 Stroke(S-)
2014-07-28 16:39:30,859 Translation(('S',) : is)
2014-07-28 16:39:34,701 Stroke(S- * P-)
2014-07-28 16:39:34,702 Translation(('SP*',) : None)
2014-07-28 16:39:34,884 Stroke(W-)
2014-07-28 16:39:34,884 Translation(('W',) : with)
2014-07-28 16:39:41,989 Stroke(S- *)
2014-07-28 16:39:41,990 Translation(('S*',) : {&s})
2014-07-28 16:39:42,678 Stroke(-P -G)
2014-07-28 16:39:42,679 Translation(('-PG',) : {.} {^ing})

**Comment by morinted** [comment]
The best behavior would probably be opt-in logging, with default 600 permissions, I think. Personally, I think password protection may be overkill if the user is just using the log for a case or for debugging.

**Comment by Skrylar** [comment]
fifo devices are a neat idea, yet impracticable on Windows. It's not quite as simple as running the *mkfifo* command there.

Turning logging off (or asking in a one-time startup dialogue) is probably the better choice.

**Comment by morinted** [comment]
Dialogue on start up is a great idea. That will let us notify the user. Thanks!
