### ISSUE TITLE
Cannot type special characters with alt, even when paused

### ISSUE THREAD

**Issue by SyntaxBlitz** [openstenoproject/plover#207]
On Windows, I can't use Alt+numpad to type in special characters. This occurs even when Plover is turned off, and the only solution is to completely close the program. This is frustrating because it's very convenient to keep Plover open at all times (and toggle when I need to use it), but I also need to be able to type accented characters when I have the program disabled.

**Comment by morinted** [comment]
This doesn't come up a lot, I'm going to close it in favor of more pressing bugs. Anyone looking to fix this issue, feel free to submit a PR.
