### ISSUE TITLE
[bug] Correction backspaces wrong number of characters.

### ISSUE THREAD

**Issue by Exaeta** [openstenoproject/plover#210]
How to replicate:

Type `S-RT S-RT S-RT P-B P-B R* * * * * *` on linux into firefox. 

Execpted output: `S-RT`
Actual output:  varies

**Comment by ezyang** [comment]
What OS, Linux? If so, this is probably the "Ibus can't deal with rapid input", see https://github.com/openstenoproject/plover/issues/218 and https://code.google.com/p/ibus/issues/detail?id=1697

**Comment by morinted** [comment]
Even though this issue is oldest, I like the information present in #218, so we will leave that issue open and continue discussion there.
