### ISSUE TITLE
Problem using Backspace/Delete and Enter/Space on the Kinesis Advantage

### ISSUE THREAD

**Issue by ecraven** [openstenoproject/plover#212]
Hello!

I have a Kinesis Advantage, which should work very well (though it doesn't seem to have n-key rollover, combinations of 8 or 9 seem to work well).

The thumb keys are very conveniently located, however the way plover handles them does not allow me to actually use them. I've copied and edited sidewinder.py to work by keycodes, not "keystrings", and Backspace for example results in an actual backspace being emitted (which it should not be, as Backspace is the A key for me).

Is there a way to fix this, short of grabbing the keyboard and adding a new uinput device for plover output?

Thanks for any help!
Peter

**Comment by hhirsch** [comment]
Can you gist or commit kinesis.py?

**Comment by ecraven** [comment]
Here you are.
I haven't tried it in some time, I hope it still works.  
If you are willing to work on this, I'll try to help out.

https://gist.github.com/ecraven/7fb938a4550c5a7195ec

**Comment by hhirsch** [comment]
Looks like this is incompatible to current master. $ plover
Traceback (most recent call last):
  File "/usr/local/bin/plover", line 3, in <module>
    from plover.main import main
  File "/usr/local/lib/python2.7/dist-packages/plover/main.py", line 22, in <module>
    import plover.gui.main
  File "/usr/local/lib/python2.7/dist-packages/plover/gui/main.py", line 15, in <module>
    import plover.app as app
  File "/usr/local/lib/python2.7/dist-packages/plover/app.py", line 20, in <module>
    import plover.config as conf
  File "/usr/local/lib/python2.7/dist-packages/plover/config.py", line 12, in <module>
    from plover.machine.registry import machine_registry
  File "/usr/local/lib/python2.7/dist-packages/plover/machine/registry.py", line 9, in <module>
    from plover.machine.kinesis import Stenotype as kinesis
  File "/usr/local/lib/python2.7/dist-packages/plover/machine/kinesis.py", line 98, in <module>
    n = len(steno_keys)
NameError: name 'steno_keys' is not defined

**Comment by hhirsch** [comment]
When plover is switched off, most keypresses result in garbage.

**Comment by ecraven** [comment]
as far as I understand the current git plover code, you'd need to get at the key code (not the keystring) in _key_down and _key_up and handle that accordingly. it shouldn't be hard to do, however the problem of special keys remains.. I can re-write kinesis.py, if you offer to adapt the core of plover to handle those special keys correctly?

**Comment by hhirsch** [comment]
Using your kinesis.py that is.

**Comment by ecraven** [comment]
I have originally taken sidewinder.py and just adapted it a bit, there weren't too many changes. I've also added kinesis.py to the list of machines in app.py

**Comment by ecraven** [comment]
see https://github.com/openstenoproject/plover/pull/232 for an up-to-date version. works here for me.

**Comment by ecraven** [comment]
this commit introduces an evdev backend instead of the xorg backend. it depends on python-evdev and having the uinput module loaded and writable by the user. in exchange for that hassle, it allows suppressing keys on linux.
it needs some more (easy) work, right now only the lower-case letters and space is supported, but it wouldn't be hard to add modifiers and the rest of the keyboard keys.
https://github.com/ecraven/plover/tree/evdev-backend

**Comment by hhirsch** [comment]
I will attemp that rewrite tonight.

**Comment by ecraven** [comment]
check out this branch, it should be a working implementation of that rewrite. it needs a bit of detailing, as explained in pull request #232 
https://github.com/ecraven/plover/tree/evdev-backend

**Comment by morinted** [comment]
As discussed, the Kinesis does not support true NKRO and at this time I don't think it's a necessary feature to strive for.
