### ISSUE TITLE
Unicode Characters above 16 bytes cause problems for backspacing and output

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#216]
NOTE: This Issue will not display correctly on some browsers/OS's. Firefox on any platform and OS X should work well.

Unicode characters that are above 16 bytes, like emoji and many non-latin characters, cause issues for Plover. This is because the "len" operator on these does not return valid values.

I discovered this issue while playing with emoji. To replicate the issue, create an entry with an emoji:

    "S": "😸",

Type the character, then "*" undo command. 2 backspaces will be sent instead of one.

Another place that the issue shows itself is if you are replacing an emoji with another one that has the same starting byte. Try these strokes:

    "S": "😸",
    "S/S": "😹",

The first stroke will output correctly, but the second will backspace once and then output a non-existent character. This is because Plover is trying to send half a byte.

**Comment by morinted** [comment]
The fix is merged and emojis and other long characters work 💩 🐈

**Comment by Achim63** [comment]
Great, thank you! The issue with incorrect backspacing is really unnerving at times.
