### ISSUE TITLE
Plover under Yosemite

### ISSUE THREAD

**Issue by Yourch2** [openstenoproject/plover#226]
Hello, I've discovered Plover and say Kudos guys ! But I can't make the application running. It crashes at the start. 
![Uploading Capture d’écran 2015-01-13 à 21.20.09.png . . .]()
could you please give newbies guidance to use it under Mac Yosemite ? Thanks a lot

**Comment by balshetzer** [comment]
Try this: https://github.com/openstenoproject/plover/issues/131

**Comment by Yourch2** [comment]
I did but didn't work. You know what ? I'm stupid. After a Mac restart it simply works.... Thanks

**Comment by Yourch2** [comment]
out of current topic, but what do you think about mac keyboard silicon skin with stenotypy letters ?

**Comment by Yourch2** [comment]
I can write in english but it doesn't work in French. Shall I install a dictionary ? which one ? where ? how to create one ? Thanks

**Comment by morinted** [comment]
If you are still curious about multi-lingual support, check out the Plover Google Groups.
