### ISSUE TITLE
Helping with French / Azerty keyboards

### ISSUE THREAD

**Issue by Yourch2** [openstenoproject/plover#227]
Hello, if you'd be interested with help to translate into French and adapt for AZERTY keyboards, please let me know
.Cheers

**Comment by balshetzer** [comment]
Thanks for the offer. 

Does Plover currently not work on AZERTY keyboards?

We haven't, yet, worked on translating Plover to other languages but when we do we'll reach out.

**Comment by Yourch2** [comment]
I don't know if it doesn't because I could make Plover work on Mac/Yosemite. But a solution is to select a Qwerty layout anyway and add a N key rollover
