### ISSUE TITLE
Cygwin doesn't support python-wxgtk2.8, install instructions needed

### ISSUE THREAD

**Issue by bootmii** [openstenoproject/plover#228]
For whatever reason, there doesn't seem to be a python-wxgtk2.8 for Cygwin. Can you release a version of Plover that runs within Cygwin but doesn't require wx?

**Comment by balshetzer** [comment]
There is a native windows version of Plover. Does that not work for you?

**Comment by morinted** [comment]
I'm going to close this as I don't see why Plover needs to support Cygwin. If there is a good reason that I can't think about, feel free to reopen the issue with your case.
