### ISSUE TITLE
Strokes to switch dicts

### ISSUE THREAD

**Issue by hhirsch** [openstenoproject/plover#233]
Add the possibility to switch dicts with strokes.

Edit by @morinted: We need commands to reorder dictionaries (can be based on dictionary file name + path, given a pull to front/push to back style command, then enable and disable with the same matcher)

**Comment by morinted** [comment]
Any ideas how this could be implemented? How do proprietary softwares manage this task? I can't imagine the UI for it quite at the moment.

**Comment by stenoknight** [comment]
Proprietary steno software does it with menus. Not possible to do with the
steno machine.

I dunno, maybe a hotkey for a dialogue that brings up a numbered list of
dictionaries, and you stroke a number to bring that one down to the bottom?

**Comment by morinted** [comment]
Is this worth the development cost or do you think it's not a common issue? Would you find yourself using it if it were present?

**Comment by stenoknight** [comment]
I'd say it would be useful to have at some point, but not a high priority.
Main thing I see myself using it for is if I forget to rearrange my
Vim/Non-Vim dictionaries before a job and have to do it in a hurry.

**Comment by Slotkenov** [comment]
I would actually love to see a is stroke for this. I'm trying to create a Dutch dictionary (just for fun) and I want to switch back and forth between Dutch and English.

**Comment by benoit-pierre** [comment]
https://pypi.org/project/plover-dict-commands/
