### ISSUE TITLE
Allow enabling and disabling Plover with a customizable hotkey

### ISSUE THREAD

**Issue by cool-RR** [openstenoproject/plover#235]

**Comment by balshetzer** [comment]
There is already the ability to turn plover on and off using a key chord. Did you want something different?

**Comment by cool-RR** [comment]
Hmm, I want to enable reenable using a definable hotkey, like ctrl-start-p or something. How can I do that?

**Comment by balshetzer** [comment]
That is not currently possible. You would have to use a steno stroke.

**Comment by cool-RR** [comment]
Hmm. But aren't steno keystrokes detected only when plover is on? So would
this work to turn plover on?

**Comment by balshetzer** [comment]
It's probably not what you want so we'll leave this feature request open.

What I was talking about: When you use your keyboard as the steno machine, even when Plover is disabled, it still listens for strokes that match commands. So you can define a stroke for suspend, resume, or toggle. Those will work even when Plover is disabled. See those commands here:
https://sites.google.com/site/ploverdoc/appendix-the-dictionary-format#TOC-The-Plover:-Control-Command

**Comment by cool-RR** [comment]
Thanks, this worked. Thank you for your persistent help Hesky!

**Comment by ezyang** [comment]
What I find is not so great about this method is, since the input is not "grabbed", enabling results in a bunch of garbage dumped to the screen.

**Comment by hhirsch** [comment]
I usually type asterisk after enabling plover to remove the garbage characters. Deleting them by default or grabbing them by default will be worse imho. If you if you guys agree, this issue can be closed.

**Comment by balshetzer** [comment]
ezyang: In which operating system are you experiencing garbage dumped to the screen when you enable Plover? Which version of Plover? Is it a Plover release or your own branch? Can you elaborate on what the "garbage" looks like? Is it the keys in the chord used to enable or something else? What is your stroke to enable? Thanks for your help.

**Comment by ezyang** [comment]
@balshetzer This may very well be the fault of the Linux evdev branch. The garbage is the NKRO emulated keypresses of the starting chord.

**Comment by chajadan** [comment]
On a current version of plover on windows 7, my enable/disable chords are properly suppressed.

**Comment by morinted** [comment]
Yup @chajadan that was an issue that was fixed not too long ago. I'm going to close this issue as the stroke works pretty well considering that the raw characters are now properly removed.

**Comment by mec07** [comment]
Just so that someone else who arrives at this thread can quickly find the answer. You can toggle plover to be enabled or disabled using the chord: `PHROLG`. More info can be found here: https://github.com/openstenoproject/plover/wiki/Dictionary-Format#plover-control-commands, where they describe it as a mnemonic for PLOver toGGLe, or PLOLG (which should be keyed as `PHROLG`)
