### ISSUE TITLE
Alt-tab doesn't work in Windows 8.1

### ISSUE THREAD

**Issue by stenoknight** [openstenoproject/plover#237]
It works in Windows 7, but doesn't appear to work in Windows 8.1. Not sure whether it worked on previous versions of Windows 8 or not.

**Comment by shayneholmes** [comment]
AHK had this issue and needed a `UIAccess=true` defined in the manifest. This is done in AHK with a script available at http://www.autohotkey.com/board/topic/70449-enable-interaction-with-administrative-programs/.

More background:
* http://superuser.com/questions/449003/autohotkey-and-windows-8-alttab-command-does-not-work
* https://github.com/synergy/synergy/issues/3268

**Comment by stenoknight** [comment]
Good to know! Thanks!!

**Comment by morinted** [comment]
To note, it works in Windows 10. That's a pretty strange case. Also, it didn't work in 8.1 with our without administrative mode, and works in Windows 10 with or without it.

**Comment by morinted** [comment]
We could fix it, maybe using https://pythonhosted.org/PyInstaller/#windows-specific-options ?

I think it's not a big deal, considering that Windows 8 is being largely replaced by Windows 10 and people who don't like either stick with Windows 7.

I'll leave the issue open but I'm skeptical of putting in the effort.

**Comment by benoit-pierre** [comment]
Is that still an issue?

**Comment by benoit-pierre** [comment]
Do we care about Windows 8.1? (Mainstream support ended on January 9, 2018 according to Wikipedia).

**Comment by morinted** [comment]
I don't think we should bother fixing this. Upgrade Windows to fix :)
