### ISSUE TITLE
Plover can start off screen and is irrecoverable

### ISSUE THREAD

**Issue by Finktron** [openstenoproject/plover#240]
Plover icon and Task Manager both show Plover.exe is working, but the window will not show up on the screen, nor does bringing the task to the front from Task Manager actually maximize the window. Hovering over the Plover icon, I can see that it appears frozen and only partially loaded. I've restarted and shut down the computer, but upon reboot the issue persists. I've made sure to unplug my Stentura from the machine but I am still not having any luck thus far. 

Thanks,

-Mike Fink

**Comment by balshetzer** [comment]
Hi,

This is a known bug, hopefully it will be fixed soon. Until then:

There is a file on your computer called plover.cfg. It's probably at a path that looks like this:
C:\Users\YourUserName\AppData\Local\plover\plover\plover.cfg

Exit Plover
Either delete this file or 
open it and find a section called: [Main Frame]
In that section are two lines, one starts with x= and the other with y=. The values are probably -32000 in your situation. Delete those two lines.
Start Plover

Let us know if that works.

Hesky

**Comment by Finktron** [comment]
Hesky,

Deleting the .cfg file seems to have done the trick. Thanks so much!

-Mike

On Sat, Mar 28, 2015 at 12:25 PM, Hesky Fisher <notifications@github.com>
wrote:

> Hi,
>
> This is a known bug, hopefully it will be fixed soon. Until then:
>
> There is a file on your computer called plover.cfg. It's probably at a
> path that looks like this:
> C:\Users\YourUserName\AppData\Local\plover\plover\plover.cfg
>
> Exit Plover
> Either delete this file or
> open it and find a section called: [Main Frame]
> In that section are two lines, one starts with x= and the other with y=.
> The values are probably -32000 in your situation. Delete those two lines.
> Start Plover
>
> Let us know if that works.
>
> Hesky
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openstenoproject/plover/issues/240#issuecomment-87271222>
> .
>



-- 
Mike Fink

**Comment by morinted** [comment]
Hesky, is this still a problem? If so, where could I fix this? Does Plover read the -32000 and can it treat that as undefined and reset to default? I'd like to fix this problem as it comes up now and then on the Groups.

**Comment by balshetzer** [comment]
Windows sets the position of minized windows to -32000,-32000. That's the source of this bug. I don't think it's been fixed. You could do what you suggested. I thought we did bounds checking already on the screen but maybe that's not working correctly.

By the way, you might also want to make a parent class for our GUI windows that has all our common behavior (like saving position in the config) so that you don't need to do fixes like this in every window separately. The common behavior has gotten pretty complex including things like cross platform focus switching.

**Comment by morinted** [comment]
Good idea. We do have a lot of windows. Thanks for the advice.

**Comment by morinted** [comment]
We are going to keep track of this issue in #272
