### ISSUE TITLE
OSX: Keyboard events send keycode zero

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#246]
All keyboard events in OSX send keycode zero but they also set the string. Most apps honor the string but some do not. Those that do not will see all of our key strokes as the letter A (at least when the keyboard is set to be the US keyboard). Ideally, the other app would just honor the string but we can mitigate the situation by sending the correct keycode, when possible. 

There are a couple of options. We can just assume the keyboard is set to US English and choose those keycodes. A better option would be to find out what the current keyboard is and send the right codes for that keyboard. The problem with either solution is that this means the user cannot type things that don't exist on that keyboard. But maybe that's the best we can do.

**Comment by balshetzer** [comment]
An app that doesn't honor the string on the event is Anki.

**Comment by Achim63** [comment]
I have yet to find a program where Plover doesn't work in OSX. As for Anki: there's so many alternatives, e.g. the free ProVoc which I use for years now. So I wouldn't tweak Plover to adjust for apps that don't conform to standard behavior in their input fields - this might lead to many problems for users of non-US keyboards and introduce other new bugs. I was rather surprised (and glad) that Plover doesn't interfere with all the key combinations outside of the part of the keyboard it uses.

Your first "solution" would mean for me having to change the keyboard layout to US English every time I want to use Plover.

The second solution would be rather elaborate (-> bugs) and time-consuming and would probably prevent me from using e.g. "ñ" or accents if I want to type Spanish with my German keyboard (or some borrowed French words, or the Ohm sign "Ω" etc.) while Plover is running. As they say: never change a running system ...

**Comment by Arthaey** [comment]
Is it Anki-specific, OSX + Qt, or all Qt applications that have this issue?

**Comment by balshetzer** [comment]
@Arthaey No Idea. The only report I've had was about Anki. A report was filed with Anki here:
https://anki.tenderapp.com/discussions/ankidesktop/14271-compatibility-with-plover-stenography-software

The response was:
Anki uses WebKit for its editing areas, so this appears to be a bug in WebKit. It's possible it's already been fixed in a subsequent release, but we're currently stuck on the existing version due to other issues. Once we get the issues solved or find an alternative solution, this problem may go away.

**Comment by Achim63** [comment]
I might check at work on Monday where we just build an app using QT - it contains text input fields so I can test this.

**Comment by Achim63** [comment]
Plover works fine in textfields within our app that uses Qt (on OSX 10.10.4).

**Comment by Arthaey** [comment]
Do you know whether your other Qt app uses Qt4 or Qt5? (Anki is stuck on Qt4.)

**Comment by Achim63** [comment]
A dev told me they were using Qt 5.5.

**Comment by morinted** [comment]
I think I can add keycodes without breaking any current functionality. It should only matter in these special cases like Anki and kdiff3. I could generate an alphabet with http://stackoverflow.com/questions/1918841/how-to-convert-ascii-character-to-cgkeycode/1971027#1971027 this kind of code, and most keys that are not alphanumeric are static keycodes that we already know.

**Comment by morinted** [comment]
**Huh, we already have hard-coded key codes when using commands.**. All the alphabet is hardcoded and other layouts won't work. E.g. "{#a b c d}" is not the same in Qwerty and Dvorak, even though "a b c d" is.

The solution is two-fold: first, we need to *generate* the keycodes based on the current layout. An implementation would be [something like this](https://github.com/abarnert/pykeycode).

Second, the `send_string` osx function would need to be adjusted to send keycodes as in `_send_sequence` in order to handle capitals and such.

I also do not know the consequence of what happens if Plover attaches an incorrect keycode. Experimentation ensues, I'm sure.

**Comment by Achim63** [comment]
That would be a really nice to have as I realized when I attached a little Win8 tablet to my Cybra (so it's kind of a "standalone" steno unit now). Not even ASCII characters like the question mark come out right when I don't switch to the US key layout. On OSX I can leave my German layout without issues.

**Comment by morinted** [comment]
Well, the work I'm describing above would only affect OSX's sending of key codes, which helps a subset of OSX programs.

For Windows… That shouldn't be happening at all. Can you explain the outcome when you start Plover on Windows with the German layout as well as what the difference is when you start Plover on Windows with the US layout? I'd be curious to dig into this, too.

**Comment by Achim63** [comment]
I was using the version that has the suggestions window - seems that one is buggy (I get all kinds of funny characters. Mostly I get the character that is on the German keyboard at the same location the stroked character is on the US keyboard - but it also acts up when I have US international selected, for instance whenever I try to type quotation marks).
I don't have those issues with the release version - there I can leave the keyboard layout on German. So I'll use that for now.

**Comment by Achim63** [comment]
I'm doomed - with the release version I get the exact same issue Mirabai had with Scrivener. Missing letters. Guess I'll have to write into Notepad++ and copy/paste to Scrivener. Your build from October takes care of that - but as stated it introduces other issues.
Maybe it's actually a bug in Scrivener for Windows (no problems in the Mac version).
Or maybe Windows knows that I'm not on good terms with it ... never was ...

**Comment by Achim63** [comment]
I played around a bit more - there seems to be certain strokes that simply don't show up immediately in your build. In the Magnum dictionary, the quotation marks are defined as "SKWR*" and "*RBGS". If I strike one of them, they don't show up - only on the next stroke they will be inserted. The closing quotation mark is missing the following space on the next stroke (it's defined as "*RBGS": "{^}\""). This happens in both Scrivener and Notepad++.
