### ISSUE TITLE
Non us keyboards

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#25]
I have played with Plover today (and really like it). 

It has a small problem as a non-us citizen. My keyboard layout differs from the us after p and l (moving rightwards). 

It would be great, if one could change the key mapping in Plover, so that one does not have to either change keyboard layouts or type wierd two or three letter combos for a single key... 

Just for reference.. the DK keyboard (which I use) goes "opå"  and "klæø" ....

Maybe a option i the gui to enter the three "differing" letters?

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-01-14T15:27:34Z
 * owner: svenne-3
 * the launchpad url was https://bugs.launchpad.net/bugs/916505

**Comment by morinted** [comment]
I'll close this as fixed, then, as it seems that in general Plover works with non-US layouts.
