### ISSUE TITLE
Windows version doesn't implement all the special keys

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#255]
The windows version hasn't implemented all the keys like Linux and osx. Also, it prints unrecognized commands, unlike the other versions.

**Comment by chajadan** [comment]
Perhaps related, when you type a stroke into the add translation box, if it was a special command, like {#less}, it doesn't capture the stroke, and instead enters "less". You end up having to type the stroke letters in manually to alter the mapping.
