### ISSUE TITLE
The Plover dictionary needs to be cleaned up

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#257]
The Plover dictionary has many non-entries and also a lack of default strokes for commands (like why isn't TKUPT a default yet?).

This issue will cover any challenges when working towards cleaning up the dictionary. Suggestions are welcome and encouraged.

**Comment by stenoknight** [comment]
So I've added many, many, many entries to my various dictionaries since I first uploaded the Plover default dictionary five years ago. I'd like to submit some of those entries for merging into the new Plover default dictionary, but some of them probably contradict what people have been using up 'til now, and I don't want to confuse anyone. Also, some of them inevitably are proper names that most people won't use, or dental-school-specific jargon that has very limited function for someone who's not captioning dental school. Still, there's a lot of definitions in there that would be extremely useful -- particularly things like Vim-specific commands.

Can I give you my most recent dictionaries and let you maybe merge them with the Plover default, but giving precedence to the Plover default dictionary in cases of conflicts, and with full discretion to purge entries that aren't helpful to the general Plover user?

**Comment by morinted** [comment]
If you give me the dictionaries, I'll diff it against the Plover default
dictionary, do some trimming, and then run it by you for approval. I
imagine that there may be some strokes that you have made that *should*
replace the Plover ones, so I'll be on the lookout for that. You can link a
zip of your dictionaries on this issue, or just email it to me directly if
you don't want it to be public.

**Comment by morinted** [comment]
Thanks for getting those to me, I'll do my best to get that done soon (I think it's one of the more fun tasks).

I have entries in my dictionary for numbers from "twenty-one" to "ninety-nine" (instead of "twenty one" and "ninety nine"). Do you think it would be worth adding those to the dictionary? Or is it "bad" because people might be confused from the word boundary when trying to write "thirty two by four planks"?

**Comment by chajadan** [comment]
It's a word boundary issue, but your case would be the default scenario,
not the exception, for most people. The whole thing's handled easily enough
currently with H-PB without those entries, but you have to stroke it. With
your entries, the burden switches to S-P when hyphen's not wanted. I'm
guessing it may very well be an improvement with your entries.

**Comment by morinted** [comment]
All right, everyone, listen up. I did some crazy manipulations and have a few gists to show you. Mirabai, if  I prioritize Plover's dictionary over your other ones, this is EXACTLY what will be replaced: https://gist.github.com/morinted/49b330d53ceb89bba491

The red shows what was in your dictionaries (that you are using right now) and the green is what Plover's default dictionary currently has. I think in most cases yours wins, so check that out.

Secondly, I have a full diff between your dictionary and Plovers. The purpose of this file, more or less, is to show what will be added if I add your dictionaries as is. All the "red" lines are what are in your dictionary and not in Plover. All the "green" lines are what are in Plover's default dict and not yours. If an entry as both red and green, it's a conflict. Warning, this is a HUGE file and will slow down bad browsers. Try Chrome or Edge? https://gist.github.com/morinted/a4541698217cbbc0224f

If you only want to see the diff file for that (the web page is slow and truncated), you can view the plaintext here: https://gist.githubusercontent.com/morinted/a4541698217cbbc0224f/raw/ea4f4aeaddb5068d9ac2d617d69cc133b8165cff/full_difference.diff

**Comment by morinted** [comment]
What purpose do these strokes serve in life?

`"H*PLD": "{&.h}",`

**Comment by morinted** [comment]
All done. You can see the output here. https://gist.github.com/morinted/55e350b1f7b23baeb43e

I think that the next step will be to use the merged files, apply these conflicts, and then look for the "fat", e.g. heavy medical terms, extra "flush" strokes, and other broken entries.

**Comment by morinted** [comment]
Really frustrating tidbits:

1. By having all the dictionaries in separate json files in our assets folder, it's hard to add these new strokes because I have to check against each and every dictionary.

It might be nice to merge all the dictionaries back into the one file, but I know that that's how it used to be and that we moved to this new system in order to make finding strokes easier. Maybe there's a better way?

2. I can't automatically merge in changes because we sort our JSON by value in Plover's dictionary, instead of by key. All the scripts I'm using assume that you sort by key. This is proving really troublesome.

Is it unreasonable to want to sort the dictionary by key (stroke) instead of value (translation)?

**Comment by stenoknight** [comment]
I thought the eventual goal was to have only two dictionaries: The main
dict.json  dictionary, sans commands, and the command dictionary. No?

There can be multiple identical definitions matched to different strokes in
a dictionary, but ideally each stroke is unique. (Multiples of the same
stroke might be matched to different definitions due to an incomplete merge
somewhere along the line, but if so, we should purge one.)

So I'm not sure I understand your question about changing the sorting. Can
you clarify?

**Comment by morinted** [comment]
If you look at `/plover/assets` right now you can see we have quite a few
dictionaries with very little content. I'd like to get rid of this. I am
okay with just 2 as you described.

The sorting: right now it is like this:

```
"SKWROB": " job",
"SAD": "sad",
```

I'd like to change it to this:

```
"SAD": "sad",
"SKWROB": " job",
```

So the difference is right now Plover sorts by value/translation (job,
sad), I'd like to sort by key/stroke (SAD, SKWROB)

**Comment by stenoknight** [comment]
I didn't think Plover sorted dictionaries at all. I thought it determined
priority based on the arbitrary order of the entries in the  json file. So
if you give it a json reading

{"SAD": "seasonal affective disorder",
"SAD": "sad"}

It will translate "SAD" as "sad", but if you give it

{"SAD": "sad",
"SAD": "seasonal affective disorder"}

It will translate "SAD" as "seasonal affective disorder".

But like I said, there shouldn't be duplicate strokes in the dictionary
anyway (if there are, we should resolve that), so it shouldn't matter what
order the entries are in.

Or am I misparsing what you're saying?

**Comment by morinted** [comment]
Right now we have a separate dictionary in the repo for prefixes and
suffixes. As I'm working on this new stuff, let's say I have the new stroke

    "HO*EUP": "{hypo^}"

Now I have to do 2 things. 1. Add this stoke to the prefix dictionary. 2.
Check if it exists in dict_unsorted.json. it does, it translates to hype.
So I delete that line.

That's a very intensive task when you consider that there are thousands of
new strokes. If there was only one dictionary, the talk would just be "set
the stroke to the suffix" and the other one would be overidden
automatically. But there are 6 or 7 and so I have to check them all and
resolve conflicts.

**Comment by morinted** [comment]
Task*

**Comment by stenoknight** [comment]
Merge away, say I. One dict.json and one commands.json works for me.

**Comment by morinted** [comment]
I like that. I'll also try sorting by keys for now and we can always revert
if we find some bad reason against it.

**Comment by Achim63** [comment]
I'm  not sure if sorting by stroke is such a good idea. A user who doesn't know about grep and want's to find the stroke for a certain word might do a "find" in a simple text editor and just take the first occurrence as his result, not knowing there might be other, even better, alternatives. His/her result could even be one that was only intended to catch a misstroke.
E.g. the Magnum strokes for "she" ("SHE", "-RB") would end up in completely different places in the dictionary.

**Comment by morinted** [comment]
I'm not going to change plover's behavior, only the depository's.
Furthermore, Plover has dictionary management now and it is not dependent
on the order of the strokes in the physical file. Do you think that's
adequate?

**Comment by Achim63** [comment]
If you're only changing the files in the assets directory and not the dict.json that's written by Plover it would be OK I guess.

**Comment by morinted** [comment]
I'll do some testing and report back here. Wouldn't it be nice if by
default Plover came with three dictionaries? "dict.json", " commands.json",
and "personal.json"? Personal is blank and the users will add to it by
default when adding strokes.

**Comment by Achim63** [comment]
That sounds like a great idea.

**Comment by morinted** [comment]
There's already an issue for this elsewhere. I'll include it as a separate change than the dictionary clean up as I feel that they are best served separately :) plus more PR's makes me feel more productive.

**Comment by morinted** [comment]
Is there a reason that we don't include the c-word in the dictionary? We already have b, f, a, and other swear words. In Britain, the c-word is very inoffensive and I am not too sure why we don't include it. However, I do realize that some people find the word exceptionally offensive and that might be why it's not included. Thoughts?

**Comment by morinted** [comment]
Check out #265, it's around 18 thousand new entries, thanks to @stenoknight

**Comment by stenoknight** [comment]
Woo-hoo!!!

But I'm gonna pull my Plover Autocrat hat on here and say that our mascot's
name is spelled Dolores, not Delores. I just like that spelling a million
times better.

**Comment by morinted** [comment]
It is probably that way in the dictionary, I'll confirm later when I have a
PC

**Comment by morinted** [comment]
@stenoknight this is pretty much done now. I'll consider your commands as supplement, and will close this issue. If you send me a list of your favorite commands, we can make another PR. If you want to include optional Vim commands, we should figure out how to make those optional for casual, non-Vim users.
