### ISSUE TITLE
Strokes being held back in OSX version (Transcriptor X)

### ISSUE THREAD

**Issue by stanographer** [openstenoproject/plover#258]
Only in the OSX version, up to the last three strokes will be held back for an indeterminate amount of time (usually ranging from a fraction of a second to several seconds) before Plover receives them and translates them. Writing more strokes "pushes" the held-back strokes, however. Although I have a suspicion that this is due to BT going into power saving mode.  When the lag starts, I typically restart Plover and it will momentarily stop but usually comes back after a few minutes of writing.

All types of strokes are equally affected. Command strokes lag just as much as text-only ones. I haven't observed this lag in the Windows version.

**Comment by Achim63** [comment]
I can reproduce this. But after a restart it mostly works fine for hours until this bug kicks in again.

**Comment by morinted** [comment]
This sounds similar to #189. Can you try Plover version 2.5.7 to see if the problem persists there? https://github.com/openstenoproject/plover/releases/download/v2.5.7/Plover.dmg

**Comment by Achim63** [comment]
I'll try to do this sometime this weekend. Might well be the same as #189 since I also use the TX Bolt protocol.

**Comment by stanographer** [comment]
I will try using 2.5.7 today to see if the same problem keeps happening.

**Comment by morinted** [comment]
Update: stroke display *does not* update when the slow down occurs, demonstrating that this is a problem with the reading of the machine itself on OSX.
