### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#261]
- Tasks
  - [ ] Lint the codebase using `flake8`
- Contributor documentation
  - [ ] Editing guide for the dictionary for dictionary contributors
  - [x] Add a Contributing.md (via PR #351)
  - [ ] Point contributors to our lint script in README / CONTRIBUTING
  - [ ] A couple diagrams explaining the hierarchy of the system would be useful for new developers getting started.
    - There could be a global diagram, and also a section for users who just want to work on the dictionary (which is less technical and doesn't involve Python)
- User documentation
  - [x] Converting the Plover Guide to Markdown (via PR #352)
  - [ ] Updating the Plover Guide:
    - Remove outdated information
    - Add a header structure to make documentation easier to reference. Link to material in Learn Plover! where appropriate.
    - Section ideas: dictionary hacking, special commands, guides on various Plover utilities (will be required with dictionary manager and suggestions window)

**Comment by jeremy-w** [comment]
@morinted I can tackle these.

I'm not clear on the first item, though:  "Editing guide for the dictionary for contributors" Could you elaborate on this?

**Comment by morinted** [comment]
Just what we do and don't want for the default dictionary → for example, adding animal names would be nice, but adding weird, special commands that are platform specific, not so much. Maybe link out to Stenodict now that it exists. Also, we have a commands.json where all commands should go. Finally, preserve the alphabetical order of the dictionary (I think it's ordered by translation)

**Comment by jeremy-w** [comment]
Perfect, thanks!

**Comment by morinted** [comment]
Here's my work in progress changelog for the next release:


Features
====================

- **Full Unicode support** on Windows, OS X, and Linux. Now you can use a non-Latin alphabet, including extended symbols such as emoji 💥
- **New lookup window**, to look up strokes for a word. Use {PLOVER:LOOKUP}
- **Configure whether space is outputted at the beginning or end** of the current stroke (default/current is like " add", new option outputs "add ")
- **New Dictionary Editor**! Lets you view and edit strokes in your dictionaries. You can filter by stroke or definition, and add, edit, and delete entries in your JSON and RTF dictionaries.
- **New Suggestions window**. The suggestions window is a training tool that watches what you are writing, and gives other strokes that have the same output. It's great for discovering briefs.
- **New commands:**
    + Repeat last stroke: repeats the last stroke exactly, useful for things like arrow keys to avoid having to do a complex stroke multiple times: `{*+}`
    + Uppercase next word, turns "word" into "WORD": `{<}`
- **New *retrospective* commands:**
    - **Retrospective capitalize**

        Capitalize last word: `{*-|}`
    - **Retrospective uppercase**

        Uppercase last word: `{*<}`
    - **Retrospective lowercase last word**

        Lower the first letter of the last word: `{*>}`
    - **Retrospective toggle asterisk**

        Change whether the last stroke did or didn't have an asterisk: `{*}`.
    - **Retrospective insert space**

        "Split" the last two strokes, turning `KAT/LOG`, "catalogue", into "cat log": `{*?}`
    - **Retrospective delete space**

        Remove a space between the last two words, turning "break off" into "breakoff": `{*!}`
    - **Retrospective currency formatting**

        Using a stroke of the form `{*($c)}`, where you can replace "$" with your own currency symbol, Plover will adjust your last stroke, if it's a number, optionally with two decimal places, (e.g. 123412.34) into currency format (in this case, $123,412.34)
- **Delete words on empty buffer**. When Plover runs out of asterisk-undos, it will start to try to delete a word at a time instead of doing nothing.
- **Add remapping of the keyboard's layout through the configuration dialog**, so that users can change which keys are suppressed and which suppressed keys correspond to steno keys. For example, you can suppress the spacebar, or set "Tab" to act as `S-`.
- **Notifications!** Information and errors are now displayed in your system's notifications system.
- **New error log**. `strokes.log` now shows strokes and translation output, `plover.log` shows errors and logged information.
- **Better portable mode**. Configuration file (`plover.cfg`) and dictionaries can be stored relatively, so Plover should work portably.
- **Radio buttons instead of red/green P for output enabled/disabled**. Tweak main user interface window to be a little more accessible for users who may have difficult distinguishing between red and green.
- **Add multiple dictionaries at once**. You can now add multiple dictionaries at once instead of one at a time in the "Add Dictionary" file selector.
- **Add output modes** (manage case and space character)

    Introduce a new breed of meta command, "MODE". Now Plover has persistent "modes" that affect the output of the text. The core of the functionality comes from controlling just:

    - The text case
    - The space character

    **For the text case, users can use "CAPS", "TITLE", "LOWER". This lets the text come out IN ALL CAPS, In Title Case, and, in all lowercase.**

    **For the space character, using "SET_STRING", users can effectively replace Plover's built in "space" character with any of their choosing.** For example, youcouldsetthecharacter to nothing, or-to-the-dash, or-ow-to-ow-any-ow-arbitrary-ow-string.

    Then, to disable the functionality, users can use "MODE:RESET_SPACE" to reset to the default space, "MODE:RESET_CASE" to reset to the default case, and "MODE:RESET" to clear the space character and the case.

    Finally, Plover ships with some **special mode names to help out programmers: "SNAKE" and "CAMEL".** Snake just sets the space character to underscores,_like_this_if_you_will, and Camel sets the next character to lowercase (using "{>}"), sets the case to Title case, and sets the space character to none, thus resulting inThisOutputStyle.

    Example dictionary for most of the strokes (reset space and case aren't useful to me personally):

    ```json
    {
     "KA*PS": "{MODE:CAPS}",
     "T-LT": "{MODE:TITLE}",
     "HR*R": "{MODE:LOWER}",
     "STPH-BG": "{MODE:SNAKE}",
     "R-FT": "{MODE:RESET}",
     "KHRAO*ER": "{MODE:RESET}",
     "TK-RBS": "{MODE:SET_SPACE:-}",
     "K-BGS": "{MODE:CAMEL}",
     "TPH-FPS": "{MODE:SET_SPACE:}"
    }
    ```


Dictionary
====================

- Split default dictionary into 3 default dictionaries. New Plover users (or users without any dictionaries configured) will find 3 dictionaries set up in their dictionary list by default: `main.json`, `commands.json`, and `user.json`. "Main" contains all the words, numbers, prefixes, and suffixes from the default dictionary, whereas  "commands" is just the commands, such as copy, paste, add dictionary translation, toggle Plover, et cetera. The "user" dictionary is a blank dictionary that new strokes will automatically be added to, alleviating one of the struggles of starting out learning steno and not realizing that it's important to separate your own strokes from the default strokes.
- Add more time increments (1:05 through to 1:55) to the default dictionary, using the `K-` and `-BG` strokes.
- Add symbols to the dictionary to match Learn Plover!
- Roughly 20,000 entries added to the main dictionary, mainly from Mirabai's and Ted's personal dictionaries. Includes some fixes, lots of new words, and steno-specific terminology.A

Fixes
====================

- The Linux keyboard is now suppressed while Plover is outputting, instead of having to backspace the keyboard keys there were pressed.
- Plover windows should no longer get stuck off screen on start up, an issue that Windows users were prone to.
- Reduce Stentura CPU usage.
- Reduce Tréal CPU usage on Linux and Mac.
- Mac OS X build is now 64-bit, and has retina display support.
- Windows now has support for all the special keys, including using the Windows key (`{#Super_L() grave space}`)
- "NKRO Keyboard" has been renamed to "Keyboard". 
- Command-C now copies in Mac dialogs, instead of closing them.

Developers
====================

- Replace hard-coded key layout with customizable list. Be
- Plover can be launched in development now with `[sudo] python2 launch.py`
- Add CONTRIBUTING.md for guidelines on submitting issues and pull requests for the repository.
- Continuous Integration has been set up to build on Windows, Mac, and Linux with AppVeyor and Travis CI.

**Comment by morinted** [comment]
Not going to keep with this game plan -- I have other ideas nowadays.
