### ISSUE TITLE
Plover Guide is out of date

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#262]
The Plover Guide has not been updated since it was released, and is written in LaTeX.

I am opinionated, but I think that we should write the Plover Guide in Markdown, and then it will be readable from GitHub directly, and if we still want to output into PDF we can use Pandoc.

**Comment by stenoknight** [comment]
Rewriting the Plover Guide in Markdown is an excellent idea.

**Comment by morinted** [comment]
It's in progress! Just like everything else :p

**Comment by lifton** [comment]
Yes, Markdown + Pandoc is the one true path.

**Comment by morinted** [comment]
I stopped working on this because features keep happening. Should we even still maintain the Plover Guide, or move docs into the wiki and have them just refer to the latest version?

**Comment by morinted** [comment]
We will consider writing a user manual in the wiki as part of the documentation for 4.0.0
