### ISSUE TITLE
Suggestion window doesn't work for first word in a sentence

### ISSUE THREAD

**Issue by Achim63** [openstenoproject/plover#264]
Since the first word in a sentence is always capitalized, the suggestion window doesn't show any results for lower case words, so it stays empty most of the time in this case.
I'd expect the search to be case independent, maybe marking the result somehow if it's not an exact match (attach e.g. " (no caps)" or some such to the stroke definition).

**Comment by morinted** [comment]
@balthamos would you be able to make a fix for this? I'm not sure where you can fit it in the UI. I think the user should be indicated *somehow* that the case doesn't match. But definitely would be useful in case you have a stroke such as "Android" and you get the suggestion for "Android" after you type "android".

Maybe it could be like this:

User types cat. Stroke suggestions:

```
cat:
KAT
KAET
Cat:
KA*T
CAT:
KA*T/KA*T
```

Thoughts?

**Comment by Achim63** [comment]
That looks fine - similar to what I do in a bash script to look up entries.

**Comment by balthamos** [comment]
As you pointed out, the current UI is insufficient for displaying multiple suggestions. It could probably be changed to mimic the list you wrote out, with maybe the words bolded to make the sections more distinct and easier to read.

Have any other ideas for how to display this information cleanly?

**Comment by morinted** [comment]
Well, if you implement it such that the information is returned in a list
of lists (assuming that you would have perfect match first, then ordered by
parity difference or position of caps?), then we can always change the UI
later. I'm alright with just providing bold rows with colons for the
definition (maybe in a regular sans serif font) then fixed-width stroke
definitions as it is now. Maybe a *slightly* lighter gray for the non-exact
matches. But we can tweak all this to our liking after trying it out :)

**Comment by balthamos** [comment]
Yea, I'm not particularly concerned about the backend logic; it should be a fairly straightforward implementation. Just thought I'd shake the bushes for any good ideas in the UI department. Measure twice, cut once kind of thing :)

**Comment by morinted** [comment]
Cool. Yeah, I'd just say something along the lines of:

**cat:**
`KAT`
**CAT:**
`KA*T`

Yeah, and with the non-exact matches with a dark grey instead of pure
black. Then maybe take a screenshot and share it here and everyone can
comment.

**Comment by stenoknight** [comment]
A bonus feature might be a basic parser that looks for the phonetic
definition based on a simple steno phonetics table + English phonetic
dictionary match and then highlights that entry with another color or
boldface or something. Highlighting the phonetic entry automatically would
be helpful for beginners who don't yet have the skill to quickly discern
phonetic from brief from misstroke, and who become confused when presented
with multiple options.

**Comment by morinted** [comment]
How do you sort the strokes currently? Is it alphabetical, by string length, or number of strokes?

**Comment by balthamos** [comment]
It currently sorts by total number of keys used, across all strokes. Generally, the word that uses the fewest keys also happens to have the fewest number of strokes, but I suppose that isn't always the case.

**Comment by balthamos** [comment]
Here's what I got:

This screenshot shows how proper suggestions are given at the beginning of a sentence (addressing original FR) and how multiple suggestions are now given for different cases.

![screen shot 2015-09-29 at 9 37 12 pm](https://cloud.githubusercontent.com/assets/38643/10183902/48603dac-66f2-11e5-9465-bd9947e251b4.png)

This next screenshot shows how multiple suggestions work with regards to phrases and prefixes/suffixes/glue:
![screen shot 2015-09-29 at 9 40 46 pm](https://cloud.githubusercontent.com/assets/38643/10183939/d66ecc94-66f2-11e5-97be-89bf34143722.png)

**Comment by morinted** [comment]
Oh man this is SO COOL. This will be super helpful for beginners...and me!
I'm assuming you don't get the ability to change the font for certain list
box rows? If so, maybe instead of a full tab, 2 spaces would look better.

**Comment by chajadan** [comment]
Woohoo! A total breakdown like that is way nice.

**Comment by balthamos** [comment]
There might be a way to adjust a listbox's cell color/font, but it wasn't working with the little effort I tried with. Maybe someone more skilled with wx can figure it out.

We should have plenty of horizontal whitespace to work with, so eating 4 characters for formatting isn't unreasonable, IMO. But I can try pulling in the indent by 2 spaces and see if that's still readable.

**Comment by chajadan** [comment]
wx.HtmlListBox is likely an easy way to go. wx.stc.StyledTextCtrl can do it
but a steeper learning curve.

**Comment by balthamos** [comment]
Here is a 2 space indent next to the 4 space:

![screen shot 2015-09-30 at 8 24 34 pm](https://cloud.githubusercontent.com/assets/38643/10211535/55eb3d2c-67b1-11e5-864a-c436c4ee89fe.png)

I personally like the 4 space, but that's just me.

**Comment by morinted** [comment]
I'm not too fussy, they are both great :) are you willing to try out the
HTML styling? I think that may be the optimal choice.

**Comment by balthamos** [comment]
I was going to push what I had right now so more people could play around with the styling.

**Comment by morinted** [comment]
Yup I like that idea too. If you submit I will review tomorrow.
