### ISSUE TITLE
Expose API for external processes to receive stroke/translation events

### ISSUE THREAD

**Issue by brentn** [openstenoproject/plover#269]
It would be good if Plover provided hooks for other programs to read/listen for stroke/translation data directly.

Currently, other programs (like StenoTray) depend on the Plover log to determine what keys are being pressed.  I'm not sure how it should be done in Python, but on Android you would use Broadcasts to broadcast events such when a stroke occurred, or what steno keys were pressed, and other programs could register to "Listen" for those broadcasts.

This would enable a host of 3rd party programs that could do analyses such as strokes-per-word, or finding common mis-strokes, without relying on the user having logging enabled - which is really a fairly inefficient hack to be using.  

I imagine that alot of games/training tools could use access to these hooks.

**Comment by stenoknight** [comment]
This would be useful to use with StreamText; currently I use Plover to
enter text into Streamtext's "text window", but this system is buggier than
their TCP/IP implementation. I believe Hesky was working on an interface
that would allow Plover to be used with YouTube Live Captioning, but as of
the last time I heard from him about it, it was still too buggy to be
reliable.

On Thu, Oct 1, 2015 at 9:46 AM, brentn <notifications@github.com> wrote:

> It would be good if Plover provided hooks for other programs to
> read/listen for stroke/translation data directly.
>
> Currently, other programs (like StenoTray) depend on the Plover log to
> determine what keys are being pressed. I'm not sure how it should be done
> in Python, but on Android you would use Broadcasts to broadcast events such
> when a stroke occurred, or what steno keys were pressed, and other programs
> could register to "Listen" for those broadcasts.
>
> This would enable a host of 3rd party programs that could do analyses such
> as strokes-per-word, or finding common mis-strokes, without relying on the
> user having logging enabled - which is really a fairly inefficient hack to
> be using.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openstenoproject/plover/issues/269>.
>



-- 
Mirabai Knight, CCP, RDR
StenoKnight CART Services
917 576 4989
mkk@stenoknight.com
http://stenoknight.com

**Comment by balshetzer** [comment]
The YouTube streaming app could benefit from such hooks. But my app has bigger problems than that right now...

**Comment by morinted** [comment]
Should this be done with sockets or is there another cross-platform IPC that people enjoy using?

**Comment by morinted** [comment]
I keep coming across this as a useful feature. Basically, we just need a similar feature to the stroke/translation logging, but over IPC if the user has it enabled.

**Comment by jeremy-w** [comment]
I've been thinking about IPC as a good way to split out the platform-specific bits without necessarily requiring those bits to be implemented in Python. This could also be useful for privilege separation. And if the main interface between the UI and the core is a TCP connection, then it becomes easy to swap out the wxPython UI for a different UI entirely (Web app, OS X native, iOS app talking over local wifi to your laptop…).

While system-wide notifications are an option (DBus on Linux, notifyd on Darwin, beats-me-but-I-bet-it-exists on Windows), a socket interface would also allow clients to submit requests rather than just passively listen for event broadcasts, which gives us scope to expand the functionality available over time.

**Comment by morinted** [comment]
I did lean towards sockets when researching this stuff. It would allow for
new exciting tools to be developed...

**Comment by jeremy-w** [comment]
We could drop in something like bottle or webpy and expose a JSON HTTP API, which would save people from having to write their own protocol stack using raw networking calls. That's less suited for broadcast notifications, though.

**Comment by jeremy-w** [comment]
Let's start with the stroke/translation bit and grow it from there.

**Comment by tkpwaeub** [comment]
Would it be terribly hard to send shell scripts from Plover, or would that be a horrible security problem?

**Comment by jeremy-w** [comment]
@tkpwaeub Could you elaborate on the workflow you have in mind?

**Comment by benoit-pierre** [comment]
This can be implemented with an extension plugin.

**Comment by nsmarkop** [comment]
I was messing around with web sockets a few weeks ago and made https://github.com/nsmarkop/plover_websocket_server which is an extension plugin that exposes all of the current Plover events using an aiohttp web server. I don't really have any plans for it and I haven't polished it up to be released to PyPI, but it sounded relevant to this issue.
