### ISSUE TITLE
PH-FP kills Plover

### ISSUE THREAD

**Issue by ms009986** [openstenoproject/plover#270]
I use PH-FP to make a long dash (—).  When I stroke PH-FP, which I defined using Plover's dictionary update command, it results in no more text from Plover.  Clicking menus and such still works, but there is no more output of text into Word and no more strokes show up in Stroke Display.  Turning off Plover and turning it back on doesn't help.  I have to close down Plover and restart it to make it work again.

I had trouble with this with the current full release of Plover, too, but it wouldn't stop text output, it just wouldn't output the —.  Although I had it working for a while somehow.

Just FYI!

Possibly relevant information:
Plover 3.0 Alpha September 30
Windows 7
Stentura 400 SRT
Eclipse user
Phoenix Theory
RTF dictionaries, not JSON

Chris

**Comment by morinted** [comment]
Hi Chris,

Can you download this simple json dictionary
<https://gist.githubusercontent.com/morinted/8fc0b968b33c54d882dc/raw/a70e64ca4e8cdbc9cfb0e8d46c1a62e5818616ab/issue270.json>,
add it to Plover, then try using the stroke after a Plover restart? Does
the issue still occur?

**Comment by ms009986** [comment]
• Opened notepad
• Named a file Test.json
• with this content (I have the carets to make the dash sticky to the words before and after)
     {
      "PH-FP": "{^}—{^}"
     }
• Added it as the bottommost dictionary in Plover
• Tried it in Word

Result:  No long dash.   I stroked PH-FP/HAEU/PH-FP and it came out just "hey".  But at least it didn't stop Plover outputting text or require Plover to be restarted.

This is the same behavior I get from the current Plover release with my RTF dictionaries.

Please let me know if I did anything wrong with the above and I'll try it again.

Chris

**Comment by ms009986** [comment]
Correction...with the above strokes the output was actually " hey " (with a space before and after).

**Comment by morinted** [comment]
Right. It's been so long that I forgot that Plover doesn't support Unicode
characters on Windows. What you need is coming from my PR #213, once it
supports non-US layouts. In the meantime, you can try out this build if you
have a US layout (or if you switch to one). In addition to full unicode
support you also get control of the Windows key :)

https://www.dropbox.com/s/gfg6t315r5p3jr2/plover_2015_oct_2_win_dict_270.exe?dl=0

**Comment by morinted** [comment]
I believe that build will fix your issue. If it doesn't, feel free to re-open.

**Comment by ms009986** [comment]
(I don't know how to reopen, but I'm assuming writing this will reopen?)

Anyway, if the above file was supposed to keep Plover from crashing when I stroke the long dash, then yes, this fixes that, and thanks!

But if it's supposed to actually put in the long dash, it doesn't do that.  What it does do is put in a wider-than-normal space.  When I highlight the wider-than-normal space and copy and paste it into Notepad, nothing is pasted (the cursor doesn't move over, there's nothing there to highlight.)

Chris

**Comment by ms009986** [comment]
Hi, I'm back!

I don't know how to reopen...I tried to post a comment on it in hopes that
that was how you reopen, but it apparently got lost.  I can just make a new
issue?  Or I can just tell you here if you'd rather.

If that file you posted to deal with the long dash was designed just to
stop Plover from freezing, then yes it works, and thanks very much!

But if you thought that version would allow the long dash, it
didn't...instead it put a bigger-than-normal space.  :-/  I tried copying
and pasting the big space into notepad (to try to see if it was a character
that I couldn't see in Word because of formatting or some such) but though
I seemed to copy it fine, when I hit paste nothing showed up in notepad.
Mysterious!

Also I noticed today that when I stroked close parenthesis (PRAEPBS,
defined as {^}) , it instead backspaced.  Maybe this is related, since it's
another symbol?

If this version was just designed to prevent freezing until unicode
characters or whatever are sorted out, then never mind, it doesn't freeze,
so this version does solve that.  And thanks again!

Chris

**Comment by morinted** [comment]
No, the intention was to fix your problem completely and correctly output the characters. Can you try outputting the em-dash and then sending what the Plover log (C:\Users\user\AppData\Local\plover\plover.log, I think) outputs?

I'm also not very familiar with the RTF implementation, so if you could also try a JSON dictionary, I'd appreciate that. Then we can determine whether the problem is in the outputting or if it's in the RTF code.

I'd ask if you could use the build of Plover in this thread, as it should have the best chance of working. I just tested it and I had no issue outputting arbitrary characters like em-dashes and emoji.

**Comment by ms009986** [comment]
Oh, no, there's that missing comment up there.  :-S

I'm using the newest one you posted in this thread.

I'm stuck with RTF since the Phoenix dictionary wouldn't convert, but I still had the test JSON dictionary with the long dash entry bottommost on my list when I did this, so if I understand correctly it should have superseded everything else?  For testing I will take out all dictionaries and only use the test dictionary...hold on...

Same result.  :-(  

I will add the close parentheses to that dictionary too...hold on...that did work.

...okay, I may see the (a) problem.  When I opened Plover's dictionary editor it showed  PH-FP as defined as {^}{^} instead of {^}—{^}, even though when I open the actual dictionary in Notepad it is defined as {^}—{^}, just like I typed it.  So I redefined the stroke, this time using the Add Translation button again as {^}—{^}, just like I have it in the dictionary, and saved changes.  I opened the dictionary again in Notepad and now it's defined as  "PH-FP": "{^}\u2014{^}".  Tried typing both strokes again and now they both work.

So I guess the long dash works, but only if you define the stroke using the dictionary editor so it can translate to the unicode code?  This could be a problem for users who like to manually edit their dictionaries.

In the interest of thoroughness here's what the log says:
2015-10-13 12:59:52,762 Stroke(P- H- -F -P)
2015-10-13 12:59:52,763 Translation(('PH-FP',) : {^}â€”{^})

But the important thing is I have my long dash!  Thanks yet again for your help!

Chris

**Comment by morinted** [comment]
I think the problem may have been the format that the dictionary was stored
in. Plover wants to deal with UTF-8, but Notepad doesn't output to UTF-8 (I
think it's ANSI). If you want, you could download Notepad++ as it saves in
UTF-8 by default.

**Comment by ms009986** [comment]
I'm good with just making entries in Plover...although I may want to move entries from dictionary to dictionary...I'll keep Notepad++ in mind.  Just for more information, I tried it with my RTF dictionaries again and the long dash killed Plover, but when I reopened it and added the entry with Plover and saved it, now the long dash works in my RTF dictionaries without the JSON dictionary!  So yay.

Odd thing...when I added the stroke using add translation, I typed PH-FP, and the little thing that looks up your stroke said "PH-F is not in the dictionary" (instead of PH-FP).  ??  But it still worked, so (shrug).

**Comment by morinted** [comment]
It is very strange. I'm glad that you are reporting this stuff. Like I
said, not totally familiar with how we handle RTF -- it's probably not
perfect, as you can tell. If you wanted to potentially alleviate some of
your problems, I'd try making a copy of your RTF dictionaries, opening them
with Notepad++ and then changing the file encoding to UTF-8, and saving.
That might convert the "bad" strokes to good ones, equivalent to as if you
had used the Add Translation dialogue.

**Comment by ms009986** [comment]
(Should I close this issue, or is it still relevant since users would
likely edit their own dictionaries?)

Chris

**Comment by morinted** [comment]
We'll close for now, not sure if it's worth teaching Plover how to convert dictionaries from ANSI to UTF-8. Rather, it's a documentation thing #261
