### ISSUE TITLE
Suggestions Display doesn't retain window size or position on exit

### ISSUE THREAD

**Issue by ms009986** [openstenoproject/plover#271]
The Stroke Display window and Plover window do fine, but when I resize Suggestions Display and close and reopen Plover it reverts back to its default position.

**Comment by morinted** [comment]
This should be a fixed by abstracting all GUI windows into a class in order
to maintain their positions, similar to the current Plover window. Thanks!

**Comment by morinted** [comment]
Moving this into #272 as the tasks should be completed together. Thanks for the report!
