### ISSUE TITLE
Failure to initialize machine crashes Plover

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#273]
Plover tries to initialize the steno machine on startup. If that throws an exception the Plover crashes with a stack trace. Usually, the solution is to delete plover.cfg and start again. On OSX, this happens on first startup because the machine is the keyboard, by default, and that requires special security permissions to be set.

It would be better if:
1) Plover caught exceptions from initializing the machine and
2) support running with no machine configured 

so that the program doesn't just crash when an invalid machine is specified but just switches to no machine and the user can go change the machine settings or use the dictionary editor or whatever else they want to do.

**Comment by morinted** [comment]
Fixed thanks to logging improvements by @benoit-pierre
