### ISSUE TITLE
Lack of shortcut to switch from QWERTY/Steno

### ISSUE THREAD

**Issue by androng** [openstenoproject/plover#275]
For people that are learning Steno, it would be helpful to have a keyboard shortcut that lets them do the quick enable/disable of Plover. Yes there is software like StenoTray so that I don't have to switch as often but it would be nice to have the option.

**Comment by morinted** [comment]
Hi @androng,

Plover supports this through a stroke -- it works while Plover is on and while it is off. In the next release of Plover, the default dictionary will come with a stroke to toggle Plover. You can peak and see the [commands.json](https://github.com/openstenoproject/plover/blob/master/plover/assets/commands.json) that will come with the new default.

In particular you probably want to add one ( :boom:  or all :boom: ) of these strokes to your dictionary:

```json
"PHROF": "{PLOVER:SUSPEND}",
"PHROLG": "{PLOVER:TOGGLE}",
"PHROPB": "{PLOVER:RESUME}",
```

To read more about the dictionary format and meta commands that Plover offers, check out [the appendix of Learn Plover! :bird: ](https://sites.google.com/site/ploverdoc/appendix-the-dictionary-format#TOC-The-Plover:-Control-Command)

Thanks,
Ted :smile_cat:
