### ISSUE TITLE
Dictionary editor won't close

### ISSUE THREAD

**Issue by ms009986** [openstenoproject/plover#278]
I apologize if I'm going overboard with the posting, but I noticed a strange behavior with the dictionary editor which I can repeat.

I clicked edit on the dictionary tab, and nothing happened immediately, so I thought I didn't quite click the button and hit it again.  Then a dictionary editor opened with a dialog asking if I was sure I wanted to lose my changes.  So apparently it registered both clicks but doesn't like having the dictionary editor open twice.

Makes sense, no need to have two dictionary editors open.  So if you hit yes, all is well, the editor closes and then another opens, but I hit no, not knowing what changes it was talking about.  

So apparently if you hit no, it opens another editor anyway, rather than Plover just cancelling the request for the second editor.   I would think the desired behavior would be to not let the Edit button work at all if the editor is already open or is opening (I don't see a reason to try and open the editor when it's open?).

I closed one of the open editors with no trouble; it warned me about losing changes, I clicked yes, and it closed normally.  When I tried to close the second one, it again warned me about losing my changes, but when I clicked yes, the editor stayed open.  I couldn't get it to close short of closing down Plover.

Restarted Plover and tried it again to see if it would recur and got the same results.

Possibly relevant information:
plover_2015_oct_2_win_dict_270
Windows 7
Stentura 400 SRT
Eclipse user
Phoenix Theory
RTF dictionaries, not JSON

Chris

PS.  Just while I'm on the subject of dictionary editor, it would be more helpful to me to see the names of my dictionaries rather than their locations (cz I can only see the beginning part of the dictionary locations in the narrow column, and they all look like C:\Users\.... etc.)  So either just showing the names of the dictionaries instead of the locations or having a new column with the names just before the location column would be more helpful.

PPS.  Which reminds me, not sure if this is a bug or just design, but when you resize a column, column widths are not retained when you reopen the dictionary editor.  So if you were curious enough about which dictionary your entry is in, you would have to resize the column every time you reopened the editor.  So the column width settings should survive closing and reopening for both the dictionary editor and Plover?

**Comment by morinted** [comment]
This is some good bug reporting. I've never really used the dictionary editor myself, but I'm definitely able to replicate all your issues here.

Some changes that I see as needing to happen:

- If there are no changes to the dictionary, don't prompt user to save changes
- Instead of trying to open a new dictionary window, the edit dictionary button should focus the already open dictionary window
- Dictionary name columns should be aligned to the right in order to show discerning information by default

Then that last task is a little more involved, but we might consider:

- Save user's sizing position for dictionary editor columns

**Comment by morinted** [comment]
Progress update on this for you!

- Dictionary column is now right-aligned so that you can see the dictionary names
- The window only prompts you to save changes if changes were actually made (includes deleting, adding, and updating fields)

Next task will be trying to fix that multi-window management that caused this issue in the first place.

**Comment by morinted** [comment]
All done. If you'd like me to make a build for you, just let me know. Thanks for the reports.

**Comment by morinted** [comment]
I made a build for you to test out the dictionary editor. Let me know how it works for you (your emdash stroke probably won't work in this build as it doesn't have the Windows keyboard emulation update)

https://www.dropbox.com/s/8mox1580wa4wyjj/plover_dictionary_editor_october_22_2015.exe?dl=0

**Comment by ms009986** [comment]
You're right, with the latest file, the — doesn't work, even when I add it
with the editor.  But I can't seem to break the editor anymore, so that's
good.  And the right-justified bit helps.

Not a bug, but it seems slow to come up, but that's probably just cz of the
150,000-odd entries.  Column widths still aren't saved, but I'm sure they
shouldn't be yet.

So the bug I posted is all fixed, and I'm going back to the — - friendly
Plover.

I'll trade you for a new bug, or at least an oversight.  I noticed that
when you add a new entry you don't have a choice of which dictionary to add
it to.  Add Translation if I remember right puts it in your bottommost
dictionary, which at least is the most likely place you would want to put a
new entry, but as far as I can tell New Entry in Dictionary Editor adds it
to the top dictionary.  I can't quite figure that logic out.

It seems sort of redundant to have a New Entry button in the editor and a
separate Add Translation button, which are really the same thing, but I
understand that you would expect to be able to add an entry in the
dictionary editor.  I think the best solution would be to name both New
Entry and Add Translation to the same thing (probably New Entry or Add
Entry would be clearest) and have the New Entry button just be coded to do
the same thing as the Add Translation button does, which is open the Add
Translation box, instead of making a new line in the editor.  That way it's
more intuitive and you don't have to code two different ways to do the same
thing.

And in either case Plover should let you choose which dictionary to add it
to. If you're making a change to your core dictionary that should be the
translation all the time, you would want it in your main dictionary, but if
you're working on a document with clients who have special requirements
(like U.S. instead of US, for example, or -- instead of —), you would want
to add it to that client's dictionary.

So in either place there should be a way to choose which dictionary to add
an entry to.  It can default to the last one, that's fine, but there should
be a drop-down or radio button to pick which dictionary you want the entry
in.  Also keyboard shortcuts would be handy.  Eclipse lets you do Ctrl-M
for your main dictionary and Ctrl-J for your job dictionary, and the rest
are Ctrl-(whatever number the dictionary is in the list), so those
shortcuts would be helpful for quick entry adds and familiar to Eclipse
users (like Mirabai).

(I can post this on the site if you'd rather, I wasn't sure if it was a
bug.)

Chris

**Comment by morinted** [comment]
This is some neat thought.

The dictionary manager, I think, adds to the dictionary that you are
currently selecting when you click new entry. So, for example, when you are
selecting a stroke from your middle dictionary, you can hit new entry and a
blank line filled in with only your middle dictionary appears.

Maybe we could change that to a drop down, allowing you to move strokes
between dictionaries?

Multiple dictionaries on add translation has come up before, but it's a low
on my priority list at the moment.

**Comment by ms009986** [comment]
The dictionary manager, I think, adds to the dictionary that you are
currently selecting when you click new entry. So, for example, when you are
selecting a stroke from your middle dictionary, you can hit new entry and a
blank line filled in with only your middle dictionary appears.


Oh, okay.


Maybe we could change that to a drop down, allowing you to move strokes between
dictionaries?


I think that would be desirable since A) it's not obvious that's how it
works and 2) it would be kind of clunky to have to go search for an entry
in the dictionary you want before you can add an entry to that dictionary.
My main dictionary is huge, so that would be a lot of scrolling to get to
the next dictionary (if I understand how it works right).


Chris

**Comment by morinted** [comment]
The other advantage of making the dictionary field a drop down would be
moving strokes between your dictionaries, which I think is a very valid use
case.

**Comment by ms009986** [comment]
More on the dictionary editor....

•  When I type in {^} in the "filter by translation" blank and hit enter
(or click the button), nothing happens.  I'm sure I have plenty of entries
in my dictionaries that have this entry in there.

As a matter of fact when I type anything in there nothing happens.

I would like to see it dynamically change as I type things without having
to hit enter or click "filter" if that wouldn't slow thing down or cause
problems.

•  Filter by stroke seems to work—unless you try to type the stroke using
your machine.  "Add translation" lets you type in a stroke with your
machine instead of manually typing it in.

I can't think of a time I wouldn't much prefer entering a stroke using my
machine, so I would like both keyboard and steno machine to work for this
input.

•  I'm still using the version of Plover you sent me that allows the long
dash (since I use that often) but I have noticed that it forgets my entry
after I exit Plover and open it back up.  Meaning whenever I open Plover
and type PH-FP for my long dash translation, Plover freezes.  I restart
Plover and click "add translation" and stroke PH-FP and readd the entry,
and it works normally until I restart Plover again.  So apparently entries
aren't being saved in the lowermost dictionary after all?  At least that
one's not.  (Still RTF dictionaries since my main dictionary wouldn't
convert.)

•  Simlarly to the long dash not working, my shortcut to add an accented e
to a word (like "fiancé") crashes Plover unless I add the translation
first.  I assume it's probably the same problem.

Chris

PS.  Let me know if you get tired of cutting and pasting to the site and
I'll enter 'em there.  Some of these things are not necessarily bugs so I'd
rather just write you an email if you're okay with that, but if you're not
just let me know.

**Comment by ms009986** [comment]
Or do these go right to the board without anyone copying and pasting?  I
just looked at the reply email.

Anyway, addendum to the above, I tried adding the dictionaries using the
dictionary editor to see if they were sticky that way, but they disappeared
from there too.

Chris

**Comment by morinted** [comment]
You are an awesome user Chris, really tearing this stuff apart...

I've noted your dictionary editor issues -- the design is not perfect and
probably does still need some work.

As for your special characters crashing Plover, that must be in Plover's
RTF code. Can you send me an RTF dictionary with some strokes that crash
Plover for you?

**Comment by ms009986** [comment]
Sure...

This has the long dash entry.  The é entry isn't in there because I
couldn't get it to stick with the editor and the syntax is different so I
can't manually add it.  Those are the two strokes I've managed to crash
Plover with so far.

Chris
