### ISSUE TITLE
Support media keys

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#279]
In my Windows branch, I added media key support. This is not present on OS X or Linux.

I've looked, and it seems like adding volume control to OSX would be trivial, and then it's a matter of finding out how to do media skip (might be a hint [here](http://stackoverflow.com/questions/3885302/make-my-cocoa-app-respond-to-the-keyboard-play-pause-key))

As for Linux, I'm not totally sure where to start. I've found multimedia controls in X11, not too sure about XLib as the list of key strings doesn't mention media at all.

Once complete on all branches, a consistent naming scheme should be chosen.

**Comment by stenoknight** [comment]
Ah, nice. I get around this by using Winamp, which supports customizable global hotkeys, for all my media, and then assigning steno strokes to the hotkeys I want to use (like Shift-Tab for rewind, etc), but a general media key option would be very useful as well.

**Comment by balshetzer** [comment]
It should be fine to add support for one OS at a time as long as it
degrades gracefully on unsupported platforms.

**Comment by morinted** [comment]
I will be working on this for OS X and #246 together. Saw some key codes in OS X for brightness and volume control, nothing really for media exists on OS X.

**Comment by morinted** [comment]
Finished!
