### ISSUE TITLE
"Command" is not on the list of valid keys

### ISSUE THREAD

**Issue by androng** [openstenoproject/plover#283]
On OS X there is a "Command" key that is used for the Alt-tab on windows. There is also an Alt key. I read https://github.com/openstenoproject/plover/blob/3e4c0b66854f0c5b8d407b2731fb3979e609c225/doc/plover_guide.tex and it looks like "Command" is not in the list of valid keys. I tried defining a dictionary entry with it too and it did not do anything. No mention of it is in https://github.com/openstenoproject/plover/blob/3e4c0b66854f0c5b8d407b2731fb3979e609c225/plover/oslayer/osxkeyboardcontrol.py

**Comment by balshetzer** [comment]
One of the keys, I think super, is command on OSX

**Comment by morinted** [comment]
Yes -- `{#Super_L()}` is what you are looking for. The Super key on Linux is equivalent to the Command key on OSX and the Windows key on Windows. This could probably be better documented ( pinging #261 )

**Comment by morinted** [comment]
Found this in "Learn Plover!", in the appendix:

> The following is the full set of keys that may be referenced with the '{#}' command in Plover (note that the `Super_L` and `Super_R` keys correspond to the command keys in OSX.):

https://sites.google.com/site/ploverdoc/appendix-the-dictionary-format
