### ISSUE TITLE
Bugfix patch: don't try to * past first word in suggestions dialog

### ISSUE THREAD

**Issue by KarlHegbloom** [openstenoproject/plover#284]
https://github.com/KarlHegbloom/plover/compare/777dccb7981025a280ab923cbaedc18346894022...KarlHegbloom:e805e737282658a686c4708adddd1e92b7fdaa24

**Comment by morinted** [comment]
Hi Karl, thanks for the bug fix. May I ask you to submit a pull request for this?

**Comment by KarlHegbloom** [comment]
I tried to but it wants me to submit a bunch of other things with it that i
thought you'd not want. It was late and i needed sleep. I'll make a topic
branch and pull request later.

**Comment by morinted** [comment]
Thanks for the PR!
