### ISSUE TITLE
Is there any plan for Python 3 conversion?

### ISSUE THREAD

**Issue by ke7ofi** [openstenoproject/plover#288]

**Comment by morinted** [comment]
Can you expand a little more on this?

**Comment by ke7ofi** [comment]
Python 2 is probably going to stick around a while, but 3 is starting to become standard. I haven't tried piping it through 2to3, as I assume it's more complex than that.

**Comment by morinted** [comment]
There is no plan at the moment. We have a lot of specific dependencies. If you are willing to investigate this I would really appreciate the effort.

**Comment by ke7ofi** [comment]
I don't have much (read: any) programming expertise; I'm just a random Arch user who got annoyed at having to type pip2.

**Comment by morinted** [comment]
That's all right, it's a valid concern. I imagine, though, that it would be
a task and a half. I would definitely want help before attempting it.

**Comment by morinted** [comment]
There is no plan at the moment, we'd have to update to wxPython Phoenix and update other dependencies. Compared to other features and bugs, it's not a major concern. @benoit-pierre has updated the shebangs in the application so there should be a little bit less coarseness while working with the development files.
