### ISSUE TITLE
Unexpected exit on quit on Mac

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#310]
Menu bar changes allow Plover to respond to command Q, but then Plover gives exit code 1 and a notification appears.

**Comment by morinted** [comment]
I believe this only happens with the Treal on.

**Comment by Achim63** [comment]
This doesn't hpapen here, I can quit Plover nicely without any error message while the Cybra is still running in Stentura mode.

**Comment by morinted** [comment]
Are you using Plover 2.5.8 or a newer version?

**Comment by Achim63** [comment]
I tried both 2.5.8 as well as the current master branch.

**Comment by morinted** [comment]
This has stopped happening since we switched to 64-bit.
