### ISSUE TITLE
When running in portable mode, strokes.log and plover.log should be stored locally

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#312]
Noticed that as I move between Mac and Windows using Plover in portable mode, all my dictionaries work fine but the strokes.log still remains in an absolute position and this breaks that configuration.

While we're add it, having Plover.log store locally while the config file is local would be better behavior for Plover to be truly portable.

**Comment by benoit-pierre** [comment]
I just tested on Linux with the self-contained egg and using Wine with the result of Pyinstaller, and it works fine:
- all paths are relative in the config: `strokes.log` + dictionaries
- both `strokes,log` and `plover.log` are created in the same directory as the config, so when in portable mode, in the directory with the executable

Did you save the configuration after switching to the version supporting relative paths?

**Comment by morinted** [comment]
Hrm, maybe the Windows version that I was using is out of date :/ seems like the Mac stores everything correctly.
