### ISSUE TITLE
Plover lookup oddities

### ISSUE THREAD

**Issue by PaulBeaudet** [openstenoproject/plover#315]
This is an issue with the current build as in repo ( Dec 11, 2015 ). On Mint Linux if that matters.

The plover lookup input text bar is adding extra spaces before word and word history is losing its place making it difficult to fingerspell anything into this entry field. Backspace(plover) also fails to work properly. Not sure how this bug is possible, the only thing that should be going on during text input seems to be on_translation_change() (ln.70 lookup.py)

Fingerspelling and plover works fine in my text editor otherwise

Notes on lookup.py: ln.77 needs a comment, where does "engine" come from? What is it? the main plover conversion routine? If so line 82 concerns me, is this changing a global state of the application? If so that is the bug. Would explain why spaces keep getting inserted if the "engine" state keeps getting reset every time the window comes into or out of focus. Probably want to make comments about dangerous uses of global states if any of this is the case, but I would really have to read it more carefully to understand.

 Ln 112 "d"? 

As an aside the cancel button is redundant and activates when enter is pressed, which is unexpected behaviour after doing something someone might habitually expect to do. ( ln.73 lookup.py ) 

Also -> Triple click also is unassigned, expected behaviour is select all.

**Comment by morinted** [comment]
Hi @PaulBeaudet,

There's a lot of stuff thrown into this issue. I think some of it has been fixed, maybe by coincidence? The cancel button no longer activates when enter is pressed, but is required by WX for the escape handle to work. Maybe you could verify that your other issues are still present and break them out into separate issues so that we can handle them one-by-one?

**Comment by morinted** [comment]
If you could reopen with bugs following the bug template and maybe an issue for each different problem, I'll be able to organize the issues. Thanks!
