### ISSUE TITLE
Update Linux install instructions to include workaround to get wxPython 3.0 under Ubuntu LTS and similar

### ISSUE THREAD

**Issue by tschulte** [openstenoproject/plover#316]
I am having some issues compiling plover on my linuxmint box. The wxPython version shipped with linuxmint (and Debian/Ubuntu) is 2.8. But with commit 0eb8fb7514695d10b105d3c1720ce4f2cae177f9 you raised the required version of wxPython to 3.0. I had some issues trying to compile wxPython. I finally managed to compile and install it, but still I get 

```
/usr/local/lib/python2.7/dist-packages/wxPython_common-3.0.3.0-py2.7.egg/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
```

during the startup of plover.

Do you really need version 3.0? I tried resetting the changes made in that commit and it seems to work? If you don't need wxPython 3.0 it might be better to leave the required version at 2.8.

**Comment by PaulBeaudet** [comment]
Had same issue, Agreed. I'm not sure why this was changed but it's only two lines of code it looks like. So it can be easily changed if 3.0 is not part of the future plans.

**Comment by PaulBeaudet** [comment]
Also, if you haven't already @tschulte  I just change those two lines I think in setup.py and main.py.  everything works as of current.

**Comment by morinted** [comment]
3.0 was required for OSX and it was pushed up on other systems to keep
everything inline. I don't mind reverting the version requirement, though
it might be harder for people who have 3.0 to know that >=2.8 applies to
them. I'd welcome a PR.

**Comment by PaulBeaudet** [comment]
This seems to be coded into the source as opposed to just being required by the setup file

    WXVER = '3.0'
    if not hasattr(sys, 'frozen'):
        import wxversion
        wxversion.ensureMinimal(WXVER)

Now if the setup file already ensures a minimal for the separate OSes I'm not sure what this layer is for. But again I'm not super familiar, I just understand it is a single point where the OS does't matter. Unless of course the constant WXVER was set by OS type. Which I guess would be fine.

Willing to bet it will take a super unnecessarily long time for WX 3 to be included in debian repos. Not sure how setup-tools satisfies its dependencies but if it's through the repos the issue will likely persist into an actual release time frame.

**Comment by morinted** [comment]
I believe Benoit-Pierre verified that it's in the 15 release of Ubuntu, so there's something for you. I believe it's pretty darn stable, but I have no qualms with lowering that number for people on previous cycles.

**Comment by benoit-pierre** [comment]
'setup.py' is used to install Plover from sources, or building an egg/wheel binary. Each distro will duplicate the requirements in its own package definition format (like a PKGBUILD for Arch Linux).

As Ted already pointed out, the version was updated for Mac OS X, and 3.0 is available in the most recent Ubuntu.

I'm not in favor of requiring a lower version just for the sake of (older) Debian/Ubuntu: there are already enough differences between Windows/Mac OS X/Linux versions of WX without adding different major versions into the mix.

Can WX 3.0 be installed with 'pip'?

**Comment by PaulBeaudet** [comment]
Well than. In that case I would say if we are waiting to do a release until the next LTS (2016) than a change is less warranted. The last LTS which doesn't include WX 3 so far, is still supported till 2019. Some of the linux audience gets sick of upgrading every six months and sticks to LTS so I'm afraid we may want an "if old linux" statement in there regardless. I'm still rocking mint 17 (ubuntu 14 lts) not all of us have the time to constantly upgrade.

Fairly certain I would have had to compile WX 3 from source, though I may have tried to pip the wrong thing. Having to pip something for someone new to plover may not be necessarily the message we are trying to get across. For people using bleeding edge source, I think changing a couple of lines of code is fine conversely speaking.

**Comment by benoit-pierre** [comment]
> Well than. In that case I would say if we are waiting to do a release until the next LTS (2016) than a change is less warranted. The last LTS which doesn't include WX 3 so far, is still supported till 2019. Some of the linux audience gets sick of upgrading every six months and sticks to LTS so I'm afraid we may want an "if old linux" statement in there regardless. I'm still rocking mint 17 (ubuntu 14 lts) not all of us have the time to constantly upgrade.

Sure, but you can't have it both ways: you either stick to a (stable) LTS with out-dated software, or need to update if you want to be able to use more bleeding edge versions.

> Fairly certain I would have had to compile WX 3 from source, though I may have tried to pip the wrong thing. Having to pip something for someone new to plover may not be necessarily the message we are trying to get across.

I don't think asking someone to use pip is harder, in fact I think it's easier than from sources: most of the dependencies can be installed through pip too, and it's than easier to remove/upgrade. We should probably register the next version to PyPi.

**Comment by PaulBeaudet** [comment]
I guess I'm thinking about this in two separate ways at the same time. One is myself and the other is a "normal" person. When I say "normal" I mean that I generally assume that people are only slightly better / more ambitious than my grandmother in terms putting software on their computer. Of course we are doomed below this definition of the "normal" threshold and there is a certain level of sophistication needed to steno but I think assuming unix/python skills for plovering is a little much.

For myself and other people who want the newest version in this repo, I don't think anything needs to be changed. Works for me. If not for someone else, we can help them. End of story. Closed

The more insidious question is release for general public consumption. Is this impending? It should be. This version is significantly better than the official.

Just trying to get a grip on what the release plan is before writing a redundant hack. In the case of release, this issue alienates part of the audience without a fix I will argue, but then again I would also argue that the current installation method in linux is alienating in general and that's a separate issue altogether.

My other curiosity. Is the difference between 2.8 and 3.0 actually outdating Plover? Certainly not breaking it in terms of functionality. This is probably just bikeshedding, no answer needed.

**Comment by morinted** [comment]
Paul I'm totally onboard with just bumping down the version number that you
pointed out, if you'd like to submit a PR that closes Tobias' issue, I'll
merge it shortly.

**Comment by benoit-pierre** [comment]
I just had to make some changes to Plover while on another (older) system, without 3.0, and I got an error when trying to use the keyboard keymap configuration dialog after patching the code to go back to wx 2.8:

`AttributeError: 'StaticText' object has no attribute 'SetLabelText'`

So if we want to go back to using 2.8, we need to do a complete pass to make sure everything still works.

**Comment by balshetzer** [comment]
I think it'd a mistake to go backwards in versions.

**Comment by morinted** [comment]
I agree. Can we close this and maybe leave a note for users on older OS's? Can Ubuntu users use pip to install wxPython 3?

**Comment by benoit-pierre** [comment]
It's not possible to use pip, but there a backport PPA for another software facing the same problem (KiCad), and I was able to use it on Linux Mint 17.3 Rosa (which is based on Ubuntu 14.04 [Trusty Tahr]):

```
> sudo apt-add-repository ppa:adamwolf/kicad-trusty-backports
> sudo apt-get update
> sudo apt-get install python-wxgtk3.0
```
```

**Comment by tschulte** [comment]
Yes, using the kicad backports repo did the trick.

**Comment by PaulBeaudet** [comment]
I'm all for closing and leaving a note in the current Linux installation notes. 

The reason for the PR and and all the noise is just that I get the vibe, that this type of barrier prevents people from trying plover out and wanted to have the conversation. Noticed in the google group we have a lot of Linux and Dvorak type people which are people that are generally willing to try new things out like Plover. However, only so many people of those people are going to have the latest Ubuntu or care to edit source code to get something to work, adding the ppa for folks on the last LTS should be simple enough when comparing to the current instructions.

**Comment by morinted** [comment]
Yes, I do appreciate the effort you've put in. You did the right thing and
certainly adding this note will help users. I'll close this once I've
created a note in the documentation.
