### ISSUE TITLE
Passport Touch not yet compatible with Plover?

### ISSUE THREAD

**Issue by 3shells** [openstenoproject/plover#317]
I have tried to use Plover. The NKRO Keyboard setting works fine, strokes come through, but when I try to use the Passport Touch, USB Connected, it says "connected" (I am using COM port 3 that it scanned for and found and the default settings) but then no strokes are coming through.

I am unsure if I am just doing some small thing wrong, or if the Passport Touch is not yet compatible, but yeah.

**Comment by balshetzer** [comment]
Which protocol is Plover set to use?

You said you're using USB. Is it a serial to USB converter or does the touch have a USB port?

**Comment by 3shells** [comment]
I am using the Passport setting on Steno Machine: (select which)

The Passport Touch does have a couple USB ports, but the cord I was provided by Advantage Software to use for the purpose of the Eclipse Student Software doing realtime is, I think (I am not exactly educated on this, but) serial into the Passport Touch and USB into the computer. I think it has to be, because when Plover scans for the Passport, it is picking up COM port 3 when it is plugged in.

**Comment by gdwaynewarner** [comment]
I would think there is a difference between the original Passport protocol and the protocol for the Passport Touch. If that's the case, that's probably why it's not working.

**Comment by morinted** [comment]
Hi @3shells 

I just emailed Advantage and they replied saying:

> if you select "compatibility mode" on the Passport Touch, it will emulate a Stentura.

So with your Passport Touch in compatibility mode, you should be able to connect to Plover with the Stentura machine selected.

Ted

**Comment by morinted** [comment]
Ah, they contacted me again with a clarification:

﻿It's actually called **emulation mode** and while in that mode:

- You can connect over Bluetooth with the Stentura protocol
- You can connect over USB with the TX Bolt protocol
