### ISSUE TITLE
Handling Alt_L(x y) in windows

### ISSUE THREAD

**Issue by benreynwar** [openstenoproject/plover#325]
Looks like winkeyboardcontrol.py has a bug is the emulation of multiple keys pressed while a modifier key is held.

Alt_L(x y) is translated to the %xy, but should really be translated to %(xy).

This is true whenever more than one key is pressed, while holding a modifier down.

This is just from looking at the code rather than testing on windows so I maybe totally wrong about this, but I thought I'd make a note of it here.

**Comment by morinted** [comment]
Thanks Ben, I think this should be fixed in my PR for the Windows keyboard handing rework. I'll close this once that code is complete and integrated into the repository.

**Comment by morinted** [comment]
Fixed with #213
