### ISSUE TITLE
Support drag-and-drop dictionary file management

### ISSUE THREAD

**Issue by jeremy-w** [openstenoproject/plover#337]
The file-picker flow to add files is slow, and reordering dictionaries requires chasing buttons.

Instead:

- Drop a dictionary on Plover (the icon or the window) to add as first dictionary consulted.
- Drag dictionaries up and down to reorder in the dictionary configurator.
- Drag a dictionary out of the window to copy to drop location? Or to yank out of the list?

**Comment by morinted** [comment]
This is present in Benoit Pierre's QT GUI

**Comment by benoit-pierre** [comment]
1. is partially supported: drag and drop on the main window
2. is supported
3. I don't think drag and drop out should be used to yank out of the list, we could make it copy the dictionary location for dragging to another application to open in it, but with no way for Plover to reload externally modified dictionaries, I think we should just close this issue and revisit if and when this is addressed.
