### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by jeremy-w** [openstenoproject/plover#346]
Two audiences:

- Users who want to file an issue
- Devs
    - Code style
    - Pull requests & tags

This is a subtask of #261.

**Comment by jeremy-w** [comment]
@morinted Please assign this to me for plover-next. Thanks!

**Comment by morinted** [comment]
I've added you as a contributor to the Open Steno Project, you can assign yourself if you except the invitation.
