### ISSUE TITLE
Implement Stentura USB protocol

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#347]
The Stentura USB protocol has been released: http://www.stenograph.com/marcom/Download-page/utilities---links.html

A friend familiar with the protocol and a Stentura writer has made this code using Python and his Stentura:

``` python
# ---------------------------
import usb.core
import usb.util
import sys

# find a Stenograph device
devicenumber = 12
dev = None
while (dev is None) and (devicenumber > 0):
    dev = usb.core.find(idVendor=0x112b, idProduct=devicenumber)
    devicenumber -= 1


# was it found?
if dev is None:
    raise ValueError('Device not found')

# set the active configuration. With no arguments, the first
# configuration will be the active one
dev.set_configuration()

# get an endpoint instance
cfg = dev.get_active_configuration()
intf = cfg[(0, 0)]

epout = usb.util.find_descriptor(
    intf,
    # match the first OUT endpoint
    custom_match = \
    lambda e: \
    usb.util.endpoint_direction(e.bEndpointAddress) == \
    usb.util.ENDPOINT_OUT)

assert epout is not None

epin = usb.util.find_descriptor(
    intf,
    # match the first IN endpoint
    custom_match = \
    lambda e: \
    usb.util.endpoint_direction(e.bEndpointAddress) == \
    usb.util.ENDPOINT_IN)

assert epin is not None


for cfg in dev:
    sys.stdout.write(str(cfg.bConfigurationValue) + '\n')
    for intf in cfg:
        sys.stdout.write('\t' + \
                         str(intf.bInterfaceNumber) + \
                         ',' + \
                         str(intf.bAlternateSetting) + \
                         '\n')
        for ep in intf:
            sys.stdout.write('\t\t' + \
                             str(ep.bEndpointAddress) + \
                             '\n')

# From Stenograph USB Writer protocol
#         0     1  2  3  4  5    6  7    8  9 10 11  12 13 14 15  16    17 18 19
#         S     G  Sequence   | Action | data len   | FileOffset | ByteCount      | param 3   | param 4   | param 5
pkt = [0x53, 0x47, 0, 0, 0, 0, 0x13, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0x08, 0x0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# Create bytearray from list of integers.
packet = bytearray(pkt)

offset8byte_steno_time = 0

# write the data
for i in range(1, 0x7fffff):  # this loop is just for testing, make a real loop with callbacks
    # update sequence number (0 to 255 works fine)
    packet[2] = (i & 255)

    # read from this offset
    packet[12] = (offset8byte_steno_time & 255)
    packet[13] = ((offset8byte_steno_time >> 8) & 255)
    packet[14] = ((offset8byte_steno_time >> 16) & 255)
    packet[15] = ((offset8byte_steno_time >> 24) & 255)


    try:
        epout.write(packet)
        data = epin.read(128, 3000) # we only asked for 8 bytes (1 stroke) - so we are only expecting 40 bytes here.
    except:
        data = None
        pass
    if data is not None:
        if len(data) > 32:
            # got some steno, process it.
            #
            # First 32 bytes is the response header.  Then the steno follows
            #
            # Byte 0: 11H#STKP where H is stenomark and # is the numeral bar.
            # Byte 1: 11WHRAO*
            # Byte 2: 11EUFRPB
            # Byte 3: 11LGTSDZ
            # Bytes 4-7: 'timestamp'
            #
            #
            # update steno offset
            offset8byte_steno_time += (len(data) - 32)
    print offset8byte_steno_time

# ---------------------------
```

We should implement this as a new machine in Plover, we can rename the current Stentura to "Stentura Serial" and this new one to "Stentura USB".

**Comment by jeremy-w** [comment]
We can do the Stentura => Stentura Serial rename ASAP. We need someone with a Stentura to do the USB integration testing, but the dev could maybe be done by anyone with a good test suite.

**Comment by Achim63** [comment]
I'd be glad to test this on my Cybra. I'd need a pre-made built, though. I wasn't lucky with building it myself yet.

**Comment by Achim63** [comment]
I got a bit further no, I can start my builds by using "python launch.py". The standalone still is broken, though, it just opens a requester with "Plover error".

So I tried this branch but it doesn't connect to my Cybra if I use USB. Vender and product ID seem correct compared to what sytem info shows me.

Trying to run sample_usb.py just says "ImportError: No module named usb.core". Would I need to install something using pip?

**Comment by morinted** [comment]
I believe the sample was written for Windows, so if you are on Windows you can do "pip install pyusb"

The branch I made is using HID, which the Stentura is not, so it will not work at all until I take the time to rewrite it.

**Comment by Achim63** [comment]
uck, Windows ;-)
Too much hassle to try this on my 8' Windows tablet, my eyes wouldn't forgive me ...

**Comment by morinted** [comment]
Sorry. When I update the branch and get something working, I'll let everyone know to try it out. It's very exciting to have the Stentura USB protocol.

**Comment by Achim63** [comment]
Seeing that many have trouble to make their Serial-to-USB adapters work, this would really be great.

**Comment by balshetzer** [comment]
I suspect that this code requires windows _and_ the stenograph driver to be installed.

**Comment by gdwaynewarner** [comment]
That's most likely true ...

Unfortunately, I didn't see anything human-readable in the USB drivers I downloaded just now (http://www.stenograph.com/ftp/updates/USB_writer_drivers.zip), so perhaps looking at those drivers with a debugger might reveal something useful.

**Comment by morinted** [comment]
[Initial version without support for older machines is available as a plugin](https://github.com/morinted/plover_stenograph_usb)
