### ISSUE TITLE
port Plover to Android for use with mobile devices and tablets 

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#35]
A mobile version of Plover can open up new user bases and application domains. Android seems to be the best choice in terms of market share and ease of development.

**Comment by morinted** [comment]
@brentn has done a good job with https://play.google.com/store/apps/details?id=com.brentandjody.stenoime&hl=en

**Comment by crypdick** [comment]
@morinted link is broken. Did StenoIME die? I'd like to get steno typing on my VR headset (Android-based).

**Comment by brentn** [comment]
Yeah, I haven't maintained the code for years, but it is available on
GitHub if that is helpful.

**Comment by crypdick** [comment]
Thanks @brentn. I get the impression it may be easier to plug my keyboard into a Raspberry Pi running a Plover server, and transmitting inputs to Android [via bluetooth](https://serverfault.com/questions/43615/setup-a-linux-computer-to-act-as-a-bluetooth-keyboard-mouse). Thoughts?

**Comment by brentn** [comment]
That's a great idea.  I've not tried working with bluetooth, but it's worth
a shot!

**Comment by morinted** [comment]
The best fork to work with is https://github.com/nimble0/dotterel
