### ISSUE TITLE
Automatically show shorter stroke definitions 

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#37]
People just learning steno are forced to either write out many words letter by letter or phonetically in several strokes, if they don't know or can't remember shorter brief forms of words and phrases already defined in their dictionary. To help increase their knowledge of the dictionary as they use Plover, optionally float a small window that captures each translation from Plover's log and searches for shorter (i.e. fewer strokes) definitions of it in the dictionary. Ideally it would also work with fingerspelled words, delineated by spaces, though that would probably require more coding. A preliminary script which runs in the terminal has been written by Stefan Curtis, but this option should be integrated into Plover's GUI for easier use:

stenoknight.com/plover/PloverCheck

**Comment by morinted** [comment]
This is done with the stroke suggestions window.
