### ISSUE TITLE
Update author attributions in About dialogue

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#372]
For the credits in the About dialogue, we have:

`Stenographer: Mirabai Knight, Coder: Joshua Harlan Lifton, Contributors: Hesky Fisher`

Maybe instead, we can mention Mirabai as the lead stenographer/founder, and then link to the GitHub contributors page, as it will be more detailed than we could ever be in the about dialogue: https://github.com/openstenoproject/plover/graphs/contributors

**Comment by morinted** [comment]
Turns out this is kind of a pain, because the contributors section just wants a list of names. There's also no good place to throw @stenoknight as founder/creator, because it has developers, artists, and docwriters as sections. Here's an attempt:

<img width="564" alt="screen shot 2016-02-21 at 1 11 25 am" src="https://cloud.githubusercontent.com/assets/5840970/13201294/3369fc0a-d838-11e5-806b-ac50fec7f8b6.png">

**Comment by jeremy-w** [comment]
That looks pretty decent to me.

**Comment by lifton** [comment]
Looks good to me as well. I'm also open to whatever other suggestions you
come up with.

On Sun, Feb 21, 2016 at 8:09 AM, Jeremy W. Sherman <notifications@github.com

**Comment by balshetzer** [comment]
Likewise, whatever you decide for this is fine with me as well.
