### ISSUE TITLE
Cmd + C closes dialog boxes.

### ISSUE THREAD

**Issue by stanographer** [openstenoproject/plover#373]
#### What I expected to happen

I expected Cmd + C to let me copy text from a text field.

#### What happened instead

Whenever I press Cmd + C to copy text in the add translation dialogue, it would close the define window instead of copying the text. I noticed it happening also with other dialogue boxes containing text fields. For instance, if I try to copy the path to the logs to paste into Finder, it closes the dialogue. Plover remains functional and running, though. I've been getting around it by copying/pasting exclusively by right-clicking and selecting copy and paste from the menu.

#### Specs

OS X 10.11.3
Plover 2.5.8
Lightspeed steno machine
TX protocol

**Comment by morinted** [comment]
Looks like http://trac.wxwidgets.org/ticket/15678 is affecting us. The workaround is to set our own label instead of '&Cancel', which treats Cmd+c as "Close"
