### ISSUE TITLE
Plover failing to output ellipsis or even triple-dot - log shows translation is correct, but no output appears in app

### ISSUE THREAD

**Issue by jeremy-w** [openstenoproject/plover#378]
Classification: Bug

Reproducibility: Always

## Summary
Plover fails to output translations corresponding to `{...}` and `{…}{ }{-|}`.

## Steps to Reproduce
1. Add translation SKWR-RBGS for `{…}{ }{-|}`. This is the same as its current definition, except it uses the ellipsis character rather than a triple-dot.
2. Add translation SKWR*RBGS for `{...}`. This gives you a triple dot without any extra space or case shifting, handy for varargs params when coding, at least that's what I'm hoping.
3. Now type SKWR-RBGS.
4. Then type SKWR*RBGS.

## Expected Results
5. You see `… ...` (ellipsis, triple-dot)

## Actual Results
5. No output!

## Version
I'm running HEAD:

33803b5 Merge pull request #376 from benoit-pierre/gui_config_sort_machines

`__version__` is 2.5.8.

## Notes
I tailed the log, and everything looks like it's working fine:

```
> tail -f ~/Library/Application\ Support/plover/strokes.log
2016-02-21 10:40:07,369 Stroke(R- W-)
2016-02-21 10:40:07,370 Translation(('WR',) : were)
2016-02-21 10:40:07,535 Stroke(K-)
2016-02-21 10:40:07,536 Translation(('K',) : can)
2016-02-21 10:40:07,685 Stroke(-S)
2016-02-21 10:40:07,686 Translation(('-S',) : {^s})
2016-02-21 10:40:15,877 Stroke(#)
2016-02-21 10:40:15,878 Translation(('#',) : None)
2016-02-21 10:40:15,966 Stroke(P-)
2016-02-21 10:40:15,966 Translation(('P',) : about)
fipu2016-02-21 10:40:17,408 Stroke(-G H- -P P-)
2016-02-21 10:40:17,408 Translation(('PH-PG',) : {PLOVER:TOGGLE})
^R
2016-02-21 10:40:19,603 Stroke(-G -S -B W- K- S- -R R-)
2016-02-21 10:40:19,604 Translation(('SKWR-RBGS',) : {…}{ }{-|})
2016-02-21 10:40:23,291 Stroke(-G -S -B W- * K- S- -R R-)
2016-02-21 10:40:23,292 Translation(('SKWR*RBGS',) : {...})
2016-02-21 10:40:32,746 Stroke(-G H- -P P-)
2016-02-21 10:40:32,747 Translation(('PH-PG',) : {PLOVER:TOGGLE})
^C⏎ 
```

Note the last bits braced by PLOVER:TOGGLE. That's what you'd expect to see, and yet nothing shows up in BBEdit. I'm especially surprised that the triple-dot doesn't work, since there's nothing tricky there at all!

The JSON dictionary definitions are:

```
"SKWR*RBGS": "{...}",
"SKWR-RBGS": "{\u2026}{ }{-|}",
```

## Configuration
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1605

**Comment by balshetzer** [comment]
I think the problem is that the ellipses are inside brackets. Plover only recognizes specific commands inside curly brackets and ellipses is not one of them. Have you tried using the same dictionary definition but without brackets around the ellipses?

**Comment by balshetzer** [comment]
same for 'triple dot'

**Comment by jeremy-w** [comment]
I cargo-culted the {} around the dots from the definition Plover told me already existed for SKWR-RBGS:

```
/Users/jeremy/Library/Application Support/plover/main.json:"SKWR-RBGS": "{^...}{ }{-|}",
```

Ah, but there it had a `{^` that I seem to have omitted. I wonder if that didn't appear in the update dialog, or if I just missed it?

Trying with the ^ now…

**Comment by jeremy-w** [comment]
Testing… And it works now. And I checked: The ^ does show up in the dictionary update window, so it was classic PEBKAC.

Thanks for the quick catch!

This suggests a dictionary linter could be pretty handy, though…

**Comment by benoit-pierre** [comment]
There are instances of `{...}` in the main dictionary, should we fix those?

```shell
> grep -F '{...}' plover/assets/main.json
"KW-BG/SKWRORBGS": "{...}",
"SKWR-RBGS/HRAO*EUBG": "{...}like{,}",
"SKWR-RBGS/KWRAO*UPB": "{...}you know,",
```
