### ISSUE TITLE
Plover should not allow adding bogus dictionary entries

### ISSUE THREAD

**Issue by jeremy-w** [openstenoproject/plover#379]
Classification: Enhancement

Reproducibility: N/A
## Summary

It's possible to add bogus dictionary entries via the dictionary update window. This results in successful translation but no output. See #378 for a recent example.
## Steps to Reproduce
1. Summon the Add Translation window.
2. Define something to translate to `{…}`.
## Expected Results
1. "Add to Dictionary" should be disabled, because this is a bogus translation that will prevent any output from occurring.
## Actual Results
1. "Add to Dictionary" remains enabled. You get surprised when you try to use the outline later.
## Version

This functionality does not exist as of Plover version 2.5.8.
## Notes

The "Add to Dictionary" button appears to always be enabled, even when neither outline nor translation have been entered, so this would be part of adding dynamic button enabling to the window.

It would be great to accomplish this by adding some sort of translation "linting" support to the core dictionary/translation functionality that will diagnose errors, so that we could provide more verbose explanations of why the button is disabled, as well as support a `plover lint foo.json` that could be run from the CLI against a dictionary file.

**Comment by morinted** [comment]
That's a little difficult. Take your case, `{…}`, how can we say that's invalid? It doesn't produce output, but it doesn't cause a crash or anything. What if they are using a future version of Plover or another piece of steno software? I'm not sold on how viable linting a steno entry would be, especially when we are talking about multiple languages/layouts in future functions.

**Comment by morinted** [comment]
One quicker change that could be made is a linting of the stroke -- verify that it is in steno order and doesn't contain unknown keys. Some people manually type in the stroke and that is error prone.

For translations, it's not as clear to me how to lint them. Thoughts, @jeremy-w

**Comment by jeremy-w** [comment]
Good points.

The "it might be a different version" concern definitely applies for a general-purpose lint, but not so much when I'm entering it via UI in a specific version of Plover.

I think the disabling idea was too far, though.

We could instead notify the user and offer to fix up steno order.

For the translation, we could demo the output - that would catch unwanted zero-width output, for sure - but it doesn't really help with glue or non-printing commands. So maybe instead linting could just be "Here's what this notation translates to in Ploverese" (so more "explain this translation"). The lint bit comes in at "I have no idea what that bit of your translation means" or "deleting these characters would have no effect on the behavior."

The idea behind both of these is to help the human to make a decision rather than make it for them.

**Comment by mulka** [comment]
I tried adding an entry for Cmd+Enter as {#Super_L(Enter)}, but I don't think Enter works here. I think it has to be Return. Would have been nice to have Plover tell me that when I added the entry.

**Comment by marnen** [comment]
@mulka Wouldn’t that be at least somewhat expected, since Enter and Return are distinct keys on Mac OS?

**Comment by mulka** [comment]
@marnen "Enter" doesn't exist in the list of supported shortcut keys in Plover. "Return", however, does exist there: https://github.com/openstenoproject/plover/blob/master/plover/key_combo.py#L21

I'm don't know about enter and return being different keys on mac. On my MacBook I only have a return key and on an HP keyboard that I sometimes use with my MacBook the enter key works the same as the built-in return key as far as I can tell.

**Comment by marnen** [comment]
@mulka I assure you, Enter and Return are semantically different on Mac OS (for example, dialog boxes in some applications interpret Return as a line break and Enter as the OK button). On your MacBook, even though there’s no dedicated Enter key, you can simulate it for applications that need it by pressing Fn-Return on the built-in keyboard, and if Enter and Return really work the same on your external keyboard, that’s a flaw in the keyboard. (More likely, though, is that the external keyboard behaves correctly and you haven’t been aware of the difference, because Enter and Return do frequently do similar things.)

**Comment by marnen** [comment]
See https://apple.stackexchange.com/questions/47565/return-vs-enter for more info on this, for example. I would think that there should be some Apple technote about this, but so far I haven’t found one.

**Comment by marnen** [comment]
Anyway, where I suppose I’m going with this is that Plover should support `#Return` as distinct from `#Enter` on Mac OS. If it doesn’t, that’s probably a bug (even if it doesn’t matter most of the time).

**Comment by benoit-pierre** [comment]
Validating the strokes part is now done, thanks to #1362.
