### ISSUE TITLE
Create a way of quickly looking up a fingerspelled word's stroke from within plover 

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#40]
Plover's dictionary is "opaque"; if a new ploverist wants to find out how to write a word, they must leave Plover, open up dictionary.json in a text editor, and grep for the word on their own. This project intends to create a nice GUI that can be summoned by a configurable {PLOVER:LOOKUP} stroke in the dictionary that opens up a small window with a text entry field. The user can then quickly fingerspell the word and see a list of strokes that will write the word. They can then dismiss the window with a simple tap of the return or Esc key.

(On second thought, this likely isn't as useful as https://blueprints.launchpad.net/plover/+spec/brief-suggestions )

**Comment by morinted** [comment]
This is implemented thanks to @mighele
