### ISSUE TITLE
Retrospective delete space ( {*!} ) is not working for numbers

### ISSUE THREAD

**Issue by david-pitty** [openstenoproject/plover#402]
Classification: Bug

Reproducibility: Always

## Summary

Retrospective delete space ( {*!} ) is not working for numbers.

## Steps to Reproduce

1. input a word like: user
2. enter numbers like: 123
3. input key combination for Retrospective delete space

## Expected Results

4. user123

## Actual Results

5. Instead, this happens: user 123

## Version

Plover version 2.5.8.317.gced379f.

Installed via: download from https://github.com/openstenoproject/plover/releases/tag/weekly-v137

## Notes

Confirmed that the Retrospective delete space works as expected with other words like: username (spelled: AOURS/TPHAEUPL/TK\*LS where TK\*LS is the stoke for Retrospective delete space)

## Configuration

OS: Windows 8.1

**Comment by morinted** [comment]
Can you confirm whether this happens with Space Placement "after" and "before" space, or just one, please?

**Comment by david-pitty** [comment]
I can replicate with both configurations.

**Comment by morinted** [comment]
Thanks for the great bug report. I can guess why this is happening, I'm hoping the fix isn't too laborous. Plover handles numbers as sort of a "special case".

**Comment by david-pitty** [comment]
Awesome, thanks! This update is amazing, loving it so far :D

**Comment by morinted** [comment]
I was able to work around #405, but this is much more annoying because numbers are handled so differently. I wish I had an exact path of what a number stroke goes through. Will be more work before I find a solution for this. Although I know this issue exists, I'm having trouble creating a unit test that uses the number bar.

**Comment by morinted** [comment]
Mm, I found a workaround. Not sure if it's kosher, but it works for your use case of `user123`.

**Comment by david-pitty** [comment]
This issue can no longer be replicated on Plover-2.5.8+449.g8ac6d69.exe
Thanks.
