### ISSUE TITLE
Retrospective delete space ( {*!} ) is not working after period

### ISSUE THREAD

**Issue by david-pitty** [openstenoproject/plover#405]
Classification: Bug

Reproducibility: Always

## Summary

Retrospective delete space ( {*!} ) is not working after period.

## Steps to Reproduce

1. Enter text after a regular period (-P)
2. Try to do a Retrospective delete space

## Expected Results

3. Space after period should be deleted

## Actual Results

3. No change

## Version

Plover version Plover version 2.5.8.317.gced379f

Installed via: download from https://github.com/openstenoproject/plover/releases/tag/weekly-v137

## Notes

Not sure if this behavior is expected, but it would be useful for correcting typos when looking for dotfiles on the console. Example: . zshrc -> .zshrc   (-P/S*EU/S*/H*/R*/KR*/TK*LS [where TK*LS is the stoke for Retrospective delete space])

workaround: use an entry on your dict for {^.^} to suppress the space after the period.

## Configuration

OS:

OS: Windows 8.1

**Comment by david-pitty** [comment]
forgot to mention that "Retrospective lowercase last word" does work after regular period.

**Comment by benoit-pierre** [comment]
Fixed by #409.
