### ISSUE TITLE
Extend steno notes and offer export

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#406]
Classification: Feature (New)

## Summary

Request to print notes.

It would be good to be able to print the notes -- or at least be able to make a .pdf with them.  The idea there is when you take one of the court reporting exams, sometimes they want your notes, and it would be good to be able to provide them.   

## Steps to Reproduce

1. I do this -- open the Notes Display
2. I do that -- and try to print.  

## Expected Results

3. This should happen: Plover should be able to use the system's printer routines to produce a PDF, or maybe even print to paper.  

## Actual Results

3. Instead, this happens. :(  Currently, there is no evidence that the printing routine exists -- no menu, nothing through a right-click (or control-click on the Mac); hence this request.  

## Version

Plover version 2.5.8+317.gced379f

**Comment by morinted** [comment]
Maybe we could not have a limit set for the paper tape, since paper tape users usually want to be able to recover all their notes?

**Comment by gdwaynewarner** [comment]
That should work!

**Comment by timthelion** [comment]
Why is there a limit at all? Is there some reason why this doesn't just revert over to a scroll bar'd window in both paper tape and raw?

**Comment by morinted** [comment]
Probably pre-optimisation? Plover's buffer was 10 until a few days ago. The
suggestions window doesn't need the full history because it's contextual.

But what if we introduced another log file for paper tape?

**Comment by timthelion** [comment]
I uploaded a very simple PR which adds the vertical scroll and gets rid of the maximum length. Very light testing doesn't reveal any problems. I don't think that there is a need for optimization in this case. When I think about it, the most a person is likely to type, at like 2 strokes a second is:
````
>>> 24*60*60*2
172800
````

Strokes a day. That's really not much ram ;)

**Comment by morinted** [comment]
Yeah. Apparently the Stentura protocol maxes out at like 8 days of constant
typing, so I think it would be fine.

**Comment by timthelion** [comment]
So my pull request allows you to have as many as 2 million strokes in the log. It also has a 'Clear' button so that you can clear out the strokes at the beginning of the excersize. You can then copy the text into a text editor and format it for printing.

**Comment by timthelion** [comment]
I just added a save button too, but it only saves as text, not as pdf or anything fancilly formated.
