### ISSUE TITLE
Capture keystrokes without outputting them on linux

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#41]
Currently the qwerty-to-steno implementation of Plover sends qwerty versions of keystrokes entered by the user, sends a corresponding number of backspace commands to delete the keystrokes, and then sends the strokes corresponding to the correct steno translation of the original keystrokes. This works fairly well in most applications, but in cases where single alphanumeric keys are mapped to commands (such as in Vim or Firefox), Plover cannot be used with a qwerty keyboard because the qwerty strokes will execute before Plover has a chance to delete them. In order to solve this, Plover needs to control the keyboard at a lower level, so that it can prevent the strokes from being sent out in the first place.

As of the most recent release, this problem is fixed in the Windows version.

**Comment by dozenfingers** [comment]
This should be a solution and it appears to be simple. It works for me on a Noppo Choc.

This is the link to the conversation: https://groups.google.com/forum/#!topic/ploversteno/RKpkNL2CMfs

and this is the code: https://github.com/benoit-pierre/plover/tree/bpierre

I hope this will help.

**Comment by morinted** [comment]
This might be fixed using grabbing of keys by @benoit-pierre in #259.
