### ISSUE TITLE
Cannot write in Visual Studio

### ISSUE THREAD

**Issue by mighele** [openstenoproject/plover#410]
Classification: Bug

Reproducibility: Always

## Summary

Plover won't output in Visual Studio 2010 or Visual Studio 2013.

## Steps to Reproduce

I am using a machine on Windows 8.1 64 bit
I have Visual Studio 2013 installed
The issue may also happen with the free community edition
I open any file in Visual Studio (or create new blank file)
I start Plover and enable it
I put the cursor into the open file in Visual Studio
I write steno keys "TH" which is mapped to "this" in my dictionary

## Expected Results

I expect to see "this" printed in Visual Studio

## Actual Results

I see "wr" printed in Visual Studio (the corresponding qwerty keyboard keys)

## Version

Plover-2.5.8+440.gced379f

## Notes

It seems to work in other rich-text applications like Microsoft word and other code editors like Pycharm and MonoDevelop. Just not in Visual Studio specifically.

## Configuration

OS:

Windows 8.1 Pro
64 Bit

**Comment by mighele** [comment]
I'm using Plover in keyboard mode with a Sidewinder keyboard

**Comment by morinted** [comment]
Mike, do you have a machine to test with? It may be the case that Visual
Studio hooks into the keyboard and overrides our access. Another option may
be running with elevated privileges.

**Comment by morinted** [comment]
Also might be nice to know if it happens in Plover 2.5.8 as well.

**Comment by mighele** [comment]
Hi Ted.

The same thing happens with 2.5.8 so looks like it isn't a newly introduced thing. Could be just what you say. I'll have to try it out with my Steno machine but it isn't currently set up.

I tried running it as Administrator but it still happens.

In trying this out, I noticed another little bug which I'll just raise an issue for.

**Comment by morinted** [comment]
I have some thoughts on this issue:

- It may be related to the alt-tab issue in Windows 8 (permissions)
- If not, the it's Visual Studio's keyboard handling. Perhaps it would work with a machine over a serial protocol, but I don't think that we'll be able to fix it if VS is really grabbing raw keyboard input.
