### ISSUE TITLE
Plover won't load - backward compatibility.

### ISSUE THREAD

**Issue by mighele** [openstenoproject/plover#411]
Classification: Bug

Reproducibility: Always

## Summary

Plover won't load when switching between 2.5.8 and 2.5.8+440.gced379f.

## Steps to Reproduce

I started using build 2.5.8+440.gced379f.
I went back to build 2.5.8

## Expected Results

Plover loads and works fine.

## Actual Results

Plover shows an error and won't load.

## Version

2.5.8+440.gced379f

## Notes

I believe this is happening because the "Stenotype Machine" was set to "Keyboard" in the newest version. Then when I loaded 2.5.8, it doesn't have "Keyboard" but instead has "NKRO Keyboard".

This isn't a major issue as the new naming is better but might be worth putting something in just for some backwards compatibility.

Workaround is:
Open Plover working version
Change machine type to Stentura
Open non-working version (which will now work)
Change machine type to NKRO Keyboard

## Configuration

OS:

Windows 8.1
64 Bit

**Comment by morinted** [comment]
In future releases, this is handled because we have a more robust init loop
that will open a configuration dialog instead of crashing. I don't think
it's worth trying to write around 2.5.8's configuration dialog.

**Comment by morinted** [comment]
When I made this change, I knew that it would throw if the config was loaded in 2.5.8. I'm willing to crop this up as a "breaking change" that merits a version bump.
