### ISSUE TITLE
Upload latest version to Pypi as part of standard release procedures

### ISSUE THREAD

**Issue by timthelion** [openstenoproject/plover#416]
Classification: Usability

Reproducibility: Always

## Summary

The latest version of plover on pypi is 2.2.0:
https://pypi.python.org/pypi/plover/2.2.0
But the latest version here is 2.5 something...

**Comment by morinted** [comment]
Last time this came up, we didn't make any actions: #185 

Might be best to remove our PyPi distro? Any idea, @benoit-pierre ?

**Comment by benoit-pierre** [comment]
I think we should update PyPi when we release the next version.

**Comment by jeremy-w** [comment]
- Do we have release procedures documented anywhere?
- Can we add the steps to update PyPi to those procedures and then close this issue?

**Comment by morinted** [comment]
Now we have an Ubuntu PPA and AUR script thanks to @benoit-pierre, this is the last area we want to post, right?

**Comment by benoit-pierre** [comment]
Yeah, but we need the proper rights to the PyPI package, @lifton / @balshetzer : can one of you add me to the Package Index Owner list? My username on PyPI is `benoit.pierre`.

**Comment by balshetzer** [comment]
Done

**Comment by benoit-pierre** [comment]
@balshetzer: thanks!

**Comment by benoit-pierre** [comment]
Done: https://pypi.python.org/pypi/plover

Note that I had to change back the project name to lower case in `setup.py` (I'll make a PR).
