### ISSUE TITLE
Larger Buffer for RAW Steno Notes

### ISSUE THREAD

**Issue by wickken** [openstenoproject/plover#418]
Classification: Enhancement

Reproducibility:  N/A 

Enhancement: Larger Buffer for RAW Steno Notes. 
I think the current buffer is about 100 strokes which is about 71 words (@1.4 strokes/word). I recommend:
1) Make the buffer limit configurable
2) Make the buffer limit 17,500 strokes (about 50 pages. 1.4 strokes/word & 250 words/page)

Plover version: 2.5.8+317.gced379f
Installed via: download from openstenoproject.org

OS: Mac OS 10.11.13

**Comment by morinted** [comment]
This is definitely we'd consider, and you can keep track of it in #406 which was opened last week.
