### ISSUE TITLE
interface to a real-time text to speech engine 

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#43]
Interface Plover to a text-to-speech engine to allow for real-time, steno-enabled, synthesized conversation. The eSpeak program is a likely candidate for a TTS engine, as it is fast and installed on Ubuntu by default. The steno interface must take into account words that might trigger false vocalizations before being integrated into a longer multi-stroke word.

**Comment by ducis** [comment]
As a leraner, I actually would like have an option that calls espeak for each chord.
(Or each word, maybe another option)
Currently I practice with >xargs -n1 espeak 2>/dev/null 
and R-R after each word.
If Plover had an auto-espeak function, I would be able to practice 
when writing a mail or doing whatever other "real" tasks other than typing in a specific session.
And espeak, while being able to pronounce non-words, cannot pronounce 
paper tape symbols.
