### ISSUE TITLE
OSX: crash when layout is set to "US: Extended"

### ISSUE THREAD

**Issue by noahfrederick** [openstenoproject/plover#432]
Classification: Crash

Reproducibility: Always

## Summary

Fresh install of Plover `weekly-v2.5.8+456.g56f1410` crashes on start under OS X Yosemite (10.10.5).

## Steps to Reproduce

1. Launch Plover.app from Finder.

## Expected Results

2. Plover starts without error.

## Actual Results

3. **Plover Error** window appears.

## Version

Plover version `weekly-v2.5.8+456.g56f1410`.

Installed via: DMG download on GitHub releases page.

## Notes

The Console shows the following stack trace from Python:

```
3/17/16 10:47:53.194 AM Plover[37507]: Traceback (most recent call last):
3/17/16 10:47:53.194 AM Plover[37507]:   File "/Applications/Plover.app/Contents/Resources/__boot__.py", line 77, in <module>
3/17/16 10:47:53.194 AM Plover[37507]:     _run()
3/17/16 10:47:53.194 AM Plover[37507]:   File "/Applications/Plover.app/Contents/Resources/__boot__.py", line 62, in _run
3/17/16 10:47:53.194 AM Plover[37507]:     exec(compile(source, path, 'exec'), globals(), globals())
3/17/16 10:47:53.194 AM Plover[37507]:   File "/Applications/Plover.app/Contents/Resources/launch.py", line 4, in <module>
3/17/16 10:47:53.194 AM Plover[37507]:     from plover.main import main
3/17/16 10:47:53.194 AM Plover[37507]:   File "plover/main.pyc", line 20, in <module>
3/17/16 10:47:53.194 AM Plover[37507]:   File "plover/gui/main.pyc", line 17, in <module>
3/17/16 10:47:53.194 AM Plover[37507]:   File "plover/app.pyc", line 21, in <module>
3/17/16 10:47:53.194 AM Plover[37507]:   File "plover/config.pyc", line 12, in <module>
3/17/16 10:47:53.194 AM Plover[37507]:   File "plover/machine/registry.pyc", line 8, in <module>
3/17/16 10:47:53.194 AM Plover[37507]:   File "plover/machine/keyboard.pyc", line 8, in <module>
3/17/16 10:47:53.194 AM Plover[37507]:   File "plover/oslayer/keyboardcontrol.pyc", line 29, in <module>
3/17/16 10:47:53.194 AM Plover[37507]:   File "plover/oslayer/osxkeyboardcontrol.pyc", line 40, in <module>
3/17/16 10:47:53.195 AM Plover[37507]:   File "plover/oslayer/mac_keycode.pyc", line 177, in <module>
3/17/16 10:47:53.195 AM Plover[37507]:   File "plover/oslayer/mac_keycode.pyc", line 173, in getlayout
3/17/16 10:47:53.195 AM Plover[37507]:   File "plover/oslayer/mac_keycode.pyc", line 79, in parselayout
3/17/16 10:47:53.195 AM Plover[37507]: UnboundLocalError: local variable 'sequences' referenced before assignment
3/17/16 10:47:53.290 AM Plover[37507]: Plover Error
3/17/16 10:47:53.290 AM Plover[37507]: 2016-03-17 10:47:53.289 Plover[37507:5632269] Plover Error
```

## Configuration

OS:

```
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1605
```

**Comment by morinted** [comment]
Just downloaded the weekly, this doesn't happen for me on 10.11.

Can you try out the previous weekly, too, because the code that failed should be the same in both weeklies.

**Comment by noahfrederick** [comment]
> Can you try out the previous weekly, too

Yes, identical behavior in the previous weekly.

I have a couple of versions of Python (2.7.11, 3.5.1) installed via Homebrew in addition to the system Python. I assume those versions won't even be in my path, though, if Plover is launched from the Finder.

I just tried Plover version 2.5.8 and it works without issue.

**Comment by benoit-pierre** [comment]
Could this only happen with only some layouts? The [code](https://github.com/openstenoproject/plover/blob/master/plover/oslayer/mac_keycode.py#L70) does looks buggy.

**Comment by morinted** [comment]
What layout is your Mac set to? Is it an international locale?

**Comment by noahfrederick** [comment]
> What layout is your Mac set to? Is it an international locale?

As in System Preferences > Keyboard > Input Sources? It's "U.S. Extended"...oh, and Plover launches without the error when I switch it to "U.S.".

**Comment by morinted** [comment]
That's good to know. I'll look into it 😄
