### ISSUE TITLE
Spaces Issue

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#437]
Classification: Bug
Reproducibility: Always

## Summary

When I write the stroke for either a new line, a new paragraph, one of the strokes I use for my website, or a new prefix after starting Plover, there is usually an unwanted space at the point where I start writing.

For instance, I added a few strokes to handle the .css definitions I have for my website: one for the body, one for captions for images, another for article introductions, etc.

As they are defined to invoke definitions in a .css stylesheet, I came up with a few outlines that start out with an almost combination of "P Class," in the form of PHRA-S, so I have these strokes:

<p class="body"> 
<p class="generic"> 
<p class="caption"> 
<p class="intro"> 
<p class="QA"> 

As I am writing these in an HTML editor that has autocomplete, the editor automatically attaches the second half of these strokes, like so:

<p class="body"></p>
<p class="generic"></p>
<p class="caption"></p>
<p class="intro"></p>
<p class="QA"></p>

The problem is, there is usually a space in there between the two greater than and less than symbols.

## Steps to Reproduce

1. I start Plover and stroke one of the appropriate outlines

## Expected Results

3. The stroke should not have a space at the end.

## Actual Results

3. Instead, this happens. :( I get "<p class="body">"  closely followed by an unwanted space.

If helpful, submit screenshots of the issue to help debug. Your `plover.log` or `strokes.log` may also be useful.

## Version:  2.5.8.487.g9d3cd22

Installed via: https://github.com/openstenoproject/plover/releases/download/weekly-v2.5.8%2B487.g9d3cd22/Plover-2.5.8.487.g9d3cd22.dmg

## Notes

Describe any debugging steps you've taken yourself.

Unfortunately, I have not tried anything of late. I just use my work-around.

If you've found a workaround, provide it here.

I have all of these definitions in a file, so I just go through the file, copy each of the definitions, and re-add them to the appropriate dictionary, which immediately fixes the problem.

## Configuration

OS:  ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F1603

I am attaching a screenshot of what it looks like in my HTML editor.
![screenshot 2016-03-19 17 00 08](https://cloud.githubusercontent.com/assets/17680111/13902023/3daf9f4e-edf5-11e5-9ecc-a95f55aa9d24.png)

**Comment by morinted** [comment]
Is it possible you need to add some attaches to your newlines? E.G. `{#Return}{^}` ? In RTF you would append a `\cxds`

**Comment by gdwaynewarner** [comment]
Whoops! I should have included a screenshot of the actual outlines. Here we go:

![screenshot 2016-03-20 01 48 47](https://cloud.githubusercontent.com/assets/17680111/13903565/18ba862e-ee3e-11e5-870f-a8221377da88.png)

As you can (hopefully) see, definition three through six have the {#Return} bits in them. The others don't require it, as I have to manually move the cursor down to the next line after I have typed what I need to type.

For the HTML bits, no returns or paragraphs are needed; just the "Keep Together" and "Cap Next," and I do the "returning" by moving the cursor to the end of the line and using either the paragraph or the return stroke.

Hope that clarifies ...!

--gdw

**Comment by morinted** [comment]
I'm afraid I still don't exactly understand the problem. Is it only on start up? Do you have Plover set to suppress space on startup?

**Comment by gdwaynewarner** [comment]
Hi, Ted.

Essentially, for the HTML stuff, the cursor should be right next to the caret after "generic," "body,", "intro," "QA," and "note."   What I usually get is what you can see in the original picture.

This usually happens when I have to restart Plover (I usually just leave it running until I have to reboot or something).

After restarting Plover, I have to go through all of those entries shown in the second image to make those outlines work correctly; otherwise, I get a space when I hit the paragraph or return strokes.

I don't have the "suppress space" option selected; I wasn't quite sure what it was for. I'm still not, actually ...

**Comment by balshetzer** [comment]
Here is a guess:

Glen uses RTF dictionaries. His definitions work fine when he enters them and they're just stored in RAM. However, when he restarts Plover then the definitions have gone through a round trip of encode/decode and they've lost their space suppression.

**Comment by morinted** [comment]
Glen, can you copy the definitions from your RTF dictionary for reference?

**Comment by gdwaynewarner** [comment]
Hi, Ted.

Here you go:

bio{^^}
Mc{^^}{-|}
{#Return}{#Return}{^^}{-|}
{#Return}{^^}{-|}
<p class="generic">{^^}{-|}
<p class="body">{^^}{-|}
<p class="caption">{^^}{-|}
<p class="intro">{^^}{-|}
<p class="QA">{^^}{-|}
<p class="note">{^^}{-|}

**Comment by gdwaynewarner** [comment]
Hmm. I don't know what happened there. Let me try that again.

bio{^^}
Mc{^^}{-|}
{#Return}{#Return}{^^}{-|}
{#Return}{^^}{-|}
<p class="generic">{^^}{-|}
<p class="body">{^^}{-|}
<p class="caption">{^^}{-|}
<p class="intro">{^^}{-|}
<p class="QA">{^^}{-|}
<p class="note">{^^}{-|}

**Comment by gdwaynewarner** [comment]
I don't know why, but they're not copying correctly. None of the HTML stuff is coming through, for some reason. One more try, with just the HTML this time:

<p class="generic">{^^}{-|}
<p class="body">{^^}{-|}
<p class="caption">{^^}{-|}
<p class="intro">{^^}{-|}
<p class="QA">{^^}{-|}
<p class="note">{^^}{-|}

**Comment by benoit-pierre** [comment]
Try a code block (between 2 ``` lines).

**Comment by gdwaynewarner** [comment]
Hmm.

Okay, I think I've got it ...

`bio{^^}`
`Mc{^^}{-|}`
`{#Return}{#Return}{^^}{-|}`
`{#Return}{^^}{-|}`
`<p class="generic">{^^}{-|}`
`<p class="body">{^^}{-|}`
`<p class="caption">{^^}{-|}`
`<p class="intro">{^^}{-|}`
`<p class="QA">{^^}{-|}`
`<p class="note">{^^}{-|}`

**Comment by balshetzer** [comment]
More importantly, this is not going to help. We need the RTF dictionary in
which you have these outlines. Ideally, you could make a new one with just
one and verify that it had this problem. Then send us that dictionary and
the logs if the problem happening.

**Comment by morinted** [comment]
Just thinking aloud, it's probably the use of `{^^}` that the RTF parser isn't handling correctly. Equivalent and maybe functional solution would be a solitary `{^}`, @gdwaynewarner

**Comment by gdwaynewarner** [comment]
Here's the dictionary they're in:

[Glenz_Fast_Plover.rtf.zip](https://github.com/openstenoproject/plover/files/186365/Glenz_Fast_Plover.rtf.zip)
So the single {^} gives me a delete space?

**Comment by morinted** [comment]
So the RTF in question looks like:

`{\*\cxs PHRAS/SKWREPB}<p class="generic"> \cxds  \cxds  \cxfc`

Which might be interpreted as `<p class="generic"> {^ ^}{-|}` which would explain your spacing problem.

**Comment by gdwaynewarner** [comment]
Hmm.

So it should be fixed like so --

<p class="generic">{^}{-|}

**Comment by gdwaynewarner** [comment]
So it should be rewritten like so --

`<p class="generic">{^^}{-|}`

**Comment by gdwaynewarner** [comment]
So it should look like this:

`<p class="generic">{^}{-|}`

**Comment by morinted** [comment]
Try it and let me know :)

**Comment by gdwaynewarner** [comment]
Okay, those new outlines are definitely doing the job ...! We'll see after the next few reboots!

Thanks for the extra efforts!
