### ISSUE TITLE
Plover enabled but suddenly starts outputting qwerty with no apparent trigger

### ISSUE THREAD

**Issue by Nat2020** [openstenoproject/plover#454]
Classification: Bug

Reproducibility: Sometimes/Unpredictable (no clear triggers, happens at random, sometimes within minutes, sometimes within hours)

## Summary

Plover is enabled, functioning as expected, then suddenly starts outputting qwerty while Plover is still enabled. I'm using an NKRO keyboard. The problem can occur partially sometimes, with letters stuck to the ends of words (e.g., "The quickd brown fox jumps over the lazy dog", with the "d" being out of place here), but the bigger problem is when it ends up outputting qwerty completely and never goes back to steno (e.g., "The quick brownwevkl;"). And the partial and complete occurrences are not necessarily sequential and have mostly been isolated so far.

## Steps to Reproduce

1. Launch Plover
2. Enable translation
3. Type normally

## Expected Results

1. Output steno for as long as Plover is enabled

## Actual Results

3. Instead, it stops outputting steno and reverts to qwerty at unpredictable times with no apparent trigger. Stops logging as well. Plover is still enabled. Need to completely restart. :(

## Version

Plover version 2.5.8 + 440.gced379f

Installed via: download from openstenoproject.org.

## Notes

It stops logging when it stops working, so I don't have anything in the logs to show for it. Toggling off and on again doesn't get it working again; have to completely restart. Unplugging and replugging the keyboard with Plover enabled does not reproduce the problem; I can unplug and replug and still have it output steno. Like I said, nothing in particular triggers it. It works just fine and then stops right in the middle of things.

## Configuration

OS:

- Windows 10, 64-bit, x64-based processor (Idk how much info is relevant here, sorry)
-Using NKRO keyboard

**Comment by Achim63** [comment]
I could reproduce this with a Sidewinder on Windows10. It must have happened after I typed a few hundred words and then just left it open for a few minutes. When I came back to the machine, it stopped putting out anything, but interestingly the suggestions window still shows the strokes and translations correctly.

Clicking on "Disable" makes the output work again! So somehow the output switched off without showing this in the GUI, and now Enable and Disable are switched around.

This is probably related to the the recent fix for the output not being reenabled after connecting a steno machine on OSX.

**Comment by benoit-pierre** [comment]
This look nothing like this bug. Please create another bug.

**Comment by Achim63** [comment]
To be honest, I'm not really interested to pursue this any further, as reproduction takes a lot of time. My Win10 machine is just for gaming, my main computer is an iMac and I'm using a "real" steno machine usually.

**Comment by benoit-pierre** [comment]
What about other users that might run into the same issue? Even if we don't investigate/fix it right now, it can be helpful knowing the issue was already present in a older version when investigating it later.
