### ISSUE TITLE
Add to Dictionary dialog should allow selecting dictionary other than topmost

### ISSUE THREAD

**Issue by tkpwaeub** [openstenoproject/plover#457]
Classification: Enhancement

Reproducibility: Not Applicable

Two things that I think would greatly enhance the usability of the dictionary:

1. I'd like it if there were a drop down to select the dictionary while adding a translation. That way I'd know exactly what dictionary I'm updating.
2. It would with really nice if we could "uncheck" dictionaries, rather than just removing them from the list.

I've already mentioned that it would be terrific if we could interact with stenodict directly from Plover, but that's worth mentioning again here, just because it would make sense to address all these things at the same time.

**Comment by morinted** [comment]
This is present in the new UI previews, thanks for the request, I hope that you get to use it soon!
