### ISSUE TITLE
Return keeps concatenating suggestions

### ISSUE THREAD

**Issue by Cat-Ion** [openstenoproject/plover#459]
Classification: Bug

Reproducibility: Always
## Summary

The words before and after a newline get concatenated in the suggestions display
## Steps to Reproduce
1. Stroke 'This'
2. Stroke '{Return}'
3. Stroke 'is'
## Expected Results
1. Suggestions show strokes for 'this' and 'is'
## Actual Results
1. Suggestions show 'thisIs'

You can keep going, too, if you hit return again and keep writing. The second word on a line resets this.
## Version

Plover version 2.5.8, rev c86df6c.

Installed via: git
## Notes

Works with spaces before and after output. Haven't found a workaround yet.
## Configuration

OS: Gentoo Linux, running awesome as WM.

**Comment by morinted** [comment]
I wonder what the behavior is with {#BackSpace}, because we may not want to split suggestions based on commands.

**Comment by Cat-Ion** [comment]
If I stroke "HEL/LO/PW-FP/WORLD" it shows suggestions for "hello", "world", and "{^world}".
If I stroke "APBG/REU", then backspace so I get "ang" and then do "*ER" I get "anier", and suggestions for "angry" and "angryier" (and *-ing gets me "any" and a suggestion for "angryy").

**Comment by benoit-pierre** [comment]
I think using `\n` instead of `{#Return}` largely address that.

**Comment by morinted** [comment]
Yes, the suggested way to fix this is using `{^\n^}` instead of `{^}{#Return}`.
