### ISSUE TITLE
Suggestions window should hide while Plover is disabled

### ISSUE THREAD

**Issue by tthurman** [openstenoproject/plover#460]
Classification: Enhancement

The suggestions window should hide while Plover is disabled. Otherwise a) it gets in the way and b) it makes meaningless suggestions based on misinterpreting qwerty.

**Comment by morinted** [comment]
Well, with a steno machine, it might be useful to check strokes without generating any output, like when someone is working on their machine for some reason... not sure, though. I'd have to ask around and see what others think.

**Comment by morinted** [comment]
For now, I'm not interested in pursuing this feature -- but if you want to implement it, feel free to reopen the issue along with a PR.
