### ISSUE TITLE
Keyboard shortcut to enable/disable Plover

### ISSUE THREAD

**Issue by stevenhao** [openstenoproject/plover#464]
Classification: Feature

Instead of pulling up the Plover window and clicking enable/disable to activate the software, there should be a keyboard shortcut/command to enable/disable it.

**Comment by morinted** [comment]
Define a stroke that maps to {PLOVER:TOGGLE}. Sample stroke from the
default dictionary is "PHROLG". Where did you look for documentation before
submitting an issue? Maybe we could place it there to help future users.

**Comment by stevenhao** [comment]
I searched the wiki (but not that hard). Thanks for the quick response.

**Comment by morinted** [comment]
No problem!
