### ISSUE TITLE
Suggestion window minimizes after 'Add Stroke' Window closes

### ISSUE THREAD

**Issue by Tarmean** [openstenoproject/plover#466]
Bug

Reproducibility: Always

## Summary

The Suggestion window can minimize even when 'Always on top' is active. This happens on both Windows and Linux to me.

## Steps to Reproduce

1. Open suggestions window, having it open on startup works as well
2. Give the suggestions window focus and then focus some other application
3. Open the plover add stroke window with the 'TKUPT' stroke
4. Close the add stroke window with escape or enter

## Expected Results

Suggestions window stays in foreground

## Actual Results

Suggestions window minimizes

## Version

Plover version 2.5.8

This happens to me in both Ubuntu 15.10 and Windows 10.

**Comment by morinted** [comment]
Is this still present in the newer builds in the [releases page](https://github.com/openstenoproject/plover/releases) ?

**Comment by Tarmean** [comment]
I currently have 52ebe0bf363164ec7782a57e23c82966c6a162a6 checked out which is the latest release.

**Comment by benoit-pierre** [comment]
I can't reproduce this, both on Linux (Arch Linux and Ubuntu 16.04) and on Windows 10. What's your window manager on Linux? Do you have wmctrl installed?

**Comment by Tarmean** [comment]
My window manager is compiz and I have wmctrl installed.

**Comment by Tarmean** [comment]
The problem went away after upgrading to Ubuntu 16.04 without a change to plover so the problem doesn't seem to lie here. Gonna close the issue and thanks for the help!
