### ISSUE TITLE
Mark strokes or words for later analysis

### ISSUE THREAD

**Issue by momotombo** [openstenoproject/plover#469]
Classification: Feature request

Reproducibility:  Not Applicable

## Summary

Mark strokes/words for later analysis.

It would be nice if one could hit a chord to mark the last entered word/chord to add to a list for later analysis. This would be helpful for anyone who wants to drill words, make new briefs later, analyze problem strokes, et cetera.

**Comment by morinted** [comment]
Couldn't you just use a particular stroke and search through your Plover
log?

**Comment by momotombo** [comment]
Not having having the particular find for that sort of thing, it probably would have taken me way too long to think of that. Whoops.

**Comment by morinted** [comment]
Mirabai also has some strokes she uses with Vim to accomplish this or
similar. To the effect of, add this word to a file then let me come back.

**Comment by stenoknight** [comment]
Yeah, I have PHOEUFP set to ` (backtick), make ` invisible in my vimrc, and
then have a one stroke macro to search for it within documents.

**Comment by momotombo** [comment]
Now that I think about it, I think what I could do is have a stroke that doesn't translate. Then I can just save the log and do a search for those strokes. Maybe that would be a good way to do it.

**Comment by Achim63** [comment]
If you're in a simple text editor, you could define a stroke that puts a special character before and after the last stroked word, e.g. an underscore or a paragraph sign (on Mac: alt+left, §, alt+right, §). In a word processor, you could do the same but also e.g. underline that word or set it to italics or small caps or even change the color (or just trigger the keyboard shortcut for a pre-defined style setting).

**Comment by morinted** [comment]
I'll say this is out of scope for now, thanks for chiming in everyone! Hope you've found a solution that works for you @momotombo
