### ISSUE TITLE
Repeat last stroke on reversed numbers outputs the EU

### ISSUE THREAD

**Issue by david-pitty** [openstenoproject/plover#470]
Classification: Bug

Reproducibility: Always
## Summary

Repeat last stroke on reversed numbers outputs the EU.
## Steps to Reproduce
1. I type: 80 (stroked 0EU8)
2. I use Repeat last stroke
## Expected Results
1. 8080
## Actual Results
1. 80 80EU
## Version

Plover v2.5.8+567.g52ebe0b.

Installed via: download from https://github.com/openstenoproject/plover/releases/tag/weekly-v2.5.8%2B567.g52ebe0b
## Notes

Issue cannot be replicated with 3131 or 0101 (there may be more).
## Configuration

OS:
Windows 8.1

**Comment by morinted** [comment]
Is the issue consistently when there is a stroke on both sides of the board? (e.g. 1, 3, and 0 are all on the left-hand side)

**Comment by david-pitty** [comment]
Also consistent with the right hand of the board, example: 98 98EU
Actually I can replication with the number 5 and any other number from the left side of the board: 51 51EU or 54 54EU

**Comment by david-pitty** [comment]
BTW, 96 69EU has a weird behavior were the repeat last stroke outputs the non reversed numbers along with the EU
