### ISSUE TITLE
Repeat Last Stroke after typing two numbers outputs the numbers reversed for some combos

### ISSUE THREAD

**Issue by david-pitty** [openstenoproject/plover#471]
Classification: Bug

Reproducibility: Always
## Summary

Repeat last stroke after typing two numbers outputs the reversed number two numbers.
## Steps to Reproduce
1. I type: 12
2. I use Repeat last stroke
## Expected Results
1. 1212
## Actual Results
1. 1221
## Version

Plover v2.5.8+567.g52ebe0b.

Installed via: download from https://github.com/openstenoproject/plover/releases/tag/weekly-v2.5.8%2B567.g52ebe0b
## Notes

Using Repeat last stroke several times keeps outputting the reversed number although EU was never typed. 
This could not be replicated with 1313, 1818, 1919, 4848, 4949, 5959
I was able to replicate with 0990, 1221, 1441, 1551, 2552, 3553, 4554
## Configuration

OS:
Windows 8.1

**Comment by david-pitty** [comment]
Issue present with both space placement configurations.

**Comment by morinted** [comment]
I get the feeling that #287, #470, and this one are all related and will require a rework of either repeat-last-stroke or the number bar...

**Comment by benoit-pierre** [comment]
Fixed in master.
