### ISSUE TITLE
Retrospective Insert Space does not resolve for largest word following the inserted space

### ISSUE THREAD

**Issue by david-pitty** [openstenoproject/plover#473]
Classification: Bug

Reproducibility: Always
## Summary

Retrospective insert space does not allow for dictionary to resolve for largest word.
## Steps to Reproduce
1. O/SRAL/SP-S/TKAEUT ("oval date")
## Expected Results
1. to validate
## Actual Results
1. to val date
## Version

Plover v2.5.8+567.g52ebe0b.

Installed via: download from https://github.com/openstenoproject/plover/releases/tag/weekly-v2.5.8%2B567.g52ebe0b
## Notes

Issue can be replicated using both space placement configurations.
Workaround: use space to separate "to" from the next stroke.
## Configuration

OS:
Windows 8.1

**Comment by morinted** [comment]
Unfortunately, the steno model doesn't lend well to retrospective actions. I'm not sure how I'd even go about fixing this one. Is there a more real-world example so I can understand the use case?

**Comment by david-pitty** [comment]
To be honest I haven't come across this issue after that case, so I don't think it should be consider a bug since I don't think this feature was designed to just add a space between the last two strokes.
