### ISSUE TITLE
Allow reload of dictionary for easier manual dictionary editing.

### ISSUE THREAD

**Issue by david-pitty** [openstenoproject/plover#474]
Classification: Enhancement

Reproducibility: Always
## Summary

Allow reload of dictionary from UI and through a Plover command like: ({PLOVER: RELOAD_DICT}).
## Version

Plover v2.5.8+567.g52ebe0b.

Installed via: download from https://github.com/openstenoproject/plover/releases/tag/weekly-v2.5.8%2B567.g52ebe0b
## Notes

Currently I have to close Plover and reopen it to use changes I do through manually editing of my dictionary (from a text editor). If there is another known workaround please let me know.
## Configuration

OS:
Windows 8.1

**Comment by morinted** [comment]
I wonder if a filesystem hook could be implemented, too, to detect changes.

**Comment by benoit-pierre** [comment]
We don't have a dedicated command, but the engine will now automatically reload outdated dictionaries on configuration update (e.g. when resetting the machine).
