### ISSUE TITLE
Start-Minimized Option

### ISSUE THREAD

**Issue by stenoknight** [openstenoproject/plover#475]
Classification: Feature (New)

Reproducibility: N/A

## Summary

When adding a translation, the Plover window comes to front unless minimized. I often forget to minimize manually on startup, so having an option to always start minimized would be extremely useful.

## Steps to Reproduce

I check the "start minimized" box in config.

## Expected Results

Plover starts minimized.

## Actual Results

Plover has to be manually minimized to keep the main window to pop up when adding translations.

If helpful, submit screenshots of the issue to help debug. Your `plover.log` or `strokes.log` may also be useful.

## Version
2.5.8

## Notes
Workaround: Minimize Plover before adding any translations.

## Configuration
???

**Comment by jeremy-w** [comment]
Would it also work to instead avoid foregrounding anything other than the "Add Translation" window?
