### ISSUE TITLE
{MODE:SET_SPACE:} not compatible with Space Placement: After Output

### ISSUE THREAD

**Issue by flyingghoti** [openstenoproject/plover#476]
Classification: Bug

Reproducibility: Always

## Summary

When {MODE:SET_SPACE:} is on and Space Placement is set to "After Output", any stroke that begins with {^ will delete the last character of the preceding stroke.

## Steps to Reproduce

1. Set Space Placement to "After Output" on the Output tab
2. Activate {MODE:SET_SPACE:}
3. Stroke TPAO/PWAR/P-P/TPHET/R-R

## Expected Results

1. Output should be "foobar.net" + newline

## Actual Results

3. Output is "fooba.ne" + newline; the "r" is deleted by the P-P stroke and the "t" by the R-R stroke.

## Version

Plover version 2.5.8+567.g52ebe0b

Installed via: git

## Notes

This problem does not occur when Space Placement: Before Output is selected.

## Configuration

OS: Windows 10 Home

**Comment by benoit-pierre** [comment]
Tentative fix here: https://github.com/openstenoproject/plover/compare/openstenoproject:403162d...benoit-pierre:bc6337d

AppVeyor build here: https://ci.appveyor.com/api/buildjobs/jr10v1l3thiokt3r/artifacts/dist/Plover-2.5.8+573.gbc6337d.exe
