### ISSUE TITLE
Windows: ALT codes do not work when Plover is open (even when disabled)

### ISSUE THREAD

**Issue by flyingghoti** [openstenoproject/plover#477]
Classification: Bug

Reproducibility: Always

## Summary

[Alt Codes](https://en.wikipedia.org/wiki/Alt_code) do nothing when Plover is turned on. This is true even when Plover is disabled. A relatively minor issue that mostly only affects new steno users who, for whatever reason, use Windows, need to type non-ASCII characters sometimes, and use Alt codes to do so. (In other words, it might just affect me.)

## Steps to Reproduce

1. Open Plover; leave it disabled.
1. Hold ALT, hit "0233" on number pad

## Expected Results

2. é

## Actual Results

3. [no output]

## Version

Plover version 2.5.8+567.g52ebe0b

Installed via: git

## Notes

Workaround is simple; either close Plover or use another method to insert non-ASCII characters.

## Configuration

OS: Windows 10 Home

**Comment by benoit-pierre** [comment]
I can reproduce this. I don't know why it's not working with PyHook: we're correctly telling it not to suppress such events... The good news is I have a [version that gets rid of PyHook](https://github.com/benoit-pierre/plover/commit/07a85b68eaefe73134088ec14cf2959bd5921d20) (for Python 3 support), and this one works correctly.

AppVeyor build here: https://ci.appveyor.com/api/buildjobs/kknlpt0oq97x9to5/artifacts/dist/Plover-2.5.8+609.g07a85b6.exe

Can you confirm this work for you?

**Comment by flyingghoti** [comment]
Yes, that build does eliminate the issue.

**Comment by jeremy-w** [comment]
@benoit-pierre Will you open a PR with that diff to resolve this issue, or is it tied up in some bigger changes?

**Comment by benoit-pierre** [comment]
I will, but not for this release.
