### ISSUE TITLE
Linux: Send events for modifiers

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#482]
Classification: Enhancement

## Summary

Some applications don't properly receive modifier keys from Plover, likely because they handle shifted states and the like on their own. For example:

- Gnome terminal (Ubuntu)
- Konsole
- KRunner

e.g. `Email: someone@example.com` would come out as `email; someone2example.com`

Plover version: Tested with 2.5.8 & current HEAD

**Comment by benoit-pierre** [comment]
* bad news: sending additional press/release events for modifiers with `send_events` does not work
* good news: switching to XInput and using XTest for sending all events work
