### ISSUE TITLE
Dictionary Manager should allow unchecking dictionaries to stop looking up in them

### ISSUE THREAD

**Issue by jeremy-w** [openstenoproject/plover#485]
_This is the other half of #457._

It would with really nice if we could "uncheck" dictionaries, rather than just removing them from the list.

This would allow easily swapping between dictionaries without having to use the current heavyweight workaround of removing and then adding back dictionaries.

**Comment by jeremy-w** [comment]
@tkpwaeub I think drag-drop reorder (#337) might make the workaround less of a bother.

The current configuration file format makes "just skip this one" a bit of a bother, but perhaps we could add something like `PLOVER_DICTIONARIES_DISABLED = 1,2,5` which would indicate the dictionary numbers in the ordered list to skip. That could go really wrong if you reorder the dictionaries without updating the disabled list, though! But that's only a worry if anyone's doing config hacking by hand vs through the Plover UI.

**Comment by hhirsch** [comment]
@jeremy-w It is common for me to type english german and french. Switching dictionaries and layouts on and off with a stroke would be vital in order for me to be able to start using plover productively at all. So far this was laughed of as unimportant.

**Comment by morinted** [comment]
Progress on changing the core layout of Plover is well underway. No one has
been laughing at it (I hope). Plugins facilitate changing the chording
system and enabling dictionary switching.

**Comment by gdwaynewarner** [comment]
One thing that might be good to do would be to add the ability for Plover to have one or two dictionaries that are unused for actual translation, but are used merely for suggesting outlines.

As for why that would be useful, I write Phoenix Theory, which has been called "stroke intensive" over the years, and sometimes I need an outline that's not in that theory dictionary, and when that happens, I look at one of the numerous other dictionaries I have available through Stenovations' Dictionary Maintenance Program, which is part of digitalCAT.

To that end, Stenovations has a few dictionaries available for download on their site:

[https://www.stenovations.com/support/downloads]

There used to be more:

[http://web.archive.org/web/20090803214205/http://www.stenovations.com/Downloads.html]

... which, of course, you can only open with their Dictionary Maintenance program, which I actually have, running under Wine.

Anyway, using one of those dictionaries that have been converted into .rtf format as a source for suggestions might be useful if one is looking for a shorter outline for a word or phrase than whatever is already in your theory dictionary.

Of course, you would need a way to distinguish the suggestions from the unused dictionaries vice the dictionaries that are in use, so perhaps that could be solved by color -- green for outlines from dictionaries that are used in translation, and red for those that are not.

For folks that are colorblind, it might be good to have those color selections configurable by the user.

A really cool thing, though, would be a "droplet" program, like Stuffit Expander, where the user could drop a dictionary from any CAT program and have it converted to either .rtf or .json, but that's another suggestion for another day.

**Comment by benoit-pierre** [comment]
Enabling/disabling dictionaries is now supported
