### ISSUE TITLE
Use case when retro-insert space command cause Plover to stop working

### ISSUE THREAD

**Issue by jaskoo80** [openstenoproject/plover#496]
Classification: Bug

Reproducibility: Always

## Summary

Plover stops working after when using a retro-insert space command after the word "postmortem"

## Steps to Reproduce

1. Stroke "postmortem" - (POEFT/PHOR/TEM)
2. Stroke "{\*?}" - (S\*PD) // this is how I defined my retro-insert space command

## Notes

I've tried the same command after other words written with 2 stroke (e.g. catalogue), 3 strokes (e.g. confidence), with a prefix and a 2 stroke (e.g. unreliable) and so on and the command work fine. Somehow it's just something with the word "postmortem"

Attached stroke logs below for words "catalogue" and "postmortem" for comparison. 
Note that my retro-insert space is defined as "S*PD"

```
Stroke(K- A- -T)
Translation(('KAT',) : cat)
Stroke(H- R- O- -G)
*Translation(('KAT',) : cat)
Translation(('KAT', 'HROG') : catalogue)
Stroke(S- * -P -D)
*Translation(('KAT', 'HROG') : catalogue)
Translation(('S*PD',) : cat log)

Stroke(P- O- -E -F -T)
Translation(('POEFT',) : post)
Stroke(P- H- O- -R)
Translation(('PHOR',) : more)
Stroke(T- -E -P -L)
*Translation(('POEFT',) : post)
*Translation(('PHOR',) : more)
Translation(('POEFT', 'PHOR', 'TEPL') : postmortem)
Stroke(S- * -P -D) <-- (Plover stops working after this until I refresh the TX Bolt protocol)
```

## Configuration

OS: Mac OS X El Capitan
Plover release: 3.0.0
Writer: Elan Cybra
Protocol: TX Bolt

**Comment by morinted** [comment]
I'll take a guess and say that this is happening because "TEPL" isn't defined and the code freaks out.
