### ISSUE TITLE
fix keyboard layout handling on OSX

### ISSUE THREAD

**Issue by benoit-pierre** [openstenoproject/plover#533]
It seems that some layouts are not correctly handled, e.g. Qwertz when using accented letters like "à". We should:
- [x] check if dead keys are correctly detected
- [x] change its `__main__` code to dump the resulting layout detection on stdout to make it easier to debug such issues
- [x] rename `oslayer/mac_keycode.py` to `oslayer/osxkeyboardlayout.py` for consistency
- [x] handle OSX layout changes
- [x] `key_combo.CHAR_TO_KEYNAME` must be used in `oslayer/osxkeyboardcontrol`, `LITERALS` should be removed (not used anymore)

**Comment by morinted** [comment]
> "*U/TKREUT/KAOUT": "{>}{&ú}" just leaves the accent. á and à work as expected.

**Comment by morinted** [comment]
The Qwertz issue came from the fact that Qwertz maps
