### ISSUE TITLE
Capitalization after a period doesn't work

### ISSUE THREAD

**Issue by Geremia** [openstenoproject/plover#556]
Classification: Bug

Reproducibility: Always

## Summary

I can't get capitalization after a period to work. I put a period+space, and it doesn't auto-capitalize the first letter of the next word after the period+space. It doesn't matter if I check "Start Capitalized" in the prefs or not.

## Steps to Reproduce

{.} is my entry. I tried {^.}{-|}, too, but to no avail.

Also, Dvorak is set as my system's default keyboard layout. I changed it to the regular US layout. Still, it doesn't auto-capitalize.

## Version

Plover version weekly-v3.0.0+80.gdc7ccc3
Installed via GitHub source of weekly-v3.0.0+80.gdc7ccc3

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, provide it here.

## Configuration

OS:

- If it's OS X,
  go to Finder, Apple menu, "About This Mac".
  - Alternatively, if you're comfortable with the Terminal, run
    `sw_vers` and paste the output.

- Linux,
  Slackware-current (14.2)
  relevant to Plover's operation: KDE Plasma
**I do not get this bug running XFCE4.**
  - uname -a: Linux alan 4.4.14 #2 SMP Fri Jun 24 13:38:27 CDT 2016 x86_64 Intel(R) Core(TM) i3 CPU       U 330  @ 1.20GHz GenuineIntel GNU/Linux

I've satisfied these reqs from requirements.txt:

> pytest
> setuptools
> pyserial>=2.6
> appdirs>=1.3.0
> hidapi
> mock
> pyobjc-core>=3.0.3; "darwin" in sys_platform
> pyobjc-framework-Cocoa>=3.0.3; "darwin" in sys_platform
> pyobjc-framework-Quartz>=3.0.3; "darwin" in sys_platform
> wxPython>=3.0; "darwin" in sys_platform
> python-xlib>=0.14; "linux" in sys_platform
> wxPython>=3.0; "linux" in sys_platform
> pywin32>=219; "win32" in sys_platform

**Comment by benoit-pierre** [comment]
Qt5 apps don't take into account the modifiers state in our simulated key press/release events, can you confirm this only happen with Qt5 applications?

**Comment by Geremia** [comment]
@benoit-pierre It only happens when I use the KDE Plasma window manager, which is Qt5. I don't get the issue in other WMs like XFCE4. This issue is indeed specific to KDE Plasma.

**Comment by benoit-pierre** [comment]
Which window manager you use should have no impact, only whether each application is Qt5 based or not. So you should see the problem when using Kwrite under XFCE4, but not with Gedit under KDE. Anyway, you can try my [incubation branch](https://github.com/benoit-pierre/plover/tree/incubation), which works fine with Qt5 applications. Note that you'll need to use the python-xlib [development version](https://github.com/python-xlib/python-xlib).

**Comment by Geremia** [comment]
@benoit-pierre I was typing into the same application, Konsole 16.04.2 (Qt 5.6.1 (built against 5.6.1)) in both KDE Plasma and XFCE4.

**Comment by benoit-pierre** [comment]
mmm, weird. Did you have something like IBus running in one and not the other?

**Comment by morinted** [comment]
Should be fixed in master with #558 getting merged. Please verify @Geremia
