### ISSUE TITLE
Plover undistributable due to license conflicts

### ISSUE THREAD

**Issue by hlieberman** [openstenoproject/plover#560]
Classification: Bug

Reproducibility: Always

## Summary

Plover contains software with incompatible licenses.

## Steps to Reproduce
As part of packaging Plover for inclusion in Debian, I found a license incompatibility that renders Plover (in my opinion) undistributable.

The majority of Plover is licensed under the GPLv2 (not the GPLv2 or any later license).  However, the file plover/oslayer/mac_keycode.py is taken from a project PyUserInput, which is licensed under the GPLv3.  The GPLv2 and GPLv3 are not compatible, as per the Free Software Foundation.  (Normally, this is not an issue, as most code licensed under GPLv2 is actually licensed under "the GPLv2, or any later license).

## Version

master

**Comment by hlieberman** [comment]
Resolution of #336 would potentially help here, if we can get the permission of all copyright holders.

**Comment by morinted** [comment]
@hlieberman Will you be able to package the next released version of Plover now that the license conflict has been resolved?

**Comment by hlieberman** [comment]
Yes, I will. The Debian packaging is basically complete, minus a few finishing touches. I should be able to submit it to Debian a couple days after the next release. It'll take another week or so to go through the ftpmasters' checks the first time, but, all in all the turn around sound be fairly fast.
