### ISSUE TITLE
Latest build on Mac: Icon bounces up and down a little, then nothing.

### ISSUE THREAD

**Issue by tkpwaeub** [openstenoproject/plover#573]
Classification: Crash/Hang/Data Loss

Reproducibility: Always

I just installed the latest weekly build, and then when I start Plover, I first get this message:

![screen shot 2016-08-07 at 2 04 06 pm](https://cloud.githubusercontent.com/assets/12265250/17464223/dede3e0e-5ca7-11e6-98d1-d7b8e862d3f3.png)

When I select "Open" the icon bounces up and down a few times, then nothing happens.

**Comment by morinted** [comment]
Some questions:

- Did you drag the application into the Applications folder first?
- What version of OS X are you running?
- What sort of output do you get if you try running the .app from the command-line? E.g. `./plover.app/Contents/MacOS/Plover`

**Comment by avh4** [comment]
I am having the same problem.  If I run `/Applications/plover.app/Contents/MacOS/Plover`, the Plover starts, and prints this in the terminal:

```
Sep  3 21:14:36  Plover[58822] <Notice>: 2016-09-03 21:14:36,589 [MainThread] ERROR: engine initialization failed
Sep  3 21:14:36  Plover[58822] <Notice>: Traceback (most recent call last):
Sep  3 21:14:36  Plover[58822] <Notice>:   File "plover/gui/main.pyc", line 241, in __init__
Sep  3 21:14:36  Plover[58822] <Notice>:   File "plover/app.pyc", line 37, in init_engine
Sep  3 21:14:36  Plover[58822] <Notice>:   File "plover/app.pyc", line 57, in update_engine
Sep  3 21:14:36  Plover[58822] <Notice>:   File "plover/app.pyc", line 179, in set_machine
Sep  3 21:14:36  Plover[58822] <Notice>:   File "plover/machine/keyboard.pyc", line 56, in start_capture
Sep  3 21:14:36  Plover[58822] <Notice>:   File "plover/oslayer/osxkeyboardcontrol.pyc", line 228, in __init__
Sep  3 21:14:36  Plover[58822] <Notice>: Exception: Enable access for assistive devices.
```

I do have Plover added in the System Preferences:

<img width="780" alt="screen shot 2016-09-03 at 9 19 21 pm" src="https://cloud.githubusercontent.com/assets/1222/18229016/23f40fd0-721c-11e6-9e67-0114b420cbba.png">

This is on OS X 10.11.6

**Comment by morinted** [comment]
@avh4 You need to re-add every new download of Plover to accessibility settings. It may help to remove the old entry and add the weeklies.

@tkpwaeub I'm afraid I don't have enough information without filling in the issue template:

https://raw.githubusercontent.com/openstenoproject/plover/master/.github/ISSUE_TEMPLATE.md

It would also help if you can get the log output when you try running from the commandline. For example, place Plover.app into your folder and then run:

`cd ~`
`./Plover.app/Contents/MacOS/Plover`

**Comment by sammy-nes** [comment]
Hi,

I am new to the Plover community, and would like first to say thank you for providing such a nice program!
I have the same issues described, although for me I am running on the latest OS Sierra 10.12.
Same, when I launch the app, the icon bounces on the dock and then disappears, with the following window:

..............
Traceback (most recent call last):
  File "/Applications/plover.app/Contents/Resources/main.py", line 84, in main
  File "plover/gui/main.pyc", line 47, in __init__
  File "wx/_core.pyc", line 8628, in __init__
  File "wx/_core.pyc", line 8196, in _BootstrapApp
  File "plover/gui/main.pyc", line 55, in OnInit
  File "plover/gui/main.pyc", line 228, in __init__
  File "plover/gui/main.pyc", line 368, in __init__
  File "plover/oslayer/osxkeyboardcontrol.pyc", line 310, in __init__
  File "plover/oslayer/osxkeyboardlayout.pyc", line 128, in __init__
  File "plover/oslayer/osxkeyboardlayout.pyc", line 150, in _update_layout
  File "plover/oslayer/osxkeyboardlayout.pyc", line 251, in _get_layout
  File "plover/oslayer/osxkeyboardlayout.pyc", line 441, in _parse_layout
KeyError: 1
.................


Any leads about that?

**Comment by benoit-pierre** [comment]
@sammy-nes: it looks like something goes wrong when trying to parse you're keyboard layout. Can you open a new issue with the relevant information (Plover version, keyboard layout being used)?

**Comment by morinted** [comment]
You may have to change to a Qwerty/US layout to use Plover for now. This is
a bug with symbolic languages like Korean and Japanese.
