### ISSUE TITLE
Plover being stuck in Raw Stroke Output mode

### ISSUE THREAD

**Issue by Tarmean** [openstenoproject/plover#576]
Classification: Bug

Always

## Summary

Plover outputs raw stroke notation for the stroke field in the Add Translation popup. If you exit from there with the {#return} stroke without writing anything plover will only output stroke notation until restarted.

## Steps to Reproduce

With the default dictionaries, enter these strokes:

DUPT
R-R

## Expected Results

Plover closes the popup and resumes normal output.

## Actual Results

Plover closes the popup and gets stuck in stroke notation output.

https://zippy.gfycat.com/JadedScrawnyHoiho.webm

## Version

Plover version 3.0.0+233.gf80a928 

## Configuration

OS: Win 10, 64 bit with prebuilt plover bin

**Comment by davidkitfriedman** [comment]
The issue doesn't seem to occur for me. 

I'm also using Windows 10, 64 bit.

Tried with <a href="https://github.com/openstenoproject/plover/releases/tag/v3.0.0">Plover 3.00</a> and also <a href="https://github.com/openstenoproject/plover/releases/tag/weekly-v3.0.0%2B199.g2396c74">Plover 3.00+199.g2396c74</a>.

**Comment by morinted** [comment]
Could you confirm this still happens in https://github.com/benoit-pierre/plover/releases/tag/ui_preview_4 @Tarmean ?

**Comment by Tarmean** [comment]
Tried it with the 64bit windows binary, still happens every time with that version. 

Seems like there is a timing issue, should I try to reproduce it on a different machine?

**Comment by benoit-pierre** [comment]
Should be fixed in the next new UI preview, @Tarmean: can you confirm [this build works](https://ci.appveyor.com/api/buildjobs/tymw68f93gfkm6y3/artifacts/dist%2Fplover-3.0.0%2B267.gd157e39-py3.exe)?

**Comment by Tarmean** [comment]
Thanks, that fixed it. Awesome work!
