### ISSUE TITLE
Definable Delete Stroke

### ISSUE THREAD

**Issue by SamuelBelli** [openstenoproject/plover#578]
Classification:  Feature (NEW)

Reproducibility: N/A
## Summary

to create a way that we would be able to define our own delete  stroke or have multiple strokes.

**Comment by morinted** [comment]
Syntax-wise, I think a good way to accomplish this would just be a `{DELETE}` command like Eclipse does. In the RTF format, it looks like `\cxdstroke`. Alternatively, if `{*}` is free, we could use that, too, but it doesn't map well to other chorded systems.

**Comment by morinted** [comment]
This has been implemented in master by setting a translation to `=undo`!
