### ISSUE TITLE
System hangs on "sudo apt-get install plover"

### ISSUE THREAD

**Issue by stevenbhardwaj** [openstenoproject/plover#595]
Classification: Hang (during install)
Reproducibility: Always (on this computer)
Summary: System hangs on "sudo apt-get install plover"

## Steps to Reproduce:
1. I installed the latest ppa
2. sudo apt-get update
3. sudo apt-get install plover

## Expected Results
4. Install should finish and I can run plover.

## Actual Results
5. See screenshot. System hangs.

## Version
Plover version: whatever auto-runs for Ubuntu from the latest ppa... 9/18/2016

## Notes
I'm still running (an older install) of plover on my other machines... it's literally a physical work-around!   ;)

## Configuration
Ubuntu 15.10
uname -a
Linux ideajy 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
![screenshot from 2016-09-18 18-45-29](https://cloud.githubusercontent.com/assets/22283410/18620405/6f584a10-7dd7-11e6-976b-d51bf7405b9e.png)

**Comment by benoit-pierre** [comment]
I really don't see how trying to install the Plover package could do that. Your screenshot shows another package is also being removed (`linux-image-...`), and the last traces are all related to that. Are you sure it's not just taking s'ome time? What if you remove said package first before attempting to install Plover again?

**Comment by stevenbhardwaj** [comment]
Gotcha, I'm trying the "apt-get remove", getting "error: cannot read '/dev/sdb': input/output error, running for 2 hours so far.

I'll leave it for another hour, then restart, just to see if it tanked the system. Regardless, I'll try a fresh ubuntu install and try again. :) 

Thanks for your response!!

![screenshot from 2016-09-19 15-26-00](https://cloud.githubusercontent.com/assets/22283410/18648670/4b94bdca-7e81-11e6-96fd-4fc738244e3a.png)

**Comment by benoit-pierre** [comment]
Is '/dev/sdb' where your root partition is located? Could be you're disk is dying... I'd check the health report with smartmontools: `sudo smartctl -H /dev/sdb`.

**Comment by stevenbhardwaj** [comment]
Wow! The "apt-get remove" finally worked after 4+ hours, and plover installed!

I'd never had a successful install take so long, but I also don't have all that extensive Linux knowledge. Now I know to give it more time.

And hey, I'm super glad to have the ppa that makes it all work so smoothly! Thanks again benoit-pierre! :dancers: 

Cheers,
Steven

**Comment by benoit-pierre** [comment]
4+ hours is not normal, I would definitively investigate those input/output errors on `/dev/sdb`.

**Comment by stevenbhardwaj** [comment]
Interesting. Thanks for the tip! I'm reading up, and will likely replace the hard disk. And here's a somewhat relevant cartoon! :)

![](http://imgs.xkcd.com/comics/datacenter_scale.png )
