### ISSUE TITLE
auto-detect writer connection state

### ISSUE THREAD

**Issue by tschulte** [openstenoproject/plover#596]
Classification: Usability, Enhancement

Reproducibility: Not Applicable
## Summary

Plover currently does not automatically discover if a serial device like the Stenoboard or ErgoDox in TX Bolt mode is disconnected and reconnected again or if the laptop comes back from standby.
## Steps to Reproduce
1. Unplug the device and plug it in again
2. or close the notebook (goes into standby) and reopen it again
## Expected Results
1. In both cases, the steno device should work again
## Actual Results
1. When unplugged and plugged in again, nothing works, hitting the refresh-button in plover does not work. I have to unplug again, hit refresh (plover discovers the device is disconnected), plug the device in again, hit refresh again.
2. When the laptop comes back from standby, I have to hit the refresh button once to get it working again.
## Version

Plover commit 244f590 (current master)
## Notes

I tried adding a timer to call _reconnect every couple of seconds, but I don't know if this is the right approach. 

I think the problem in scenario 1 is that plover still has the device (/dev/ttyACM0 in my case) "open". When the device is plugged in again, it therefore gets assigned the next free device /dev/ttyACM1. Hitting refresh in plover releases the handle to /dev/ttyACM0 again, thus allowing that name to be taken on the next plug in of the device.
## Configuration

OS: Linuxmint 17.2 Cinnamon

**Comment by morinted** [comment]
When the device "disconnects", do you get an exception? I get read exceptions on OSX.

**Comment by tschulte** [comment]
Yes, I get

```
Exception in thread Thread-1-machine:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/tobias/projects/steno/plover/plover/machine/txbolt.py", line 74, in run
    raw = self.serial_port.read(max(1, self.serial_port.inWaiting()))
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 475, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

**Comment by morinted** [comment]
On Windows it works because the device comes back to the same COM port
often. Maybe on linux/Mac we should treat this exception as a disconnect.

**Comment by tschulte** [comment]
I get the same exception after standby. Handling this exception for disconnecting would solve half the problem. But for reconnecting there still needs to be some other mechanism. Maybe polling only while disconnected would do the trick.

**Comment by morinted** [comment]
Is it viable to poll? What if the device serial port changes? For example, with Bluetooth connections.

**Comment by tschulte** [comment]
You mean if it changes from /dev/ttyACM0 to ttyACM1? Isn't this what issue #135 is all about? This issue is about detecting unplug and plug on the same port.

By the way, I just tested with my ErgoDox in TX Bolt mode on Windows 7. It is nearly the same behavior: although the port seems to come back as the same COM number, it is not working. I have to click refresh in plover, unplug and plug the ErgoDox, only then I can click refresh again.

**Comment by morinted** [comment]
Good to know. I'd argue that most useful initially would be properly
handling the disconnect state -- reconnect could come later. It's easier
with the Treal or Stenograph because finding a USB device doesn't have an
address in the same way that a COM or serial port does.

I'm not opposed to a reconnecting state for serial, but I do worry slightly
that it would be annoying to users if it is too aggressive. Maybe we could
limit the reconnect time to something like 30 tries one second apart, which
would handle the case where the machine sleeps.

**Comment by tschulte** [comment]
I see, in treal.py there is already some code to handle reconnect. I tried to refactor the code, moving the reconnect code from treal.py to base.py. The disconnect is now automatically discovered, but it does not reconnect. Maybe this is because I am not fluent in python, and my Java understanding of exception handling might not match Pythons exception handling.

Please see https://github.com/tschulte/plover/commit/efb8e7441960f61921630bce808639c9f3e7ca2f.

**Comment by tschulte** [comment]
I could not work on this for some days, because suddenly plover did not run any more on my machine. It took me 12 days to figure out `git clean -fdx` would do the trick -- I think this was due to switching between master and my branch. Beginner error, I think.

Any ways. I had one tiny error. Now reconnect works. I'm not sure if I did everything correctly for Stentura and treal, though. And the tests for Stentura are broken due to my changes.

And you are right. The current approach might be too aggressive. I will limit the reconnect tries and maybe increase the ping interval. Also the logging while disconnected and retrying needs some work. Currently every retry results in a new popup message.

Could you please review my changes so far and give me feedback if my changes are going in the right direction and what you think I should change.

https://github.com/tschulte/plover/commits/auto-reconnect-writer

**Comment by tschulte** [comment]
Both TxBolt and Stentura set the `timeout` on connect, doesn't this mean, the timeout in the settings dialog is defunct?

**Comment by benoit-pierre** [comment]
> Both TxBolt and Stentura set the timeout on connect, doesn't this mean, the timeout in the settings dialog is defunct?

A change in the machine options is handled by the engine: the machine will be automatically reconfigured (by stopping the current capture and starting a new one with the updated parameters).

For TX Bolt, the user set timeout is ignored; as timeout handling is part of the protocol (a timeout on read is one way of detecting the end of a stroke).

**Comment by mulka** [comment]
I'd also like this feature. I'm using Stenomod with the TX Bolt protocol.

**Comment by tschulte** [comment]
I finally found some time to have a look at this again. I tried to port the basic idea of that pull request over to the new code base. I found `SerialStenotypeBase._iter_packets()` to be a good candidate to have this functionality. Gemini and procat already use that method. I could successfully change txbolt and passport to use that function as well (by using `1` as packet_size). I just left stentura alone, because it is the only driver that is completely different.

But: 

> For TX Bolt, the user set timeout is ignored; as timeout handling is part of the protocol (a timeout on read is one way of detecting the end of a stroke).

Is this really true. I also saw the code handling this, but is it really necessary to check for the timeout here? At least with my devices it still works when using `_iter_packets()`.

**Comment by tschulte** [comment]
But the main problem is that the machines do not catch any exceptions in the `run()` method. When there is an error, the thread just dies and an exception is logged to the console.

Either we make sure that every machine does catch exceptions in their run method, or we automatically discover if the thread is not running any more but should be running and close the com port and set the state to errror. And the engine (as proposed in the pull request) does handle the reconnect. Or can this even be outsourced to a plugin?

**Comment by tschulte** [comment]
I created a pull request that enables plover to notice the connection lost.

Additionally I created a plugin (https://github.com/tschulte/plover_auto_reconnect_machine) that will automatically reconnect as soon as the steno machine gets connected.

I think that is the best approach to not put the reconnect logic in plover but have it in a plugin and keep the plover engine as it is.

Please have a look at the pull request and test the plugin. It only works with the mentioned pull request applied. I have only tested it on Linux so far.

**Comment by tschulte** [comment]
This issue was marked as low-priority and post-4.0. But it seems it is important enough, that other people create workarounds/hacks for it: https://twitter.com/stenoblog/status/1157379149251694592.

Do you really want this to be post-4.0?

**Comment by morinted** [comment]
Certainly not a bad feature to have!

It wouldn't be considered a breaking change (warranting an increment from
4.x to 5.x) upon its inclusion -- that's all that determines whether
something "has" to be in 4.0 👍

**Comment by tschulte** [comment]
Ah, that makes sense. Thanks for the clarification.
