### ISSUE TITLE
Space applied before period after -S when space added "after" output

### ISSUE THREAD

**Issue by codepoke-kk** [openstenoproject/plover#606]
Classification: Bug

Reproducibility: Always
## Summary

When finishing the last word in a sentence with -S, typing TP-PL allows a space between the s and .
## Steps to Reproduce

Enter KWEGS/-S/TP-PL
## Expected Results

questions.
## Actual Results

questions . 

If helpful, submit screenshots of the issue to help debug. Your `plover.log` or `strokes.log` may also be useful.
## Version

Plover version weekly-v3.0.0+266.g9487982
Plover 3.0.0+100gc240d71

Installed via: git weekly
## Notes

Problem only occurs if space is added "after" output
## Configuration

OS:
Windows 7

**Comment by benoit-pierre** [comment]
Blackbox test:
```python
    def test_bug606(self):
        for steno, translation in (
            ('KWEGS', 'question'),
            ('-S'   , '{^s}'    ),
            ('TP-PL', '{.}'     ),
        ):
            self.dictionary.set(normalize_steno(steno), translation)
        self.formatter.set_space_placement('After Output')
        for steno in (
            'KWEGS',
            '-S',
            'TP-PL',
        ):
            stroke = steno_to_stroke(steno)
            self.translator.translate(stroke)
        self.assertEqual(self.output.text, u'questions. ')
```

**Comment by benoit-pierre** [comment]
Fixed in master.
