### ISSUE TITLE
Windows 7: Plover - system tray option?

### ISSUE THREAD

**Issue by p2635** [openstenoproject/plover#626]
Classification: UI/Usability

## Summary

Not sure if this has been logged already, but it would be useful to be able to minimize plover into the system tray.

## Version

Plover version 3.0.0.
Installed via: download from openstenoproject.org,

**Comment by benoit-pierre** [comment]
The new UI as support for that, the most recent development build for Window is available [here](https://ci.appveyor.com/project/morinted/plover/branch/master/job/2q54rw9p9rnaj5o9/artifacts).

**Comment by p2635** [comment]
as long as its in progress I don't mind, I'll close this
