### ISSUE TITLE
Custom Mac layout makes Plover crash

### ISSUE THREAD

**Issue by sammy-nes** [openstenoproject/plover#627]
Classification: Crash/Hang/Data Loss

Reproducibility: Each time I open Plover with a custom keyboard layout made with Ukelele
## Summary

I have Plover crashing right after Plover icon bounces on the dock when **I have a custom keyboard layout enabled** (all in latin languages)
I have created a custom layout with Ukelele because I have my own keycaps arrangements on my keyboards. Same bug when when I launch it with some other pre installed non latin language layouts like Japanese, but some non latin language layouts works fine like Gurmukhi. 

When I enable any other latin pre installed layout it opens flawlessly.

<img width="805" alt="2016-10-22 17 40 37" src="https://cloud.githubusercontent.com/assets/22985030/19618213/bd66eeac-987e-11e6-86ce-37fd7d907cd0.png">

Thank you for your kind help
## Version

Plover version  v3.0.0+266.g9487982
## Configuration

OS: Mac Sierra 10.12

**Comment by benoit-pierre** [comment]
Thanks, can you share the file for your custom layout?

**Comment by sammy-nes** [comment]
Sure, here is the keyboard layout I am using. It is in the Library/Keyboard Layouts folder

[francemaster.keylayout.zip](https://github.com/openstenoproject/plover/files/545712/francemaster.keylayout.zip)

**Comment by morinted** [comment]
Could you share this layout so that I can test it?

**Comment by morinted** [comment]
Hi @sammy-nes -- I added code to fallback if we fail to read the keyboard layout (at the very least, prevents a crash!) -- would you try it? https://github.com/openstenoproject/plover/pull/724

I suspect key combos will fail to work (`{#command(c) command(v)}`). Maybe I can dig deeper and get something working.

**Comment by morinted** [comment]
I think keyboard shortcuts will work now, too.
