### ISSUE TITLE
"Return" commands do not work at all.

### ISSUE THREAD

**Issue by paholg** [openstenoproject/plover#632]
Classification: Bug

Reproducibility: Always

## Summary

I cannot get plover to emit a return command. Everything else seems to work fine, it's just "return" that is giving me trouble.

## Steps to Reproduce

1. Issue any of the commands in `commands.json` that contain `Return`: TPHEPBT,  SKWRAEURBGS, SKWRAURBGS, SKW-BGS, R*R, or R-R.

## Expected Results

1. Return presses should be registered!

## Actual Results

1. Nothing. Well, if issued after a word, the space after that word will be deleted. But nothing else.

As you can see here:

![](http://i.imgur.com/ja40zrz.png)

The commands are defined in `commands.json` and plover registers them, but it doesn't output anything. The suggestions display contains only the one that I mistyped.

## Version

Plover version 3.0.0

Obtained from the Arch User Repository.

## Notes
If I type "R-R" into `xev`, a tool that  prints the contents of X events, this is the output:

```
FocusOut event, serial 34, synthetic NO, window 0x2600001,
    mode NotifyGrab, detail NotifyAncestor

FocusIn event, serial 34, synthetic NO, window 0x2600001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 34, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   2   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyRelease event, serial 34, synthetic NO, window 0x2600001,
    root 0x1eb, subw 0x0, time 2639523, (2029,812), root:(2029,834),
    state 0x10, keycode 57 (keysym 0x6e, n), same_screen YES,
    XLookupString gives 1 bytes: (6e) "n"
    XFilterEvent returns: False

MappingNotify event, serial 34, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

FocusOut event, serial 34, synthetic NO, window 0x2600001,
    mode NotifyGrab, detail NotifyAncestor

FocusIn event, serial 34, synthetic NO, window 0x2600001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 34, synthetic NO, window 0x0,
    keys:  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
```

As far as I can tell,  the `FocusIn`, `FocusOut`, and `KeymapNotify` events are just Plover doing its thing. I'm not sure what `MappingNotify` is, and I haven't seen it show up in any other plover output.

Really strange to me is that I'm getting a key release event for the key "n". It's not always there, and sometimes it's "b" instead, but when present it's always a key release event with no accompanying key press event.

 
## Configuration

OS: Arch Linux.

    $ uname -a
    Linux box 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux

I am using the xmonad window manager with no desktop environment.

Edit: I have just tested using xfce instead of xmonad and the issue persists, so it's almost certainly not xmonad doing something weird.

**Comment by benoit-pierre** [comment]
There has been a number of changes since 3.0.0, including switching to Xinput. I just updated the [AUR git package](https://aur.archlinux.org/packages/plover-git/), can you try with that?

**Comment by benoit-pierre** [comment]
Note: make sure `commands.json` is updated (remove it, and Plover will recreate it from its internal version).

**Comment by paholg** [comment]
Ah, I probably should have verified that I was on the newest version. Oops.

Anyway, that fails with this error:

```
❯❯ plover                                                                                                                                                                                                   12:10:05
Unexpected error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/plover/main.py", line 72, in main
    code = gui.main(config)
  File "/usr/lib/python2.7/site-packages/plover/gui_qt/main.py", line 112, in main
    app = Application(config, use_qt_notifications)
  File "/usr/lib/python2.7/site-packages/plover/gui_qt/main.py", line 31, in __init__
    from plover.gui_qt.main_window import MainWindow
  File "/usr/lib/python2.7/site-packages/plover/gui_qt/main_window.py", line 14, in <module>
    from plover.gui_qt.main_window_ui import Ui_MainWindow
ImportError: No module named main_window_ui
```

I tried also cloning the github repo and running from there, but that fails too:
```
❯❯ ./setup.py launch                                                                                                                                                                                        12:12:55
running launch
running build_py
running egg_info
writing plover.egg-info/PKG-INFO
writing dependency_links to plover.egg-info/dependency_links.txt
writing entry points to plover.egg-info/entry_points.txt
writing top-level names to plover.egg-info/top_level.txt
writing requirements to plover.egg-info/requires.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'plover.egg-info/SOURCES.txt'
/usr/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 490, in <module>
    **kwargs
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "./setup.py", line 134, in run
    with self.project_on_sys_path():
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "./setup.py", line 87, in project_on_sys_path
    pkg_resources.require('%s==%s' % (ei_cmd.egg_name, ei_cmd.egg_version))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 852, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'hidapi' distribution was not found and is required by plover
```
while i have `hidapi`:
```
❯❯ pacman -Ss hidapi                                                                                                                                                                                        12:14:52
community/hidapi 0.8.0rc1-2 [installed]
    Simple library for communicating with USB and Bluetooth HID devices
community/python2-hidapi 0.7.99.19-1 [installed]
    A Cython interface to the hidapi from signal11/hidapi
```

Although I find it interesting that the AUR package seems to use python2 while this uses python3.

**Comment by benoit-pierre** [comment]
Sorry about the error with the AUR package, looking into it. And yes, it does still uses Python 2 because there's no `python-hidapi` available. If you want to run from source (using Python 3), check `linux/README.md` for instructions.

**Comment by benoit-pierre** [comment]
I fixed the AUR package if you want to give it another go.

**Comment by paholg** [comment]
That fixed, it thanks so much!
