### ISSUE TITLE
ContextualVersionConflict with Python-xlib using Ubuntu 16.04

### ISSUE THREAD

**Issue by Elktro** [openstenoproject/plover#639]
Classification: Bug, Crash
Reproducibility: Always

## Summary

Cannot start or test the plover version bfb4849cd9d23f65e6bae886185c96b292755a25 with Ubuntu 16.04 

$uname -a

Linux triton 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

## Steps to Reproduce

1. Get the plover version bfb4849cd9d23f65e6bae886185c96b292755a25
2. Run ./tests.sh or./launch.sh

This results to error:

$./launch.sh 
running launch
running build_py
running egg_info
writing entry points to plover.egg-info/entry_points.txt
writing plover.egg-info/PKG-INFO
writing requirements to plover.egg-info/requires.txt
writing dependency_links to plover.egg-info/dependency_links.txt
writing top-level names to plover.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'plover.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 494, in <module>
    **kwargs
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "./setup.py", line 134, in run
    with self.project_on_sys_path():
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "./setup.py", line 87, in project_on_sys_path
    pkg_resources.require('%s==%s' % (ei_cmd.egg_name, ei_cmd.egg_version))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-xlib 0.14 (/usr/lib/python3/dist-packages), Requirement.parse('python-xlib>=0.16'), {'plover'})

I tried to fix the issue by installing the latest version of xlib from: https://pypi.python.org/pypi/python-xlib#downloads

But after installing it, I got the same error.

**Comment by benoit-pierre** [comment]
How did you install the new python-xlib? Did you follow the instructions in `linux/README.md`?

**Comment by Elktro** [comment]
After following the instruction in linux/README.md, I was able to run the plover using the ./launch.sh.

It is a bit misleading that there is several readme-files that do not refer each other. I just read the README.rst in the root directory.

**Comment by morinted** [comment]
Thanks for the feedback. I do plan on rewriting the readme to address this,
among other issues.
