### ISSUE TITLE
Suggested words to abbreviate

### ISSUE THREAD

**Issue by KelseyHigham** [openstenoproject/plover#64]
I dunno if this is something done by traditional stenotype systems, but since Plover knows every word that passes through it, it occurs to me that it could log them, figure out which keystroke-heavy words are typed most often, and suggest that they be abbreviated. Right now, typists can try to minimize keystrokes if they notice words that bother them, but a computer can probably do it better.

(Fun fact: My X4 hasn't actually arrived yet! I don't actually know whether this solves a real problem. I'm more asking because I feel like it would bring peace of mind — I know that one key for being a good stenographer is to maintain your dictionary, so I think it'd be neat if my computer could help me with that.)

**Comment by morinted** [comment]
This is in progress with the training tools.
