### ISSUE TITLE
Feature Request: command to show/hide suggestions window

### ISSUE THREAD

**Issue by JasonWoof** [openstenoproject/plover#645]
Classification: Feature (New)

## Summary

Plover command to toggle visibility of suggestions window.

## Use description/case

1. I map a stroke to {PLOVER:SUGGESTIONS_WINDOW} or some such.
2. I stroke said stroke and the suggestions window opens.
3. I stroke it again later and the suggestions window closes.

**Comment by morinted** [comment]
I think that each GUI tool should optionally be able to define a command name for bringing to front. Thoughts, @benoit-pierre ?

Though, I would make it so that {PLOVER:SUGGESTIONS_WINDOW} only raises the window → to close it you would raise/focus it, then press escape (this is how add translation and look up currently work)

**Comment by JasonWoof** [comment]
"raising" doesn't do anything on my system. I use a tiled window manager. I don't see the point of a window being "open" if you can't see it. From a user perspective, I can see it or I can't. Hiding it behind other windows is no different to me than it being closed.

I've mostly stopped using the suggestion window because I got sick of moving it around with the mouse.

I just want to be able to assign a stroke to show suggestions, and a stroke to hide it (could be the same stroke again, or one for closing windows)

**Comment by morinted** [comment]
Is it not true that "raising" the window would focus it so that you could close it with `{#Escape}`?

**Comment by JasonWoof** [comment]
No, raising is ignored. The "raising" approach might have problems on other systems/setups when the suggestions window is open, but not in the current workspace. I've been leaving mine open in a different workspace.
