### ISSUE TITLE
Output slow down on macOS

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#648]
Performance

Reproducibility: Rarely

## Summary

Depending on my system, maybe it's to do with charging and battery life, it seems that app nap catches just the keyboard output somehow, and the output responds very slowly while the paper tape still functions at regular speed.

## Steps to Reproduce

1. Run Plover on Mac
2. After a while, output might start to slow down

## Version

Plover version: new UI off master.

## Suggestion

I was able to fix by adding app nope to the initialization of OSX's KeyboardEmulation.

**Comment by benoit-pierre** [comment]
I though the AppNope stuff worked for the whole process, does this mean we need it for any thread we start? Is there a UI the user can use to whitelist applications? How does it work for other applications?

**Comment by morinted** [comment]
I think we can add something to the [NSList manifest])https://www.jamf.com/jamf-nation/discussions/10566/prevent-app-nap) -- though for development appnope works well for me.

I only posted this as a bug (not a PR), because like you, I thought that App Nap was process-wide. Yet, the results don't lie. A scenario: on TX Bolt, let's say I stroke "How are you?". There will be no response, and I'll think that maybe the machine disconnected, but then H will output, then a couple seconds, then o, then w, etc. I usually restart Plover to get it to work again. Reconnecting the machine doesn't fix it.

If I restart Plover, it happens again eventually, usually within ~5 minutes of writing. Then I added appnope to the layout thread and it never did it again.

**Comment by benoit-pierre** [comment]
OK, so does it work (development with `sudo ./launch.sh`, and generated app/dmg) with this patch:
```diff
diff --git i/launch.sh w/launch.sh
index b65cc1d..d483109 100755
--- i/launch.sh
+++ w/launch.sh
@@ -1,4 +1,11 @@
 #!/bin/sh
 
-cd "$(dirname "$(readlink -e "$0")")" &&
+set -ex
+
+cd "$(dirname "$(readlink -e "$0")")"
+case "$OSTYPE" in
+  darwin*)
+    defaults write org.openstenoproject.plover NSAppSleepDisabled -bool true
+    ;;
+esac
 exec ./setup.py launch -- "$@"
diff --git i/plover/main.py w/plover/main.py
index 0adb9fa..42f8adf 100644
--- i/plover/main.py
+++ w/plover/main.py
@@ -12,9 +12,6 @@ import sys
 import traceback
 import argparse
 
-if sys.platform.startswith('darwin'):
-    import appnope
-
 import plover.oslayer.processlock
 from plover.oslayer.config import CONFIG_DIR
 from plover.config import CONFIG_FILE, Config
@@ -60,8 +57,6 @@ def main():
     try:
         # Ensure only one instance of Plover is running at a time.
         with plover.oslayer.processlock.PloverLock():
-            if sys.platform.startswith('darwin'):
-                appnope.nope()
             init_config_dir()
             # This must be done after calling init_config_dir, so
             # Plover's configuration directory actually exists.
diff --git i/setup.py w/setup.py
index 294e795..601e2ae 100755
--- i/setup.py
+++ w/setup.py
@@ -239,11 +239,14 @@ class BinaryDistApp(PyInstallerDist):
         dictionary = tree.getroot().find('dict')
         for name, value in (
             # Enable retina display support.
-            ('key'   , 'NSPrincipalClass'),
-            ('string', 'NSApplication'   ),
+            ('key'   , 'NSPrincipalClass'  ),
+            ('string', 'NSApplication'     ),
+            ('key'   , 'NSAppSleepDisabled'),
+            ('true'  , None                ),
         ):
             element = Element(name)
-            element.text = value
+            if value is not None:
+                element.text = value
             element.tail = '\n'
             dictionary.append(element)
         tree.write(plist_info_fname)
```
?

**Comment by benoit-pierre** [comment]
I'd be interested to know if the problem happen when launching with `-g none` (using the current master without the above patch), as in: is it because of the use of `QThread`?

**Comment by morinted** [comment]
Running with no GUI right now to test it out. I had forgotten about this issue because I was running a branch with AppNope on the output thread.

**Comment by morinted** [comment]
Never slowed down without the GUI.
