### ISSUE TITLE
\n wrong backspacing

### ISSUE THREAD

**Issue by rbrewer123** [openstenoproject/plover#652]
Classification: bug

Reproducibility: always

## Summary

`\n\n` dictionary entry doesn't operate properly with `*` on plover 3.1.0 with "before" output spacing on Windows.

## Steps to Reproduce

1. add `"SKW": "\n\n"` to `user.json`
2. start plover 3.1.0 on windows
3. stroke "S/S/S/SKW"
4. stroke "*"

Cursor is now not in the expected position.

## Expected Results

Cursor should remove exactly the two newlines, and no more.  

## Actual Results

Instead, cursor ends up erasing one more character (I think).

## Version

Plover version 3.1.0 running on Windows 10.  Have also seen it with 3.1.0 on Windows 7.

Installed via: download from github release

## Notes

Tried using `\\n` in dictionary entry, which did not fix the problem.

## Configuration

OS: Windows 10

**Comment by morinted** [comment]
I'd be curious to know if you have better luck with {^\n\n^}

**Comment by rbrewer123** [comment]
That works.  My first version had a final `^` which still saw the problem.  I also tested with only the initial `^` and that works too.

**Comment by morinted** [comment]
Just tried this, seems fixed in the current master.
