### ISSUE TITLE
Silent build failure when pyqt-distutils is not installed

### ISSUE THREAD

**Issue by JasonWoof** [openstenoproject/plover#654]
Classification: bug

Reproducibility: Always

## Summary

setup.py continues is if nothing went wrong when it fails to find pyqt-distutils. But then if you try to run plover, it can't find modules for it's windows.

Specifically this code:

```
    try:
        from pyqt_distutils.build_ui import build_ui
    except ImportError:
        pass
```

Please, instead of just "pass", print a helpful error message, and (if setup.py was invoked with the "launch" command) exit.

Ditto for a few lines earlier where it tries to import PyQt5

I'm testing today's master branch on Debian unstable.

**Comment by benoit-pierre** [comment]
Closing: this is due to setuptools being too old, we now require `setuptools>=30.3.0`.
