### ISSUE TITLE
how to verify release download?

### ISSUE THREAD

**Issue by treaki** [openstenoproject/plover#655]
hi,

i want to try out your software, because i am not used to python and dont want to do any compiling and are happely using debian i thing the fastes way is to use ur deb package. I have been guided to your github release page but before i can start downloading there is something that i am missing. And that is a way of veryfining the download integrity. So i am used to have some hash files checksums along to binary file downloads that are digitaly signed using pgp so i can verify that youre software hasnt been modified on the way to my system. So please sign your releases so i can check them befor i install them.

thanks a lot in advance

security aware (maybe with a little bit, how to call it in english..., fetishism after what i have heard from Snowden and co.) german advanced computer user (say like this to do dont be misunderstood when using the term hacker to someone who dosent know what it mean particulary)

treaki

PS: sorry it seams like i cant write text anymore without any annotations (cause my head is full of thinks i have to explain about whats diffrent then most would susspect) and in proper engish less then ever ever because i have to lookup any third word/saying inside my dict(tionary) because of i dont am a good/native speaker as you may be)

**Comment by morinted** [comment]
I believe @benoit-pierre's PPAs are the only signed packages we have. https://launchpad.net/~benoit.pierre/+archive/ubuntu/plover

I'm not sure of Benoit Pierre's process for creating the `.deb` and whether it would be easy to add a signature and hash.

**Comment by benoit-pierre** [comment]
Closing in favor of #910.
