### ISSUE TITLE
Bug: Can't assign "C" on my keyboard to act as key on steno 

### ISSUE THREAD

**Issue by squarology** [openstenoproject/plover#667]
Bug

Reproducibility: Always

## Summary

I am trying to assign my "c" key on my keyboard to act as the first "T" on the steno board but I can't get it to work. I am assuming it simply clicks on "Clear" since whenever I type in "c" all the info is cleared.

## Steps to Reproduce

1. I click on "Configure"
2. I double-click a Steno Key/Action
3. I hit "c" on my keyboard
4. The info is cleared and c is not registered 

## Expected Results

5. I should be able to see +c beside "Keys for T-"

## Actual Results

5. Instead, I see "None".

## Version

Plover version 3.1.0

Installed via: https://github.com/openstenoproject/plover/releases/tag/v3.1.0

## Notes

I've tried holding shift and alt and using the arrow keys to change the focus to ok and cancel buttons but nothing has worked.

## Configuration

OS:

Windows 10 Pro, Version 1607

**Comment by morinted** [comment]
Can you make sure Plover's output is disabled and test again, please?

**Comment by squarology** [comment]
I made sure Plover's output was disabled and tested again but the result was the same: when I try assigning the "c" key on my keyboard to a Steno key, "None" appears.

**Comment by morinted** [comment]
In the default layout, c is A, have you unmapped that first? I'm assuming
you are on a qwerty layout.

**Comment by squarology** [comment]
I'm on a custom layout, and c is not mapped to any Steno Key currently.

**Comment by morinted** [comment]
Which key does c map to on a standard layout?

Can you share the keymap[keyboard] line of your plover.cfg? Should be in AppData\Local\plover\plover\

**Comment by squarology** [comment]
Well, I went back and changed my layout so that a "z" would be where the "c" was so that I could assign that key to a Steno key so it's not a problem that affects me anymore but for future reference people should know you can't assign "c" to a steno key.
