### ISSUE TITLE
Please allow normal key names with the number bar in strokes

### ISSUE THREAD

**Issue by JasonWoof** [openstenoproject/plover#672]
Classification: Feature (New)

## Summary

I just made a dictionary with all the number strokes I understand, and it was super-weird that it didn't work when I listed they key names in steno order like this:

    "#S": "1"

Please support that. It would be really confusing to move the number key mapping without this feature, and also without it, it's confusing to make miss-strokes for w ords with the number bar.

**Comment by morinted** [comment]
I think this used to be supported. I think to normalize, we'd have two options:

- Convert `#STKP` into `12K3`
- Convert `12K3` into `#STKP`

I think the second option bodes well for the ideal of de-magicifying steno. The number bar gets so much special treatment and maybe it shouldn't.

**Comment by JasonWoof** [comment]
I think of this as primarily a interface issue. I think that the ``DUPT`` dialog should be tolerant of ``#STKP`` just as the other input box in that form is tolerant of extra white space.

Don't get me wrong... I love the second version. it's just that I don't want this little interface clean-up to be held back because of that being a big decision or something. Also, I think both forms (``#S`` and ``1``) should be supported in the ``DUPT`` form regardless of what the canonical form is.

**Comment by JasonWoof** [comment]
Oops, I mean I like the first version (``#STKP`` or ``#S``)

**Comment by morinted** [comment]
Yeah, but the same code is used when loading and saving the dictionary. You
want to ensure that looking up #1, #S, and 1 all return the same entry.

**Comment by JasonWoof** [comment]
Yes, of course it should be canonicalized before saving or searching. I'm suggesting that a filter be used that converts the value in the DUPT dialog box to the canonical form before it's used (saved in this case) and other forms (like lookup?) that allow you to enter a stroke should probably have the same filter.

**Comment by morinted** [comment]
It should already work that way, if I'm understanding you correctly. It's
just that #S isn't being handled properly.

**Comment by JasonWoof** [comment]
Cool, sound like we are on the same page, I wasn't sure before.

**Comment by thumbquat** [comment]
Somewhat related, I was on the discord and someone said:

>are there any settings or plugins to show steno chords with the number bar as # plus the letters instead of showing numbers (in the Suggestions Window, Lookup, and Add Translation boxes and such)? Like #TA instead of 25

Made a quick branch here a few days ago:
[features/number-translations](https://github.com/thumbquat/plover/commit/44f5081c36bbd80d7408ed2d3ccd627887e3c428)

Was thinking about making a PR with it, but found this issue and am having second thoughts.

I feel like the _right_ solution is probably un-specializing the number bar entirely. Can think of some downside/side effects of that change though (namely: legacy expectations, migration of 1 => #S style dictionary entries).

Would be happy to take a look at the changes that would be necessary for that, however!

Thoughts?

**Comment by morinted** [comment]
I wish the number bar weren't so special. It does feel like a pretty huge
breaking change, though, if we were to remove it.

What we could do is consider creating a new system where # is just a key,
and then making that the new default system, and updating dictionaries.
Finally, allow people to go back and switch to the old one.

RTF conversions is another potential issue.

**Comment by thumbquat** [comment]
That sounds like a reasonable path forward. 
Might have a little play, shouldn't be too bad, really... It's quite good that can just be a plugin :)

For RTF I think we'd always have to support the "standard", at least on import. Could make it part of loading? Then in memory it's plover-style #

**Comment by fourshade** [comment]
If there's any room for making breaking changes, I would highly recommend this one. I was rather confused when a tool that searched the default dictionary (without importing Plover) could find entries for all the usual number combos *except* the basic single digits. In fact, the Discord bot I'm running has its dictionary compiled by a script; at the top of that script I found: 
```
# Somehow these are missing...
NUMBERS = {
    "#S": "1",
    "#T": "2",
    "#P": "3",
    "#H": "4",
    "#A": "5",
    "#O": "0",
    "#-F": "6",
    "#-P": "7",
    "#-L": "8",
    "#-T": "9",
}
```
Using "aliases" for normalization is just fine, i.e. 3 becomes #P when loading dictionary keys from disk. That doesn't need any special treatment by the translation engine, just the file loader. I imagine the loaders are where the bulk of the work needs to be done, but I don't know enough about the RTF format to work on that just yet.

**Comment by benoit-pierre** [comment]
Normalization is now correctly done, thanks to #1362.
