### ISSUE TITLE
Max 6 keypresses recognized

### ISSUE THREAD

**Issue by stevenbhardwaj** [openstenoproject/plover#673]
Classification: bug
Reproducibility: always

Plover only sees chords with maximum 6 keypresses. 7-key strokes get recognized as other things. 

## Steps to Reproduce
I type in plover.
I tried reinstalling once.

## Expected Results
It should make all chords.

## Actual Results
No change.

## Version
Plover 3.1.0
Installed via whl file per directions just today

## Notes
Haven't found workaround, other than using another computer. The same sidewinder keyboard works fine with plover (3.0) on the other computer.
I used plover often on the problem-experiencing computer for six months haven't for the past two months.
A previous installation that had worked fine on this computer (before those two months) wouldn't open when I clicked it. I reinstalled the new version and it worked fine.

## Configuration
Linux ayjy-Meerkat 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Using sidewinder under keyboard.

**Comment by benoit-pierre** [comment]
Can you try the current master? This might be the same issue as #644.

**Comment by stevenbhardwaj** [comment]
Sorry for the delay. I'll be trying to install the master but I'm enough of a linux newbie that I usually only successfully install things with .deb files or with isolated and explicit directions.

But I don't want everything to wait on me so I'll just close the issue!

**Comment by benoit-pierre** [comment]
I made a deb yesterday that I think should fix your issue, would you mind testing if it works? See here: https://groups.google.com/d/msg/ploversteno/mKqsi0DsqKY/4xgjYBi7AQAJ

Make sure you have my PPA enabled, and your packages updated, as you need a recent enough version of python-setuptools:
```shell
sudo apt-add-repository -y ppa:benoit.pierre/plover && sudo apt-get update
```

**Comment by stevenbhardwaj** [comment]
works like a charm! wow, thanks!!!
