### ISSUE TITLE
Config file in wrong directory on Linux

### ISSUE THREAD

**Issue by JasonWoof** [openstenoproject/plover#674]
Classification: bug

There should not be any config files in ``$HOME/$XDG_DATA_HOME/``

The plover configuration directory should be ``$HOME/$XDG_CONFIG_HOME/plover``

If ``$XDG_CONFIG_HOME`` is not set, then use ".config" like so: ``$HOME/.config/plover``

Please move plover.cfg there.

I think of user.json as a config file too, but I certainly can understand that being considered a data file.

**Comment by morinted** [comment]
The config location is determined in this file: https://github.com/openstenoproject/plover/blob/master/plover/oslayer/config.py

We are using `appdirs.user_data_dir('plover', 'plover')`. To change to user_config_dir, we would need to handle migration/support for the old directories. It seems like the fact that it's not in a Plover directory for you is an [appdirs](https://pypi.python.org/pypi/appdirs) or system configuration bug?

**Comment by benoit-pierre** [comment]
It use to be in `~/.config/plover` (dictionaries too) before switching to `appdirs.user_data_dir(...)`. There was no handling of migration, but I don't know if the switch impacted Windows / OSX similarly. What are the locations for `~/.config/plover`/`appdirs.user_data_dir(...)` on those platforms.

We certainly don't want to split config/dictionaries locations, as this would make relative paths / portable mode support harder.

**Comment by morinted** [comment]
I don't think there was a change on Mac/Windows when switching to appdirs.

**Comment by benoit-pierre** [comment]
OK, according the appdirs documentation switching to `appdirs.user_config_dir` would only impact Linux:
* Mac OS X:		    same as `user_data_dir`
* Unix:		    `~/.config/<AppName>` (or in `$XDG_CONFIG_HOME`, if defined)
* Win *:		    same as `user_data_dir`

**Comment by JasonWoof** [comment]
Huh, I didn't realize that Mac and windows keep data and configuration files in the same place. Seems like a terrible idea. Config files are the sort of things that you can track with git well. Not so with several 10MB log files.
