### ISSUE TITLE
Open the config folder from the GUI

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#697]
## Summary

As a user I want to be able to open the config folder from the GUI so that I don't need to search my file system for Plover's config file, log file, and plugins folder.

Considerations:
- If the log file has been saved to another folder, it might still be hard to find
- There's no clear place in the UI to put this.

**Comment by morinted** [comment]
I don't think the toolbar is really the place for those, would be better in
menus or config.

**Comment by nsmarkop** [comment]
So were you thinking more like putting Open Config Folder under the Configure option here:

![image](https://user-images.githubusercontent.com/4577561/42415840-59bf3130-8223-11e8-8531-1411f73549bc.png)

? I can make a pull request adding it there if you think that's a good spot in the core UI. Putting it in configure itself seems like it might be a little hard to find a good place for it, and it'd probably be too out of the way to be used frequently (I need the config folder a lot...).

**Comment by morinted** [comment]
Yeah, I think that would be a great place for it!
