### ISSUE TITLE
plover doesn't run on Kubuntu 14.04

### ISSUE THREAD

**Issue by noureddin** [openstenoproject/plover#703]
Classification: Crash

Reproducibility: Always (on my system)

## Summary

I have installed `plover` from the PPA on my Kubuntu 14.04\*, and when I try to launch it, either from the applications menu or from the commandline, I get a lengthy error message:

![error](https://cloud.githubusercontent.com/assets/2486008/23397072/856bf5ac-fd9f-11e6-87e3-422e9c025486.png)

And when it's run from the terminal, the same GUI message appears with the following in the terminal. It's seems to be the same message

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/plover/main.py", line 84, in main
>     gui = plover.gui.main.PloverGUI(config)
>   File "/usr/lib/python2.7/dist-packages/plover/gui/main.py", line 47, in __init__
>     wx.App.__init__(self, redirect=False)
>   File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8628, in __init__
>     self._BootstrapApp()
>   File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8196, in _BootstrapApp
>     return _core_.PyApp__BootstrapApp(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/plover/gui/main.py", line 55, in OnInit
>     frame = MainFrame(self.config)
>   File "/usr/lib/python2.7/dist-packages/plover/gui/main.py", line 228, in __init__
>     Output(self.consume_command, self.steno_engine))
>   File "/usr/lib/python2.7/dist-packages/plover/gui/main.py", line 368, in __init__
>     self.keyboard_control = KeyboardEmulation()
>   File "/usr/lib/python2.7/dist-packages/plover/oslayer/xkeyboardcontrol.py", line 1123, in __init__
>     self.display = display.Display()
>   File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 89, in __init__
>     self.display = _BaseDisplay(display)
>   File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 71, in __init__
>     protocol_display.Display.__init__(self, *args, **keys)
>   File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 68, in __init__
>     name, host, displayno)
>   File "/usr/lib/python2.7/dist-packages/Xlib/support/connect.py", line 101, in get_auth
>     return mod.get_auth(sock, dname, host, dno)
>   File "/usr/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", line 119, in new_get_auth
>     au = xauth.Xauthority()
>   File "/usr/lib/python2.7/dist-packages/Xlib/xauth.py", line 47, in __init__
>     raise error.XauthError('~/.Xauthority: %s' % err)
> XauthError: ~/.Xauthority: [Errno 2] No such file or directory: '/2/nour/.tmp/kde-nour/xauth-1000-_0'
> 
> 
> (plover:25790): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
> 10:15:03: Debug: Adding duplicate image handler for 'Windows bitmap file'
> 

A small clarification: my `/tmp` is a symlink to `/2/nour/.tmp`.

\* (I really appreciate that you still support Ubuntu Trusty. Thanks!)

## Steps to Reproduce

1. Run `plover`

## Expected Results

2. Plover window should appear.

## Actual Results

3. Instead, an error message pops. :(

## Version

Plover version 3.1.0.

Installed via: apt-get, through the official [PPA](https://launchpad.net/%7Ebenoit.pierre/+archive/ubuntu/plover).

## Configuration

- GNU/Linux, Kubuntu 14.04.5 LTS, KDE 4.11
- uname -a: `Linux nour-pc 3.13.0-101-generic #148-Ubuntu SMP Thu Oct 20 22:08:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by benoit-pierre** [comment]
Looks like a problem in `python-xlib`. Can you confirm:
* you're using `python-xlib` version 0.17-1ppa3trusty1
* you get a similar error when running `python2 -c 'from Xlib.display import Display; Display()'` in a terminal

**Comment by noureddin** [comment]
Thanks for the quick reply, Mr @benoit-pierre!  
Yes, exactly; your statements are correct. Confirmed.

It's the package provided with the Plover in the PPA. The only other version available for Trusty is 0.14, which I couldn't install without removing Plover, so I didn't.

**Comment by benoit-pierre** [comment]
I pushed version 0.19 of python-xlib to my PPA, please update and check it fixes your issue.

**Comment by noureddin** [comment]
Yes, it now works! Thank you.
