### ISSUE TITLE
Dictionaries in the cloud

### ISSUE THREAD

**Issue by marnanel** [openstenoproject/plover#716]
Classification: Enhancement

Reproducibility: n/a

## Summary

We should have a built-in ability to read and write cloud dictionaries-- in particular, Google Drive, Dropbox, and WebDAV.

(In this case, the present local dictionaries will effectively become cached copies.)

**Comment by infodungeon** [comment]
Providing a path setting to the dictionaries would allow this as Drive, Dropbos etc sync local drive stores.

**Comment by morinted** [comment]
This is a duplicate of #128 and for now my stance is still that we should just use the native clients on the operating system and use the local paths in Plover.
