### ISSUE TITLE
Deleting \_(ツ)_/ deletes too much text

### ISSUE THREAD

**Issue by arxanas** [openstenoproject/plover#720]
Classification: Bug

Reproducibility: Always

## Summary

Trying to delete `\_(ツ)_/` also deletes a large amount of the preceding text. Also, my entry which reads as

```
"SHR*UG/SHR*UG": "¯\\_(ツ)_/¯",
```

In my dictionary file only renders as `\_(ツ)_/`, which is to say that the hands are missing for some reason. This might be related.

## Steps to Reproduce

1. Add entry for `\_(ツ)_/`. Mine is `SHR*UG/SHR*UG`.
2. Write some text.
3. Stroke `\_(ツ)_/`.
4. Stroke `*` to delete it.

## Expected Results

4. Only `\_(ツ)_/` is deleted. In my case, that would leave me with the word "shrug", which is the translation of `SHR*UG`.

## Actual Results

4. `\_(ツ)_/` is deleted, but also a great deal of the preceding text (usually the entire paragraph, but not necessarily the whole document, as far as I can tell). Then the word "shrug" is written out afterwards.

Here's a transcript from my `strokes.log`. In particular, note that the full form of the emoticon is written out in the log (with its hands) even though it isn't actually written out in the resulting output.

```
2017-03-09 15:20:05,198 Stroke(HEL : ['H-', '-E', '-L'])
2017-03-09 15:20:05,198 Translation(('HEL',) : "hell")
2017-03-09 15:20:05,508 Stroke(HROE : ['H-', 'R-', 'O-', '-E'])
2017-03-09 15:20:05,509 *Translation(('HEL',) : "hell")
2017-03-09 15:20:05,509 Translation(('HEL', 'HROE') : "hello")
2017-03-09 15:20:05,754 Stroke(-RGS : ['-R', '-G', '-S'])
2017-03-09 15:20:05,754 Translation(('-RGS',) : "{,}")
2017-03-09 15:20:06,032 Stroke(WORLD : ['W-', 'O-', '-R', '-L', '-D'])
2017-03-09 15:20:06,032 Translation(('WORLD',) : "world")
2017-03-09 15:20:06,828 Stroke(SHR*UG : ['S-', 'H-', 'R-', '*', '-U', '-G'])
2017-03-09 15:20:06,828 Translation(('SHR*UG',) : "shrug")
2017-03-09 15:20:07,058 Stroke(SHR*UG : ['S-', 'H-', 'R-', '*', '-U', '-G'])
2017-03-09 15:20:07,058 *Translation(('SHR*UG',) : "shrug")
2017-03-09 15:20:07,058 Translation(('SHR*UG', 'SHR*UG') : "¯\_(ツ)_/¯")
2017-03-09 15:20:07,695 *Stroke(* : ['*'])
2017-03-09 15:20:07,695 *Translation(('SHR*UG', 'SHR*UG') : "¯\_(ツ)_/¯")
2017-03-09 15:20:07,695 Translation(('SHR*UG',) : "shrug")
```

## Version

Plover version c3a4f96be7a9dec310641c2adea54b600f1be81f, built from source.

## Notes

The shrug rendered incorrectly in previous versions of Plover on OS X (which 7439d3a769e8855ebbb6c422e43dec13b46eaffd was presumably meant to fix). It now renders more correctly, in that there isn't a weird 0 in the sequence, but there are still no hands for the emoticon.

`git bisect` tells me that 6ff6a5912a55f1a9c42a83544c88af2f2980161f is the first bad commit. I can see it being a problem with control being held in some inappropriate scenario, since <kbd>ctrl+bksp</kbd> is "delete last word" in OS X. cc its author @morinted 

## Configuration

OS:

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.3
BuildVersion:   16D32
```

**Comment by benoit-pierre** [comment]
OK, so 2 different bugs then:
* `¯\_(ツ)_/¯` is rendered as `\_(ツ)_/`, do you have the right version of PyObjc installed? (`pyobjc-core==3.1.1+plover2` and `pyobjc-framework-Cocoa==3.1.1+plover2`), does it happen in all applications?
* undoing `¯\_(ツ)_/¯` does not work correctly, but clearly if it's not rendered properly (missing characters) then Plover will try to backspace too many characters anyway

**Comment by benoit-pierre** [comment]
Also, what's your keyboard layout?

**Comment by arxanas** [comment]
Looks like the problems are a combination of

1) Using the ABC Extended layout for OS X, which adds more special characters that you can write by holding modifier keys, and
2) Having a window manager open that intercepts some of the modifier keystrokes.

When I switch back to ABC (the default qwerty layout) and close my window manager, I can type ¯\_(ツ)_/¯ and have it backspace fine.

I can't imagine how one would solve this problem. (Maybe it would work to add a Plover command to copy a given string to the pasteboard, and then paste that string.This would fix the problem of not rendering correctly in some keyboard layouts, but not the problem of backspacing.) I'm closing this issue given that it's specific to my computer configuration.

**Comment by morinted** [comment]
Did the "hands" work before the mentioned commit?

**Comment by arxanas** [comment]
@morinted Yes, it appears that the hands worked. The problem was that my window manager was eating my hands. (That's not a sentence I thought I would ever say...) When I go back to that commit and disable it, the hands appear.

**Comment by morinted** [comment]
So the only bug is the incompatibility with ABC Extended?

**Comment by arxanas** [comment]
Yes. I think you mentioned this before, but I had forgotten about it.

**Comment by morinted** [comment]
Looking into it.

**Comment by morinted** [comment]
@arxanas can I get confirmation on whether this PR fixes it? https://github.com/openstenoproject/plover/pull/724

**Comment by arxanas** [comment]
@morinted Yes, it works!
