### ISSUE TITLE
Plover Error: can not start Plover 3.1.1 on OS X 10.9.5

### ISSUE THREAD

**Issue by ivanov** [openstenoproject/plover#725]
Classification: Bug

Reproducibility: Always

## Summary

Trying to start Plover 3.1.1 on OS X 10.9.5 results in a "Plover Error" dialog, with options to either "Open Console" or "Terminate".

Opening the console reveals these logs:

3/11/17 7:58:12.127 PM Plover[74895]: Plover Error
3/11/17 7:58:14.957 PM com.apple.launchd.peruser.501[195]: (org.openstenoproject.plover.115488[74895]) Exited with code: 255

## Version

Plover version 3.1.1.

Installed via: download from github.

## Notes

Running Plover on the command line directly from the Plover.App folder results in the following:

```
 /Applications/plover.app/Contents/MacOS/Plover 
Traceback (most recent call last):
  File "/Applications/plover.app/Contents/Resources/__boot__.py", line 81, in <module>
    _run()
  File "/Applications/plover.app/Contents/Resources/__boot__.py", line 66, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/plover.app/Contents/Resources/main.py", line 22, in <module>
    import wx
  File "wx/__init__.pyc", line 45, in <module>
  File "wx/_core.pyc", line 4, in <module>
  File "wx/_core_.pyc", line 14, in <module>
  File "wx/_core_.pyc", line 10, in __load
ImportError: dlopen(/Applications/plover.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so, 2): Symbol not found: _OBJC_CLASS_$_NSURLRequest
  Referenced from: /Applications/plover.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
  Expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
 in /Applications/plover.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
2017-03-11 18:30:59.521 Plover[74144:507] Plover Error
```

If you've found a workaround, provide it here.

## Configuration

OS:

Mac OS X 10.9.5

**Comment by morinted** [comment]
Unfortunately, Plover 3.1.1 will only run on 10.10+ because the build tools we use only support the last two major versions of macOS.

The only workaround available is to use an older version of Plover.

**Comment by morinted** [comment]
@ivanov I'm experimenting with different ways to build Plover than what we use now. Could you try this test build and see if it runs on Mavericks or if you get a similar error?

https://drive.google.com/file/d/0B_4v0_ER8UlwTEcyZ1FWUjVKZ28/view?usp=sharing

Ted

**Comment by ivanov** [comment]
@morinted Thanks, Ted - that build on Google drive did indeed work.

(I was also able to get plover running from source, but it took some hand running of pyuic and pyrcc and minor patching to accomodate the results)

**Comment by morinted** [comment]
Wow, I'm surprised that that build worked. That's good news for future releases as I built that on Sierra. Thanks for the quick follow up!

**Comment by ivanov** [comment]
Let me make sure that 3.1.1 is still broken for me like it was before... Maybe it's a result of a moving target of me making changes locally to get the git version up and running...

**Comment by ivanov** [comment]
Yeap. 3.1.1 is still broken. For what it's worth, the new build you made for me is 77.8Mb on disk, whereas the one for 3.1.1 is only 36.7Mb. 
<img width="566" alt="screen shot 2017-03-13 at 12 41 54 pm" src="https://cloud.githubusercontent.com/assets/118211/23872219/ae5ab926-07ea-11e7-8d12-545e01680ccb.png">

**Comment by morinted** [comment]
Yep, the new one is much bigger as we include a full python installation
(in anticipation of plugin development).

You can try, for fun, running from source with:
./Plover.app/Contents/Frameworks/python3.6 -m plover.main

**Comment by morinted** [comment]
Now this is in master and the current weekly release: https://github.com/openstenoproject/plover/releases

Let me know if Plover stops working on your version of macOS again 😁
