### ISSUE TITLE
customizable steno machine

### ISSUE THREAD

**Issue by nickxyzt** [openstenoproject/plover#73]
In order to support multiple languages, which use various steno machines, Plover should read the configuration from a file.
For instance, in Italy there is the Michela stenotype (stenoterminale Michela), which has the keys arranged in a totally different layout.
In order to write in Italian, the dictionary must be defined using the letters defined in "stenoterminale Michela", which are different from the stenotype machine used for English.
Below is the steno machine for italian:
![250px-Tastiera_macchina_Michela_con_rappresentazione_tasti_letterali](https://f.cloud.github.com/assets/206858/371666/2b0a70dc-a341-11e2-9fb5-a092ae37f847.jpg)

**Comment by morinted** [comment]
With the customizable keymap I think this is more possible now for users to do with their own custom machines and firmware using NKRO.
