### ISSUE TITLE
Uppercase last word also uppercases prefix of next word

### ISSUE THREAD

**Issue by arxanas** [openstenoproject/plover#741]
Classification: Bug

Reproducibility: Always

## Summary

When using [the uppercase last word stroke](https://github.com/openstenoproject/plover/wiki/Dictionary-Format#uppercase-last-word) `{*<}`, if I uppercase the last word, and then type a prefix stroke for the next word, the prefix stroke also comes out as uppercase. Presumably, this should only happen for suffix strokes attached to the previous word.

## Steps to Reproduce

Consider my dictionary:

```json
"KPA*TS": "{*<}",
"TPAO": "foo",
"*ER": "{^er}",
"KAUPB": "{con^}",
```

Observe the following translations:

```
TPAO/KPA*TS/*ER/TPAO = FOOER foo      --> good, {^er} should be retroactively uppercased
TPAO/KPA*TS/KAUPB/TPAO = FOO CONfoo   --> bad, second word should be "confoo", not "CONfoo"
```

## Version

Plover version 4.0.0.dev0 @ 4c9567cdf41af70313d0b5c4fa5681070e72ec93 (current HEAD).

Installed via: source

**Comment by benoit-pierre** [comment]
Fixed with #807.
