### ISSUE TITLE
Closing tool windows causes exceptions on stroke

### ISSUE THREAD

**Issue by nimble0** [openstenoproject/plover#755]
Classification: Bug

Reproducibility: Always

After closing tool windows (Suggestions and Paper Tape), exceptions are reported after each stroke.

## Steps to Reproduce

1. Launch Plover such that there is terminal output.
2. Open Suggestions/Paper Tape.
3. Close Suggestions/Paper Tape.
4. Activate Plover.
5. Press any stroke.

## Expected Results

No output in terminal.

## Actual Results

The following exceptions are reported but program continues to run and behavior is normal. When the paper tape has been closed, memory is also leaked.

When Suggestions has been closed:

Traceback (most recent call last):
  File "/home/nimble/projects/plover/plover/gui_qt/suggestions_dialog.py", line 133, in on_translation
    self._words = self._words + action.text
AttributeError: 'NoneType' object has no attribute '_words'

When Paper Tape has been closed:

Traceback (most recent call last):
  File "/home/nimble/projects/plover/plover/gui_qt/paper_tape.py", line 115, in on_stroke
    self._show_stroke(stroke)
  File "/home/nimble/projects/plover/plover/gui_qt/paper_tape.py", line 108, in _show_stroke
    self.tape.appendPlainText(text)
RuntimeError: wrapped C/C++ object of type QPlainTextEdit has been deleted

## Version

Plover 4.0.0.dev1 e051e0b16a37c1ec4501c359591254d4df0627f3

First appeared: cf1e7a989e1f3296dc6e6567f367ca8fafece8e9

## Configuration

OS: Linux Mint 17

Python 3.4.3

PyQt5 5.2.1+dfsg-1ubuntu8

Qt version: 5.2.1
SIP version: 4.15.5
PyQt version: 5.2.1

**Comment by nimble0** [comment]
On further inspection the memory leak looks to be unrelated to this bug.

**Comment by benoit-pierre** [comment]
Closing: the culprit is the version of PyQt5 being too old. We now require at least 5.8.2. Please open another issue for the memory leak.
