### ISSUE TITLE
Python Crashing in 4.0.0

### ISSUE THREAD

**Issue by gbtru4life** [openstenoproject/plover#759]
Classification: Crash
Reproducibility: Most of the time

## Summary

When editing the dictionary and searching for strokes/entries that don't exist Python crashes. 

## Steps to Reproduce

1. Open your dictionary in Build 4.0.0
2. Search for something to edit
3. After about four searches (mostly when searching for an entry that doesn't exist)  a Not Responding Window appears and then it says that Python crashed.  

## Expected Results

3. No crash.

## Actual Results

3. Crash

If helpful, submit screenshots of the issue to help debug. Your `plover.log` or `strokes.log` may also be useful.

## Version

Plover version Plover 4.0.0.dev1+3.gc691766 

(Click the "About…" button in the main Plover window to see the version
number.)

If the problem is known to be present in more than one version, please list all of those.

Installed via: Link sent from a Plover developer

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, provide it here.

## Configuration

OS: W7 - Pro, SP1, 64-bit

- If it's OS X,
  go to Finder, Apple menu, "About This Mac".
  - Alternatively, if you're comfortable with the Terminal, run
    `sw_vers` and paste the output.

- If it's Linux,
  provide information on your distro and any customization
  relevant to Plover's operation (desktop environment, window manager, ???).
  - uname -a output might also be useful.

- If it's Windows,
  press the Windows key + PauseBreak key together in order to bring up
  the Windows version information.

**Comment by morinted** [comment]
Can you confirm this still happens with the current weekly? https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev1%2B20.g60a373f

**Comment by morinted** [comment]
> Search for something to edit

Searching as in stroke or translation?
