### ISSUE TITLE
RTF dictionary fails round-trip

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#773]
**Classification**:  Bug

**Reproducibility**: Always

## Summary

Essentially, when I quit Plover and start it up again, some of my dictionary entries that have "keep together" attributes set (you know, that include the "^" symbol) all have  been modified such that outlines that should look like this --

`{^}&lt;p class="body">{^} {-|}`

-- end up looking like this:

`{^ &lt;p class="body"> ^} {-|}`

## Steps to Reproduce

1. Test outlines
2. Quit and restart Plover

## Expected Results

3. This should happen:

 The outline that looked like this before --

**{^}&lt;p class="body">{^} {-|}**

-- should look the same.

## Actual Results

I have screenshots, but I posted this issue -- complete with screenshots -- in the Plover Google group here:

https://groups.google.com/forum/#!topic/ploversteno/qo_vXTcJLxY

## Version

Plover version: 4.0.0.dev1+20.g60a373f

## Notes

There were other issues with the new build (lengthy pauses between what was stroked and what appeared on the screen), so I dropped back to version 3.0.0+328.g07e17fe, where I found the same issue with the dictionaries.

There was a suggestion to just use .json dictionaries, but while that might work, if the user is, as I am, coming from a regular CAT software background, chances are good they're not going to have a .json version of their dictionary. I know I don't, and I don't know of anything on the Mac that will reliably convert an .rtf file into a .json file ... though in truth, I think it has been about a year since I last checked, and the crap I found online just plain didn't work.

**If you've found a workaround, provide it here.**

I thought I could get away with copying the fixed version of the dictionary to another folder and replacing that dictionary with the copy just before starting Plover, but I still had the same issue, which leads me to believe that the issue occurs during the start-up routines.

## Configuration

ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F2315

**Comment by morinted** [comment]
Until we rewrite our RTF implementation, I would define problem strokes in a supplementary JSON dictionary.

To make an empty JSON dictionary on a Mac:

- Open TextEdit
- In the menu bar, select "Format > Make Plain Text"
- Enter `{}` into the window 

![screen shot 2017-06-04 at 1 05 10 pm](https://cloud.githubusercontent.com/assets/5840970/26763752/bd217314-4926-11e7-843a-008f50f0d2b3.png)

- File > Save...
- Enter a file name, e.g. `glenzspecial.json`

![screen shot 2017-06-04 at 1 05 58 pm](https://cloud.githubusercontent.com/assets/5840970/26763754/c8283fd6-4926-11e7-91c0-7d2d568e9f60.png)

- Make sure to select "Use .json" in the save warning

![screen shot 2017-06-04 at 1 06 04 pm](https://cloud.githubusercontent.com/assets/5840970/26763755/cf22282e-4926-11e7-9416-b1502b5e4ecc.png)

- Add this dictionary to Plover. I would only add your special strokes to it, and continue using your main dictionary for everything else.

**Comment by gdwaynewarner** [comment]
Thanks, Ted.

I finally got around to doing that, but I had to use skEdit to make the .json file, because my copy of TextEdit wouldn't let me save the file with that extension.

That said, I noticed something odd as I was making the definitions into the new .json dictionary. I was adding this one --

{^}&lt;p class="caption">{^} {-|}

-- and I noticed that the definition of the outline in the window looked a bit ... off. I grabbed a screenshot so you could see what I was seeing:
![screen shot 2017-06-05 at 8 24 56 am](https://cloud.githubusercontent.com/assets/17680111/26790719/8e5926d2-49c9-11e7-8e03-e46b2d8e1a6e.png)

That is to say, the highlighted outline on the left is what I should see in the window on the right, where it says "PHRAS /KAP maps to," and the outline being displayed doesn't look very much like what's on the left side of the screenshot.

Hope that makes sense ...

**Comment by morinted** [comment]
Hey, that's a cool bug. I guess QT is actually trying to render the HTML in
the translation!

**Comment by gdwaynewarner** [comment]
Ha ha ha! Yes, it's always good to be able to find the cool bug!

**Comment by gdwaynewarner** [comment]
Any news on this one?

**Comment by benoit-pierre** [comment]
Should be fixed in #1364.
