### ISSUE TITLE
Lengthy Pause During Use

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#778]
Classification: Bug

Reproducibility: Sometimes

## Summary

What has been going on of late with build 4.0.0.dev1+20.g60a373f is I will be writing along, and then everything stops for about a minute, then the translations fills in what I had written before and continues on as if nothing has happened.

So far I have not noticed any particular pattern to this behavior; it seems to be totally random.

## Steps to Reproduce

1. I write stuff, and sometimes Plover just stops sending what I've written to the document I'm working on.

## Expected Results

3. Plover should send what I wrote to the document I'm writing in.

## Actual Results

**_3. Instead, this happens_** :(

As I was writing the contents of number three up there, Plover stopped after "should" for about two minutes, and then started back up again. Unfortunately, I don't see anything that explains what was going on during those two minutes.

I guess I could have taken a screenshot of the window I was writing in and the clock, but I didn't think about that at the time!

## Version

**_Plover version_** 4.0.0.dev1+20.g60a373f

If the problem is known to be present in more than one version, please list all of those.

NA

**_Installed via:_** Downloaded from openstenoproject.org

## Notes

**_Describe any debugging steps you've taken yourself._**

I checked a few of the files in the Plover folder (plover.cfg and plover.log -- after making copies of them, of course) but neither of those had any data ... but I just now took a look in the Mac's Console program, and found these:

**_6/10/17 8:46:51.576 PM WindowServer[207]: disable_update_timeout: UI updates were forcibly disabled by application "Plover" for over 1.00 seconds. Server has re-enabled them._**

**_6/10/17 8:46:58.760 PM WindowServer[207]: common_reenable_update: UI updates were finally reenabled by application "Plover" after 8.18 seconds (server forcibly re-enabled them after 1.00 seconds)_**

**_If you've found a workaround, provide it here._**

Ha ha ha! That's why I'm here!

## Configuration

**_OS_**:

Mac OS X 10.10.5

**Comment by benoit-pierre** [comment]
Is Plover hidden to the tray? Or do you have any of its windows open? (And which ones).

**Comment by tkpwaeub** [comment]
Similar problem for me. I'm using a Macbook Pro, and Stentura 400 SRT, and the most recent release of Plover. In addition to the long pause, Plover will sometimes lose its connection to the machine.

**Comment by KoiOates** [comment]
This is happening for me from time to time, using XUbuntu, release 16.04 on an HP Pavillion g6-1d80nr laptop. The length of the pause varies, usually it's only a few seconds, but I get the minute or two long ones too. This may or may not be a coincidence, but I can't think of one time it happenned when I only had one small dictionary checked. When it happens I have a lot of large dictionaries loaded and am usually writing at a faster pace. When Plover resumes translating, it also translates all the strokes that I've done since it paused. I always have the main Plover window, the Suggestions window, and sometimes the Paper Tape window open somewhere on my desktop.

**Comment by benoit-pierre** [comment]
Also, do any of you have the strokes/translation logging enabled?

**Comment by KoiOates** [comment]
Logging for strokes on mine.

**Comment by morinted** [comment]
I don't have logging or the suggestions window open and have never had this
issue.

**Comment by gdwaynewarner** [comment]
Benoit-Pierre, I'm on a Mac, so no system tray. At the time, I only had the main window and the Suggestions windows open. I believe I have strokes logging enabled.

In view of what Ted has reported, I will kill off the Suggestions window and the logging and see how that goes.

**Comment by Wilfried84** [comment]
Just to add that I'm having the same issue. Running on OSX 10.11.6. No logging is on. I generally have the suggestions window open.

**Comment by benoit-pierre** [comment]
Any news? Does killing logging/suggestions fix the issue? The paper tape / suggestions updates should have no impact on the engine output (different thread), except if the suggestions block when asking the engine for suggestions, which I don't see happening. (Tested by adding some `time.sleep` calls in both). Writing to the log is done from the engine thread, so a slow disk could impact output.

Googling for `WindowServer[207]: disable_update_timeout` does point to macOS issues:
* https://www.macissues.com/2015/01/08/how-to-manage-intermittent-lag-in-os-x-yosemite/
* https://www.jamf.com/jamf-nation/discussions/22595/avoid-security-update-2016-003-for-os-x-el-capitan-10-11-6

That leaves @KoiOates, are you using the AppImage or running from source?

**Comment by gdwaynewarner** [comment]
Hmm. I don't know why I didn't receive an e-mail letting me know there were an update. Sorry about that.

Anyway, I still get the occasional pause, but I see you have found a link to the poor performance of the OS I'm running, which I can't fix right now (this old iMac needs more RAM, but this model only accepts six gigs, max.

**Comment by gdwaynewarner** [comment]
Hmm. I don't know why I didn't receive an e-mail letting me know there were an update. Sorry about that.

Anyway, I still get the occasional pause, but I see you have found a link to the poor performance of the OS I'm running, which I can't fix right now (this old iMac needs more RAM, but this model only accepts six gigs, max).

**Comment by benoit-pierre** [comment]
@gdwaynewarner: just to be clear, does any of my suggestions have any impact?

**Comment by gdwaynewarner** [comment]
I thought I had killed off the logging, but it appears I did not do so correctly. I just shut both logging and the "Log Translations" off, and will test to see how things go. They appear to have come back after a system crash (bad web browser behavior).

**Comment by gdwaynewarner** [comment]
A few hours ago, Plover froze on me again.

Unfortunately, the Suggestions window was open again, so I closed it, and made sure it would not open again without my specifically opening it by unchecking the appropriate checkbox ... so I will be doing more testing and get back to you within a couple days.

**Comment by KoiOates** [comment]
@benoit-pierre Running from source. I've tried a few days straight with suggestions and logging turned off, I still get the pauses though.

**Comment by gdwaynewarner** [comment]
It's been a while since I've spent a significant amount of time using Plover, but I had to work on a transcript the other day, and did so with the Suggestions window closed as suggested -- er, recommended, and I am pleased to report that I didn't experience any freezing during that session.

The next day, after actually quitting Plover before going to bed, I started it up and activated the Suggestions window, and shortly after, I started getting those pauses again.

... so the problem might lie somewhere in the code for the Suggestions window, I'm guessing.

**Comment by benoit-pierre** [comment]
Could you try the latest [master build](https://47-4652212-gh.circle-artifacts.com/0/tmp/circle-artifacts.6F8dms8/plover-4.0.0.dev2%252B28.g37c65eb.dmg)? The PyQt5 version was updated to the latest LTS, so who knows... If that does not work, I'll make a build which limit the numbers of last suggestions. Alternatively, you could check if the pauses happen only when there are many entries, and if regularly clearing the history fix the issue.

**Comment by gdwaynewarner** [comment]
Just downloaded and installed the new build. It's running, so that's good ... but I'll have to do some serious testing later (bedtime!).

Thanks!

**Comment by gdwaynewarner** [comment]
Okay, using the new build, I had the Suggestions window open, and actually had no issues. Then a few days later, after having quit and restarted Plover a few times over a few days, I did get a freeze. Unfortunately, I didn't time it, but I think it was for about 30 seconds.

**Comment by gdwaynewarner** [comment]
While working on (yet another) transcript, I decided to test the new build (Plover 4.0.0.dev6+5.ga564116  on Mac OS X 10.10.5) to see if the problem was still present.  

Because I had been adding new outlines to my dictionary like crazy, I thought it might be a good idea to have the Suggestions window open ... so I opened it, pinned it so I could see it all the time, and started writing.

After a few minutes, I had got to a point where I had just written about 10 words ... and none of them appeared on the screen.

I then opened the Console program and searched for Plover ... and nothing at all appeared.

Unfortunately, I didn't think to search for the Plover.cfg file; I just closed the Suggestions window and decided to file a bit of an update to this bug report.

Well. That transcript won't write itself, so ...

**Comment by benoit-pierre** [comment]
This might have been fixed by #1188.

**Comment by benoit-pierre** [comment]
Another suggestions widget related speed up: #1481. Would love some feedback.

**Comment by benoit-pierre** [comment]
Is this still happening?

**Comment by gdwaynewarner** [comment]
Yes, actually. It happened just a few minutes ago, with the current build.

**Comment by benoit-pierre** [comment]
> Yes, actually. It happened just a few minutes ago, with the current build.

What does current build means? v4.0.0.dev11 or the latest continuous release? Always provide the exact version.

Anyway, let's ignore @KoiOates case for now (which looks like a different issue), what's the constant in your case? It's always when the suggestions are shown, right? Is it still the same system?

**Comment by gdwaynewarner** [comment]
I am using this build:

[image: Screen Shot 2022-06-29 at 1.43.44 PM.png]
I don't use the Suggestions window anymore, so it's definitely not that.
It's just Plover and whatever I'm writing into at the time, which means
Firefox or Nisus Writer Pro <http://www.nisuswriter.com>.

Same system (2009 17 inch MacBook Pro, running Mac OS 10.13.6 High Sierra).

Sorry that this will probably make the bug harder to track down, but on the
plus side, it doesn't happen very often, so that's something.

--gdw

**Comment by benoit-pierre** [comment]
Screenshot is not showing... It's better to copy-paste the version.

> It's just Plover and whatever I'm writing into at the time, which means Firefox or Nisus Writer Pro

So no active Plover window?

You could try running without the QT GUI (`-g none`).

You still get those `WindowServer` messages in the Mac's Console?

> Sorry that this will probably make the bug harder to track down, but on the plus side, it doesn't happen very often, so that's something.

Has the frequency changed?

**Comment by gdwaynewarner** [comment]
Here's the version number:

Plover 4.0.0.dev10


I'm not sure about running without the GUI. Sometimes I need to add
something to the dictionary -- though I haven't done that in a while now.
Usually I just run Plover and whatever I'm writing into hides Plover from
view.

As for the Console, that's not anything I have open without needing to do
so, so I guess I can't really say what's going on in there.

Sorry!

**Comment by benoit-pierre** [comment]
> Here's the version number: Plover 4.0.0.dev10

So clearly not the definition of "current build"...

> I'm not sure about running without the GUI. Sometimes I need to add something to the dictionary -- though I haven't done that in a while now.

And you still can when using `-g none`. Assuming `{PLOVER:ADD_TRANSLATION}` is mapped to `TKUPT`, the procedure for adding a new `TEFT/-G` → "testing" mapping is:
- stroke `TKUPT`
- stroke `TEFT`
- stroke `TKUPT` again
- enter (fingerspell/write) "testing"
- stroke `TKUPT` one last time to finalize: this will add the new mapping to your "favorite" dictionary

> Usually I just run Plover and whatever I'm writing into hides Plover from view.

OK, but visible or not, is the suggestions window open? What about the paper tape? Does the issue happen if all Plover windows are closed?

**Comment by benoit-pierre** [comment]
> As for which version of Plover I'm running, its version number is actually 4.0.0.dev11+21.g486a032, which is the current version to me and most non-devs or testers. The number I provided before came from Plover's About window. Not sure why the two don't match, though.

That's not normal, are you sure you don't ended up with another version of Plover installed in your plugins directory?

**Comment by gdwaynewarner** [comment]
I'm not sure how to find out, actually! Where is the Plugins directory
located?

**Comment by benoit-pierre** [comment]
In the configuration directory (easily accessible through the "File" → "Open config folder" menu entry).

**Comment by gdwaynewarner** [comment]
Okay, so in the Plugins folder, I have  a folder labeled "mac," inside of
which is  a couple of folders labeled "bin" and "lib."

The bin folder has three files, named "plover," "plover_plugins," and
"plover_send_command."

The "Lib" folder has a folder labeled "python," which has another folder
named "site-packages," which has a lot of stuff in it!

**Comment by benoit-pierre** [comment]
From the presence of a `plover` file in the bin directory, I imagine you also have a `plover-4.0.0.dev10.dist-info` directory in `site-packages`, right?

**Comment by gdwaynewarner** [comment]
It took a while to find, but yes, that's there! Should I delete it?

**Comment by benoit-pierre** [comment]
OK, so you definitively have another version of Plover installed in your plugin directory: this version is the one that end up being used. You are indeed running dev10.

> It took a while to find, but yes, that's there! Should I delete it?

You need to delete more than the dist-info directory. I would nuke the whole plugins directory and re-install the plugins you need.

Alternatively, try uninstalling by using the command `plover -s plover_plugins uninstall plover` from a terminal (replace the first `plover` with the right incantation which I can never remember because I've never used a Mac).

**Comment by benoit-pierre** [comment]
Found the incantation (see https://github.com/openstenoproject/plover/wiki/Troubleshooting:-Common-Issues#mac): `/Applications/Plover.app/Contents/MacOS/Plover -s plover_plugins uninstall plover`.

**Comment by gdwaynewarner** [comment]
Okay, I'll do just that.

**Comment by benoit-pierre** [comment]
> It's a bit weird that that issue (plover python plugin gets double-installed) happens in the first place, but a guess of why it happens is
> 
>     * originally an old version of Plover (e.g. version 1) is installed
> 
>     * you install some plugin that requires a newer version of Plover (e.g. version 2). Then `pip` will install Plover 2 in new version.
> 
>     * The version 2 remains "fixed" there and is somehow "prioritized", even when you upgrade to something else (e.g. version 3).

That's exactly how I think it happened, yes. And since the plugins directory takes priority, the old version is still used. (The same can happen with a old version of plugin installed in the plugins directory taking precedence over an newer version embedded with a more recent Plover distribution).

> I didn't test however. Also I don't see an easy way to prevent this (maybe use pkg_resources to check if it happens and warn the user to upgrade manually)

Detecting it is not that easy. Preventing it might be possible by always adding a constraint to the install command that would pin Plover to the current version.

What I had started to implement is a mechanism to check a plugin's compatibility with Plover (by making mandatory the need to declare the version needed in the requirements). I stopped because PyPI/Python packaging sucks, so that information may not always be available in PyPI's metadata (when there's only a source distribution for a particular version, but no wheel, thanks to a bug in setuptools).

> Side note, there's also an issue on Mac that if you install some package contains compiled binary, then upgrade Plover version such that Python version is changed (e.g. Python 3.8 → Python 3.9) then Plover will fail to start.

The plugins directory is normally versioned (according to the Python version), at least it is on other platforms (e.g. `plugins/linux/lib/python3.9/site-packages/` on Linux). Is that not the case on macOS?

**Comment by benoit-pierre** [comment]
Also, you should be able to start with `--no-user-plugins` to deactivate the user's plugins directory (while still being able to manage those plugins with the manager).

**Comment by gdwaynewarner** [comment]
Okay, it took a while, but I think it's gone. Here's the current version
number from the About box:

Plover 4.0.0.dev11+21.g486a032


Okay, so now I have to reinstall a few plugins!

**Comment by gdwaynewarner** [comment]
Sorry, I had completely forgotten about this one! Everything appears to be working just fine. The only whine I have is that when I use the Mac's "Get Info" window to change the icon to the original P, the "fixed" icon doesn't always appear, for some odd reason.

On the plus side, I always have a lot of stuff open, so I don't see my desktop that often, so I can live with that.
