### ISSUE TITLE
Alfred hotkeys disables letters

### ISSUE THREAD

**Issue by dimonster** [openstenoproject/plover#779]
Classification: Bug

Reproducibility: Always

## Summary

After using an Alfred hotkey combination, Plover won't type the letter used in the hotkey combination.

## Steps to Reproduce

1. Open and enable Plover. Stroke `TEFT` and produce "test" successfully where the dictionary contains `"TEFT": "test",`.
2. Switch to iTerm using brief `"T*ERPLZ": "{#Control_L(Alt_L(Super_L(Shift_L(t))))}"`, which triggers Alfred workflow using the hotkey `⌃⌥⌘⇧T` to bring iTerm to focus. 
3. Stroke `TEFT` and produce the text "es" (both t's are dropped).

Extra:
4. Disable Plover using brief `"PHROLG": "{PLOVER:TOGGLE}",` 
5. Hit "t" on laptop keyboard once. This produces no characters and nothing appears in the keyboard viewer. 
6. Hit "t" on laptop keyboard *again*. This produces "t", shows properly in the keyboard viewer, and then "t" continues to work from here on.

This applies to any letter used as a hotkey in an Alfred workflow or feature. For example, this brief to open Alfred's Clipboard History Viewer causes "c" to stop working: `"KPWR*": "{#command(option(c))}",`

## Expected Results

Stroked words should type all the letters in their translations.

## Actual Results

Stroked words do not type the letters used in hotkeys. 

## Version

Plover version [3.1.0](https://github.com/openstenoproject/plover/releases/tag/v3.1.0).

Installed via: [download from GitHub](https://github.com/openstenoproject/plover/releases/tag/v3.1.0).

Does **not** occur in Plover version [3.0.0+266](https://github.com/openstenoproject/plover/releases/tag/weekly-v3.0.0%2B266.g9487982).

Does occur in Plover v3.1.0, v3.1.1, and v4.0.0.

## Notes

Restarting Alfred makes this problem go away, and most other Alfred features do not appear to cause problems. The dropped letters still appear in Plover's Paper Tape, Suggestions, and stroke log with the correct translation shown but the letter does not appear/is not typed on screen. Nothing shows in Alfred's workflow debug log. Switching back to Plover 3.0.0 fixes the problem. Disabling Character Accent menu did not change anything:

> macOS has a feature where holding down a key brings up an accent menu. This can sometimes drop keys when typing quickly, such as TO/FPLT producing t. instead of to. To disable this, follow the instructions in this article: "[How to Disable the Character Accent Menu in OS X Mountain Lion](https://www.tekrevue.com/tip/how-to-disable-the-character-accent-menu-in-os-x-mountain-lion/)".

## Configuration

Mac OS X.

**Comment by morinted** [comment]
This may be related to the keys being held down by OSXKeyboardControl (it was a recently discovered mistake that I haven't fixed in master).

If you have a machine that supports serial, would you be able to confirm that that works with your use case?

If not, I can produce a build that shouldn't have the issue.

**Comment by dimonster** [comment]
Thanks for looking at this so quickly @morinted. I do not have a machine that supports serial so I cannot confirm if it works for this use case. Is there anything else I can do to help?

**Comment by morinted** [comment]
If you are running from source, you can try this patch:

```diff
diff --git a/plover/oslayer/osxkeyboardcontrol.py b/plover/oslayer/osxkeyboardcontrol.py
index e9ebf33..7e4de2c 100644
--- a/plover/oslayer/osxkeyboardcontrol.py
+++ b/plover/oslayer/osxkeyboardcontrol.py
@@ -215,7 +215,7 @@ class KeyboardCapture(threading.Thread):
                                       kCGEventFlagMaskNonCoalesced)
             has_nonsupressible_modifiers = \
                 CGEventGetFlags(event) & ~suppressible_modifiers
-            if has_nonsupressible_modifiers and event_type == kCGEventKeyDown:
+            if has_nonsupressible_modifiers:
                 return PASS_EVENT_THROUGH

             keycode = CGEventGetIntegerValueField(
```

If not, here is a direct link to download a build with the patch applied on master (c1ab5e845): https://89-22791365-gh.circle-artifacts.com/0/tmp/circle-artifacts.Llm8k6S/plover-3.0.0%252B626.g642ccc4-py3.dmg

**Comment by dimonster** [comment]
@morinted the direct link build worked, thanks

**Comment by morinted** [comment]
Thank you for confirming that this fixes the issue!
