### ISSUE TITLE
Michela, Italian chorded keyboard

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#780]
The Italian senate uses Michela, the piano-like chorded machine

https://it.wikipedia.org/wiki/Macchina_Michela

![Italian Michela machine](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Michela_Machine_.jpg/440px-Michela_Machine_.jpg)

The theory, the dictionary sample which I have is copyrighted and I cannot share, seems to be mostly orthographic, but is implemented just with prefixes:

```
{\*\cxs IUencf}per\cxds 
```

However I'm told that traditionally it's like the English system and the dictionaries follow a phonetic theory and are assembled by hand.

Layout:

![Michela layout](https://cloud.githubusercontent.com/assets/27013654/24818268/ff4dcd74-1bdf-11e7-9e37-f11dbd35a3c1.jpg)

Theory booklet:

[Michela in brief](https://github.com/openstenoproject/plover/files/906771/Michela.in.brief.ENG.pdf)

This system was discussed in and requires #742 to be completed.

**Comment by GBriotti** [comment]
Hi Morin, I'm not sure if this is the ri
[The Michela stenotype System (ENG) (h).pdf](https://github.com/openstenoproject/plover/files/1073944/The.Michela.stenotype.System.ENG.h.pdf)
ght place, but this is an updated version of the booklet.

**Comment by ossossosso** [comment]
Hi Ted.
I've bought the manual for the Italian Michela System. I already know and use the Melani system (syllabic method), but I'm really interested also to learn indeed this phonetic one. I'd like to compare and understand if one can takes advantages from the other and viceversa, and use the more comfortable for me.

Just reading the manual without practice on the machine is not easy to do. Even if I've converted in Plover the layout to the Michela one, as you said, without a dictionary is pretty useless.

I really don't know how to get it because out of the Senate the system is not used. Maybe the only solution would be to buy Eclipse...
Anyway, can I ask you how do you have the dictionary? Can be purchased as I did with the Melani dictionary? Or maybe could be shared for studying purpose.

Thank you in advance for any information.

**Comment by tthurman** [comment]
I might have lost some context here. What's the difference between Michela and Melani? Do they both use a musical keyboard?

IIRC the system you described on the bug tracker was Michela. Am I correct?

Are you looking for an English dictionary adapted for the Michela or Melani system? (rather than a Plover driver to read from musical keyboards, at this stage.)

In the Italian political system, do you have a senator representing you who might be able to tell us more?

peace,
Marn

On August 22, 2017 9:59:47 AM GMT+01:00, ossossosso <notifications@github.com> wrote:
>Hi Ted.
>I've bought the manual for the Italian Michela System. I already know
>and use the Melani system (syllabic method), but I'm really interested
>also to learn indeed this phonetic one. I'd like to compare and
>understand if one can takes advantages from the other and viceversa,
>and use the more comfortable for me.
>
>Just reading the manual without practice on the machine is not easy to
>do. Even if I've converted in Plover the layout to the Michela one, as
>you said, without a dictionary is pretty useless.
>
>I really don't know how to get it because out of the Senate the system
>is not used. Maybe the only solution would be to buy Eclipse...
>Anyway, can I ask you how do you have the dictionary? Can be purchased
>as I did with the Melani dictionary? Or maybe could be shared for
>studying purpose.
>
>Thank you in advance for any information.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openstenoproject/plover/issues/780#issuecomment-323964264

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by morinted** [comment]
I’m working on acquiring a free dictionary and learning materials for the Michela system in Italian. The support within Plover is dependent on us finishing our plugins implementation with Plover version 4. Definitely keep watching the GitHub issue, I’ll update as I go. My personal life has been pretty busy lately so I haven’t had too much time to develop on Plover.On Aug 22, 2017, at 9:10 AM, Thomas Thurman <notifications@github.com> wrote:I might have lost some context here. What's the difference between Michela and Melani? Do they both use a musical keyboard?

IIRC the system you described on the bug tracker was Michela. Am I correct?

Are you looking for an English dictionary adapted for the Michela or Melani system? (rather than a Plover driver to read from musical keyboards, at this stage.)

In the Italian political system, do you have a senator representing you who might be able to tell us more?

peace,
Marn

On August 22, 2017 9:59:47 AM GMT+01:00, ossossosso <notifications@github.com> wrote:
>Hi Ted.
>I've bought the manual for the Italian Michela System. I already know
>and use the Melani system (syllabic method), but I'm really interested
>also to learn indeed this phonetic one. I'd like to compare and
>understand if one can takes advantages from the other and viceversa,
>and use the more comfortable for me.
>
>Just reading the manual without practice on the machine is not easy to
>do. Even if I've converted in Plover the layout to the Michela one, as
>you said, without a dictionary is pretty useless.
>
>I really don't know how to get it because out of the Senate the system
>is not used. Maybe the only solution would be to buy Eclipse...
>Anyway, can I ask you how do you have the dictionary? Can be purchased
>as I did with the Melani dictionary? Or maybe could be shared for
>studying purpose.
>
>Thank you in advance for any information.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openstenoproject/plover/issues/780#issuecomment-323964264

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openstenoproject/plover","title":"openstenoproject/plover","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/openstenoproject/plover" class="">https://github.com/openstenoproject/plover</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tthurman in #780: I might have lost some context here. What's the difference between Michela and Melani? Do they both use a musical keyboard?\n\nIIRC the system you described on the bug tracker was Michela. Am I correct?\n\nAre you looking for an English dictionary adapted for the Michela or Melani system? (rather than a Plover driver to read from musical keyboards, at this stage.)\n\nIn the Italian political system, do you have a senator representing you who might be able to tell us more?\n\npeace,\nMarn\n\nOn August 22, 2017 9:59:47 AM GMT+01:00, ossossosso \<a href="mailto:u003cnotifications@github.com" class="">u003cnotifications@github.com</a>\u003e wrote:\n\u003eHi Ted.\n\u003eI've bought the manual for the Italian Michela System. I already know\n\u003eand use the Melani system (syllabic method), but I'm really interested\n\u003ealso to learn indeed this phonetic one. I'd like to compare and\n\u003eunderstand if one can takes advantages from the other and viceversa,\n\u003eand use the more comfortable for me.\n\u003e\n\u003eJust reading the manual without practice on the machine is not easy to\n\u003edo. Even if I've converted in Plover the layout to the Michela one, as\n\u003eyou said, without a dictionary is pretty useless.\n\u003e\n\u003eI really don't know how to get it because out of the Senate the system\n\u003eis not used. Maybe the only solution would be to buy Eclipse...\n\u003eAnyway, can I ask you how do you have the dictionary? Can be purchased\n\u003eas I did with the Melani dictionary? Or maybe could be shared for\n\u003estudying purpose.\n\u003e\n\u003eThank you in advance for any information.\n\u003e\n\u003e-- \n\u003eYou are receiving this because you are subscribed to this thread.\n\u003eReply to this email directly or view it on GitHub:\n\<a href="u003ehttps://github.com/openstenoproject/plover/issues/780#issuecomment-323964264\n\n--" class="">u003ehttps://github.com/openstenoproject/plover/issues/780#issuecomment-323964264\n\n--</a> \nSent from my Android device with K-9 Mail. Please excuse my brevity."}],"action":{"name":"View Issue","url":"<a href="https://github.com/openstenoproject/plover/issues/780#issuecomment-324021033" class="">https://github.com/openstenoproject/plover/issues/780#issuecomment-324021033</a>"}}}

**Comment by ossossosso** [comment]
Michela is a phonetic system, similar to the English one. Melani is a syllabic system. Michela was born more then 100 years ago (if I'm not wrong) and it is monstly used in the senate and other few public istitutions. Melani was born later, around 80s. It is used by all italian companies for real time subtitling and Court or city council transcription. After the success for the Italian language, this system has been also used for the spanish (and maybe portugese) language.
Michela system use a machine similar to a piano instrument. Actually I don't know if you can buy for personal use. I don't think so. Melani system use the same as american machines.

**Comment by keyb-cutter** [comment]
Actually they are both syllabic system, but Melani is an orthographic system (like the Velotype). Also if it is implemented on a US Stenotype keyboard  Melani system totally differs from the english steno  theory (which is phonetic) because the words are represented as they are written and the operator, writing the word endings, indicates also the space at the end of each word.
Besides Michela is a phonetic system (historically was the first steno phonetic keyboard to appear on the market in 1876) and so nowadays it is used by the italian Senate with a CAT system and translating dictionaries (like Stenotype, Grand Jean and Palantype). Anyway, due to the fact that Italian is a transparent language (grapheme=phoneme) it's very easy to develop an orthographic theory for the Michela and use it in the same way of Melani and Velotype.

**Comment by ossossosso** [comment]
My mistake. I wrote "syllabic" but I mean orthographic. Both are syllabic.

**Comment by Sillabix** [comment]
Anyway at the moment all the Michela manuals on the market are outdated and quite useless for computer aided transcription because they were written before the application of TE and the advent of the realtime theory for the Michela-MIDI keyboard in 2002. A new updated manual with the conflict free theory should be published in the near future.

**Comment by morinted** [comment]
@Sillabix wrote:

```
Bank one and bank four are used to write decades and numbers so you can write every number up to 99. If you have to write multiple numbers of 3 digits you write the first number in bank 4 then the other two in bank one and four. If the digits are four you write the first two and then the last two and so on. Then we use to write some words to mean hundreds thousands, million, billion etc, like "cent", "mila" for 000, "mion" for 000.000 and "miar" for 000.000.000. We don't need to reverse numbers cause with bank one and four you can write double digits in every order. About doubling number I discovered this trick reading the Plover lessons and I surely will adopt it. About currency symbols we don't use them at all because our reports are a bit formal and we tend not to use any symbol. Anyway, we don't use to write digits everytime. Sometime we need to write out numbers, like when they refer to days, week etc. We could never write in our reports "4 days" or "7 years" but always "four days" and  "seven years".(edited)
Also I'm starting to use the "U" key as a number bar, to avoid that numbers could come out when you make a misstroke and miss to write the vowel in bank 3.
```

**Comment by morinted** [comment]
Benoit Pierre has made good progress in implementing the MIDI keyboard protocol as well as the Michela layout. Once the next weekly is out the plugins will likely be available for Michela users to try.

**Comment by Sillabix** [comment]
Ok, grat. I'll soon share with the community the following: 

1) first Michela-Plover italian dictionary;
2) pdf with the realtime theory;
3) instructions to build a cheap Michela keyb starting from a MIDI keyb.

**Comment by Sillabix** [comment]
Ok, great. I'll soon share with the community the following: 

1) first Michela-Plover italian dictionary;
2) pdf with the realtime theory;
3) instructions to build a cheap Michela keyb starting from a MIDI keyb.

**Comment by Sillabix** [comment]
I'm preparing the dictionary above and I have some doubts about the correct prefixes/suffixes syntax to use for Italian. I read here https://github.com/openstenoproject/plover/wiki/Dictionary-Format that Plover can use some built in orthographic rules:  

> {^ish} is an orthographic-aware suffix that will add "ish" to the end of the previous word. E.g. RED/EURB will output reddish. Note: addition of a second "d" caused by Plover's understanding of English orthography

If this orthography understanding is based on English, I'm not sure if this can create problems with Italian. For instance, with TE is possible to modify the prefixes/suffixes rules table (c.d. "Intelligent prefix/suffix rules) just editing them in a special table. For instance, for the english suffix {^er} the rules "^er=&er,er,A[e]er,^[ey]ier,ker,&or,or,^[e]or,&ar,ar,^[e]ar,^[y]iar" produce the following changes of the root word: boast>boaster, brake>braker, comply>complier, family>familiar and so on. In the TE dictionary I'm using at the present time there are several "intelligent prefixes/suffixes" (with the {^word} {word^} syntax) together with specific rules for Italian (that are checked against an Italian spelling dictionary). What could happen leaving this syntax also in a Plover dictionary without any specific grammar rule for Italian?  Is it necessary to change all these intelligent prefixes/suffixes in standard prefixes/suffixes with the {^}word or word {^} syntax?

**Comment by morinted** [comment]
"Systems" do get their own set of orthography rules, and we can also supply an Italian word list for spelling look up.

It would be nice to have the list of orthography rules for implementation into the system.

**Comment by arxanas** [comment]
Is the plugin at https://github.com/benoit-pierre/plover_michela in a workable state?

**Comment by Sillabix** [comment]
Yes, it works. I'm still waiting for the Italian dictionary conversion from
rtf to json.

Il 20 feb 2018 08:52, "Waleed Khan" <notifications@github.com> ha scritto:

**Comment by Sillabix** [comment]
Here it is the latest plugin upgrade with the steno dictionary (a big thanks to Benoit Pierre).


https://github.com/benoit-pierre/plover_michela

**Comment by benoit-pierre** [comment]
Closing, as we now have everything needed for Michela support.

**Comment by Sillabix** [comment]
The instructions for building a keyboard were also missing. Here is a small tutorial I made. I hope you enjoy it.

https://youtu.be/q9Y9jtOB7G0
