### ISSUE TITLE
Grandjean French System

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#781]
Grandjean "V" layout for French stenography.

Thanks to the amazing work by @azizyemloul we have a lot of information to work off of to implement this system.

- https://github.com/azizyemloul/plover-france
- https://github.com/azizyemloul/plover-france-dict

I've been told by another user that the continental layout (the V layout) is available on an Élan Mira, and that it speaks the regular Stenograph protocol. This is the mapping that was observed:

```
// It is unclear to me which symbols have to be used. I believe it's at least one of these variants:
SKPMTF*RNLYOEAUI£ᴎ$D[
SKPMTF*RNLYOEAUILn$DC
// This is what the Mira displays:
SKPMTF*RNLYOEAUILn$D[

STKPWHRAO*EUFRPBLGTSD
```

Some discussion on the system was had on #134

**Comment by greenwyrt** [comment]
Implemented in https://github.com/stenomax/plover_grandjean
