### ISSUE TITLE
Stentura Protege wont connect via USB

### ISSUE THREAD

**Issue by huah007** [openstenoproject/plover#806]
Classification: UI/Usability

Reproducibility: Always, 

Plover won't look for anythingother than a serial port and I don't have one on my laptop.

## Steps to Reproduce

Evrytime you try to start up it won't connect to my writer.

1. I turn it on
2. It doen't work.

## Expected Results

3. it should connect to my writer

## Actual Results

3. Instead, it doesn't

If helpful, submit screenshots of the issue to help debug. Your `plover.log` or `strokes.log` may also be useful.

## Version

Plover version 3.1.1

## Notes

I tried to update my writers USB drivers and it still hasn't had an effect. 

If you've found a workaround, provide it here.

## Configuration

OS:  Windows 10

**Comment by morinted** [comment]
USB support for Stenograph machines is not ready for release, I'm waiting to hear back from the company regarding an issue with older models.

In the meanwhile the only solution is to run through serial, which involves getting a USB-to-serial adapter for your computer. You can read about [how to connect the 400SRT](https://github.com/openstenoproject/plover/wiki/How-to-setup-and-use-Plover-with-a-Stentura-400SRT) which should be pretty similar to the protege. As always, it's recommended to read your manual to see what it takes to get the machine transmitting serial.
