### ISSUE TITLE
Windows don't stay always on top

### ISSUE THREAD

**Issue by amikumanto** [openstenoproject/plover#811]
Classification: Bug

Reproducibility: Sometimes

## Summary

The paper tape and suggestions windows sometimes don't stay above other windows despite being set to always on top. Specifically, this seems to happen after always on top is disabled and then re-enabled, however this only occurs if I first select a non-Plover window. The only way to make the windows become always on top after this is to close & re-open them, and then set them to always on top without selecting a non-Plover window first. This only seems to happen sometimes though - once it starts happening it happens consistently, but I can't tell what causes it to initially occur.

## Steps to Reproduce

1. Open either the suggestions or paper tape window, and set it to always on top.
2. After verifying that it stays on top of other windows, disable always on top.
3. Switch to any window that isn't a part of Plover.
4. Switch back, and then re-enable always on top
5. Check if it still stays above other windows.

## Expected Results

6. It should stay above other windows

## Actual Results

6. It doesn't

## Version

Plover version 4.0.0.dev1+20.g60a373f.

Installed via: download from GitHub (it's the portable version if that makes any difference)

## Notes

For some reason, the issue persists ever after restarting Plover (although I think it goes away if I restart my computer). It may related to the version of windows I'm using, since this only started occurring after I came back from a period of not practicing or using steno and my computer auto-updated during that time. It may also be related to how long the system has been running or hibernation - I tend go for fairly long stretches without shutting down my computer, instead just hibernating it at night when it's not in use. I know this has caused issues with other programs in the past (most notably my mouse which will occasionally just stop working entirely when I resume), so maybe it's related to this too.

## Configuration

Windows 10 Version 1607 (OS Build 14393.1593)

**Comment by morinted** [comment]
This is likely a QT or Windows bug, I'm not sure we could fix it from within Plover.

**Comment by benoit-pierre** [comment]
Is it still an issue with the latest pre-release?

**Comment by amikumanto** [comment]
yes, as of plover-4.0.0.dev6+5.ga564116-win32 it's still an issue

**Comment by greenwyrt** [comment]
This appears to be fixed as of dev 12 (on windows at least)
