### ISSUE TITLE
Suggestion window shows wrong output for strokes starting with TKO*

### ISSUE THREAD

**Issue by Achim63** [openstenoproject/plover#820]
Classification: Bug

Reproducibility: Always

## Summary

Wrong output in suggestion window.

## Steps to Reproduce

1. Strike TKO\* or TKO\*EURBT

## Expected Results

As long as those strokes are not defined in any dictionary, they should appear as above in the suggestion window.

## Actual Results

For TKO\*:
\*:
   PWHRET
   STR*EUFBG

For TKO*EURBT:
EURBT: no suggestions

## Version

Plover version 4.0.0.dev2+35.gc5e03f6.

## Configuration

OS: macOS Sierra 10.12.6

<img width="445" alt="bildschirmfoto 2017-09-17 um 22 27 42" src="https://user-images.githubusercontent.com/10847639/30524605-743e4d10-9bf7-11e7-981f-293ba31eafd1.png">

**Comment by benoit-pierre** [comment]
That's not really how the suggestions window work: it looks at the recent output, split it into words, and give suggestions on those.

So when you use an un-translate like `TKO*`:
- the output is `TKO*`
- `TKO*` is split into 2 words: `TKO` and `*`
- a number of reverse lookups are performed (previous words +`TKO*`, `TKO*`, `*`), but none of them yield anything
- as a fallback, the last word is shown with the text "no suggestions"

**Comment by Achim63** [comment]
That's certainly confusing.
