### ISSUE TITLE
Request: retrospective title case meta

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#821]
Classification: Bug

Reproducibility: Always

## Summary

_**I have a stroke for "burden of proof." I wanted to write it as "Burden of Proof," so after stroking the outline, I then stroked the Cap Last stroke, and nothing happened.**_
## Steps to Reproduce

_**1. I stroke a phrase that I want the last word to be capitalized
2. I then stroke the Cap Last outline**_

## Expected Results

3. _**"Burden of proof" should have become "Burden of Proof."**_

## Actual Results

3. Instead, this happens. :(

_**I ended up with "Burden of proof."**_

If helpful, submit screenshots of the issue to help debug. Your `plover.log` or `strokes.log` may also be useful.

## Version

_**Plover version Plover 4.0.0.dev2+28.g37c65eb  (Mac OS X)**_

If the problem is known to be present in more than one version, please list all of those.

_**I've never tried to do that before, so I don't know if the same thing happens in other versions.**_
Installed via:  _** Download from openstenoproject.org**_

## Notes

_**Working on a transcript ... no time to troubleshoot, but I don't think that's anything I would have control over.**_

If you've found a workaround, provide it here.  _**No workarounds found**_

## Configuration

OS: _**Mac OS X 10.10.5**_

**Comment by morinted** [comment]
With #807 the retro-last-word command will *actually* operate on the last word, not the last stroke.

**Comment by benoit-pierre** [comment]
#807 will not change anything in this case, the last word is `.`, so `proof` will be unchanged.

**Comment by morinted** [comment]
Right, if the stroke is `burden of proof.` and not `burden of proof` then it won't work as expected.

**Comment by gdwaynewarner** [comment]
The stroke for "burden of proof" I'm using is PW*-URP.
The punctuation in the original post wasn't part of the stroke ... so I stroked the Cap Next stroke (KP-PB), then the stroke for "burden of proof," -- and again, the quotes and comma were _NOT_ included at the time -- PW*-URP, and finally, the Cap Last stroke, which gave me "_Burden of proof_" instead of the desired "_Burden of Proof_."

**Comment by gdwaynewarner** [comment]
Perhaps a retroactive "Title Mode" might be in order for what I'm looking for here.

... and speaking of title mode, little words like "of," "and," "to," etc. are not capitalized in a title, generally -- unless they're the first word in the title, that is.

**Comment by gdwaynewarner** [comment]
Any updates on this one?

**Comment by user202729** [comment]
I guess someone making a (macro) plugin is possible but there isn't too many people interested...

For now, a workaround is to define custom outlines for each one. (or make Python dictionary to generate them)

**Comment by greenwyrt** [comment]
Implemented with [plover-retro-text-transform](https://github.com/nimble0/plover_retro_text_transform)
