### ISSUE TITLE
Control_L(2) fails to activate macOS 10.12 Switch Desktop shortcut

### ISSUE THREAD

**Issue by fedde-s** [openstenoproject/plover#835]
Classification: Bug

Reproducibility: Always

## Summary

When I use the [Left Hand Modifier Keys](http://www.openstenoproject.org/stenodict/dictionaries/lh_modifier_keys.html) dictionary on my system, the macOS Mission Control shortcuts do not respond to the Control+1 through Control+9 chords to switch to different Desktops/spaces. 

## Steps to Reproduce

1. Open the **Mission Control** application (part of macOS) and enable at least two spaces in the top bar.
2. Open the **Keyboard** item in **System Preferences**, click the **Shortcuts** tab, navigate to **Mission Control** in the list on the left and enable the shortcuts of the form ‘Switch to Desktop 2’ — `^2`, while Plover is disabled.
3. Turn on Plover and stroke a set of chords that maps to `{#Control_L(2)}`, such as `KHR/#P` in the dictionary linked above.

## Expected Results

4. macOS should switch to Desktop 2, which probably has no open windows at this point, visually indicating the action by shifting sideways with the kind of smooth animation Apple users like in their UIs.

## Actual Results

4. macOS does not react to the shortcut in any way.

## Version

Plover version 3.1.1

Installed via: Homebrew (`brew cask install plover`)

## Notes

I also use [**Karabiner Elements**](https://pqrs.org/osx/karabiner/) to swap my CapsLock and Escape keys and to remap my menu key to a Compose key using an old [`DefaultKeyBindings.dict` file](http://lolengine.net/blog/2012/06/17/compose-key-on-os-x), but do not think that this affects these particular keys/modifiers.

According to the **Karabiner-EventViewer** application included in Karabiner Elements, the actual flags being sent with the digit include not only `Ctrl`, but also `Fn`. When I use the actual Control key on my (external) keyboard while Plover is disabled, it only lists the `Ctrl` flag.

I have also had issues with these Mission Control shortcuts using the regular Control keywhile Plover is enabled, but only the second or third time I use the same shortcut. Control-based shortcuts in text-mode tools running in [iTerm2](https://www.iterm2.com/) seem to work fine in all three ways (without Plover enabled, with Plover enabled and by means of Plover)

## Configuration

OS:
```ShellSession
% sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G1036
```

**Comment by fedde-s** [comment]
@morinted, commit 6ff6a5912a55f1a9c42a83544c88af2f2980161f in `master` indicates that you have some experience with the combination of the `Ctrl` and `Fn` modifiers in macOS Sierra. Is that commit included in the current release, and if not, can it be included in a 3.1.2 release? Plover is practically unusable for me as an [Amethyst](https://ianyh.com/amethyst/) user until it is, as I have to ploggle every single time I want to switch to a different window.

**Comment by benoit-pierre** [comment]
You could also install the latest v4.0.0 weekly.

**Comment by benoit-pierre** [comment]
Note that 6ff6a59 has been cherry-picked as 6b82870d, so it's already part of 3.1.1. I suggest you test whether the latest development version fix your issue or not.

**Comment by fedde-s** [comment]
Thank you for the immediate response, @benoit-pierre. I will look into how to install and track that branch of releases later.

**Comment by fedde-s** [comment]
Although the commit you just linked looks like a completely unrelated one to me.

**Comment by fedde-s** [comment]
Ah, never mind, you probably meant <https://github.com/openstenoproject/plover/commit/587716ea5d2d712304005041e0d803cd1e4f78f7>.

**Comment by benoit-pierre** [comment]
Yep, I got it wrong, it's 587716ea. Also latest development version can be installed from here: https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev5%2B9.gba958374

**Comment by fedde-s** [comment]
Thanks again!

**Comment by fedde-s** [comment]
Both my issues are solved in 4.x.x!! I am currently slowly but happily practicing my steno skills by writing this message in chords on a low-cost gaming keyboard, all in my preferred setup. I look forward to being able to keep this version up to date using homebrew or pip. Thank you once again for the fast and helpful replies!

**Comment by morinted** [comment]
Thanks for the follow-up 👍
