### ISSUE TITLE
All Caps Last Word Behavior 

### ISSUE THREAD

**Issue by Wilfried84** [openstenoproject/plover#838]
Classification: Usability

Reproducibility: Always

## Summary

When I write out a raw steno outline, I fingerspell it in lower case, with / and *, followed by an all caps stroke. In the previous version of Plover, it would make the whole thing all caps. Now it'll only upper case up to the last / or *. So to get the whole thing all caps, one has to hit the caps stroke before each / and *. Could we have a way to get back the old behavior? (I used Pover v. 3 until the latest weekly.)

## Expected Results

TEFT/TH/AOT/LAOIN

## Actual Results

teft/th/aot/LAOIN

## Version

weekly-v4.0.0.dev5+9.gba958374

**Comment by Wilfried84** [comment]
To add, I discovered that all caps also stops at an apostrophe. So if you try to all caps don't, you end you with don'T. Using a capitalize stroke after it also results in don'T.

**Comment by morinted** [comment]
This seems to be in the same vein as #836

**Comment by Wilfried84** [comment]
Ah, didn't see that.

**Comment by benoit-pierre** [comment]
It would be more efficient to use the [`show_stroke.py` Python dictionary](https://github.com/benoit-pierre/plover_python_dictionary/blob/master/test/show_stroke.py) for outputting raw strokes.

**Comment by morinted** [comment]
Uppercasing the entire last word (up to spacing, treating symbols as part of the word) could be a plugin. I do think that there are easier ways to write raw steno than fingerspelling, though.

**Comment by morinted** [comment]
No plans to implement this behavior at the moment. The show_stroke.py python dictionary should be adequate for writing raw steno.
