### ISSUE TITLE
Strange behaviour when using the toggle asterisk translation.

### ISSUE THREAD

**Issue by LukeSilva** [openstenoproject/plover#849]
## Summary
Strange behaviour when using the toggle asterisk translation.

## Reproducing
The following blackbox tests describe the strange behaviour, and what I would expect the output to be.
```
    def test_bug849a(self):
        r'''
        # Fails on the third stroke with ' due'
        "-P": ".",
        "*P": "{*}",
        "TKAOU": "due",
        "TKAO*U": "dew",

        TKAOU  ' due'
        -P      ' due .' 
        *P     ' dew'
        '''

    def test_bug849b(self):
        r'''
        # Fails on the third stroke with ' dew'
        "KPA*": "{^}{-|}",
        "*P": "{*}",
        "TKAOU": "due",
        "TKAO*U": "dew",

        KPA*   ''
        TKAOU  'Due'
        *P     'Dew'
        '''
```
## Plover Version
Latest master, commit 8886a7c77ffe5d0d32f3e7c742338d37c3d8b068

## System
Ubuntu Linux 16.04

**Comment by benoit-pierre** [comment]
I already have a fix for that in a6e8acd1dc69cde62dab2f9a9becbac27092a96d, I'll make a PR.
