### ISSUE TITLE
After stroking return, Plover deletes the last letter of the last word

### ISSUE THREAD

**Issue by GriffinTy** [openstenoproject/plover#851]
## Summary

I have R-R defined for return `{^}{#Return}{^}{-|}`. When I stroke it, the first one creates a backspace, erasing the last letter of the last word stroked.  Ted pointed out that this happens on space after, but not space before. 

## Reproducing

```python
    def test_spaces_deleted(self):
        r'''
        "KUPBTS": "countries",
        "R-R": "{^}{#Return}{^}{-|}",

        :spaces_after
        KUPBTS "countries "
        R-R "countries"
        '''
```

## Plover Version

 Plover 4.0.0.dev5+9.gba95837

## System

Ubuntu 16.04

**Comment by benoit-pierre** [comment]
It's normal, no? Because of `{^}` the trailing space is removed. It's the same if you use `TK-LS` (`{^^}`) after stroking `countries`.

**Comment by morinted** [comment]
The black box test fails, you get "countri" instead of "countries"

**Comment by benoit-pierre** [comment]
Ah, never mind then.
