### ISSUE TITLE
Mac: Plover does not see keypresses from Python virtual keyboard

### ISSUE THREAD

**Issue by jarmitage** [openstenoproject/plover#867]
## Summary

I have a custom device for which I am developing a Python program to create the key press events, however Plover does not seem to register keypresses from the `pykeyboard` and `pynput` libraries that I have tested with, which are both based on the Quartz Python package.

## Reproducing

This is my Python script for generating keypresses, testing using the aforementioned libraries. Neither library's keypresses are output in the Plover Stroke Display window.

```python
import time
import sys
import json
from pythonosc import dispatcher
from pythonosc import osc_server

import pykeyboard
k = pykeyboard.PyKeyboard()

from pynput.keyboard import Key, Controller
keyboard = Controller()

def press_key (unused_addr, key):
    k.press_key(key)
    # keyboard.press(key)
    print ("Key pressed: {}".format(key))

def release_key (unused_addr, key):
    k.release_key(key)
    # keyboard.release(key)
    print ("Key released: {}".format(key))

if __name__ == "__main__":
    dispatcher = dispatcher.Dispatcher()
    dispatcher.map("/press_key", press_key)
    dispatcher.map("/release_key", release_key)

    server = osc_server.ThreadingOSCUDPServer(("127.0.0.1", 57130), dispatcher)
    print("Serving on {}".format(server.server_address))
    server.serve_forever()
```

## Plover Version

3.1.1

## System

macOS Sierra 10.12.1

**Comment by benoit-pierre** [comment]
I would be easier to develop a custom machine plugin rather than try to emulate key press/release events in the hope that Plover can use them with the keyboard machine: after all, Plover itself needs to simulate key events, which means that those must be ignored by the keyboard machine.

**Comment by jarmitage** [comment]
Can you explain what you mean by "custom machine plugin"?

For the device I am working on, it makes less sense at this point for it to send keypresses itself, since there is some sensor signal processing required which I prefer to develop on my desktop.

I have previously been using the following Java imports to make virtual keyboards that work with Plover. I have been trying to port this to a new setup that gets away from Java (inside Processing).

```java
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
```

**Comment by benoit-pierre** [comment]
Example machine plugins:
- https://github.com/benoit-pierre/plover_midi
- https://github.com/morinted/plover-treal

**Comment by jarmitage** [comment]
Ok I think I get it. So it's an API for external devices to input strokes into Plover?

If I created one of these, how would I add it to Plover?

**Comment by benoit-pierre** [comment]
For development, you should run Plover from source, and add your plugin directory to PYTHONPATH or use an editable install (`pip -e .` or `setup.py develop`).

Once the development is done, you can publish your package to PyPI and people will be able to install it using the [plugins manager](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev5%2B9.gba958374).

**Comment by jarmitage** [comment]
Super, thank you @benoit-pierre.
