### ISSUE TITLE
Add friendly names for built-in metas

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#870]
## Summary
We should add friendly names for built-in metas like was done for macros.

**Comment by nsmarkop** [comment]
Just for my clarification, is this to get all the sorts of things for capitalization, currency, etc. in https://github.com/openstenoproject/plover/wiki/Dictionary-Format#text-formatting extracted out to a place like plover.meta by implementing them all as meta plugins with nice names? With aliases to the old syntax for use in plover.formatting.
