### ISSUE TITLE
Serial protocols can be broken by enabling Xon/Xoff

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#876]
## Summary

Certain TX Bolt users have noticed that SW- chords don't work when Xon/Xoff is enabled. I've written a note in the wiki instructing users to [disable the setting](https://github.com/openstenoproject/plover/wiki/Troubleshooting:-Common-Issues#when-using-tx-bolt-any-chord-with-sw--in-it-doesnt-come-out-right) but it is troublesome that it is possible to enable it in the first place when it couldn't serve any utility for these machines.

## Reproducing

- Enable Xon/Xoff in serial settings for TX Bolt
- Write a chord with SW in it, such as SWEUFT
- Paper tape should show SWEUFT, but only shows EUFT.

**Comment by benoit-pierre** [comment]
Fixed by #880.
