### ISSUE TITLE
Add fast system switching

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#877]
## Summary

There have been several recent requests (Russian, Danish) to change the steno system on the fly. I think we should consider it as a feature request for people who eventually plan to write in multiple languages with rapid switching with Plover.

**Comment by benoit-pierre** [comment]
This can be trivially done with a command plugin.

**Comment by nsmarkop** [comment]
I wrote the trivial command plugin to do this for anybody that wants to use it:

https://github.com/nsmarkop/plover_system_switcher

Is this functionality something that would ideally be done in Plover's engine or is a plugin the long term vision of it?

**Comment by benoit-pierre** [comment]
The goal is really to offload as much as possible to plugins, keeping the core of Plover simple. Note that even if the functionality is not implemented in Plover directly, we can always ship it together with other essential plugins we automatically include in our distributions (like we do for Treal support and the plugins manager).

**Comment by nsmarkop** [comment]
Interesting bug that only seems to happen with this fast switching via a stroke (using my plugin) but not when switching via the Configuration menu.

Steps:
1. Have two systems that don't share all of their keys
2. Open up the Paper Tape
3. Type some stuff that includes some of the keys that aren't shared
4. Type your stroke that executes the system switching command
5. Get an unhandled exception like the one below:

``` zsh
{ plover } master » Traceback (most recent call last):       /cygdrive/o/Software/Projects/plover
  File "O:\Software\Projects\plover\plover\gui_qt\paper_tape.py", line 122, in on_stroke
    self._show_stroke(stroke)
  File "O:\Software\Projects\plover\plover\gui_qt\paper_tape.py", line 114, in _show_stroke
    text = self._formatter(stroke)
  File "O:\Software\Projects\plover\plover\gui_qt\paper_tape.py", line 106, in _paper_format
    index = system.KEY_ORDER[key]
KeyError: 'K-'

```

**Comment by benoit-pierre** [comment]
Closing this issue, thanks to @nsmarkop's plugin. @nsmarkop: can you open a dedicated issue for the problem report in your last comment?
