### ISSUE TITLE
Toggle Asterisk stroke cannot be used in other translations

### ISSUE THREAD

**Issue by LukeSilva** [openstenoproject/plover#884]
## Summary

The toggle asterisk stroke cannot be used as a stroke within a multi-stroke translation

## Reproducing

```
    def test_bug884(self):
        r'''
        "*P": "{*}",
        "AUS": "auscultate",
        "A*US": "Australia",
        "AUS/*P/*P": "AUS",
        "A*US/*P": "Austria",

        AUS     ' auscultate'
        *P      ' Australia'
        *P      ' AUS'
        *       ' Australia'
        *       ' auscultate'
        *       ''
        A*US    ' Australia'
        *P      ' Austria'
        '''
```

## Plover Version

git: 866ad93

## System

Ubuntu 16.04.3 running via source, in unity DE.

**Comment by benoit-pierre** [comment]
That's how macros work: similarly to undo, macros can only be mapped to a single stroke, and they always match, so you can't use the same stroke as part of other multi-strokes definitions.
