### ISSUE TITLE
Undo new paragraph deletes extra letters (MacOS)

### ISSUE THREAD

**Issue by millipz** [openstenoproject/plover#891]
## Summary

When undoing (*) new paragraph stroke (SKWREURBGS), extra letters are deleted.

## Reproducing

If I stroke:

```
  T    R   EU          
  T   H                
 S K W RA   U R B G S  
          *           
```

I get: "Try t" as the final output.

Tested in Safari, Chrome, Stickies, TextEdit

## Plover Version

4.0.0.dev6+5.ga564116

## System

MacOS 10.12.6

**Comment by benoit-pierre** [comment]
What's your "new paragraph" definition? For reference: `{#Return}` is not undoable, but `{^\n^}` is.

**Comment by millipz** [comment]
I'm using the default commands.json. The definition is ```{#Return}{#Return}{^}{-|}```

**Comment by benoit-pierre** [comment]
So `SKWRAEURBGS` / `SKWRAURBGS`. It's normal, if you want to be able to undo those, replace `{#Return}` by `{^\n^}`.

**Comment by millipz** [comment]
Okay thanks!

Can I ask out of curiosity why `{^\n^}` is not used in the default dictionary?

**Comment by benoit-pierre** [comment]
I guess it would make sense to update some of those definitions.

**Comment by benoit-pierre** [comment]
Made a note in #400.

**Comment by millipz** [comment]
Brilliant, thank you for your help!
