### ISSUE TITLE
Error when switching systems with Paper Tape open

### ISSUE THREAD

**Issue by nsmarkop** [openstenoproject/plover#893]
## Summary

When switching systems via a command like [my plugin](https://github.com/nsmarkop/plover_system_switcher) with the Paper Tape open an error always happens when the keys used in the switching stroke are not in the system that was switched to.

## Reproducing

Steps:
1. Have two systems that don't share all of their keys
2. Open up the Paper Tape
3. Type your stroke containing keys that aren't shared between the two systems that executes the system switching command
5. Get an unhandled exception like the one below:

``` zsh
{ plover } master » Traceback (most recent call last):       /cygdrive/o/Software/Projects/plover
  File "O:\Software\Projects\plover\plover\gui_qt\paper_tape.py", line 122, in on_stroke
    self._show_stroke(stroke)
  File "O:\Software\Projects\plover\plover\gui_qt\paper_tape.py", line 114, in _show_stroke
    text = self._formatter(stroke)
  File "O:\Software\Projects\plover\plover\gui_qt\paper_tape.py", line 106, in _paper_format
    index = system.KEY_ORDER[key]
KeyError: 'K-'
```

The above was the result of switching between the standard English system and [my WIP Korean system](https://github.com/nsmarkop/plover_korean). I was using `KASZ` to switch from English to Korean.

## Plover Version

Running from source - d5c8e45.

## System

Windows 10

**Comment by benoit-pierre** [comment]
Should be fixed by #1452.
