### ISSUE TITLE
Error when attempting to edit a read-only dictionary

### ISSUE THREAD

**Issue by nsmarkop** [openstenoproject/plover#897]
## Summary

When trying to edit a read only dictionary, Plover always crashes with the following trace:

``` cmd
O:\Software\Projects\plover>edit: editing failed
Traceback (most recent call last):
  File "O:\Software\Projects\plover\plover\gui_qt\dictionary_editor.py", line 384, in on_finished
    in self._model.modified)
  File "O:\Software\Projects\plover\plover\steno_dictionary.py", line 271, in save
    d.save()
  File "O:\Software\Projects\plover\plover\steno_dictionary.py", line 74, in save
    assert not self.readonly
AssertionError
```

Obviously if a dictionary is code / read only then someone shouldn't be wanting to edit it through the Dictionary Editor but it doesn't appear to be restricted.

## Reproducing

1. Add a read-only dictionary (like a .py dictionary via the plover-python-dictionary plugin)
2. Double click the dictionary in the main Plover window to open up the Dictionary Editor window
3. Click the "Add a new translation" button
4. Click the X on the Dictionary Editor window without having entered anything
5. Error out / crash

## Plover Version

Running from source - d5c8e45.

## System

Windows 10

**Comment by morinted** [comment]
@nsmarkop are you able to confirm that #1007 fixes this issue?

**Comment by morinted** [comment]
Okay, so even if we merged that I'd want to keep this open.
