### ISSUE TITLE
Add second-class support for certain dictionary formats (RTF)

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#909]
## Summary

Treating RTF as a fully-supported format is dishonest as it fails round-trip saves. And, as RTF is meant to be an interchange format, it can be misleading to convert some Plover-specific syntax to RTF as it will have no meaning in other steno software.

The barrier between RTF and Plover-native dictionary formats should be made more clear, likely by implementing an import/export system (which could also handle conversions between native formats, potentially).

**Comment by gdwaynewarner** [comment]
Thanks, Ted.

I can't say for sure, but I am fairly sure that many new students o' steno are starting with Plover and an .rtf version of a theory dictionary.  Eventually, they may end up in a school and have to learn to use regular CAT software, and discover that many of their outlines are suddenly broken.

Adding "Export to .rtf" should (hopefully!) take care of that.

**Comment by greenwyrt** [comment]
Saving to rtf from plover is implemented in [plover-better-rtf](https://github.com/sammdot/plover-better-rtf/)
