### ISSUE TITLE
Only save the configuration when it's explicitly modified

### ISSUE THREAD

**Issue by benoit-pierre** [openstenoproject/plover#915]
The current behavior is to save the configuration on exit, always:
* if plover somehow crashes, any changes to the configuration are lost
* invalid manual changes to the configuration will also be lost, replaced by default values

**Comment by millipz** [comment]
Hi, this might be niggling, but I would expect the config to be saved on shut down if Plover is running in the background. I've no idea of the logistics of this, but it's a pretty common use case I imagine. I'm running v4 on windows 7

**Comment by km-pg** [comment]
+1 for this. My computer crashed recently and Plover went back to the old state. It was rather annoying, so hoping configuration will be saved to disk when it is changed in the future.

**Comment by mulka** [comment]
+1 for this. My computer crashed recently and Plover went back to the old state. It was rather annoying, so hoping configuration will be saved to disk when it is changed in the future.

**Comment by benoit-pierre** [comment]
Closed by #1123.
