### ISSUE TITLE
Can't download Plover to Windows 7

### ISSUE THREAD

**Issue by mikesimoli** [openstenoproject/plover#916]
## Summary

No matter how many times I click on the v 3.1.1. link in Github, it won't download for Windows 7.  I click but nothing happens.  No install wizard, no additional tab, no popup, nothing.  :(

## Reproducing

1.  Visit Plover Page.
2.  Click on "Download Stable Edition"
3.  Click on v. 3.1.1. for Windows.
4.  Nothing happens.  

## System

Windows 7, Internet Explorer 11

**Comment by morinted** [comment]
Is it possible that you have an antivirus that is swallowing the download?

**Comment by mikesimoli** [comment]
Maybe I guess but then usually I get a warning "do I want to proceed" or "do I trust the content".  I have Norton 360

**Comment by gdwaynewarner** [comment]
Might be good if you were to try closing Norton down, download the file -- though you should probably download a copy of the preview of version 4.0 instead:

https://github.com/openstenoproject/plover/releases

If that doesn't work, you may have to rely on "Sneaker-Net" ... which is where you go to somebody else's computer, download the file, save it to a flash drive, and install it that way.  

Good luck!
