### ISSUE TITLE
Feature Request: Ability to Merge Two Dictionaries

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#922]
## Summary

I have an .rtf dictionary that has my outlines for writing Cheap and Sleazy, which require the "keep with next" symbol (you know ... {^} which I use to ensure there are no extra spaces anywhere, basically).

Somewhere along the way, that feature stopped working in Plover, so this --

**{^}&lt;p class=&quot;body&quot;&gt;{^} {-|}**

-- became this:

**{^ &lt;p class=&quot;body&quot;&gt; ^} {^} {-|}**

I followed Ted's recommendation and created a .json dictionary for that, so all of those entries exist in that dictionary.

Now that support for most of the dictionary formats is coming, I would like to be able to basically merge those two dictionaries, so that I could make them available to one of the professional CATs, should the need arise ... preferably without having to copy and paste each entry one by one.

In digitalCAT's Dictionary Maintenance program, I would just right-click the entry and select either "Copy to" or "Move to," which would then present me with a file navigation window so I could select the appropriate dictionary.

In the case of multiple entries, the Dictionary Maintenance program has "Merge Dictionaries," which works as you would expect.

Ultimately what I'm trying to do is copy all of the entries in the big dictionary (.rtf) to the smaller dictionary (.json), without having to do it one entry at a time.

## Reproducing

No real way to reproduce this one, other than using the outlines I posted up there in an .rtf dictionary, quit Plover, start it again, and check to see if the outline works correctly.

## Plover Version

Plover 4.0.0.dev6+5.ga564116   

## System

Mac OS X 10.10.5

**Comment by gdwaynewarner** [comment]
So  ... is anything going on with this one?

**Comment by SeaLiteral** [comment]
It sounds/looks like a plugin could be made for it...

**Comment by morinted** [comment]
One way I've pictured this in the dictionary editor:

- Have the ability to open multiple dictionaries at once in the editor. (conflicts between dictionaries should be highlighted some way)
- Include a "Save as..." which will save the current view, including filters, of the dictionary editor.
  - e.g. you filter for translations with `{#` in them and then save-as to get a commands dictionary.
  - after saving, you are given the option to add the newly created dictionary to the list of dictionaries.

**Comment by gdwaynewarner** [comment]
Sounds good, Ted!
On a (slightly) nother matter, I noticed that a few of my mode strokes were working, so I re-defined the first one, and as I was trying to add it to the .json dictionary vice the RTF dictionary, I found that the .json dictionary somehow was made inactive.

As I was having other problems at that point (slow browser, Finder not responding at one point, etc.), I decided to quit everything and run [Onyx](https://www.titanium-software.fr/en/onyx.html), so hopefully that took care of whatever issue was going on there.

**Comment by benoit-pierre** [comment]
Implemented in #1244.
