### ISSUE TITLE
Unable to Update to the New Version of the Plugin Manager

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#923]
## Summary

I started the Plugin Manager to see if there were any updates for the plugins I have installed, and I saw that there was an update for the Plugin Manager itself.

Unfortunately, when I tried to install it, I got this in the dialogue window:

**_Could not find a version that satisfies the requirement plover[gui_qt]>=4.0.0.dev8 (from plover-plugins-manager==0.5.11.dev0) (from versions: 2.2.0, 3.1.0, 3.1.1, 4.0.0.dev7)
No matching distribution found for plover[gui_qt]>=4.0.0.dev8 (from plover-plugins-manager==0.5.11.dev0)_**

## Reproducing

Essentially, I just opened the Plugin Manager, clicked the "State" field twice, so it would display my installed plugins, noticed that the Plugin Manager itself was outdated, clicked the Plugin Manager field in the State field, and then clicked the Update button.

The text I pasted in was from the dialogue box that appeared during the update.

## Plover Version

Plover 4.0.0.dev6+5.ga564116 

## System

Mac OS X 10.10.5

**Comment by Fubrite** [comment]
I have the same problem on Linux Mint 18.3.

I'll update with my version of Plover and the error message ASAP.

**Comment by benoit-pierre** [comment]
That's because the latest version require a newer version of Plover. This will be fixed once we may a new weekly.

**Comment by gdwaynewarner** [comment]
Ah, good to know! Thanks, Benoit-Pierre.
