### ISSUE TITLE
Plover does not save port selection

### ISSUE THREAD

**Issue by aaplmike** [openstenoproject/plover#925]
## Summary

Hello. I have a Stentura 400SRT and MacBook Pro, using a USB serial adapter into a null modem cable. Plover's configuration screen sees /dev/cu.usbserial (via the Prolific driver), and I can select it. However, trying to connect always get "errno 2: can't connect to None". WHen I go back, the wrong port is selected (the first on the list is selected)>

I've also just tried selecting /dev/cu.usbserial, saving, then immediately going back into Configure and it's already changed the port back to the first in the list.

## Reproducing

0) turn off Stentura
1) Attach null serial cable to DB9 port on back
2) Attach other end to USB Serial adapter
3) Turn on steno machine
4) Launch Plover
5) Configure
6) Select '/dev/cu.usbserial'
7) Select 9600, N81 with no HW/XON-OFF boxes checked
8) Attempt to connect
9) Get error

## Plover Version

3.1.1

## System

MacOS High Sierra (10.13.3)

**Comment by aaplmike** [comment]
I've verified the USB Serial cable is seen by the system. I've tried both straight through and null modem cables. The red light on the Stentura never illuminates in any manner. I'll try to connect to one of my other serial devices to verify the USB Serial adapter is indeed working from the computer end.

**Comment by benoit-pierre** [comment]
Might have been fixed by #1036. Feel free to re-open if you can reproduce the problem with the latest v4.0.0.
