### ISSUE TITLE
Plover is very slow

### ISSUE THREAD

**Issue by Twey** [openstenoproject/plover#927]
## Summary

I use Plover on two machines, via TX Bolt from an Ergodox.  On one machine, Plover works as expected: pressing a key causes the corresponding word to be written.  On the other, my home machine, Plover is very slow, with uneven delays of up to two seconds between typing a simple brief and having the word appear in its window.  The machine specifications and configurations are almost identical.  I packaged and ran 4.0.0.dev6 in the hope that this problem would be solved, but it is not.

In a bizarre twist, I have discovered that if I should `strace` (to a console) one of Plover's child threads, Plover begins responding immediately to my keypresses.  On detaching the strace, it resumes lagging.  `strace`ing to a file does not have this property; I can only surmise that delaying one of the syscalls to write to the console is what causes Plover to become more responsive.

I tried to record a video to show the effect, but the overhead of recording also seems to mitigate it significantly :(

## Reproducing

- launch Plover
- type

## Plover Version

4.0.0.dev6

## System

Linux, NixOS, xmonad

**Comment by benoit-pierre** [comment]
So there's no delay with the keyboard machine?

**Comment by Twey** [comment]
The machine has no (noticeable) delay itself.  Whilst `strace`ing Plover, steno is crisp and responsive.

**Comment by benoit-pierre** [comment]
What I mean is when using NKRO, instead of TX Bolt emulation. In other words, is the delay only present when using the TX Bolt machine?

**Comment by Twey** [comment]
Oh!  No, keyboard input is also delayed.

**Comment by benoit-pierre** [comment]
OK, if you enable the paper tape, you see a delay between the end of a stroke, and the time it appears on the tape? Or it's delayed at the output stage?

**Comment by benoit-pierre** [comment]
What differences are there between the environments of your 2 machines? Same Linux distributions? Python versions? Xorg versions? Same window managers?

**Comment by Twey** [comment]
Ah, good call.  No, the paper tape shows the stroke immediately, but there's a delay between its appearance on the tape and its appearance in a window.

My systems are almost identical, both running the same Linux distribution, same window manager, same Python versions, probably the same Xorg versions.  There may be some minor differences (I don't have access to my other machine at the moment to compare — it's in the office) but they are both running NixOS unstable, updated within the past week or so.

**Comment by benoit-pierre** [comment]
It would be a good idea to the versions of all the dependencies used by Plover, just to make sure.

**Comment by Twey** [comment]
Never mind — I notice another pattern: I was using my terminal window to test.  Seems it's the terminal that's at fault here: other applications don't show the delay.

Sorry for wasting your time!

**Comment by benoit-pierre** [comment]
Out of curiosity, what's the terminal? I myself have noticed some issues with kitty: no delays, but when Plover send consecutive backspaces, it does not always work.

**Comment by Twey** [comment]
It's xfce4-terminal, GTK-based. I'm not sure why it has this behaviour but it might be something to do with GTK_IM_MODULE. It's a bit awkward to test because it has a daemon.
