### ISSUE TITLE
CaseCATalyst Dictionary Imports With No Entries

### ISSUE THREAD

**Issue by gdwaynewarner** [openstenoproject/plover#940]
## Summary

I downloaded the Phoenix Theory StenoKeys dictionary from the Phoenix Theory website:

http://www.phoenixtheory.com/job-dictionaries-for-all-pt-editions

When I tried to open it within Plover, the resultant dictionary was empty.

## Reproducing

I downloaded the file from the link I posted above (http://www.phoenixtheory.com/job-dictionaries-for-all-pt-editions), decompressed the link, and attempted to open the dictionary from within Plover.

![screen shot 2018-04-17 at 2 44 34 pm](https://user-images.githubusercontent.com/17680111/38900010-bbd616b4-424e-11e8-826f-69ada40b11f4.png)

## Plover Version

Plover 4.0.0.dev8

## System

Mac OS X 10.10.5

**Comment by benoit-pierre** [comment]
This is a known issue with this plugin and the Eclipse and Digital ones: https://github.com/marnanel/plover_eclipse_dictionary/pull/6. The dictionary are actually correctly loaded, but their contents is not shown in the editor.

**Comment by gdwaynewarner** [comment]
Ah, that's good to know! Thanks, Pierre! I will keep the Case dictionary around for future testing when this bug is properly stomped!

**Comment by winstond** [comment]
Just a side note - I don't think this page has a Pheonix Theory dictionary on it, just specific dictionary "ammendments"...
http://www.phoenixtheory.com/job-dictionaries-for-all-pt-editions

I wonder if that is possibly an issue?

Looking at the screenshot provided, I downloaded that file and it is tiny - no way it has 130K Phoenix Theory definitions in it.

**Comment by gdwaynewarner** [comment]
Hi, Winston.

Yes, the StenoKeys dictionary is a special dictionary for CaseCATalyst that allows the stenographer to basically do what Plover does -- write into other applications.

It also includes a few other commands that Plover now has (Select All, for one, cursor movement commands for another) ... and it only has 125 entries.

[(http://www.phoenixtheory.com/wp-content/uploads/2016/03/Documentation_Case-CATalyst-StenoKeys-v2.pdf)]

.... but since it was in Case format, I thought it would be an ideal dictionary to test the new plugin with.

**Comment by winstond** [comment]
That seems to use an .sgdct file rather than the usual .dct file. 
Since it not a JET MDB file like the other .dct files I'm not sure how it would be read in since that is what the plugin expects.

And then once it is read in, it would be a question of matching the commands in CaseCATalyst to the equivalent commands in Plover.  If Plover uses the exact same command language (doubtful) then maybe not too hard - otherwise very hard/manual/error prone as a lookup file from one set of commands to another would have to be maintained.  Much different than just simple mapping of keys, with some manipulations to sort out if a Plover - needs to be added or other symbols for prefix/suffix using the Flags field in the CaseCATalyst file format.

I don't think it would be wise to try to maintain that.  However you _could_ allow a knowledgeable user to supply their own mapping file which could be used to do the conversion with anything not in the mapping, and not a regular keystroke pattern, to be dropped with a log somewhere of what didn't make it in.

**Comment by gdwaynewarner** [comment]
Yes, that is true, but I also had the same issue with the other two
dictionary converter plugins. I think they're supposed to be fixed, but
still nothing released in the form of a new plugin ...?

**Comment by gdwaynewarner** [comment]
I ran into a court reporting student the other day who can no longer access the student version of her CAT software (Case, for the curious) because she is no longer a student.

During our conversation (on Facebook), I mentioned these dictionary plugins, and that they don't work in the current version of Plover, but the problem has been identified and fixed, but not implemented until the next release.

It's been nearly 18 months without a weekly. Howzabout a pre-release weekly with support for the new plugins? That would help a *LOT* of students and potential Plover users.

**Comment by morinted** [comment]
I don't think the dictionary plugins are ready for action yet, unrelated to
the current version of Plover.

**Comment by gdwaynewarner** [comment]
Did I misread this one?

[https://github.com/marnanel/plover_eclipse_dictionary/pull/6](url)

**Comment by morinted** [comment]
That pull request is what's required to fix the plugin for usage in Plover.

**Comment by gdwaynewarner** [comment]
That's good, right? Because if that fix is implemented, the plugin would work correctly ... or am I missing something?

**Comment by gdwaynewarner** [comment]
Any updates on this one?

**Comment by user202729** [comment]
As you can see, the bottleneck here is that the author of that plugin is inactive and won't merge pull requests.

You can install from Benoit's fork at https://github.com/benoit-pierre/plover_eclipse_dictionary/tree/fix_implementation (which is the source of the pull request) instead. There are guide on how to install package from GitHub.

**Comment by gdwaynewarner** [comment]
Good to know! Thanks!

**Comment by benoit-pierre** [comment]
Closing, as there's really nothing actionable here.
