### ISSUE TITLE
Jackdaw / Kinglet plugins?

### ISSUE THREAD

**Issue by Timbus** [openstenoproject/plover#945]
Hi. I was just learning about alternative steno systems and I noticed that a few years ago there were a few attempts to get 'Jackdaw' support into plover, but it wasn't really possible at the time.

I am very keen on trying out jackdaw to see if I prefer it to steno, so I was wondering if any progress could be made to have them made into plugins now that 4.0 is out? I'd attempt to do it myself but not really familiar with the plover plugin system, not to mention a lot of the work seems to have been done by Benoit-Pierre already.

**Comment by greenwyrt** [comment]
Plugins for these two layouts have been implemented. See [wiki page](https://github.com/openstenoproject/plover/wiki/Steno-Layouts-%26-Supported-Languages)
