### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by dragon7fly** [openstenoproject/plover#949]
I am unable ti=o install Plover on my windows machine. I have a compatible keyboard, but the application does not install properly and I get the error

![capture](https://user-images.githubusercontent.com/39173981/39984735-fad73c0e-5710-11e8-96f5-988af128d0a6.PNG)

**Comment by benoit-pierre** [comment]
Plover cannot write to `c:\Users\Melissa\AppData\Local\plover\plover\plover.log`:
* does that file already exists?
* can you check the permissions of that file or the parent folders?

**Comment by DanLanglois** [comment]
I see here, the use of user's %APPDATA% for personal data. I think that indeed, most applications store their settings in the Application Data folders at C:\Users\username\AppData\, by default. But, each Windows user account has its own Application Data folders. This, is so each Windows user account can have its own application data and settings if programs use this folder. 

I think that all users will have permissions to their own AppData folders. 

So okay, starting over, I see here the use of user's %LOCALAPPDATA% for personal data. But, just to be clear, I guess not shared data? I mean this as a Plover dev question: will your error log file be user specific? If different users run the app on the same computer will you have different logs? Or rather can you have? 

Anyways, there is %ProgramData% for shared data, although this folder is hidden. Also, some applications—especially PC games—choose to store their settings under the Documents folder at C:\Users\username\Documents. This makes it even easier for people to find, back up, and edit these files.

So I'm considering: where would be the best "standard" place to put an application's debug log file in a Windows user environment? If I put the logs somewhere in %appdata%, this means that each user has its own set of logs.  I'd prefer having all logs at a single location..?
