### ISSUE TITLE
Strokes.log also logs when plover is paused

### ISSUE THREAD

**Issue by JeremyGG** [openstenoproject/plover#979]
## Summary

 When Plover is paused, it will continue to log strokes as if I'm still using it, so it would also log stuff like WASD when playing video games.  To me this seems like that's not intentional.

## Reproducing

 - turn on logging
 - pause Plover
 - type some stuff
 - check logs

## Plover Version

Plover 4.0.0.dev8+8.ge062cda 

## System

 windows 10

**Comment by benoit-pierre** [comment]
This is because `pausing` only pause Plover's output: Plover will still listen to strokes so output can be enabled / toggled back on with the commands `{PLOVER:RESUME}` or `{PLOVER:TOGGLE}`.
